Monitoring System: CacheService Class Reference
CacheService Class Reference
Simulated Cache service.
Public Member Functions
trace_span cache_lookup (const trace_context &parent_ctx, const std::string &key)
Check cache for user data.
Static Private Member Functions
static std::string generate_span_id ()
Private Attributes
std::string service_name_ = "cache_service"
Detailed Description
Simulated Cache service.
Definition at line 259 of file multi_service_tracing_example.cpp.
Member Function Documentation
cache_lookup()
trace_span CacheService::cache_lookup (const trace_context & parent_ctx, const std::string & key) inline
Check cache for user data.
Definition at line 267 of file multi_service_tracing_example.cpp.
{
        std::cout << "\n[" << service_name_ << "] Cache lookup" << std::endl;
        // Create child span
        trace_span span;
        span.trace_id = parent_ctx.trace_id;
        span.span_id = generate_span_id();
        span.parent_span_id = parent_ctx.span_id;
        span.operation_name = "cache_get";
        span.service_name = service_name_;
        span.start_time = std::chrono::system_clock::now();
        // Inherit baggage
        span.baggage = parent_ctx.baggage;
        // Add cache-specific tags
        span.tags["cache.type"] = "redis";
        span.tags["cache.key"] = key;
        std::cout << "   → Created child span: " << span.span_id << std::endl;
        // Simulate cache miss
        std::this_thread::sleep_for(2ms);
        span.end_time = std::chrono::system_clock::now();
        span.calculate_duration();
        span.status = trace_span::status_code::ok;
        span.tags["cache.hit"] = "false";
        std::cout << "   ○ Cache miss (duration: "
                  << span.duration.count() << "µs)" << std::endl;
        return span;
    }
References kcenon::monitoring::trace_span::baggage, kcenon::monitoring::trace_context::baggage, kcenon::monitoring::trace_span::calculate_duration(), kcenon::monitoring::trace_span::duration, kcenon::monitoring::trace_span::end_time, generate_span_id(), kcenon::monitoring::trace_span::operation_name, kcenon::monitoring::trace_span::parent_span_id, kcenon::monitoring::trace_span::service_name, service_name_, kcenon::monitoring::trace_span::span_id, kcenon::monitoring::trace_context::span_id, kcenon::monitoring::trace_span::start_time, kcenon::monitoring::trace_span::status, kcenon::monitoring::trace_span::tags, kcenon::monitoring::trace_span::trace_id, and kcenon::monitoring::trace_context::trace_id.
Referenced by simulate_multi_service_request().
generate_span_id()
static std::string CacheService::generate_span_id () inline static private
Definition at line 303 of file multi_service_tracing_example.cpp.
{
        std::string id;
        for (int i = 0; i < 16; ++i) {
            id += "0123456789abcdef"[rand() % 16];
        }
        return id;
    }
Referenced by cache_lookup().
Member Data Documentation
service_name_
std::string CacheService::service_name_ = "cache_service" private
Definition at line 261 of file multi_service_tracing_example.cpp.
Referenced by cache_lookup().
The documentation for this class was generated from the following file:
examples/multi_service_tracing_example.cpp