Monitoring System: example_logger Class Reference
example_logger Class Reference
Simple logger for examples.
Public Member Functions
example_logger (const std::string &prefix="LOG")
common::VoidResult log (log_level level, const std::string &message) override
common::VoidResult log (log_level level, const std::string &message, const std::string &, int, const std::string &) override
common::VoidResult log (const log_entry &entry) override
bool is_enabled (log_level level) const override
common::VoidResult set_level (log_level level) override
log_level get_level () const override
common::VoidResult flush () override
size_t count () const
Private Attributes
std::string prefix_
std::atomic< size_t > count_ {0}
log_level min_level_ = log_level::trace
Detailed Description
Simple logger for examples.
Examples
monitor_factory_pattern_example.cpp.
Definition at line 113 of file monitor_factory_pattern_example.cpp.
Constructor & Destructor Documentation
example_logger()
example_logger::example_logger (const std::string & prefix = "LOG") inline explicit
Examples
monitor_factory_pattern_example.cpp.
Definition at line 120 of file monitor_factory_pattern_example.cpp.
        : prefix_(prefix) {}
Member Function Documentation
count()
size_t example_logger::count () const inline
Examples
monitor_factory_pattern_example.cpp.
Definition at line 157 of file monitor_factory_pattern_example.cpp.
{ return count_.load(); }
References count_.
flush()
common::VoidResult example_logger::flush () inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 152 of file monitor_factory_pattern_example.cpp.
{
        std::cout << std::flush;
        return common::ok();
    }
get_level()
log_level example_logger::get_level () const inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 148 of file monitor_factory_pattern_example.cpp.
{
        return min_level_;
    }
References min_level_.
is_enabled()
bool example_logger::is_enabled (log_level level) const inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 139 of file monitor_factory_pattern_example.cpp.
{
        return static_cast<int>(level) >= static_cast<int>(min_level_);
    }
References min_level_.
log() [1/3]
common::VoidResult example_logger::log (const log_entry & entry) inline override
Definition at line 135 of file monitor_factory_pattern_example.cpp.
{
        return log(entry.level, entry.message);
    }
References log().
log() [2/3]
common::VoidResult example_logger::log (log_level level, const std::string & message) inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 123 of file monitor_factory_pattern_example.cpp.
{
        std::cout << "[" << prefix_ << "] [" << to_string(level) << "] "
                  << message << std::endl;
        count_++;
        return common::ok();
    }
References count_, prefix_, and kcenon::monitoring::to_string().
Referenced by log(), and log().
log() [3/3]
common::VoidResult example_logger::log (log_level level, const std::string & message, const std::string & , int , const std::string &) inline override
Definition at line 130 of file monitor_factory_pattern_example.cpp.
{
        return log(level, message);
    }
References log().
set_level()
common::VoidResult example_logger::set_level (log_level level) inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 143 of file monitor_factory_pattern_example.cpp.
{
        min_level_ = level;
        return common::ok();
    }
References min_level_.
Member Data Documentation
count_
std::atomic<size_t> example_logger::count_ {0} private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 116 of file monitor_factory_pattern_example.cpp.
{0};
Referenced by count(), and log().
min_level_
log_level example_logger::min_level_ = log_level::trace private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 117 of file monitor_factory_pattern_example.cpp.
Referenced by get_level(), is_enabled(), and set_level().
prefix_
std::string example_logger::prefix_ private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 115 of file monitor_factory_pattern_example.cpp.
Referenced by log().
The documentation for this class was generated from the following file:
examples/monitor_factory_pattern_example.cpp