Monitoring System: kcenon::monitoring::alert_rule Class Reference
kcenon::monitoring::alert_rule Class Reference
Defines conditions and behavior for alert triggering.
#include <alert_rule.h>
Public Member Functions
alert_rule (std::string name)
Construct an alert rule with a name.
const std::string & name () const
Get rule name.
const std::string & group () const
Get rule group.
alert_rule & set_group (std::string group_name)
Set rule group.
alert_severity severity () const
Get alert severity.
alert_rule & set_severity (alert_severity sev)
Set alert severity.
const alert_labels & labels () const
Get labels.
alert_rule & add_label (const std::string &key, const std::string &value)
Add a label.
const alert_annotations & annotations () const
Get annotations.
alert_rule & set_summary (std::string summary)
Set alert summary.
alert_rule & set_description (std::string description)
Set alert description.
alert_rule & set_runbook_url (std::string url)
Set runbook URL.
const alert_rule_config & config () const
Get configuration.
alert_rule & set_evaluation_interval (std::chrono::milliseconds interval)
Set evaluation interval.
alert_rule & set_for_duration (std::chrono::milliseconds duration)
Set for duration (pending time before firing)
alert_rule & set_repeat_interval (std::chrono::milliseconds interval)
Set notification repeat interval.
bool is_enabled () const
Check if rule is enabled.
alert_rule & set_enabled (bool enabled)
Enable or disable rule.
alert_rule & set_trigger (std::shared_ptr< alert_trigger > trigger)
Set the trigger for this rule.
std::shared_ptr< alert_trigger > trigger () const
Get the trigger.
alert create_alert (double value) const
Create an alert from this rule.
common::VoidResult validate () const
Validate rule configuration.
const std::string & metric_name () const
Get metric name to monitor.
alert_rule & set_metric_name (std::string name)
Set metric name to monitor.
Private Attributes
std::string name_
std::string group_
std::string metric_name_
alert_severity severity_ = alert_severity::warning
alert_labels labels_
alert_annotations annotations_
alert_rule_config config_
bool enabled_
std::shared_ptr< alert_trigger > trigger_
Detailed Description
Defines conditions and behavior for alert triggering.
An alert rule encapsulates the logic for when alerts should be triggered, how they should be labeled and annotated, and where notifications should be routed.
Thread Safety:
This class is thread-safe for read operations after construction. Trigger evaluation may require external synchronization depending on trigger implementation.
Examples
alert_triggers_example.cpp.
Definition at line 82 of file alert_rule.h.
Constructor & Destructor Documentation
alert_rule()
kcenon::monitoring::alert_rule::alert_rule (std::string name) inline explicit
Construct an alert rule with a name.
Parameters
name Unique rule name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 88 of file alert_rule.h.
        : name_(std::move(name))
        , enabled_(true) {}
Member Function Documentation
add_label()
alert_rule & kcenon::monitoring::alert_rule::add_label (const std::string & key, const std::string & value) inline
Add a label.
Parameters
key Label key
value Label value
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 142 of file alert_rule.h.
{
        labels_.set(key, value);
        return *this;
    }
References labels_, and kcenon::monitoring::alert_labels::set().
Referenced by main(), TEST(), and TEST().
annotations()
const alert_annotations & kcenon::monitoring::alert_rule::annotations () const inline
Get annotations.
Returns
Alert annotations
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 151 of file alert_rule.h.
{ return annotations_; }
References annotations_.
Referenced by TEST().
config()
const alert_rule_config & kcenon::monitoring::alert_rule::config () const inline
Get configuration.
Returns
Rule configuration
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 187 of file alert_rule.h.
{ return config_; }
References config_.
create_alert()
alert kcenon::monitoring::alert_rule::create_alert (double value) const inline
Create an alert from this rule.
Parameters
value Current metric value
Returns
Created alert
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 256 of file alert_rule.h.
{
        alert a(name_, labels_);
        a.annotations = annotations_;
        a.severity = severity_;
        a.value = value;
        a.rule_name = name_;
        a.group_key = group_.empty() ? name_ : group_;
        return a;
    }
References kcenon::monitoring::alert::annotations, annotations_, group_, kcenon::monitoring::alert::group_key, labels_, name_, kcenon::monitoring::alert::rule_name, kcenon::monitoring::alert::severity, severity_, and kcenon::monitoring::alert::value.
Referenced by TEST(), and TEST().
group()
const std::string & kcenon::monitoring::alert_rule::group () const inline
Get rule group.
Returns
Rule group name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 102 of file alert_rule.h.
{ return group_; }
References group_.
Referenced by TEST().
is_enabled()
bool kcenon::monitoring::alert_rule::is_enabled () const inline
Check if rule is enabled.
Returns
True if enabled
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 223 of file alert_rule.h.
{ return enabled_; }
References enabled_.
Referenced by TEST(), and TEST().
labels()
const alert_labels & kcenon::monitoring::alert_rule::labels () const inline
Get labels.
Returns
Alert labels
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 134 of file alert_rule.h.
{ return labels_; }
References labels_.
Referenced by TEST().
metric_name()
const std::string & kcenon::monitoring::alert_rule::metric_name () const inline
Get metric name to monitor.
Returns
Metric name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 293 of file alert_rule.h.
{ return metric_name_; }
References metric_name_.
Referenced by TEST().
name()
const std::string & kcenon::monitoring::alert_rule::name () const inline
Get rule name.
Returns
Rule name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 96 of file alert_rule.h.
{ return name_; }
References name_.
Referenced by main(), set_metric_name(), and TEST().
set_description()
alert_rule & kcenon::monitoring::alert_rule::set_description (std::string description) inline
Set alert description.
Parameters
description Description text
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 168 of file alert_rule.h.
{
        annotations_.description = std::move(description);
        return *this;
    }
References annotations_, and kcenon::monitoring::alert_annotations::description.
Referenced by main(), and TEST().
set_enabled()
alert_rule & kcenon::monitoring::alert_rule::set_enabled (bool enabled) inline
Enable or disable rule.
Parameters
enabled Enable state
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 230 of file alert_rule.h.
{
        enabled_ = enabled;
        return *this;
    }
References enabled_.
Referenced by TEST(), and TEST().
set_evaluation_interval()
alert_rule & kcenon::monitoring::alert_rule::set_evaluation_interval (std::chrono::milliseconds interval) inline
Set evaluation interval.
Parameters
interval Evaluation interval
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 194 of file alert_rule.h.
{
        config_.evaluation_interval = interval;
        return *this;
    }
References config_, and kcenon::monitoring::alert_rule_config::evaluation_interval.
Referenced by TEST(), and TEST().
set_for_duration()
alert_rule & kcenon::monitoring::alert_rule::set_for_duration (std::chrono::milliseconds duration) inline
Set for duration (pending time before firing)
Parameters
duration Duration before firing
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 204 of file alert_rule.h.
{
        config_.for_duration = duration;
        return *this;
    }
References config_, and kcenon::monitoring::alert_rule_config::for_duration.
Referenced by TEST().
set_group()
alert_rule & kcenon::monitoring::alert_rule::set_group (std::string group_name) inline
Set rule group.
Parameters
group_name Group name
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 109 of file alert_rule.h.
{
        group_ = std::move(group_name);
        return *this;
    }
References group_.
Referenced by TEST(), and TEST().
set_metric_name()
alert_rule & kcenon::monitoring::alert_rule::set_metric_name (std::string name) inline
Set metric name to monitor.
Parameters
name Metric name
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 300 of file alert_rule.h.
{
        metric_name_ = std::move(name);
        return *this;
    }
References metric_name_, and name().
Referenced by main(), TEST(), and TEST().
set_repeat_interval()
alert_rule & kcenon::monitoring::alert_rule::set_repeat_interval (std::chrono::milliseconds interval) inline
Set notification repeat interval.
Parameters
interval Repeat interval
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 214 of file alert_rule.h.
{
        config_.repeat_interval = interval;
        return *this;
    }
References config_, and kcenon::monitoring::alert_rule_config::repeat_interval.
Referenced by TEST().
set_runbook_url()
alert_rule & kcenon::monitoring::alert_rule::set_runbook_url (std::string url) inline
Set runbook URL.
Parameters
url Runbook URL
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 178 of file alert_rule.h.
{
        annotations_.runbook_url = std::move(url);
        return *this;
    }
References annotations_, and kcenon::monitoring::alert_annotations::runbook_url.
Referenced by TEST().
set_severity()
alert_rule & kcenon::monitoring::alert_rule::set_severity (alert_severity sev) inline
Set alert severity.
Parameters
sev Severity level
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 125 of file alert_rule.h.
{
        severity_ = sev;
        return *this;
    }
References severity_.
Referenced by main(), TEST(), and TEST().
set_summary()
alert_rule & kcenon::monitoring::alert_rule::set_summary (std::string summary) inline
Set alert summary.
Parameters
summary Summary text
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 158 of file alert_rule.h.
{
        annotations_.summary = std::move(summary);
        return *this;
    }
References annotations_, kcenon::monitoring::alert_annotations::summary, and kcenon::monitoring::summary.
Referenced by main(), TEST(), and TEST().
set_trigger()
alert_rule & kcenon::monitoring::alert_rule::set_trigger (std::shared_ptr< alert_trigger > trigger) inline
Set the trigger for this rule.
Parameters
trigger Trigger implementation
Returns
Reference to this for chaining
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 240 of file alert_rule.h.
{
        trigger_ = std::move(trigger);
        return *this;
    }
References trigger(), and trigger_.
Referenced by main(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
severity()
alert_severity kcenon::monitoring::alert_rule::severity () const inline
Get alert severity.
Returns
Severity level
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 118 of file alert_rule.h.
{ return severity_; }
References severity_.
Referenced by TEST(), and TEST().
trigger()
std::shared_ptr< alert_trigger > kcenon::monitoring::alert_rule::trigger () const inline
Get the trigger.
Returns
Trigger implementation
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 249 of file alert_rule.h.
{ return trigger_; }
References trigger_.
Referenced by main(), set_trigger(), and TEST().
validate()
common::VoidResult kcenon::monitoring::alert_rule::validate () const inline
Validate rule configuration.
Returns
Result indicating if configuration is valid
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 270 of file alert_rule.h.
{
        if (name_.empty()) {
            error_info err(monitoring_error_code::invalid_argument,
                          "Rule name cannot be empty");
            return common::VoidResult::err(err.to_common_error());
        }
        if (!config_.validate()) {
            error_info err(monitoring_error_code::invalid_configuration,
                          "Rule configuration is invalid");
            return common::VoidResult::err(err.to_common_error());
        }
        if (!trigger_) {
            error_info err(monitoring_error_code::invalid_argument,
                          "Rule must have a trigger");
            return common::VoidResult::err(err.to_common_error());
        }
        return common::ok();
    }
References config_, kcenon::monitoring::invalid_argument, kcenon::monitoring::invalid_configuration, name_, kcenon::monitoring::error_info::to_common_error(), trigger_, and kcenon::monitoring::alert_rule_config::validate().
Referenced by main(), TEST(), TEST(), TEST(), and TEST().
Member Data Documentation
annotations_
alert_annotations kcenon::monitoring::alert_rule::annotations_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 311 of file alert_rule.h.
Referenced by annotations(), create_alert(), set_description(), set_runbook_url(), and set_summary().
config_
alert_rule_config kcenon::monitoring::alert_rule::config_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 312 of file alert_rule.h.
Referenced by config(), set_evaluation_interval(), set_for_duration(), set_repeat_interval(), and validate().
enabled_
bool kcenon::monitoring::alert_rule::enabled_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 313 of file alert_rule.h.
Referenced by is_enabled(), and set_enabled().
group_
std::string kcenon::monitoring::alert_rule::group_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 307 of file alert_rule.h.
Referenced by create_alert(), group(), and set_group().
labels_
alert_labels kcenon::monitoring::alert_rule::labels_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 310 of file alert_rule.h.
Referenced by add_label(), create_alert(), and labels().
metric_name_
std::string kcenon::monitoring::alert_rule::metric_name_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 308 of file alert_rule.h.
Referenced by metric_name(), and set_metric_name().
name_
std::string kcenon::monitoring::alert_rule::name_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 306 of file alert_rule.h.
Referenced by create_alert(), name(), and validate().
severity_
alert_severity kcenon::monitoring::alert_rule::severity_ = alert_severity::warning private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 309 of file alert_rule.h.
Referenced by create_alert(), set_severity(), and severity().
trigger_
std::shared_ptr<alert_trigger> kcenon::monitoring::alert_rule::trigger_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 314 of file alert_rule.h.
Referenced by set_trigger(), trigger(), and validate().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/alert/alert_rule.h