Monitoring System: simple_console_logger Class Reference
simple_console_logger Class Reference
Simple logger implementation for demonstration.
Public Member Functions
simple_console_logger (log_level min=log_level::debug)
kcenon::common::VoidResult log (log_level level, const std::string &message) override
kcenon::common::VoidResult log (const log_entry &entry) override
bool is_enabled (log_level level) const override
kcenon::common::VoidResult set_level (log_level level) override
log_level get_level () const override
kcenon::common::VoidResult flush () override
size_t get_log_count () const
Private Attributes
log_level min_level_ = log_level::debug
std::atomic< size_t > log_count_ {0}
Detailed Description
Simple logger implementation for demonstration.
Examples
logger_di_integration_example.cpp.
Definition at line 30 of file logger_di_integration_example.cpp.
Constructor & Destructor Documentation
simple_console_logger()
simple_console_logger::simple_console_logger (log_level min = log_level::debug) inline explicit
Examples
logger_di_integration_example.cpp.
Definition at line 36 of file logger_di_integration_example.cpp.
        : min_level_(min) {}
Member Function Documentation
flush()
kcenon::common::VoidResult simple_console_logger::flush () inline override
Examples
logger_di_integration_example.cpp.
Definition at line 84 of file logger_di_integration_example.cpp.
{
        std::cout << std::flush;
        return kcenon::common::ok();
    }
get_level()
log_level simple_console_logger::get_level () const inline override
Examples
logger_di_integration_example.cpp.
Definition at line 80 of file logger_di_integration_example.cpp.
{
        return min_level_;
    }
References min_level_.
get_log_count()
size_t simple_console_logger::get_log_count () const inline
Examples
logger_di_integration_example.cpp.
Definition at line 89 of file logger_di_integration_example.cpp.
{ return log_count_.load(); }
References log_count_.
is_enabled()
bool simple_console_logger::is_enabled (log_level level) const inline override
Examples
logger_di_integration_example.cpp.
Definition at line 71 of file logger_di_integration_example.cpp.
{
        return static_cast<int>(level) >= static_cast<int>(min_level_);
    }
References min_level_.
Referenced by log().
log() [1/2]
kcenon::common::VoidResult simple_console_logger::log (const log_entry & entry) inline override
Definition at line 63 of file logger_di_integration_example.cpp.
{
        std::string msg = entry.message;
        if (!entry.file.empty()) {
            msg += " [" + entry.file + ":" + std::to_string(entry.line) + " " + entry.function + "]";
        }
        return log(entry.level, msg);
    }
References log().
log() [2/2]
kcenon::common::VoidResult simple_console_logger::log (log_level level, const std::string & message) inline override
Examples
logger_di_integration_example.cpp.
Definition at line 39 of file logger_di_integration_example.cpp.
{
        if (!is_enabled(level)) {
            return kcenon::common::ok();
        }
        auto now = std::chrono::system_clock::now();
        auto time = std::chrono::system_clock::to_time_t(now);
        // Thread-safe time conversion
        std::tm tm_buf;
#ifdef _WIN32
        localtime_s(&tm_buf, &time);
#else
        localtime_r(&time, &tm_buf);
#endif
        std::cout << "[" << std::put_time(&tm_buf, "%H:%M:%S")
                  << "] [" << to_string(level) << "] "
                  << message << std::endl;
        log_count_++;
        return kcenon::common::ok();
    }
References is_enabled(), log_count_, and kcenon::monitoring::to_string().
Referenced by log().
set_level()
kcenon::common::VoidResult simple_console_logger::set_level (log_level level) inline override
Examples
logger_di_integration_example.cpp.
Definition at line 75 of file logger_di_integration_example.cpp.
{
        min_level_ = level;
        return kcenon::common::ok();
    }
References min_level_.
Member Data Documentation
log_count_
std::atomic<size_t> simple_console_logger::log_count_ {0} private
Examples
logger_di_integration_example.cpp.
Definition at line 33 of file logger_di_integration_example.cpp.
{0};
Referenced by get_log_count(), and log().
min_level_
log_level simple_console_logger::min_level_ = log_level::debug private
Examples
logger_di_integration_example.cpp.
Definition at line 32 of file logger_di_integration_example.cpp.
Referenced by get_level(), is_enabled(), and set_level().
The documentation for this class was generated from the following file:
examples/logger_di_integration_example.cpp