Monitoring System: PerformanceMonitoringTest Class Reference
PerformanceMonitoringTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void simulate_work (std::chrono::milliseconds duration)
Protected Attributes
performance_profiler profiler
performance_monitor monitor
Detailed Description
Definition at line 21 of file test_performance_monitoring.cpp.
Member Function Documentation
SetUp()
void PerformanceMonitoringTest::SetUp () inline override protected
Definition at line 26 of file test_performance_monitoring.cpp.
{
        profiler.clear_all_samples();
        monitor.set_enabled(true);
    }
References kcenon::monitoring::performance_profiler::clear_all_samples(), monitor, profiler, and kcenon::monitoring::performance_monitor::set_enabled().
simulate_work()
void PerformanceMonitoringTest::simulate_work (std::chrono::milliseconds duration) inline protected
Definition at line 34 of file test_performance_monitoring.cpp.
{
        std::this_thread::sleep_for(duration);
    }
TearDown()
void PerformanceMonitoringTest::TearDown () inline override protected
Definition at line 31 of file test_performance_monitoring.cpp.
{ monitor.cleanup(); }
References kcenon::monitoring::performance_monitor::cleanup(), and monitor.
Member Data Documentation
monitor
performance_monitor PerformanceMonitoringTest::monitor protected
Definition at line 24 of file test_performance_monitoring.cpp.
Referenced by SetUp(), and TearDown().
profiler
performance_profiler PerformanceMonitoringTest::profiler protected
Definition at line 23 of file test_performance_monitoring.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
tests/test_performance_monitoring.cpp