Monitoring System: kcenon::monitoring::system_monitor Class Reference
kcenon::monitoring::system_monitor Class Reference
System resource monitor.
#include <performance_monitor.h>
Public Member Functions
system_monitor ()
~system_monitor ()
system_monitor (const system_monitor &)=delete
system_monitor & operator= (const system_monitor &)=delete
system_monitor (system_monitor &&) noexcept
system_monitor & operator= (system_monitor &&) noexcept
common::Result< system_metrics > get_current_metrics () const
Get current system metrics.
common::Result< bool > start_monitoring (std::chrono::milliseconds interval=std::chrono::milliseconds(1000))
Start monitoring system resources.
common::Result< bool > stop_monitoring ()
Stop monitoring.
bool is_monitoring () const
Check if monitoring is active.
std::vector< system_metrics > get_history (std::chrono::seconds duration=std::chrono::seconds(60)) const
Get historical metrics.
Private Attributes
std::unique_ptr< monitor_impl > impl_
Detailed Description
System resource monitor.
Definition at line 293 of file performance_monitor.h.
Constructor & Destructor Documentation
system_monitor() [1/3]
kcenon::monitoring::system_monitor::system_monitor ()
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
~system_monitor()
kcenon::monitoring::system_monitor::~system_monitor ()
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
system_monitor() [2/3]
kcenon::monitoring::system_monitor::system_monitor (const system_monitor &) delete
system_monitor() [3/3]
kcenon::monitoring::system_monitor::system_monitor (system_monitor &&) noexcept
Member Function Documentation
get_current_metrics()
common::Result< system_metrics > kcenon::monitoring::system_monitor::get_current_metrics () const
Get current system metrics.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h, and basic_monitoring_example.cpp.
Referenced by main(), and TEST_F().
get_history()
std::vector< system_metrics > kcenon::monitoring::system_monitor::get_history (std::chrono::seconds duration = std::chrono::seconds(60)) const
Get historical metrics.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by TEST_F().
is_monitoring()
bool kcenon::monitoring::system_monitor::is_monitoring () const
Check if monitoring is active.
Returns
True if system resource monitoring is currently running
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
operator=() [1/2]
system_monitor & kcenon::monitoring::system_monitor::operator= (const system_monitor &) delete
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
operator=() [2/2]
system_monitor & kcenon::monitoring::system_monitor::operator= (system_monitor &&) noexcept
start_monitoring()
common::Result< bool > kcenon::monitoring::system_monitor::start_monitoring (std::chrono::milliseconds interval = std::chrono::milliseconds(1000))
Start monitoring system resources.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by kcenon::monitoring::performance_monitor::initialize(), and TEST_F().
stop_monitoring()
common::Result< bool > kcenon::monitoring::system_monitor::stop_monitoring ()
Stop monitoring.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by kcenon::monitoring::performance_monitor::cleanup(), and TEST_F().
Member Data Documentation
impl_
std::unique_ptr<monitor_impl> kcenon::monitoring::system_monitor::impl_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 296 of file performance_monitor.h.
The documentation for this class was generated from the following file:
include/kcenon/monitoring/core/performance_monitor.h