Monitoring System: kcenon::monitoring::webhook_notifier Class Reference
kcenon::monitoring::webhook_notifier Class Reference
Sends alerts to a webhook endpoint.
#include <alert_notifiers.h>
Public Types
using http_sender_func
Public Member Functions
webhook_notifier (const webhook_config &config, std::shared_ptr< alert_formatter > formatter=nullptr)
Construct webhook notifier.
std::string name () const override
Get notifier name.
common::VoidResult notify (const alert &a) override
Send a notification for an alert.
common::VoidResult notify_group (const alert_group &group) override
Send a notification for an alert group.
bool is_ready () const override
Check if notifier is ready.
void set_http_sender (http_sender_func sender)
Set HTTP sender function for actual HTTP calls.
const webhook_config & config () const
Get configuration.
Public Member Functions inherited from kcenon::monitoring::alert_notifier
virtual ~alert_notifier ()=default
Private Member Functions
common::VoidResult send_with_retry (const std::string &payload)
Private Attributes
webhook_config config_
std::shared_ptr< alert_formatter > formatter_
http_sender_func http_sender_
Detailed Description
Sends alerts to a webhook endpoint.
Note: Actual HTTP implementation requires network_system integration or an external HTTP client. This implementation provides the interface and can be extended with actual HTTP support.
Definition at line 197 of file alert_notifiers.h.
Member Typedef Documentation
http_sender_func
using kcenon::monitoring::webhook_notifier::http_sender_func
Initial value:
 std::function<common::VoidResult(
        const std::string& url,
        const std::string& method,
        const std::unordered_map<std::string, std::string>& headers,
        const std::string& body
    )>
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 199 of file alert_notifiers.h.
Constructor & Destructor Documentation
webhook_notifier()
kcenon::monitoring::webhook_notifier::webhook_notifier (const webhook_config & config, std::shared_ptr< alert_formatter > formatter = nullptr) inline explicit
Construct webhook notifier.
Parameters
config Webhook configuration
formatter Alert formatter (default: JSON)
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 211 of file alert_notifiers.h.
        : config_(config)
        , formatter_(formatter ? formatter : std::make_shared<json_alert_formatter>()) {}
Member Function Documentation
config()
const webhook_config & kcenon::monitoring::webhook_notifier::config () const inline
Get configuration.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 260 of file alert_notifiers.h.
{ return config_; }
References config_.
is_ready()
bool kcenon::monitoring::webhook_notifier::is_ready () const inline override virtual
Check if notifier is ready.
Returns
True if ready to send notifications
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 234 of file alert_notifiers.h.
{
        return config_.validate() && http_sender_ != nullptr;
    }
References config_, http_sender_, and kcenon::monitoring::webhook_config::validate().
name()
std::string kcenon::monitoring::webhook_notifier::name () const inline override virtual
Get notifier name.
Returns
Notifier name
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 216 of file alert_notifiers.h.
{
        return "webhook:" + config_.url;
    }
References config_, and kcenon::monitoring::webhook_config::url.
notify()
common::VoidResult kcenon::monitoring::webhook_notifier::notify (const alert & a) inline override virtual
Send a notification for an alert.
Parameters
a Alert to notify about
Returns
Result indicating success or failure
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 220 of file alert_notifiers.h.
{
        if (!config_.send_resolved && a.state == alert_state::resolved) {
            return common::ok();
        }
        std::string payload = formatter_->format(a);
        return send_with_retry(payload);
    }
References config_, formatter_, kcenon::monitoring::resolved, kcenon::monitoring::webhook_config::send_resolved, send_with_retry(), and kcenon::monitoring::alert::state.
notify_group()
common::VoidResult kcenon::monitoring::webhook_notifier::notify_group (const alert_group & group) inline override virtual
Send a notification for an alert group.
Parameters
group Alert group to notify about
Returns
Result indicating success or failure
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 229 of file alert_notifiers.h.
{
        std::string payload = formatter_->format_group(group);
        return send_with_retry(payload);
    }
References formatter_, and send_with_retry().
send_with_retry()
common::VoidResult kcenon::monitoring::webhook_notifier::send_with_retry (const std::string & payload) inline private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 263 of file alert_notifiers.h.
{
        if (!http_sender_) {
            return common::VoidResult::err(error_info(monitoring_error_code::operation_failed, "No HTTP sender configured").to_common_error());
        }
        auto headers = config_.headers;
        headers["Content-Type"] = config_.content_type;
        for (size_t attempt = 0; attempt <= config_.max_retries; ++attempt) {
            auto result = http_sender_(config_.url, config_.method, headers, payload);
            if (result.is_ok()) {
                return result;
            }
            if (attempt < config_.max_retries) {
                std::this_thread::sleep_for(config_.retry_delay);
            }
        }
        return common::VoidResult::err(static_cast<int>(monitoring_error_code::retry_attempts_exhausted),
                               "Failed to send webhook after " +
                               std::to_string(config_.max_retries) + " retries");
    }
References config_, kcenon::monitoring::webhook_config::content_type, kcenon::monitoring::webhook_config::headers, http_sender_, kcenon::monitoring::webhook_config::max_retries, kcenon::monitoring::webhook_config::method, kcenon::monitoring::operation_failed, kcenon::monitoring::retry_attempts_exhausted, kcenon::monitoring::webhook_config::retry_delay, and kcenon::monitoring::webhook_config::url.
Referenced by notify(), and notify_group().
set_http_sender()
void kcenon::monitoring::webhook_notifier::set_http_sender (http_sender_func sender) inline
Set HTTP sender function for actual HTTP calls.
Parameters
sender Function to send HTTP requests
This allows injecting a real HTTP implementation:
notifier->set_http_sender([](const std::string& url,
                             const std::string& method,
                             const auto& headers,
                             const std::string& body) {
    // Use network_system or other HTTP client
    return http_client.request(url, method, headers, body);
});
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 253 of file alert_notifiers.h.
{
        http_sender_ = std::move(sender);
    }
References http_sender_.
Member Data Documentation
config_
webhook_config kcenon::monitoring::webhook_notifier::config_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 287 of file alert_notifiers.h.
Referenced by config(), is_ready(), name(), notify(), and send_with_retry().
formatter_
std::shared_ptr<alert_formatter> kcenon::monitoring::webhook_notifier::formatter_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 288 of file alert_notifiers.h.
Referenced by notify(), and notify_group().
http_sender_
http_sender_func kcenon::monitoring::webhook_notifier::http_sender_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 289 of file alert_notifiers.h.
Referenced by is_ready(), send_with_retry(), and set_http_sender().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/alert/alert_notifiers.h