Monitoring System: UserService Class Reference
UserService Class Reference
Simulated User service.
Public Member Functions
trace_span get_user_profile (const trace_context &parent_ctx, const std::string &user_id)
Fetch user profile.
Static Private Member Functions
static std::string generate_span_id ()
Private Attributes
std::string service_name_ = "user_service"
Detailed Description
Simulated User service.
Examples
multi_service_tracing_example.cpp.
Definition at line 175 of file multi_service_tracing_example.cpp.
Member Function Documentation
generate_span_id()
static std::string UserService::generate_span_id () inline static private
Examples
multi_service_tracing_example.cpp.
Definition at line 223 of file multi_service_tracing_example.cpp.
{
        std::string id;
        for (int i = 0; i < 16; ++i) {
            id += "0123456789abcdef"[rand() % 16];
        }
        return id;
    }
Referenced by get_user_profile().
get_user_profile()
trace_span UserService::get_user_profile (const trace_context & parent_ctx, const std::string & user_id) inline
Fetch user profile.
Examples
multi_service_tracing_example.cpp.
Definition at line 183 of file multi_service_tracing_example.cpp.
{
        std::cout << "\n[" << service_name_ << "] Fetching user profile" << std::endl;
        std::cout << "   User ID from baggage: " << parent_ctx.baggage.at("user.id") << std::endl;
        // Create child span
        trace_span span;
        span.trace_id = parent_ctx.trace_id;
        span.span_id = generate_span_id();
        span.parent_span_id = parent_ctx.span_id;
        span.operation_name = "get_user_profile";
        span.service_name = service_name_;
        span.start_time = std::chrono::system_clock::now();
        // Inherit baggage
        span.baggage = parent_ctx.baggage;
        // Add database query tags
        span.tags["db.system"] = "postgresql";
        span.tags["db.name"] = "users_db";
        span.tags["db.statement"] = "SELECT * FROM users WHERE id = ?";
        span.tags["db.user_id"] = user_id;
        std::cout << "   → Created child span: " << span.span_id << std::endl;
        std::cout << "     Parent span: " << span.parent_span_id << std::endl;
        // Simulate database query
        std::this_thread::sleep_for(15ms);
        span.end_time = std::chrono::system_clock::now();
        span.calculate_duration();
        span.status = trace_span::status_code::ok;
        span.tags["db.rows_returned"] = "1";
        std::cout << "   ✓ User profile fetched (duration: "
                  << span.duration.count() << "µs)" << std::endl;
        return span;
    }
References kcenon::monitoring::trace_context::baggage, kcenon::monitoring::trace_span::baggage, kcenon::monitoring::trace_span::calculate_duration(), kcenon::monitoring::trace_span::duration, kcenon::monitoring::trace_span::end_time, generate_span_id(), kcenon::monitoring::trace_span::operation_name, kcenon::monitoring::trace_span::parent_span_id, kcenon::monitoring::trace_span::service_name, service_name_, kcenon::monitoring::trace_context::span_id, kcenon::monitoring::trace_span::span_id, kcenon::monitoring::trace_span::start_time, kcenon::monitoring::trace_span::status, kcenon::monitoring::trace_span::tags, kcenon::monitoring::trace_context::trace_id, and kcenon::monitoring::trace_span::trace_id.
Referenced by simulate_multi_service_request().
Member Data Documentation
service_name_
std::string UserService::service_name_ = "user_service" private
Examples
multi_service_tracing_example.cpp.
Definition at line 177 of file multi_service_tracing_example.cpp.
Referenced by get_user_profile().
The documentation for this class was generated from the following file:
examples/multi_service_tracing_example.cpp