Monitoring System: kcenon::monitoring::simple_http_client Class Reference
kcenon::monitoring::simple_http_client Class Reference
Simple HTTP client using basic socket operations.
#include <http_transport.h>
Classes
struct url_parts
Public Member Functions
simple_http_client (std::chrono::milliseconds timeout=std::chrono::milliseconds(30000))
common::Result< http_response > send (const http_request &request) override
Send HTTP request and receive response.
bool is_available () const override
Check if transport is available.
std::string name () const override
Get transport name.
Public Member Functions inherited from kcenon::monitoring::http_transport
virtual ~http_transport ()=default
Private Member Functions
url_parts parse_url (const std::string &url)
Private Attributes
std::chrono::milliseconds default_timeout_ {30000}
bool use_tls_ {false}
Detailed Description
Simple HTTP client using basic socket operations.
This implementation provides basic HTTP functionality without external dependencies. For production use, consider integrating a full HTTP library like libcurl or cpp-httplib.
Definition at line 141 of file http_transport.h.
Constructor & Destructor Documentation
simple_http_client()
kcenon::monitoring::simple_http_client::simple_http_client (std::chrono::milliseconds timeout = std::chrono::milliseconds(30000)) inline explicit
Definition at line 147 of file http_transport.h.
        : default_timeout_(timeout) {}
Member Function Documentation
is_available()
bool kcenon::monitoring::simple_http_client::is_available () const inline override virtual
Check if transport is available.
Implements kcenon::monitoring::http_transport.
Definition at line 179 of file http_transport.h.
{
        // Stub transport cannot actually send data
        return false;
    }
name()
std::string kcenon::monitoring::simple_http_client::name () const inline override virtual
Get transport name.
Implements kcenon::monitoring::http_transport.
Definition at line 184 of file http_transport.h.
{
        return "stub";
    }
parse_url()
url_parts kcenon::monitoring::simple_http_client::parse_url (const std::string & url) inline private
Definition at line 197 of file http_transport.h.
{
        url_parts parts;
        // Find scheme
        auto scheme_end = url.find("://");
        if (scheme_end == std::string::npos) {
            return parts;
        }
        parts.scheme = url.substr(0, scheme_end);
        // Find host and port
        auto host_start = scheme_end + 3;
        auto path_start = url.find('/', host_start);
        if (path_start == std::string::npos) {
            path_start = url.length();
        }
        auto host_port = url.substr(host_start, path_start - host_start);
        auto colon_pos = host_port.find(':');
        if (colon_pos != std::string::npos) {
            parts.host = host_port.substr(0, colon_pos);
            try {
                parts.port = std::stoi(host_port.substr(colon_pos + 1));
            } catch (...) {
                return parts;
            }
        } else {
            parts.host = host_port;
            parts.port = (parts.scheme == "https") ? 443 : 80;
        }
        // Extract path
        if (path_start < url.length()) {
            parts.path = url.substr(path_start);
        } else {
            parts.path = "/";
        }
        parts.valid = !parts.host.empty();
        return parts;
    }
References kcenon::monitoring::simple_http_client::url_parts::host, kcenon::monitoring::simple_http_client::url_parts::path, kcenon::monitoring::simple_http_client::url_parts::port, kcenon::monitoring::simple_http_client::url_parts::scheme, and kcenon::monitoring::simple_http_client::url_parts::valid.
Referenced by send().
send()
common::Result< http_response > kcenon::monitoring::simple_http_client::send (const http_request & request) inline override virtual
Send HTTP request and receive response.
Implements kcenon::monitoring::http_transport.
Definition at line 150 of file http_transport.h.
{
        // Parse URL to extract host, port, and path
        auto url_parts = parse_url(request.url);
        if (!url_parts.valid) {
            error_info err(monitoring_error_code::invalid_configuration,
                          "Invalid URL: " + request.url);
            return common::Result<http_response>::err(err.to_common_error());
        }
        use_tls_ = url_parts.scheme == "https";
        // No real HTTP transport available. Return error instead of
        // fake 202 success, so callers know data was NOT sent.
        // Build with MONITORING_WITH_NETWORK_SYSTEM=ON for real transport.
        static bool warned = false;
        if (!warned)
        {
            std::cerr << "[monitoring_system] WARNING: Trace export configured but no HTTP "
                      << "transport available. Build with MONITORING_WITH_NETWORK_SYSTEM=ON "
                      << "or provide a real http_transport implementation. "
                      << "Trace data is NOT being exported.\n";
            warned = true;
        }
        error_info err(monitoring_error_code::invalid_configuration,
                      "No HTTP transport available (stub mode)");
        return common::Result<http_response>::err(err.to_common_error());
    }
References kcenon::monitoring::invalid_configuration, parse_url(), kcenon::monitoring::simple_http_client::url_parts::scheme, kcenon::monitoring::error_info::to_common_error(), kcenon::monitoring::http_request::url, use_tls_, and kcenon::monitoring::simple_http_client::url_parts::valid.
Member Data Documentation
default_timeout_
std::chrono::milliseconds kcenon::monitoring::simple_http_client::default_timeout_ {30000} private
Definition at line 143 of file http_transport.h.
{30000};
use_tls_
bool kcenon::monitoring::simple_http_client::use_tls_ {false} private
Definition at line 144 of file http_transport.h.
{false};
Referenced by send().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/exporters/http_transport.h