Monitoring System: kcenon::monitoring::fault_tolerance_manager< T > Class Template Reference
kcenon::monitoring::fault_tolerance_manager< T > Class Template Reference
Fault tolerance manager template class.
#include <fault_tolerance_manager.h>
Public Member Functions
fault_tolerance_manager ()
fault_tolerance_manager (const std::string &name)
fault_tolerance_manager (const std::string &name, const fault_tolerance_config &cfg)
template<typename Func >
common::Result< T > execute (Func &&func)
Execute a function with fault tolerance.
template<typename Func >
common::Result< T > execute_with_timeout (Func &&func, std::chrono::milliseconds timeout)
Execute a function with timeout.
common::Result< bool > is_healthy ()
Check if fault tolerance manager is healthy.
fault_tolerance_metrics get_metrics () const
Get fault tolerance metrics.
const std::string & get_name () const
Get manager name.
Private Member Functions
void initialize ()
template<typename Func >
common::Result< T > execute_internal (Func &&func)
template<typename Func >
common::Result< T > execute_circuit_breaker_first (Func &&func)
template<typename Func >
common::Result< T > execute_retry_first (Func &&func)
Private Attributes
std::string name_
fault_tolerance_config config_
std::unique_ptr< circuit_breaker > circuit_breaker_
std::unique_ptr< retry_executor< T > > retry_executor_
fault_tolerance_metrics metrics_
Detailed Description
template<typename T>
class kcenon::monitoring::fault_tolerance_manager< T >
Fault tolerance manager template class.
Combines circuit breaker and retry logic for resilient operations.
Template Parameters
T The return value type of operations
Definition at line 105 of file fault_tolerance_manager.h.
Constructor & Destructor Documentation
fault_tolerance_manager() [1/3]
template<typename T > kcenon::monitoring::fault_tolerance_manager< T >::fault_tolerance_manager () inline
Definition at line 107 of file fault_tolerance_manager.h.
                              : name_("default"), config_() {
        initialize();
    }
References kcenon::monitoring::fault_tolerance_manager< T >::initialize().
fault_tolerance_manager() [2/3]
template<typename T > kcenon::monitoring::fault_tolerance_manager< T >::fault_tolerance_manager (const std::string & name) inline explicit
Definition at line 111 of file fault_tolerance_manager.h.
        : name_(name), config_() {
        initialize();
    }
References kcenon::monitoring::fault_tolerance_manager< T >::initialize().
fault_tolerance_manager() [3/3]
template<typename T > kcenon::monitoring::fault_tolerance_manager< T >::fault_tolerance_manager (const std::string & name, const fault_tolerance_config & cfg) inline explicit
Definition at line 116 of file fault_tolerance_manager.h.
        : name_(name), config_(cfg) {
        initialize();
    }
References kcenon::monitoring::fault_tolerance_manager< T >::initialize().
Member Function Documentation
execute()
template<typename T > template<typename Func > common::Result< T > kcenon::monitoring::fault_tolerance_manager< T >::execute (Func && func) inline
Execute a function with fault tolerance.
Template Parameters
Func The function type to execute (must return common::Result<T>)
Parameters
func The function to execute
Returns
common::Result<T> containing success value or error
Definition at line 129 of file fault_tolerance_manager.h.
{
        metrics_.total_operations++;
        common::Result<T> op_result = common::Result<T>::err(error_info(monitoring_error_code::operation_failed, "Not executed").to_common_error());
        if (config_.circuit_breaker_first) {
            op_result = execute_circuit_breaker_first(std::forward<Func>(func));
        } else {
            op_result = execute_retry_first(std::forward<Func>(func));
        }
        if (op_result.is_ok()) {
            metrics_.successful_operations++;
        } else {
            metrics_.failed_operations++;
        }
        return op_result;
    }
References kcenon::monitoring::fault_tolerance_config::circuit_breaker_first, kcenon::monitoring::fault_tolerance_manager< T >::config_, kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first(), kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first(), kcenon::monitoring::fault_tolerance_metrics::failed_operations, kcenon::monitoring::fault_tolerance_manager< T >::metrics_, kcenon::monitoring::operation_failed, kcenon::monitoring::fault_tolerance_metrics::successful_operations, and kcenon::monitoring::fault_tolerance_metrics::total_operations.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
execute_circuit_breaker_first()
template<typename T > template<typename Func > common::Result< T > kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first (Func && func) inline private
Definition at line 229 of file fault_tolerance_manager.h.
{
        if (config_.enable_circuit_breaker && circuit_breaker_) {
            if (config_.enable_retry && retry_executor_) {
                return execute_with_circuit_breaker<T>(*circuit_breaker_, name_, [this, &func]() {
                    return retry_executor_->execute(func);
                });
            }
            return execute_with_circuit_breaker<T>(*circuit_breaker_, name_, std::forward<Func>(func));
        }
        if (config_.enable_retry && retry_executor_) {
            return retry_executor_->execute(std::forward<Func>(func));
        }
        return func();
    }
References kcenon::monitoring::fault_tolerance_manager< T >::circuit_breaker_, kcenon::monitoring::fault_tolerance_manager< T >::config_, kcenon::monitoring::fault_tolerance_config::enable_circuit_breaker, kcenon::monitoring::fault_tolerance_config::enable_retry, kcenon::monitoring::execute_with_circuit_breaker(), kcenon::monitoring::fault_tolerance_manager< T >::name_, and kcenon::monitoring::fault_tolerance_manager< T >::retry_executor_.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute(), and kcenon::monitoring::fault_tolerance_manager< T >::execute_internal().
execute_internal()
template<typename T > template<typename Func > common::Result< T > kcenon::monitoring::fault_tolerance_manager< T >::execute_internal (Func && func) inline private
Definition at line 221 of file fault_tolerance_manager.h.
{
        if (config_.circuit_breaker_first) {
            return execute_circuit_breaker_first(std::forward<Func>(func));
        }
        return execute_retry_first(std::forward<Func>(func));
    }
References kcenon::monitoring::fault_tolerance_config::circuit_breaker_first, kcenon::monitoring::fault_tolerance_manager< T >::config_, kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first(), and kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first().
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute_with_timeout().
execute_retry_first()
template<typename T > template<typename Func > common::Result< T > kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first (Func && func) inline private
Definition at line 245 of file fault_tolerance_manager.h.
{
        if (config_.enable_retry && retry_executor_) {
            if (config_.enable_circuit_breaker && circuit_breaker_) {
                return retry_executor_->execute([this, &func]() {
                    return execute_with_circuit_breaker<T>(*circuit_breaker_, name_, func);
                });
            }
            return retry_executor_->execute(std::forward<Func>(func));
        }
        if (config_.enable_circuit_breaker && circuit_breaker_) {
            return execute_with_circuit_breaker<T>(*circuit_breaker_, name_, std::forward<Func>(func));
        }
        return func();
    }
References kcenon::monitoring::fault_tolerance_manager< T >::circuit_breaker_, kcenon::monitoring::fault_tolerance_manager< T >::config_, kcenon::monitoring::fault_tolerance_config::enable_circuit_breaker, kcenon::monitoring::fault_tolerance_config::enable_retry, kcenon::monitoring::execute_with_circuit_breaker(), kcenon::monitoring::fault_tolerance_manager< T >::name_, and kcenon::monitoring::fault_tolerance_manager< T >::retry_executor_.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute(), and kcenon::monitoring::fault_tolerance_manager< T >::execute_internal().
execute_with_timeout()
template<typename T > template<typename Func > common::Result< T > kcenon::monitoring::fault_tolerance_manager< T >::execute_with_timeout (Func && func, std::chrono::milliseconds timeout) inline
Execute a function with timeout.
Template Parameters
Func The function type to execute (must return common::Result<T>)
Parameters
func The function to execute
timeout Maximum execution time
Returns
common::Result<T> containing success value or error
Definition at line 158 of file fault_tolerance_manager.h.
{
        metrics_.total_operations++;
        auto future_result = std::async(std::launch::async, [this, func = std::forward<Func>(func)]() mutable {
            return this->execute_internal(std::move(func));
        });
        if (future_result.wait_for(timeout) == std::future_status::timeout) {
            metrics_.timeouts++;
            metrics_.failed_operations++;
            return common::make_error<T>(static_cast<int>(monitoring_error_code::operation_timeout),
                               "Operation timed out after " + std::to_string(timeout.count()) + "ms");
        }
        auto op_result = future_result.get();
        if (op_result.is_ok()) {
            metrics_.successful_operations++;
        } else {
            metrics_.failed_operations++;
        }
        return op_result;
    }
References kcenon::monitoring::fault_tolerance_manager< T >::execute_internal(), kcenon::monitoring::fault_tolerance_metrics::failed_operations, kcenon::monitoring::fault_tolerance_manager< T >::metrics_, kcenon::monitoring::operation_timeout, kcenon::monitoring::fault_tolerance_metrics::successful_operations, kcenon::monitoring::fault_tolerance_metrics::timeouts, and kcenon::monitoring::fault_tolerance_metrics::total_operations.
Referenced by TEST_F().
get_metrics()
template<typename T > fault_tolerance_metrics kcenon::monitoring::fault_tolerance_manager< T >::get_metrics () const inline
Get fault tolerance metrics.
Definition at line 199 of file fault_tolerance_manager.h.
{
        return metrics_;
    }
References kcenon::monitoring::fault_tolerance_manager< T >::metrics_.
Referenced by TEST_F().
get_name()
template<typename T > const std::string & kcenon::monitoring::fault_tolerance_manager< T >::get_name () const inline
Get manager name.
Definition at line 206 of file fault_tolerance_manager.h.
{
        return name_;
    }
References kcenon::monitoring::fault_tolerance_manager< T >::name_.
initialize()
template<typename T > void kcenon::monitoring::fault_tolerance_manager< T >::initialize () inline private
Definition at line 211 of file fault_tolerance_manager.h.
                      {
        if (config_.enable_circuit_breaker) {
            circuit_breaker_ = std::make_unique<circuit_breaker>(config_.circuit_config);
        }
        if (config_.enable_retry) {
            retry_executor_ = std::make_unique<retry_executor<T>>(name_ + "_retry", config_.retry_cfg);
        }
    }
References kcenon::monitoring::fault_tolerance_manager< T >::circuit_breaker_, kcenon::monitoring::fault_tolerance_config::circuit_config, kcenon::monitoring::fault_tolerance_manager< T >::config_, kcenon::monitoring::fault_tolerance_config::enable_circuit_breaker, kcenon::monitoring::fault_tolerance_config::enable_retry, kcenon::monitoring::fault_tolerance_manager< T >::name_, kcenon::monitoring::fault_tolerance_config::retry_cfg, and kcenon::monitoring::fault_tolerance_manager< T >::retry_executor_.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::fault_tolerance_manager(), kcenon::monitoring::fault_tolerance_manager< T >::fault_tolerance_manager(), and kcenon::monitoring::fault_tolerance_manager< T >::fault_tolerance_manager().
is_healthy()
template<typename T > common::Result< bool > kcenon::monitoring::fault_tolerance_manager< T >::is_healthy () inline
Check if fault tolerance manager is healthy.
Returns
common::Result<bool> indicating health status
Definition at line 186 of file fault_tolerance_manager.h.
{
        if (config_.enable_circuit_breaker && circuit_breaker_) {
            auto state = circuit_breaker_->get_state();
            if (state == circuit_state::OPEN) {
                return common::ok(false);
            }
        }
        return common::ok(true);
    }
References kcenon::monitoring::fault_tolerance_manager< T >::circuit_breaker_, kcenon::monitoring::fault_tolerance_manager< T >::config_, and kcenon::monitoring::fault_tolerance_config::enable_circuit_breaker.
Referenced by TEST_F().
Member Data Documentation
circuit_breaker_
template<typename T > std::unique_ptr<circuit_breaker> kcenon::monitoring::fault_tolerance_manager< T >::circuit_breaker_ private
Definition at line 262 of file fault_tolerance_manager.h.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first(), kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first(), kcenon::monitoring::fault_tolerance_manager< T >::initialize(), and kcenon::monitoring::fault_tolerance_manager< T >::is_healthy().
config_
template<typename T > fault_tolerance_config kcenon::monitoring::fault_tolerance_manager< T >::config_ private
Definition at line 261 of file fault_tolerance_manager.h.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute(), kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first(), kcenon::monitoring::fault_tolerance_manager< T >::execute_internal(), kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first(), kcenon::monitoring::fault_tolerance_manager< T >::initialize(), and kcenon::monitoring::fault_tolerance_manager< T >::is_healthy().
metrics_
template<typename T > fault_tolerance_metrics kcenon::monitoring::fault_tolerance_manager< T >::metrics_ mutable private
Definition at line 264 of file fault_tolerance_manager.h.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute(), kcenon::monitoring::fault_tolerance_manager< T >::execute_with_timeout(), and kcenon::monitoring::fault_tolerance_manager< T >::get_metrics().
name_
template<typename T > std::string kcenon::monitoring::fault_tolerance_manager< T >::name_ private
Definition at line 260 of file fault_tolerance_manager.h.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first(), kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first(), kcenon::monitoring::fault_tolerance_manager< T >::get_name(), and kcenon::monitoring::fault_tolerance_manager< T >::initialize().
retry_executor_
template<typename T > std::unique_ptr<retry_executor<T> > kcenon::monitoring::fault_tolerance_manager< T >::retry_executor_ private
Definition at line 263 of file fault_tolerance_manager.h.
Referenced by kcenon::monitoring::fault_tolerance_manager< T >::execute_circuit_breaker_first(), kcenon::monitoring::fault_tolerance_manager< T >::execute_retry_first(), and kcenon::monitoring::fault_tolerance_manager< T >::initialize().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/reliability/fault_tolerance_manager.h