Monitoring System: console_logger Class Reference
console_logger Class Reference
Simple console logger implementing ILogger interface.
Public Member Functions
common::VoidResult log (log_level level, const std::string &message) override
common::VoidResult log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function) override
common::VoidResult log (const log_entry &entry) override
bool is_enabled (log_level level) const override
common::VoidResult set_level (log_level level) override
log_level get_level () const override
common::VoidResult flush () override
common::Result< metrics_snapshot > get_monitoring_data () override
common::Result< health_check_result > health_check () override
std::string get_component_name () const override
void set_monitor (std::shared_ptr< IMonitor > monitor)
int get_message_count () const
Private Attributes
std::atomic< int > message_count_ {0}
log_level min_level_ {log_level::info}
std::shared_ptr< IMonitor > monitor_
Detailed Description
Simple console logger implementing ILogger interface.
This demonstrates that ANY implementation of ILogger can work with monitoring_system, not just logger_system's logger class.
Examples
bidirectional_di_example.cpp.
Definition at line 37 of file bidirectional_di_example.cpp.
Member Function Documentation
flush()
common::VoidResult console_logger::flush () inline override
Examples
bidirectional_di_example.cpp.
Definition at line 97 of file bidirectional_di_example.cpp.
{
        std::cout.flush();
        return std::monostate{};
    }
get_component_name()
std::string console_logger::get_component_name () const inline override
Examples
bidirectional_di_example.cpp.
Definition at line 119 of file bidirectional_di_example.cpp.
{
        return "console_logger";
    }
get_level()
log_level console_logger::get_level () const inline override
Examples
bidirectional_di_example.cpp.
Definition at line 93 of file bidirectional_di_example.cpp.
{
        return min_level_;
    }
References min_level_.
get_message_count()
int console_logger::get_message_count () const inline
Examples
bidirectional_di_example.cpp.
Definition at line 128 of file bidirectional_di_example.cpp.
{
        return message_count_.load();
    }
References message_count_.
get_monitoring_data()
common::Result< metrics_snapshot > console_logger::get_monitoring_data () inline override
Examples
bidirectional_di_example.cpp.
Definition at line 103 of file bidirectional_di_example.cpp.
{
        metrics_snapshot snapshot;
        snapshot.source_id = "console_logger";
        snapshot.add_metric("total_messages", message_count_.load());
        snapshot.add_metric("is_enabled", is_enabled(log_level::info) ? 1.0 : 0.0);
        return snapshot;
    }
References kcenon::monitoring::metrics_snapshot::add_metric(), is_enabled(), message_count_, and kcenon::monitoring::metrics_snapshot::source_id.
health_check()
common::Result< health_check_result > console_logger::health_check () inline override
Examples
bidirectional_di_example.cpp.
Definition at line 111 of file bidirectional_di_example.cpp.
{
        health_check_result result;
        result.status = health_status::healthy;
        result.message = "Console logger operational";
        result.metadata["message_count"] = std::to_string(message_count_.load());
        return result;
    }
References kcenon::monitoring::health_check_result::message, message_count_, kcenon::monitoring::health_check_result::metadata, and kcenon::monitoring::health_check_result::status.
is_enabled()
bool console_logger::is_enabled (log_level level) const inline override
Examples
bidirectional_di_example.cpp.
Definition at line 84 of file bidirectional_di_example.cpp.
{
        return level >= min_level_;
    }
References min_level_.
Referenced by get_monitoring_data().
log() [1/3]
common::VoidResult console_logger::log (const log_entry & entry) inline override
Definition at line 80 of file bidirectional_di_example.cpp.
{
        return log(entry.level, entry.message, entry.file, entry.line, entry.function);
    }
References log().
log() [2/3]
common::VoidResult console_logger::log (log_level level, const std::string & message) inline override
Examples
bidirectional_di_example.cpp.
Definition at line 44 of file bidirectional_di_example.cpp.
{
        if (level < min_level_) {
            return std::monostate{};
        }
        message_count_++;
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);
        std::tm tm{};
#ifdef _MSC_VER
        localtime_s(&tm, &time_t);
#else
        localtime_r(&time_t, &tm);
#endif
        std::cout << "[" << std::put_time(&tm, "%Y-%m-%d %H:%M:%S") << "] "
                  << "[" << to_string(level) << "] "
                  << message << std::endl;
        // If monitor is injected, record logging metrics
        if (monitor_) {
            monitor_->record_metric("messages_logged", message_count_.load());
        }
        return std::monostate{};
    }
References message_count_, min_level_, monitor_, and kcenon::monitoring::to_string().
Referenced by log(), and log().
log() [3/3]
common::VoidResult console_logger::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline override
Definition at line 72 of file bidirectional_di_example.cpp.
{
        std::string detailed_message = message + " [" + file + ":" +
                                      std::to_string(line) + " in " + function + "]";
        return log(level, detailed_message);
    }
References log().
set_level()
common::VoidResult console_logger::set_level (log_level level) inline override
Examples
bidirectional_di_example.cpp.
Definition at line 88 of file bidirectional_di_example.cpp.
{
        min_level_ = level;
        return std::monostate{};
    }
References min_level_.
set_monitor()
void console_logger::set_monitor (std::shared_ptr< IMonitor > monitor) inline
Examples
bidirectional_di_example.cpp.
Definition at line 124 of file bidirectional_di_example.cpp.
{
        monitor_ = std::move(monitor);
    }
References monitor_.
Member Data Documentation
message_count_
std::atomic<int> console_logger::message_count_ {0} private
Examples
bidirectional_di_example.cpp.
Definition at line 39 of file bidirectional_di_example.cpp.
{0};
Referenced by get_message_count(), get_monitoring_data(), health_check(), and log().
min_level_
log_level console_logger::min_level_ {log_level::info} private
Examples
bidirectional_di_example.cpp.
Definition at line 40 of file bidirectional_di_example.cpp.
{log_level::info};
Referenced by get_level(), is_enabled(), log(), and set_level().
monitor_
std::shared_ptr<IMonitor> console_logger::monitor_ private
Examples
bidirectional_di_example.cpp.
Definition at line 41 of file bidirectional_di_example.cpp.
Referenced by log(), and set_monitor().
The documentation for this class was generated from the following file:
examples/bidirectional_di_example.cpp