Monitoring System: kcenon::monitoring::composite_health_check Class Reference
kcenon::monitoring::composite_health_check Class Reference
Composite health check that aggregates multiple sub-checks.
#include <health_monitor.h>
Public Member Functions
composite_health_check (const std::string &name, health_check_type type, bool all_required=true)
Construct a composite health check.
std::string get_name () const override
Get the human-readable name of this health check.
health_check_type get_type () const override
Get the type of this health check (liveness, readiness, or startup).
void add_check (std::shared_ptr< health_check > check)
Add a child health check to this composite.
health_check_result check () override
Execute all child checks and return the aggregate result.
Public Member Functions inherited from kcenon::monitoring::health_check
virtual ~health_check ()=default
virtual std::chrono::milliseconds get_timeout () const
Get the maximum time allowed for this check to complete.
virtual bool is_critical () const
Whether this check is critical for overall system health.
Private Member Functions
health_check_result check_all_required (const std::vector< health_check_result > &results)
health_check_result check_any_required (const std::vector< health_check_result > &results)
Private Attributes
std::string name_
health_check_type type_
bool all_required_
std::vector< std::shared_ptr< health_check > > checks_
std::mutex mutex_
Detailed Description
Composite health check that aggregates multiple sub-checks.
Evaluates a collection of child health checks and returns an aggregate result. Supports two aggregation modes:
all_required (AND): All checks must pass for healthy status
any_required (OR): At least one check must pass for healthy status
Thread Safety
Thread-safe. Uses a mutex to protect the checks_ collection.
See also
health_check For the base interface
Definition at line 219 of file health_monitor.h.
Constructor & Destructor Documentation
composite_health_check()
kcenon::monitoring::composite_health_check::composite_health_check (const std::string & name, health_check_type type, bool all_required = true) inline
Construct a composite health check.
Parameters
name Human-readable name for this composite check
type The check type (liveness, readiness, or startup)
all_required If true (default), all sub-checks must pass (AND mode); if false, at least one must pass (OR mode)
Definition at line 228 of file health_monitor.h.
        : name_(name)
        , type_(type)
        , all_required_(all_required) {}
Member Function Documentation
add_check()
void kcenon::monitoring::composite_health_check::add_check (std::shared_ptr< health_check > check) inline
Add a child health check to this composite.
Parameters
check The health check to add
Definition at line 244 of file health_monitor.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        checks_.push_back(std::move(check));
    }
References check(), checks_, and mutex_.
Referenced by TEST_F(), and TEST_F().
check()
health_check_result kcenon::monitoring::composite_health_check::check () inline override virtual
Execute all child checks and return the aggregate result.
Returns
Aggregate health_check_result based on the aggregation mode
Implements kcenon::monitoring::health_check.
Definition at line 253 of file health_monitor.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (checks_.empty()) {
            return health_check_result::healthy("No checks configured");
        }
        std::vector<health_check_result> results;
        results.reserve(checks_.size());
        for (const auto& chk : checks_) {
            results.push_back(chk->check());
        }
        if (all_required_) {
            return check_all_required(results);
        } else {
            return check_any_required(results);
        }
    }
References all_required_, check_all_required(), check_any_required(), checks_, kcenon::monitoring::health_check_result::healthy(), and mutex_.
Referenced by add_check(), TEST_F(), and TEST_F().
check_all_required()
health_check_result kcenon::monitoring::composite_health_check::check_all_required (const std::vector< health_check_result > & results) inline private
Definition at line 275 of file health_monitor.h.
{
        bool has_unhealthy = false;
        bool has_degraded = false;
        std::string message;
        for (const auto& result : results) {
            if (result.status == health_status::unhealthy) {
                has_unhealthy = true;
                message += result.message + "; ";
            } else if (result.status == health_status::degraded) {
                has_degraded = true;
                message += result.message + "; ";
            }
        }
        if (has_unhealthy) {
            return health_check_result::unhealthy(message.empty() ? "One or more checks failed" : message);
        }
        if (has_degraded) {
            return health_check_result::degraded(message.empty() ? "One or more checks degraded" : message);
        }
        return health_check_result::healthy("All checks passed");
    }
References kcenon::monitoring::health_check_result::degraded(), kcenon::monitoring::degraded, kcenon::monitoring::health_check_result::healthy(), kcenon::monitoring::health_check_result::unhealthy(), and kcenon::monitoring::unhealthy.
Referenced by check().
check_any_required()
health_check_result kcenon::monitoring::composite_health_check::check_any_required (const std::vector< health_check_result > & results) inline private
Definition at line 299 of file health_monitor.h.
{
        bool any_healthy = false;
        std::string message;
        for (const auto& result : results) {
            if (result.status == health_status::healthy) {
                any_healthy = true;
                break;
            }
            message += result.message + "; ";
        }
        if (any_healthy) {
            return health_check_result::healthy("At least one check passed");
        }
        return health_check_result::unhealthy(message.empty() ? "All checks failed" : message);
    }
References kcenon::monitoring::health_check_result::healthy(), kcenon::monitoring::healthy, and kcenon::monitoring::health_check_result::unhealthy().
Referenced by check().
get_name()
std::string kcenon::monitoring::composite_health_check::get_name () const inline override virtual
Get the human-readable name of this health check.
Returns
The health check name
Implements kcenon::monitoring::health_check.
Definition at line 236 of file health_monitor.h.
{ return name_; }
References name_.
get_type()
health_check_type kcenon::monitoring::composite_health_check::get_type () const inline override virtual
Get the type of this health check (liveness, readiness, or startup).
Returns
The health check type
Implements kcenon::monitoring::health_check.
Definition at line 238 of file health_monitor.h.
{ return type_; }
References type_.
Member Data Documentation
all_required_
bool kcenon::monitoring::composite_health_check::all_required_ private
Definition at line 319 of file health_monitor.h.
Referenced by check().
checks_
std::vector<std::shared_ptr<health_check> > kcenon::monitoring::composite_health_check::checks_ private
Definition at line 320 of file health_monitor.h.
Referenced by add_check(), and check().
mutex_
std::mutex kcenon::monitoring::composite_health_check::mutex_ mutable private
Definition at line 321 of file health_monitor.h.
Referenced by add_check(), and check().
name_
std::string kcenon::monitoring::composite_health_check::name_ private
Definition at line 317 of file health_monitor.h.
Referenced by get_name().
type_
health_check_type kcenon::monitoring::composite_health_check::type_ private
Definition at line 318 of file health_monitor.h.
Referenced by get_type().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/health/health_monitor.h