Monitoring System: kcenon::monitoring::file_notifier Class Reference
kcenon::monitoring::file_notifier Class Reference
Writes alerts to a file.
#include <alert_notifiers.h>
Public Member Functions
file_notifier (std::string file_path, std::shared_ptr< alert_formatter > formatter=nullptr)
Construct file notifier.
std::string name () const override
Get notifier name.
common::VoidResult notify (const alert &a) override
Send a notification for an alert.
common::VoidResult notify_group (const alert_group &group) override
Send a notification for an alert group.
bool is_ready () const override
Check if notifier is ready.
Public Member Functions inherited from kcenon::monitoring::alert_notifier
virtual ~alert_notifier ()=default
Private Member Functions
common::VoidResult write_to_file (const std::string &content)
Private Attributes
std::string file_path_
std::shared_ptr< alert_formatter > formatter_
std::mutex mutex_
Detailed Description
Writes alerts to a file.
Appends alert notifications to a specified file, useful for logging or audit trails.
Definition at line 299 of file alert_notifiers.h.
Constructor & Destructor Documentation
file_notifier()
kcenon::monitoring::file_notifier::file_notifier (std::string file_path, std::shared_ptr< alert_formatter > formatter = nullptr) inline explicit
Construct file notifier.
Parameters
file_path Path to output file
formatter Alert formatter (default: text)
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 306 of file alert_notifiers.h.
        : file_path_(std::move(file_path))
        , formatter_(formatter ? formatter : std::make_shared<text_alert_formatter>()) {}
Member Function Documentation
is_ready()
bool kcenon::monitoring::file_notifier::is_ready () const inline override virtual
Check if notifier is ready.
Returns
True if ready to send notifications
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 323 of file alert_notifiers.h.
{
        return !file_path_.empty();
    }
References file_path_.
name()
std::string kcenon::monitoring::file_notifier::name () const inline override virtual
Get notifier name.
Returns
Notifier name
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 311 of file alert_notifiers.h.
{
        return "file:" + file_path_;
    }
References file_path_.
notify()
common::VoidResult kcenon::monitoring::file_notifier::notify (const alert & a) inline override virtual
Send a notification for an alert.
Parameters
a Alert to notify about
Returns
Result indicating success or failure
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 315 of file alert_notifiers.h.
{
        return write_to_file(formatter_->format(a));
    }
References formatter_, and write_to_file().
notify_group()
common::VoidResult kcenon::monitoring::file_notifier::notify_group (const alert_group & group) inline override virtual
Send a notification for an alert group.
Parameters
group Alert group to notify about
Returns
Result indicating success or failure
Implements kcenon::monitoring::alert_notifier.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 319 of file alert_notifiers.h.
{
        return write_to_file(formatter_->format_group(group));
    }
References formatter_, and write_to_file().
write_to_file()
common::VoidResult kcenon::monitoring::file_notifier::write_to_file (const std::string & content) inline private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 328 of file alert_notifiers.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        std::ofstream file(file_path_, std::ios::app);
        if (!file) {
            return common::VoidResult::err(static_cast<int>(monitoring_error_code::storage_write_failed),
                                   "Failed to open file: " + file_path_);
        }
        auto now = std::chrono::system_clock::now();
        auto time_t_now = std::chrono::system_clock::to_time_t(now);
        char time_buf[26];
#ifdef _MSC_VER
        ctime_s(time_buf, sizeof(time_buf), &time_t_now);
#else
        std::strncpy(time_buf, std::ctime(&time_t_now), sizeof(time_buf) - 1);
        time_buf[sizeof(time_buf) - 1] = '\0';
#endif
        file << "=== " << time_buf;
        file << content << "\n\n";
        return common::ok();
    }
References file_path_, mutex_, and kcenon::monitoring::storage_write_failed.
Referenced by notify(), and notify_group().
Member Data Documentation
file_path_
std::string kcenon::monitoring::file_notifier::file_path_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 353 of file alert_notifiers.h.
Referenced by is_ready(), name(), and write_to_file().
formatter_
std::shared_ptr<alert_formatter> kcenon::monitoring::file_notifier::formatter_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 354 of file alert_notifiers.h.
Referenced by notify(), and notify_group().
mutex_
std::mutex kcenon::monitoring::file_notifier::mutex_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h.
Definition at line 355 of file alert_notifiers.h.
Referenced by write_to_file().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/alert/alert_notifiers.h