Monitoring System: kcenon::monitoring::collector_base< Derived > Class Template Reference
kcenon::monitoring::collector_base< Derived > Class Template Reference
CRTP base class for metric collectors.
#include <collector_base.h>
Public Member Functions
collector_base ()=default
virtual ~collector_base ()=default
collector_base (const collector_base &)=delete
collector_base & operator= (const collector_base &)=delete
collector_base (collector_base &&)=delete
collector_base & operator= (collector_base &&)=delete
bool initialize (const config_map &config)
Initialize the collector with configuration.
std::vector< metric > collect ()
Collect metrics from the data source.
std::string get_name () const
Get the name of this collector.
std::vector< std::string > get_metric_types () const
Get supported metric types.
bool is_healthy () const
Check if the collector is healthy.
stats_map get_statistics () const
Get collector statistics.
bool is_enabled () const
Check if collector is enabled.
size_t get_collection_count () const
Get collection count.
size_t get_collection_errors () const
Get error count.
Protected Member Functions
metric create_base_metric (const std::string &name, double value, const std::unordered_map< std::string, std::string > &tags={}, const std::string &="") const
Create a metric with common tags.
Protected Attributes
bool enabled_ {true}
std::mutex stats_mutex_
std::atomic< size_t > collection_count_ {0}
std::atomic< size_t > collection_errors_ {0}
Private Member Functions
Derived & derived ()
Get reference to derived class (CRTP helper)
const Derived & derived () const
Detailed Description
template<typename Derived>
class kcenon::monitoring::collector_base< Derived >
CRTP base class for metric collectors.
This template class implements common functionality shared by all collectors:
Configuration parsing (enabled state)
Collection with error handling and statistics
Health monitoring
Statistics tracking (collection count, error count)
Template Parameters
Derived The derived collector class (CRTP pattern)
Definition at line 83 of file collector_base.h.
Constructor & Destructor Documentation
collector_base() [1/3]
template<typename Derived > kcenon::monitoring::collector_base< Derived >::collector_base () default
~collector_base()
template<typename Derived > virtual kcenon::monitoring::collector_base< Derived >::~collector_base () virtual default
collector_base() [2/3]
template<typename Derived > kcenon::monitoring::collector_base< Derived >::collector_base (const collector_base< Derived > &) delete
collector_base() [3/3]
template<typename Derived > kcenon::monitoring::collector_base< Derived >::collector_base (collector_base< Derived > &&) delete
Member Function Documentation
collect()
template<typename Derived > std::vector< metric > kcenon::monitoring::collector_base< Derived >::collect () inline
Collect metrics from the data source.
Returns
Collection of metrics
Definition at line 113 of file collector_base.h.
{
        if (!enabled_) {
            return {};
        }
        try {
            auto metrics = derived().do_collect();
            ++collection_count_;
            return metrics;
        } catch (...) {
            ++collection_errors_;
            return {};
        }
    }
References kcenon::monitoring::collector_base< Derived >::collection_count_, kcenon::monitoring::collector_base< Derived >::collection_errors_, kcenon::monitoring::collector_base< Derived >::derived(), and kcenon::monitoring::collector_base< Derived >::enabled_.
create_base_metric()
template<typename Derived > metric kcenon::monitoring::collector_base< Derived >::create_base_metric (const std::string & name, double value, const std::unordered_map< std::string, std::string > & tags = {}, const std::string & = "") const inline protected
Create a metric with common tags.
Parameters
name Metric name
value Metric value
tags Additional tags
unit Optional unit string (not used, for documentation)
Returns
Created metric
Definition at line 201 of file collector_base.h.
                                                                                   {},
                              const std::string& /* unit */ = "") const {
        metric m;
        m.name = name;
        m.value = value;
        m.timestamp = std::chrono::system_clock::now();
        m.tags = tags;
        m.tags["collector"] = Derived::collector_name;
        return m;
    }
derived() [1/2]
template<typename Derived > Derived & kcenon::monitoring::collector_base< Derived >::derived () inline private
Get reference to derived class (CRTP helper)
Definition at line 225 of file collector_base.h.
{ return static_cast<Derived&>(*this); }
Referenced by kcenon::monitoring::collector_base< Derived >::collect(), kcenon::monitoring::collector_base< Derived >::get_metric_types(), kcenon::monitoring::collector_base< Derived >::get_statistics(), kcenon::monitoring::collector_base< Derived >::initialize(), and kcenon::monitoring::collector_base< Derived >::is_healthy().
derived() [2/2]
template<typename Derived > const Derived & kcenon::monitoring::collector_base< Derived >::derived () const inline private
Definition at line 226 of file collector_base.h.
{ return static_cast<const Derived&>(*this); }
get_collection_count()
template<typename Derived > size_t kcenon::monitoring::collector_base< Derived >::get_collection_count () const inline
Get collection count.
Returns
Number of successful collections
Definition at line 184 of file collector_base.h.
{ return collection_count_.load(); }
References kcenon::monitoring::collector_base< Derived >::collection_count_.
get_collection_errors()
template<typename Derived > size_t kcenon::monitoring::collector_base< Derived >::get_collection_errors () const inline
Get error count.
Returns
Number of failed collections
Definition at line 190 of file collector_base.h.
{ return collection_errors_.load(); }
References kcenon::monitoring::collector_base< Derived >::collection_errors_.
get_metric_types()
template<typename Derived > std::vector< std::string > kcenon::monitoring::collector_base< Derived >::get_metric_types () const inline
Get supported metric types.
Returns
Vector of supported metric type names
Definition at line 140 of file collector_base.h.
{
        return derived().do_get_metric_types();
    }
References kcenon::monitoring::collector_base< Derived >::derived().
get_name()
template<typename Derived > std::string kcenon::monitoring::collector_base< Derived >::get_name () const inline
Get the name of this collector.
Returns
Collector name from Derived::collector_name
Definition at line 132 of file collector_base.h.
{
        return Derived::collector_name;
    }
get_statistics()
template<typename Derived > stats_map kcenon::monitoring::collector_base< Derived >::get_statistics () const inline
Get collector statistics.
Returns
Map of statistic name to value
Definition at line 159 of file collector_base.h.
{
        std::lock_guard<std::mutex> lock(stats_mutex_);
        stats_map stats;
        // Common statistics
        stats["enabled"] = enabled_ ? 1.0 : 0.0;
        stats["collection_count"] = static_cast<double>(collection_count_.load());
        stats["collection_errors"] = static_cast<double>(collection_errors_.load());
        // Let derived class add specific statistics
        derived().do_add_statistics(stats);
        return stats;
    }
References kcenon::monitoring::collector_base< Derived >::collection_count_, kcenon::monitoring::collector_base< Derived >::collection_errors_, kcenon::monitoring::collector_base< Derived >::derived(), kcenon::monitoring::collector_base< Derived >::enabled_, and kcenon::monitoring::collector_base< Derived >::stats_mutex_.
initialize()
template<typename Derived > bool kcenon::monitoring::collector_base< Derived >::initialize (const config_map & config) inline
Initialize the collector with configuration.
Parameters
config Configuration options (common: "enabled")
Returns
true if initialization successful
Definition at line 99 of file collector_base.h.
{
        // Parse common configuration
        if (auto it = config.find("enabled"); it != config.end()) {
            enabled_ = (it->second == "true" || it->second == "1");
        }
        // Delegate to derived class for specific initialization
        return derived().do_initialize(config);
    }
References kcenon::monitoring::collector_base< Derived >::derived(), and kcenon::monitoring::collector_base< Derived >::enabled_.
is_enabled()
template<typename Derived > bool kcenon::monitoring::collector_base< Derived >::is_enabled () const inline
Check if collector is enabled.
Returns
true if enabled
Definition at line 178 of file collector_base.h.
{ return enabled_; }
References kcenon::monitoring::collector_base< Derived >::enabled_.
is_healthy()
template<typename Derived > bool kcenon::monitoring::collector_base< Derived >::is_healthy () const inline
Check if the collector is healthy.
Returns
true if collector is operational
Definition at line 148 of file collector_base.h.
{
        if (!enabled_) {
            return true;  // Disabled collectors are considered healthy
        }
        return derived().is_available();
    }
References kcenon::monitoring::collector_base< Derived >::derived(), and kcenon::monitoring::collector_base< Derived >::enabled_.
operator=() [1/2]
template<typename Derived > collector_base & kcenon::monitoring::collector_base< Derived >::operator= (collector_base< Derived > &&) delete
operator=() [2/2]
template<typename Derived > collector_base & kcenon::monitoring::collector_base< Derived >::operator= (const collector_base< Derived > &) delete
Member Data Documentation
collection_count_
template<typename Derived > std::atomic<size_t> kcenon::monitoring::collector_base< Derived >::collection_count_ {0} protected
Definition at line 218 of file collector_base.h.
{0};
Referenced by kcenon::monitoring::collector_base< Derived >::collect(), kcenon::monitoring::collector_base< Derived >::get_collection_count(), and kcenon::monitoring::collector_base< Derived >::get_statistics().
collection_errors_
template<typename Derived > std::atomic<size_t> kcenon::monitoring::collector_base< Derived >::collection_errors_ {0} protected
Definition at line 219 of file collector_base.h.
{0};
Referenced by kcenon::monitoring::collector_base< Derived >::collect(), kcenon::monitoring::collector_base< Derived >::get_collection_errors(), and kcenon::monitoring::collector_base< Derived >::get_statistics().
enabled_
template<typename Derived > bool kcenon::monitoring::collector_base< Derived >::enabled_ {true} protected
Definition at line 214 of file collector_base.h.
{true};
Referenced by kcenon::monitoring::collector_base< Derived >::collect(), kcenon::monitoring::collector_base< Derived >::get_statistics(), kcenon::monitoring::collector_base< Derived >::initialize(), kcenon::monitoring::collector_base< Derived >::is_enabled(), and kcenon::monitoring::collector_base< Derived >::is_healthy().
stats_mutex_
template<typename Derived > std::mutex kcenon::monitoring::collector_base< Derived >::stats_mutex_ mutable protected
Definition at line 217 of file collector_base.h.
Referenced by kcenon::monitoring::collector_base< Derived >::get_statistics().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/collectors/collector_base.h