Monitoring System: kcenon::monitoring::performance_profiler Class Reference
kcenon::monitoring::performance_profiler Class Reference
Performance profiler for code sections.
#include <performance_monitor.h>
Classes
struct profile_data
Public Member Functions
common::Result< bool > record_sample (const std::string &operation_name, std::chrono::nanoseconds duration, bool success=true)
Record a performance sample.
common::Result< performance_metrics > get_metrics (const std::string &operation_name) const
Get performance metrics for an operation.
std::vector< performance_metrics > get_all_metrics () const
Get all performance metrics.
common::Result< bool > clear_samples (const std::string &operation_name)
Clear samples for an operation.
void clear_all_samples ()
Clear all samples.
void set_enabled (bool enabled)
Enable or disable profiling.
bool is_enabled () const
Check if profiling is enabled.
void set_max_samples (std::size_t max_samples)
Set maximum samples per operation.
void set_lock_free_mode (bool enable)
Enable lock-free collection path (Sprint 3-4)
bool is_lock_free_mode () const
Check if lock-free mode is enabled.
Private Attributes
std::unordered_map< std::string, std::unique_ptr< profile_data > > profiles_
std::shared_mutex profiles_mutex_
std::atomic< bool > enabled_ {true}
std::size_t max_samples_per_operation_ {10000}
std::size_t max_profiles_ {10000}
std::atomic< bool > use_lock_free_path_ {false}
Detailed Description
Performance profiler for code sections.
Thread Safety:
Thread-safe. All public methods can be called concurrently.
Uses std::shared_mutex for read/write synchronization on profiles
Uses per-profile std::mutex for sample data protection
Uses std::atomic for counters and flags
Definition at line 137 of file performance_monitor.h.
Member Function Documentation
clear_all_samples()
void kcenon::monitoring::performance_profiler::clear_all_samples ()
Clear all samples.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by kcenon::monitoring::performance_monitor::reset(), and PerformanceMonitoringTest::SetUp().
clear_samples()
common::Result< bool > kcenon::monitoring::performance_profiler::clear_samples (const std::string & operation_name)
Clear samples for an operation.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
get_all_metrics()
std::vector< performance_metrics > kcenon::monitoring::performance_profiler::get_all_metrics () const
Get all performance metrics.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
get_metrics()
common::Result< performance_metrics > kcenon::monitoring::performance_profiler::get_metrics (const std::string & operation_name) const
Get performance metrics for an operation.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by kcenon::monitoring::performance_benchmark::run().
is_enabled()
bool kcenon::monitoring::performance_profiler::is_enabled () const inline
Check if profiling is enabled.
Returns
True if profiling is currently enabled
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 201 of file performance_monitor.h.
{ return enabled_; }
References enabled_.
is_lock_free_mode()
bool kcenon::monitoring::performance_profiler::is_lock_free_mode () const inline
Check if lock-free mode is enabled.
Returns
True if lock-free collection path is active
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 228 of file performance_monitor.h.
{
        return use_lock_free_path_;
    }
References use_lock_free_path_.
record_sample()
common::Result< bool > kcenon::monitoring::performance_profiler::record_sample (const std::string & operation_name, std::chrono::nanoseconds duration, bool success = true)
Record a performance sample.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by kcenon::monitoring::scoped_timer::complete(), and kcenon::monitoring::performance_benchmark::run().
set_enabled()
void kcenon::monitoring::performance_profiler::set_enabled (bool enabled) inline
Enable or disable profiling.
Parameters
enabled True to enable profiling, false to disable
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 195 of file performance_monitor.h.
{ enabled_ = enabled; }
References enabled_.
Referenced by kcenon::monitoring::performance_monitor::set_enabled().
set_lock_free_mode()
void kcenon::monitoring::performance_profiler::set_lock_free_mode (bool enable) inline
Enable lock-free collection path (Sprint 3-4)
When enabled, uses thread-local buffers for lock-free metric collection. This provides significantly better performance under high concurrency.
Parameters
enable true to enable lock-free path, false for legacy path
Note
Lock-free path is experimental in Sprint 3-4
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 220 of file performance_monitor.h.
{
        use_lock_free_path_ = enable;
    }
References use_lock_free_path_.
set_max_samples()
void kcenon::monitoring::performance_profiler::set_max_samples (std::size_t max_samples) inline
Set maximum samples per operation.
Parameters
max_samples Maximum number of samples to retain per operation
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 207 of file performance_monitor.h.
{
        max_samples_per_operation_ = max_samples;
    }
References max_samples_per_operation_.
Member Data Documentation
enabled_
std::atomic<bool> kcenon::monitoring::performance_profiler::enabled_ {true} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 152 of file performance_monitor.h.
{true};
Referenced by is_enabled(), and set_enabled().
max_profiles_
std::size_t kcenon::monitoring::performance_profiler::max_profiles_ {10000} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 154 of file performance_monitor.h.
{10000};  // LRU eviction threshold
max_samples_per_operation_
std::size_t kcenon::monitoring::performance_profiler::max_samples_per_operation_ {10000} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 153 of file performance_monitor.h.
{10000};
Referenced by set_max_samples().
profiles_
std::unordered_map<std::string, std::unique_ptr<profile_data> > kcenon::monitoring::performance_profiler::profiles_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 150 of file performance_monitor.h.
profiles_mutex_
std::shared_mutex kcenon::monitoring::performance_profiler::profiles_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 151 of file performance_monitor.h.
use_lock_free_path_
std::atomic<bool> kcenon::monitoring::performance_profiler::use_lock_free_path_ {false} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 157 of file performance_monitor.h.
{false};
Referenced by is_lock_free_mode(), and set_lock_free_mode().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/core/performance_monitor.h