Monitoring System: monitor_factory Class Reference
monitor_factory Class Reference
Monitor factory implementing singleton pattern with DI.
Public Member Functions
void set_shared_logger (std::shared_ptr< ILogger > logger)
std::shared_ptr< IMonitor > get_monitor () override
std::shared_ptr< IMonitor > create_monitor (const std::string &name) override
std::vector< std::string > list_monitors () const
size_t monitor_count () const
void reset ()
Static Public Member Functions
static std::shared_ptr< monitor_factory > instance ()
Private Member Functions
monitor_factory ()=default
Private Attributes
std::shared_ptr< IMonitor > default_monitor_
std::unordered_map< std::string, std::shared_ptr< IMonitor > > named_monitors_
std::shared_ptr< ILogger > shared_logger_
std::mutex factory_mutex_
Static Private Attributes
static std::shared_ptr< monitor_factory > instance_ = nullptr
static std::mutex instance_mutex_
Detailed Description
Monitor factory implementing singleton pattern with DI.
Examples
monitor_factory_pattern_example.cpp.
Definition at line 30 of file monitor_factory_pattern_example.cpp.
Constructor & Destructor Documentation
monitor_factory()
monitor_factory::monitor_factory () private default
Examples
monitor_factory_pattern_example.cpp.
Referenced by instance().
Member Function Documentation
create_monitor()
std::shared_ptr< IMonitor > monitor_factory::create_monitor (const std::string & name) inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 70 of file monitor_factory_pattern_example.cpp.
{
        std::lock_guard<std::mutex> lock(factory_mutex_);
        auto it = named_monitors_.find(name);
        if (it != named_monitors_.end()) {
            return it->second;
        }
        auto monitor = std::make_shared<performance_monitor>();
        named_monitors_[name] = monitor;
        return monitor;
    }
References factory_mutex_, and named_monitors_.
get_monitor()
std::shared_ptr< IMonitor > monitor_factory::get_monitor () inline override
Examples
monitor_factory_pattern_example.cpp.
Definition at line 60 of file monitor_factory_pattern_example.cpp.
{
        std::lock_guard<std::mutex> lock(factory_mutex_);
        if (!default_monitor_) {
            default_monitor_ = std::make_shared<performance_monitor>();
        }
        return default_monitor_;
    }
References default_monitor_, and factory_mutex_.
instance()
static std::shared_ptr< monitor_factory > monitor_factory::instance () inline static
Examples
monitor_factory_pattern_example.cpp.
Definition at line 43 of file monitor_factory_pattern_example.cpp.
{
        std::lock_guard<std::mutex> lock(instance_mutex_);
        if (!instance_) {
            instance_ = std::shared_ptr<monitor_factory>(new monitor_factory());
        }
        return instance_;
    }
References instance_, instance_mutex_, and monitor_factory().
Referenced by example_1_basic_factory(), example_2_named_monitors(), example_3_factory_with_logger(), example_4_monitor_reuse(), example_5_provider_interface(), example_6_aggregating_pattern(), and example_7_factory_lifecycle().
list_monitors()
std::vector< std::string > monitor_factory::list_monitors () const inline
Examples
monitor_factory_pattern_example.cpp.
Definition at line 83 of file monitor_factory_pattern_example.cpp.
{
        std::lock_guard<std::mutex> lock(factory_mutex_);
        std::vector<std::string> names;
        names.reserve(named_monitors_.size());
        for (const auto& [name, _] : named_monitors_) {
            names.push_back(name);
        }
        return names;
    }
References factory_mutex_, and named_monitors_.
monitor_count()
size_t monitor_factory::monitor_count () const inline
Examples
monitor_factory_pattern_example.cpp.
Definition at line 95 of file monitor_factory_pattern_example.cpp.
{
        std::lock_guard<std::mutex> lock(factory_mutex_);
        return named_monitors_.size() + (default_monitor_ ? 1 : 0);
    }
References default_monitor_, factory_mutex_, and named_monitors_.
reset()
void monitor_factory::reset () inline
Examples
monitor_factory_pattern_example.cpp.
Definition at line 100 of file monitor_factory_pattern_example.cpp.
                 {
        std::lock_guard<std::mutex> lock(factory_mutex_);
        default_monitor_.reset();
        named_monitors_.clear();
    }
References default_monitor_, factory_mutex_, and named_monitors_.
set_shared_logger()
void monitor_factory::set_shared_logger (std::shared_ptr< ILogger > logger) inline
Examples
monitor_factory_pattern_example.cpp.
Definition at line 51 of file monitor_factory_pattern_example.cpp.
{
        std::lock_guard<std::mutex> lock(factory_mutex_);
        shared_logger_ = logger;
        // Note: Logger injection not available in performance_monitor yet
        // Future enhancement: Add ILogger support to performance_monitor
    }
References factory_mutex_, and shared_logger_.
Member Data Documentation
default_monitor_
std::shared_ptr<IMonitor> monitor_factory::default_monitor_ private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 35 of file monitor_factory_pattern_example.cpp.
Referenced by get_monitor(), monitor_count(), and reset().
factory_mutex_
std::mutex monitor_factory::factory_mutex_ mutable private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 38 of file monitor_factory_pattern_example.cpp.
Referenced by create_monitor(), get_monitor(), list_monitors(), monitor_count(), reset(), and set_shared_logger().
instance_
std::shared_ptr< monitor_factory > monitor_factory::instance_ = nullptr static private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 32 of file monitor_factory_pattern_example.cpp.
Referenced by instance().
instance_mutex_
std::mutex monitor_factory::instance_mutex_ static private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 33 of file monitor_factory_pattern_example.cpp.
Referenced by instance().
named_monitors_
std::unordered_map<std::string, std::shared_ptr<IMonitor> > monitor_factory::named_monitors_ private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 36 of file monitor_factory_pattern_example.cpp.
Referenced by create_monitor(), list_monitors(), monitor_count(), and reset().
shared_logger_
std::shared_ptr<ILogger> monitor_factory::shared_logger_ private
Examples
monitor_factory_pattern_example.cpp.
Definition at line 37 of file monitor_factory_pattern_example.cpp.
Referenced by set_shared_logger().
The documentation for this class was generated from the following file:
examples/monitor_factory_pattern_example.cpp