Monitoring System: kcenon::monitoring::otlp_grpc_exporter Class Reference
kcenon::monitoring::otlp_grpc_exporter Class Reference
OTLP gRPC trace exporter.
#include <otlp_grpc_exporter.h>
Public Member Functions
otlp_grpc_exporter (const otlp_grpc_config &config)
Construct with configuration.
otlp_grpc_exporter (const otlp_grpc_config &config, std::unique_ptr< grpc_transport > transport)
Construct with configuration and custom transport.
common::VoidResult start ()
Start the exporter.
common::VoidResult export_spans (const std::vector< trace_span > &spans) override
Export a batch of spans.
common::VoidResult flush () override
Flush pending exports.
common::VoidResult shutdown () override
Shutdown the exporter.
std::unordered_map< std::string, std::size_t > get_stats () const override
Get exporter statistics.
otlp_exporter_stats get_detailed_stats () const
Get detailed statistics.
bool is_running () const
Check if exporter is running.
const otlp_grpc_config & config () const
Get configuration.
Public Member Functions inherited from kcenon::monitoring::trace_exporter_interface
virtual ~trace_exporter_interface ()=default
Private Member Functions
common::Result< grpc_response > send_with_retry (const grpc_request &request)
Static Private Member Functions
static bool is_retryable_error (int status_code)
static std::pair< std::string, uint16_t > parse_endpoint (const std::string &endpoint)
Private Attributes
otlp_grpc_config config_
std::unique_ptr< grpc_transport > transport_
std::atomic< bool > running_ {false}
std::atomic< std::size_t > exported_spans_ {0}
std::atomic< std::size_t > dropped_spans_ {0}
std::atomic< std::size_t > failed_exports_ {0}
std::atomic< std::size_t > retries_ {0}
std::mutex stats_mutex_
std::chrono::microseconds total_export_time_ {0}
Detailed Description
OTLP gRPC trace exporter.
Exports trace spans to an OpenTelemetry-compatible backend via gRPC. Implements batching, retry with exponential backoff, and async export.
Definition at line 380 of file otlp_grpc_exporter.h.
Constructor & Destructor Documentation
otlp_grpc_exporter() [1/2]
kcenon::monitoring::otlp_grpc_exporter::otlp_grpc_exporter (const otlp_grpc_config & config) inline explicit
Construct with configuration.
Parameters
config Exporter configuration
Definition at line 397 of file otlp_grpc_exporter.h.
        : config_(config), transport_(create_default_grpc_transport()) {}
otlp_grpc_exporter() [2/2]
kcenon::monitoring::otlp_grpc_exporter::otlp_grpc_exporter (const otlp_grpc_config & config, std::unique_ptr< grpc_transport > transport) inline
Construct with configuration and custom transport.
Parameters
config Exporter configuration
transport Custom gRPC transport (for testing)
Definition at line 405 of file otlp_grpc_exporter.h.
        : config_(config), transport_(std::move(transport)) {}
Member Function Documentation
config()
const otlp_grpc_config & kcenon::monitoring::otlp_grpc_exporter::config () const inline
Get configuration.
Definition at line 550 of file otlp_grpc_exporter.h.
{
        return config_;
    }
References config_.
export_spans()
common::VoidResult kcenon::monitoring::otlp_grpc_exporter::export_spans (const std::vector< trace_span > & spans) inline override virtual
Export a batch of spans.
Parameters
spans Spans to export
Returns
common::VoidResult indicating success or failure
Implements kcenon::monitoring::trace_exporter_interface.
Definition at line 438 of file otlp_grpc_exporter.h.
{
        if (spans.empty()) {
            return common::ok();
        }
        if (!transport_->is_connected()) {
            dropped_spans_ += spans.size();
            return common::VoidResult::err(error_info(
                monitoring_error_code::network_error,
                "Not connected to OTLP receiver",
                "otlp_grpc_exporter"
            ).to_common_error());
        }
        // Convert spans to OTLP format
        auto payload = otlp_span_converter::convert_to_otlp(
            spans,
            config_.service_name,
            config_.service_version,
            config_.resource_attributes);
        // Prepare gRPC request
        grpc_request request;
        request.service = "opentelemetry.proto.collector.trace.v1.TraceService";
        request.method = "Export";
        request.body = std::move(payload);
        request.timeout = config_.timeout;
        // Add headers/metadata
        for (const auto& [key, value] : config_.headers) {
            request.metadata[key] = value;
        }
        // Send with retry
        auto start_time = std::chrono::steady_clock::now();
        auto send_result = send_with_retry(request);
        auto end_time = std::chrono::steady_clock::now();
        {
            std::lock_guard<std::mutex> lock(stats_mutex_);
            total_export_time_ += std::chrono::duration_cast<std::chrono::microseconds>(
                end_time - start_time);
        }
        if (send_result.is_ok()) {
            exported_spans_ += spans.size();
            return common::ok();
        } else {
            failed_exports_++;
            dropped_spans_ += spans.size();
            return common::VoidResult::err(error_info(
                monitoring_error_code::operation_failed,
                "Failed to export spans: " + send_result.error().message,
                "otlp_grpc_exporter"
            ).to_common_error());
        }
    }
References kcenon::monitoring::grpc_request::body, config_, kcenon::monitoring::otlp_span_converter::convert_to_otlp(), dropped_spans_, exported_spans_, failed_exports_, kcenon::monitoring::otlp_grpc_config::headers, kcenon::monitoring::grpc_request::metadata, kcenon::monitoring::grpc_request::method, kcenon::monitoring::network_error, kcenon::monitoring::operation_failed, kcenon::monitoring::otlp_grpc_config::resource_attributes, send_with_retry(), kcenon::monitoring::grpc_request::service, kcenon::monitoring::otlp_grpc_config::service_name, kcenon::monitoring::otlp_grpc_config::service_version, stats_mutex_, kcenon::monitoring::grpc_request::timeout, kcenon::monitoring::otlp_grpc_config::timeout, kcenon::monitoring::error_info::to_common_error(), total_export_time_, and transport_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
flush()
common::VoidResult kcenon::monitoring::otlp_grpc_exporter::flush () inline override virtual
Flush pending exports.
Implements kcenon::monitoring::trace_exporter_interface.
Definition at line 499 of file otlp_grpc_exporter.h.
{
        // Synchronous exporter - nothing to flush
        return common::ok();
    }
get_detailed_stats()
otlp_exporter_stats kcenon::monitoring::otlp_grpc_exporter::get_detailed_stats () const inline
Get detailed statistics.
Definition at line 528 of file otlp_grpc_exporter.h.
{
        otlp_exporter_stats stats;
        stats.spans_exported = exported_spans_.load();
        stats.spans_dropped = dropped_spans_.load();
        stats.export_failures = failed_exports_.load();
        stats.retries = retries_.load();
        std::lock_guard<std::mutex> lock(const_cast<std::mutex&>(stats_mutex_));
        stats.total_export_time = total_export_time_;
        return stats;
    }
References dropped_spans_, kcenon::monitoring::otlp_exporter_stats::export_failures, exported_spans_, failed_exports_, kcenon::monitoring::otlp_exporter_stats::retries, retries_, kcenon::monitoring::otlp_exporter_stats::spans_dropped, kcenon::monitoring::otlp_exporter_stats::spans_exported, stats_mutex_, kcenon::monitoring::otlp_exporter_stats::total_export_time, and total_export_time_.
Referenced by TEST_F().
get_stats()
std::unordered_map< std::string, std::size_t > kcenon::monitoring::otlp_grpc_exporter::get_stats () const inline override virtual
Get exporter statistics.
Implements kcenon::monitoring::trace_exporter_interface.
Definition at line 516 of file otlp_grpc_exporter.h.
{
        return {
            {"exported_spans", exported_spans_.load()},
            {"dropped_spans", dropped_spans_.load()},
            {"failed_exports", failed_exports_.load()},
            {"retries", retries_.load()}
        };
    }
References dropped_spans_, exported_spans_, failed_exports_, and retries_.
Referenced by TEST_F(), TEST_F(), and TEST_F().
is_retryable_error()
static bool kcenon::monitoring::otlp_grpc_exporter::is_retryable_error (int status_code) inline static private
Definition at line 601 of file otlp_grpc_exporter.h.
{
        // gRPC status codes that are retryable:
        // 1 = CANCELLED, 4 = DEADLINE_EXCEEDED, 8 = RESOURCE_EXHAUSTED,
        // 10 = ABORTED, 14 = UNAVAILABLE
        return status_code == 1 || status_code == 4 || status_code == 8 ||
               status_code == 10 || status_code == 14;
    }
Referenced by send_with_retry().
is_running()
bool kcenon::monitoring::otlp_grpc_exporter::is_running () const inline
Check if exporter is running.
Definition at line 543 of file otlp_grpc_exporter.h.
{
        return running_.load();
    }
References running_.
Referenced by TEST_F().
parse_endpoint()
static std::pair< std::string, uint16_t > kcenon::monitoring::otlp_grpc_exporter::parse_endpoint (const std::string & endpoint) inline static private
Definition at line 609 of file otlp_grpc_exporter.h.
{
        std::string host = "localhost";
        uint16_t port = 4317;
        auto colon_pos = endpoint.rfind(':');
        if (colon_pos != std::string::npos) {
            host = endpoint.substr(0, colon_pos);
            try {
                port = static_cast<uint16_t>(std::stoi(endpoint.substr(colon_pos + 1)));
            } catch (...) {
                port = 4317;
            }
        } else {
            host = endpoint;
        }
        return {host, port};
    }
References kcenon::monitoring::host.
Referenced by start().
send_with_retry()
common::Result< grpc_response > kcenon::monitoring::otlp_grpc_exporter::send_with_retry (const grpc_request & request) inline private
Definition at line 555 of file otlp_grpc_exporter.h.
{
        std::size_t attempt = 0;
        auto backoff = config_.initial_backoff;
        while (attempt < config_.max_retry_attempts) {
            auto result = transport_->send(request);
            if (result.is_ok()) {
                const auto& response = result.value();
                // gRPC status 0 = OK
                if (response.status_code == 0) {
                    return result;
                }
                // Check if error is retryable
                if (is_retryable_error(response.status_code)) {
                    attempt++;
                    retries_++;
                    if (attempt < config_.max_retry_attempts) {
                        std::this_thread::sleep_for(backoff);
                        backoff = std::min(backoff * 2, config_.max_backoff);
                    }
                    continue;
                }
                // Non-retryable error
                return common::make_error<grpc_response>(
                    static_cast<int>(monitoring_error_code::operation_failed),
                    "OTLP export failed with status: " +
                        std::to_string(response.status_code) + " - " + response.status_message);
            }
            // Transport error
            attempt++;
            retries_++;
            if (attempt < config_.max_retry_attempts) {
                std::this_thread::sleep_for(backoff);
                backoff = std::min(backoff * 2, config_.max_backoff);
            }
        }
        return common::make_error<grpc_response>(
            static_cast<int>(monitoring_error_code::operation_failed),
            "OTLP export failed after " + std::to_string(config_.max_retry_attempts) + " retries");
    }
References config_, kcenon::monitoring::otlp_grpc_config::initial_backoff, is_retryable_error(), kcenon::monitoring::otlp_grpc_config::max_backoff, kcenon::monitoring::otlp_grpc_config::max_retry_attempts, kcenon::monitoring::operation_failed, retries_, and transport_.
Referenced by export_spans().
shutdown()
common::VoidResult kcenon::monitoring::otlp_grpc_exporter::shutdown () inline override virtual
Shutdown the exporter.
Implements kcenon::monitoring::trace_exporter_interface.
Definition at line 507 of file otlp_grpc_exporter.h.
{
        running_ = false;
        transport_->disconnect();
        return common::ok();
    }
References running_, and transport_.
Referenced by TEST_F().
start()
common::VoidResult kcenon::monitoring::otlp_grpc_exporter::start () inline
Start the exporter.
Returns
common::VoidResult indicating success or failure
Definition at line 414 of file otlp_grpc_exporter.h.
{
        auto validate_result = config_.validate();
        if (validate_result.is_err()) {
            return validate_result;
        }
        // Parse endpoint
        auto [host, port] = parse_endpoint(config_.endpoint);
        // Connect to server
        auto connect_result = transport_->connect(host, port);
        if (connect_result.is_err()) {
            return connect_result;
        }
        running_ = true;
        return common::ok();
    }
References config_, kcenon::monitoring::otlp_grpc_config::endpoint, kcenon::monitoring::host, parse_endpoint(), running_, transport_, and kcenon::monitoring::otlp_grpc_config::validate().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
config_
otlp_grpc_config kcenon::monitoring::otlp_grpc_exporter::config_ private
Definition at line 382 of file otlp_grpc_exporter.h.
Referenced by config(), export_spans(), send_with_retry(), and start().
dropped_spans_
std::atomic<std::size_t> kcenon::monitoring::otlp_grpc_exporter::dropped_spans_ {0} private
Definition at line 386 of file otlp_grpc_exporter.h.
{0};
Referenced by export_spans(), get_detailed_stats(), and get_stats().
exported_spans_
std::atomic<std::size_t> kcenon::monitoring::otlp_grpc_exporter::exported_spans_ {0} private
Definition at line 385 of file otlp_grpc_exporter.h.
{0};
Referenced by export_spans(), get_detailed_stats(), and get_stats().
failed_exports_
std::atomic<std::size_t> kcenon::monitoring::otlp_grpc_exporter::failed_exports_ {0} private
Definition at line 387 of file otlp_grpc_exporter.h.
{0};
Referenced by export_spans(), get_detailed_stats(), and get_stats().
retries_
std::atomic<std::size_t> kcenon::monitoring::otlp_grpc_exporter::retries_ {0} private
Definition at line 388 of file otlp_grpc_exporter.h.
{0};
Referenced by get_detailed_stats(), get_stats(), and send_with_retry().
running_
std::atomic<bool> kcenon::monitoring::otlp_grpc_exporter::running_ {false} private
Definition at line 384 of file otlp_grpc_exporter.h.
{false};
Referenced by is_running(), shutdown(), and start().
stats_mutex_
std::mutex kcenon::monitoring::otlp_grpc_exporter::stats_mutex_ private
Definition at line 389 of file otlp_grpc_exporter.h.
Referenced by export_spans(), and get_detailed_stats().
total_export_time_
std::chrono::microseconds kcenon::monitoring::otlp_grpc_exporter::total_export_time_ {0} private
Definition at line 390 of file otlp_grpc_exporter.h.
{0};
Referenced by export_spans(), and get_detailed_stats().
transport_
std::unique_ptr<grpc_transport> kcenon::monitoring::otlp_grpc_exporter::transport_ private
Definition at line 383 of file otlp_grpc_exporter.h.
Referenced by export_spans(), send_with_retry(), shutdown(), and start().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/exporters/otlp_grpc_exporter.h