Monitoring System: ServiceA Class Reference
ServiceA Class Reference
Public Member Functions
ServiceA ()
~ServiceA () override
std::string get_name () const override
int get_id () const
Public Member Functions inherited from IService
virtual ~IService ()=default
Static Public Member Functions
static int get_instance_count ()
static void reset_count ()
Private Attributes
int id_
Static Private Attributes
static std::atomic< int > instance_count_ {0}
Detailed Description
Definition at line 39 of file test_di_container.cpp.
Constructor & Destructor Documentation
ServiceA()
ServiceA::ServiceA () inline
Definition at line 45 of file test_di_container.cpp.
: id_(++instance_count_) {}
~ServiceA()
ServiceA::~ServiceA () inline override
Definition at line 46 of file test_di_container.cpp.
{ --instance_count_; }
References instance_count_.
Member Function Documentation
get_id()
int ServiceA::get_id () const inline
Definition at line 53 of file test_di_container.cpp.
{ return id_; }
References id_.
get_instance_count()
static int ServiceA::get_instance_count () inline static
Definition at line 55 of file test_di_container.cpp.
{ return instance_count_.load(); }
References instance_count_.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_name()
std::string ServiceA::get_name () const inline override virtual
Implements IService.
Definition at line 48 of file test_di_container.cpp.
    {
        return "ServiceA_" + std::to_string(id_);
    }
References id_.
Referenced by ServiceB::get_name().
reset_count()
static void ServiceA::reset_count () inline static
Definition at line 57 of file test_di_container.cpp.
{ instance_count_ = 0; }
References instance_count_.
Referenced by DIContainerTest::SetUp(), and DIContainerTest::TearDown().
Member Data Documentation
id_
int ServiceA::id_ private
Definition at line 42 of file test_di_container.cpp.
Referenced by get_id(), and get_name().
instance_count_
std::atomic< int > ServiceA::instance_count_ {0} static private
Definition at line 60 of file test_di_container.cpp.
{0};
Referenced by get_instance_count(), reset_count(), and ~ServiceA().
The documentation for this class was generated from the following file:
tests/test_di_container.cpp