Monitoring System: kcenon::monitoring::health_check_builder Class Reference
kcenon::monitoring::health_check_builder Class Reference
Fluent builder for creating functional_health_check instances.
#include <health_monitor.h>
Public Member Functions
health_check_builder & with_name (const std::string &name)
Set the health check name.
health_check_builder & with_type (health_check_type type)
Set the health check type.
health_check_builder & with_check (std::function< health_check_result()> func)
Set the callable that performs the health check.
health_check_builder & with_timeout (std::chrono::milliseconds timeout)
Set the maximum duration allowed for the check.
health_check_builder & critical (bool is_critical)
Mark this check as critical for overall system health.
std::shared_ptr< functional_health_check > build ()
Build and return the configured functional_health_check.
Private Attributes
std::string name_
health_check_type type_ {health_check_type::liveness}
std::function< health_check_result()> check_func_
std::chrono::milliseconds timeout_ {std::chrono::milliseconds(1000)}
bool critical_ {false}
Detailed Description
Fluent builder for creating functional_health_check instances.
auto check = health_check_builder()
    .with_name("redis")
    .with_type(health_check_type::readiness)
    .with_check([]() {
        return ping_redis()
            ? health_check_result::healthy("Redis OK")
            : health_check_result::unhealthy("Redis unreachable");
    })
    .with_timeout(std::chrono::milliseconds(500))
    .critical(true)
    .build();
See also
functional_health_check For the type created by build()
Definition at line 605 of file health_monitor.h.
Member Function Documentation
build()
std::shared_ptr< functional_health_check > kcenon::monitoring::health_check_builder::build () inline
Build and return the configured functional_health_check.
Returns
Shared pointer to the constructed health check
Definition at line 661 of file health_monitor.h.
{
        return std::make_shared<functional_health_check>(
            name_, type_, check_func_, timeout_, critical_);
    }
References check_func_, critical_, name_, timeout_, and type_.
Referenced by TEST_F().
critical()
health_check_builder & kcenon::monitoring::health_check_builder::critical (bool is_critical) inline
Mark this check as critical for overall system health.
Parameters
is_critical true if system should be marked unhealthy when this check fails
Returns
Reference to this builder for chaining
Definition at line 652 of file health_monitor.h.
{
        critical_ = is_critical;
        return *this;
    }
References critical_.
Referenced by TEST_F().
with_check()
health_check_builder & kcenon::monitoring::health_check_builder::with_check (std::function< health_check_result()> func) inline
Set the callable that performs the health check.
Parameters
func A callable returning health_check_result
Returns
Reference to this builder for chaining
Definition at line 632 of file health_monitor.h.
{
        check_func_ = std::move(func);
        return *this;
    }
References check_func_.
Referenced by TEST_F(), and TEST_F().
with_name()
health_check_builder & kcenon::monitoring::health_check_builder::with_name (const std::string & name) inline
Set the health check name.
Parameters
name Human-readable name
Returns
Reference to this builder for chaining
Definition at line 612 of file health_monitor.h.
{
        name_ = name;
        return *this;
    }
References name_.
Referenced by TEST_F(), and TEST_F().
with_timeout()
health_check_builder & kcenon::monitoring::health_check_builder::with_timeout (std::chrono::milliseconds timeout) inline
Set the maximum duration allowed for the check.
Parameters
timeout Timeout duration
Returns
Reference to this builder for chaining
Definition at line 642 of file health_monitor.h.
{
        timeout_ = timeout;
        return *this;
    }
References timeout_.
with_type()
health_check_builder & kcenon::monitoring::health_check_builder::with_type (health_check_type type) inline
Set the health check type.
Parameters
type The check type (liveness, readiness, or startup)
Returns
Reference to this builder for chaining
Definition at line 622 of file health_monitor.h.
{
        type_ = type;
        return *this;
    }
References type_.
Referenced by TEST_F(), and TEST_F().
Member Data Documentation
check_func_
std::function<health_check_result()> kcenon::monitoring::health_check_builder::check_func_ private
Definition at line 669 of file health_monitor.h.
Referenced by build(), and with_check().
critical_
bool kcenon::monitoring::health_check_builder::critical_ {false} private
Definition at line 671 of file health_monitor.h.
{false};
Referenced by build(), and critical().
name_
std::string kcenon::monitoring::health_check_builder::name_ private
Definition at line 667 of file health_monitor.h.
Referenced by build(), and with_name().
timeout_
std::chrono::milliseconds kcenon::monitoring::health_check_builder::timeout_ {std::chrono::milliseconds(1000)} private
Definition at line 670 of file health_monitor.h.
{std::chrono::milliseconds(1000)};
Referenced by build(), and with_timeout().
type_
health_check_type kcenon::monitoring::health_check_builder::type_ {health_check_type::liveness} private
Definition at line 668 of file health_monitor.h.
{health_check_type::liveness};
Referenced by build(), and with_type().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/health/health_monitor.h