Monitoring System: kcenon::monitoring::cooldown_tracker Class Reference
kcenon::monitoring::cooldown_tracker Class Reference
Tracks cooldown periods for alert notifications.
#include <alert_pipeline.h>
Public Member Functions
cooldown_tracker (std::chrono::milliseconds default_cooldown)
Set default cooldown period.
bool is_in_cooldown (const std::string &fingerprint) const
Check if alert is in cooldown.
void record_notification (const std::string &fingerprint)
Record notification time.
void set_cooldown (const std::string &fingerprint, std::chrono::milliseconds cooldown)
Set custom cooldown for specific alert.
std::chrono::milliseconds remaining_cooldown (const std::string &fingerprint) const
Get time remaining in cooldown.
void clear_cooldown (const std::string &fingerprint)
Clear cooldown state for an alert.
void reset ()
Clear all cooldown state.
Private Member Functions
std::chrono::milliseconds get_cooldown_for (const std::string &fingerprint) const
Private Attributes
std::chrono::milliseconds default_cooldown_
std::mutex mutex_
std::unordered_map< std::string, std::chrono::steady_clock::time_point > last_notification_
std::unordered_map< std::string, std::chrono::milliseconds > custom_cooldowns_
Detailed Description
Tracks cooldown periods for alert notifications.
Prevents notification spam by enforcing minimum intervals between notifications for the same alert.
Examples
alert_pipeline_example.cpp.
Definition at line 403 of file alert_pipeline.h.
Constructor & Destructor Documentation
cooldown_tracker()
kcenon::monitoring::cooldown_tracker::cooldown_tracker (std::chrono::milliseconds default_cooldown) inline explicit
Set default cooldown period.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 408 of file alert_pipeline.h.
        : default_cooldown_(default_cooldown) {}
Member Function Documentation
clear_cooldown()
void kcenon::monitoring::cooldown_tracker::clear_cooldown (const std::string & fingerprint) inline
Clear cooldown state for an alert.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 476 of file alert_pipeline.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        last_notification_.erase(fingerprint);
    }
References last_notification_, and mutex_.
get_cooldown_for()
std::chrono::milliseconds kcenon::monitoring::cooldown_tracker::get_cooldown_for (const std::string & fingerprint) const inline private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 490 of file alert_pipeline.h.
{
        auto it = custom_cooldowns_.find(fingerprint);
        if (it != custom_cooldowns_.end()) {
            return it->second;
        }
        return default_cooldown_;
    }
References custom_cooldowns_, and default_cooldown_.
Referenced by is_in_cooldown(), and remaining_cooldown().
is_in_cooldown()
bool kcenon::monitoring::cooldown_tracker::is_in_cooldown (const std::string & fingerprint) const inline
Check if alert is in cooldown.
Parameters
fingerprint Alert fingerprint
Returns
True if in cooldown
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 416 of file alert_pipeline.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = last_notification_.find(fingerprint);
        if (it == last_notification_.end()) {
            return false;
        }
        auto now = std::chrono::steady_clock::now();
        auto cooldown = get_cooldown_for(fingerprint);
        return (now - it->second) < cooldown;
    }
References get_cooldown_for(), last_notification_, and mutex_.
Referenced by main().
record_notification()
void kcenon::monitoring::cooldown_tracker::record_notification (const std::string & fingerprint) inline
Record notification time.
Parameters
fingerprint Alert fingerprint
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 433 of file alert_pipeline.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        last_notification_[fingerprint] = std::chrono::steady_clock::now();
    }
References last_notification_, and mutex_.
Referenced by main().
remaining_cooldown()
std::chrono::milliseconds kcenon::monitoring::cooldown_tracker::remaining_cooldown (const std::string & fingerprint) const inline
Get time remaining in cooldown.
Parameters
fingerprint Alert fingerprint
Returns
Remaining cooldown time, or zero if not in cooldown
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 454 of file alert_pipeline.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = last_notification_.find(fingerprint);
        if (it == last_notification_.end()) {
            return std::chrono::milliseconds::zero();
        }
        auto now = std::chrono::steady_clock::now();
        auto cooldown = get_cooldown_for(fingerprint);
        auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
            now - it->second);
        if (elapsed >= cooldown) {
            return std::chrono::milliseconds::zero();
        }
        return cooldown - elapsed;
    }
References get_cooldown_for(), last_notification_, and mutex_.
Referenced by main().
reset()
void kcenon::monitoring::cooldown_tracker::reset () inline
Clear all cooldown state.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 484 of file alert_pipeline.h.
                 {
        std::lock_guard<std::mutex> lock(mutex_);
        last_notification_.clear();
    }
References last_notification_, and mutex_.
Referenced by main().
set_cooldown()
void kcenon::monitoring::cooldown_tracker::set_cooldown (const std::string & fingerprint, std::chrono::milliseconds cooldown) inline
Set custom cooldown for specific alert.
Parameters
fingerprint Alert fingerprint
cooldown Custom cooldown duration
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 443 of file alert_pipeline.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        custom_cooldowns_[fingerprint] = cooldown;
    }
References custom_cooldowns_, and mutex_.
Referenced by main().
Member Data Documentation
custom_cooldowns_
std::unordered_map<std::string, std::chrono::milliseconds> kcenon::monitoring::cooldown_tracker::custom_cooldowns_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 501 of file alert_pipeline.h.
Referenced by get_cooldown_for(), and set_cooldown().
default_cooldown_
std::chrono::milliseconds kcenon::monitoring::cooldown_tracker::default_cooldown_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 498 of file alert_pipeline.h.
Referenced by get_cooldown_for().
last_notification_
std::unordered_map<std::string, std::chrono::steady_clock::time_point> kcenon::monitoring::cooldown_tracker::last_notification_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 500 of file alert_pipeline.h.
Referenced by clear_cooldown(), is_in_cooldown(), record_notification(), remaining_cooldown(), and reset().
mutex_
std::mutex kcenon::monitoring::cooldown_tracker::mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 499 of file alert_pipeline.h.
Referenced by clear_cooldown(), is_in_cooldown(), record_notification(), remaining_cooldown(), reset(), and set_cooldown().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/alert/alert_pipeline.h