Monitoring System: ApiGatewayService Class Reference
ApiGatewayService Class Reference
Simulated API Gateway service.
Public Member Functions
trace_span handle_request (const std::string &endpoint, const std::string &method)
Handle incoming HTTP request.
trace_context create_context (const trace_span &span)
Create trace context for propagation.
Static Private Member Functions
static std::string generate_trace_id ()
static std::string generate_span_id ()
Private Attributes
std::string service_name_ = "api_gateway"
Detailed Description
Simulated API Gateway service.
Examples
multi_service_tracing_example.cpp.
Definition at line 40 of file multi_service_tracing_example.cpp.
Member Function Documentation
create_context()
trace_context ApiGatewayService::create_context (const trace_span & span) inline
Create trace context for propagation.
Examples
multi_service_tracing_example.cpp.
Definition at line 80 of file multi_service_tracing_example.cpp.
{
        trace_context ctx;
        ctx.trace_id = span.trace_id;
        ctx.span_id = span.span_id;
        ctx.trace_flags = "01";  // Sampled
        ctx.baggage = span.baggage;
        std::cout << "   → Context for propagation: "
                  << ctx.to_w3c_traceparent() << std::endl;
        return ctx;
    }
References kcenon::monitoring::trace_context::baggage, kcenon::monitoring::trace_span::baggage, kcenon::monitoring::trace_context::span_id, kcenon::monitoring::trace_span::span_id, kcenon::monitoring::trace_context::to_w3c_traceparent(), kcenon::monitoring::trace_context::trace_flags, kcenon::monitoring::trace_context::trace_id, and kcenon::monitoring::trace_span::trace_id.
Referenced by simulate_multi_service_request().
generate_span_id()
static std::string ApiGatewayService::generate_span_id () inline static private
Examples
multi_service_tracing_example.cpp.
Definition at line 103 of file multi_service_tracing_example.cpp.
{
        // Generate 16-character hex string (8 bytes)
        std::string id;
        for (int i = 0; i < 16; ++i) {
            id += "0123456789abcdef"[rand() % 16];
        }
        return id;
    }
Referenced by handle_request().
generate_trace_id()
static std::string ApiGatewayService::generate_trace_id () inline static private
Examples
multi_service_tracing_example.cpp.
Definition at line 94 of file multi_service_tracing_example.cpp.
{
        // Generate 32-character hex string (16 bytes)
        std::string id;
        for (int i = 0; i < 32; ++i) {
            id += "0123456789abcdef"[rand() % 16];
        }
        return id;
    }
Referenced by handle_request().
handle_request()
trace_span ApiGatewayService::handle_request (const std::string & endpoint, const std::string & method) inline
Handle incoming HTTP request.
Examples
multi_service_tracing_example.cpp.
Definition at line 48 of file multi_service_tracing_example.cpp.
{
        std::cout << "\n[" << service_name_ << "] Processing " << method << " " << endpoint << std::endl;
        // Create root span for this request
        trace_span span;
        span.trace_id = generate_trace_id();
        span.span_id = generate_span_id();
        span.operation_name = "http_request";
        span.service_name = service_name_;
        span.start_time = std::chrono::system_clock::now();
        // Add HTTP-specific tags
        span.tags["http.method"] = method;
        span.tags["http.url"] = endpoint;
        span.tags["http.target"] = endpoint;
        span.tags["component"] = "http_server";
        // Add baggage for cross-cutting concerns
        span.baggage["user.id"] = "user-12345";
        span.baggage["session.id"] = "sess-67890";
        span.baggage["request.priority"] = "high";
        std::cout << "   → Created root span: " << span.span_id << std::endl;
        std::cout << "     Trace ID: " << span.trace_id << std::endl;
        std::cout << "     Baggage: user.id=" << span.baggage["user.id"] << std::endl;
        return span;
    }
References kcenon::monitoring::trace_span::baggage, generate_span_id(), generate_trace_id(), kcenon::monitoring::trace_span::operation_name, kcenon::monitoring::trace_span::service_name, service_name_, kcenon::monitoring::trace_span::span_id, kcenon::monitoring::trace_span::start_time, kcenon::monitoring::trace_span::tags, and kcenon::monitoring::trace_span::trace_id.
Referenced by simulate_multi_service_request().
Member Data Documentation
service_name_
std::string ApiGatewayService::service_name_ = "api_gateway" private
Examples
multi_service_tracing_example.cpp.
Definition at line 42 of file multi_service_tracing_example.cpp.
Referenced by handle_request().
The documentation for this class was generated from the following file:
examples/multi_service_tracing_example.cpp