var examples =
[
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_config.h", "d1/d07/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2alert_2alert_config_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h", "d1/dfc/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2alert_2alert_manager_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_notifiers.h", "d4/d58/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2alert_2alert_notifiers_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h", "da/db0/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2alert_2alert_pipeline_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h", "d5/d15/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2alert_2alert_rule_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_triggers.h", "d1/d98/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2alert_2alert_triggers_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/event_bus.h", "dd/d6d/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2core_2event_bus_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/event_types.h", "df/df8/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2core_2event_types_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h", "de/d4a/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2core_2performance_monitor_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/event_bus_interface.h", "d8/d83/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2interfa2efde646667c84cb7867746b38659936.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/metric_collector_interface.h", "de/d73/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2interfaec024d697000a07cca610cb752bdf846.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/metric_types_adapter.h", "de/d3e/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2interfa08b226b096fa0f6656c06399ef68f616.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitorable_interface.h", "dc/d8c/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2interfac924286c968c8afffe31e6b68e49770d.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h", "d0/d5d/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2interfaces_2monitoring_core_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/observer_interface.h", "de/d5e/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2interfa4dfa0af67e55c47a7c4e1b8c83c2b52e.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/plugins/collector_plugin.h", "d9/dcc/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2plugins_2collector_plugin_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/utils/hot_path_helper.h", "db/d12/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2utils_2hot_path_helper_8h-example.html", null ],
    [ "/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/utils/statistics.h", "d7/dae/_2home_2runner_2work_2monitoring_system_2monitoring_system_2include_2kcenon_2monitoring_2utils_2statistics_8h-example.html", null ]
];