var hierarchy =
[
    [ "kcenon::monitoring::adaptation_stats", "d8/dfc/structkcenon_1_1monitoring_1_1adaptation__stats.html", null ],
    [ "kcenon::monitoring::adaptive_collector", "d0/d02/classkcenon_1_1monitoring_1_1adaptive__collector.html", null ],
    [ "kcenon::monitoring::adaptive_config", "d7/dd0/structkcenon_1_1monitoring_1_1adaptive__config.html", null ],
    [ "kcenon::monitoring::adaptive_monitor", "d4/da7/classkcenon_1_1monitoring_1_1adaptive__monitor.html", null ],
    [ "kcenon::monitoring::adaptive_scope", "d9/d64/classkcenon_1_1monitoring_1_1adaptive__scope.html", null ],
    [ "kcenon::monitoring::aggregation_processor", "df/d6f/classkcenon_1_1monitoring_1_1aggregation__processor.html", null ],
    [ "kcenon::monitoring::aggregation_result", "d2/d1f/structkcenon_1_1monitoring_1_1aggregation__result.html", null ],
    [ "kcenon::monitoring::aggregation_rule", "d0/dba/structkcenon_1_1monitoring_1_1aggregation__rule.html", null ],
    [ "kcenon::monitoring::aggregation_processor::aggregator_entry", "d7/d92/structkcenon_1_1monitoring_1_1aggregation__processor_1_1aggregator__entry.html", null ],
    [ "kcenon::monitoring::alert", "d1/d1e/structkcenon_1_1monitoring_1_1alert.html", null ],
    [ "kcenon::monitoring::resource_threshold_monitor::alert", "d2/de4/structkcenon_1_1monitoring_1_1resource__threshold__monitor_1_1alert.html", null ],
    [ "kcenon::monitoring::alert_aggregator", "de/d7b/classkcenon_1_1monitoring_1_1alert__aggregator.html", null ],
    [ "kcenon::monitoring::alert_aggregator_config", "d4/dbb/structkcenon_1_1monitoring_1_1alert__aggregator__config.html", null ],
    [ "kcenon::monitoring::alert_annotations", "da/d7d/structkcenon_1_1monitoring_1_1alert__annotations.html", null ],
    [ "kcenon::monitoring::alert_deduplicator", "d4/d46/classkcenon_1_1monitoring_1_1alert__deduplicator.html", null ],
    [ "kcenon::monitoring::alert_formatter", "d5/dd8/classkcenon_1_1monitoring_1_1alert__formatter.html", [
      [ "kcenon::monitoring::json_alert_formatter", "d3/d68/classkcenon_1_1monitoring_1_1json__alert__formatter.html", null ],
      [ "kcenon::monitoring::text_alert_formatter", "d3/d8d/classkcenon_1_1monitoring_1_1text__alert__formatter.html", null ]
    ] ],
    [ "kcenon::monitoring::alert_group", "d5/d2f/structkcenon_1_1monitoring_1_1alert__group.html", null ],
    [ "kcenon::monitoring::alert_inhibitor", "d9/d97/classkcenon_1_1monitoring_1_1alert__inhibitor.html", null ],
    [ "kcenon::monitoring::alert_labels", "d7/db4/structkcenon_1_1monitoring_1_1alert__labels.html", null ],
    [ "kcenon::monitoring::alert_manager", "d6/d6d/classkcenon_1_1monitoring_1_1alert__manager.html", null ],
    [ "kcenon::monitoring::alert_manager_config", "da/d9b/structkcenon_1_1monitoring_1_1alert__manager__config.html", null ],
    [ "kcenon::monitoring::alert_manager_metrics", "d2/d5b/structkcenon_1_1monitoring_1_1alert__manager__metrics.html", null ],
    [ "kcenon::monitoring::alert_notifier", "d5/d9f/classkcenon_1_1monitoring_1_1alert__notifier.html", [
      [ "kcenon::monitoring::buffered_notifier", "de/de3/classkcenon_1_1monitoring_1_1buffered__notifier.html", null ],
      [ "kcenon::monitoring::callback_notifier", "db/da9/classkcenon_1_1monitoring_1_1callback__notifier.html", null ],
      [ "kcenon::monitoring::console_color_notifier", "de/d1c/classkcenon_1_1monitoring_1_1console__color__notifier.html", null ],
      [ "kcenon::monitoring::file_notifier", "dc/dea/classkcenon_1_1monitoring_1_1file__notifier.html", null ],
      [ "kcenon::monitoring::log_notifier", "d3/d26/classkcenon_1_1monitoring_1_1log__notifier.html", null ],
      [ "kcenon::monitoring::multi_notifier", "d0/d50/classkcenon_1_1monitoring_1_1multi__notifier.html", null ],
      [ "kcenon::monitoring::routing_notifier", "da/d18/classkcenon_1_1monitoring_1_1routing__notifier.html", null ],
      [ "kcenon::monitoring::statistics_notifier", "d0/d28/classkcenon_1_1monitoring_1_1statistics__notifier.html", null ],
      [ "kcenon::monitoring::webhook_notifier", "dd/dc5/classkcenon_1_1monitoring_1_1webhook__notifier.html", null ]
    ] ],
    [ "kcenon::monitoring::alert_pipeline", "d5/d40/classkcenon_1_1monitoring_1_1alert__pipeline.html", null ],
    [ "kcenon::monitoring::alert_rule", "d4/d6a/classkcenon_1_1monitoring_1_1alert__rule.html", null ],
    [ "kcenon::monitoring::alert_rule_config", "d1/d0c/structkcenon_1_1monitoring_1_1alert__rule__config.html", null ],
    [ "kcenon::monitoring::alert_rule_group", "d2/d80/classkcenon_1_1monitoring_1_1alert__rule__group.html", null ],
    [ "kcenon::monitoring::alert_silence", "d3/d7c/structkcenon_1_1monitoring_1_1alert__silence.html", null ],
    [ "kcenon::monitoring::alert_template", "df/dbb/classkcenon_1_1monitoring_1_1alert__template.html", null ],
    [ "kcenon::monitoring::alert_trigger", "d2/d59/classkcenon_1_1monitoring_1_1alert__trigger.html", [
      [ "kcenon::monitoring::absent_trigger", "d4/d43/classkcenon_1_1monitoring_1_1absent__trigger.html", null ],
      [ "kcenon::monitoring::anomaly_trigger", "de/d4f/classkcenon_1_1monitoring_1_1anomaly__trigger.html", null ],
      [ "kcenon::monitoring::composite_trigger", "d6/d4a/classkcenon_1_1monitoring_1_1composite__trigger.html", null ],
      [ "kcenon::monitoring::delta_trigger", "d2/d8e/classkcenon_1_1monitoring_1_1delta__trigger.html", null ],
      [ "kcenon::monitoring::range_trigger", "d0/de5/classkcenon_1_1monitoring_1_1range__trigger.html", null ],
      [ "kcenon::monitoring::rate_of_change_trigger", "da/dcc/classkcenon_1_1monitoring_1_1rate__of__change__trigger.html", null ],
      [ "kcenon::monitoring::threshold_trigger", "da/d11/classkcenon_1_1monitoring_1_1threshold__trigger.html", null ],
      [ "moving_average_trigger", "d9/d83/classmoving__average__trigger.html", null ],
      [ "periodic_trigger", "dd/d6d/classperiodic__trigger.html", null ]
    ] ],
    [ "ApiGatewayService", "d2/d3d/classApiGatewayService.html", null ],
    [ "AuthService", "d6/d38/classAuthService.html", null ],
    [ "kcenon::monitoring::battery_info", "da/d26/structkcenon_1_1monitoring_1_1battery__info.html", null ],
    [ "kcenon::monitoring::battery_info_collector", "d0/d42/classkcenon_1_1monitoring_1_1battery__info__collector.html", null ],
    [ "kcenon::monitoring::battery_reading", "d1/d09/structkcenon_1_1monitoring_1_1battery__reading.html", null ],
    [ "kcenon::monitoring::plugin_metric_collector::cached_metric", "d2/d27/structkcenon_1_1monitoring_1_1plugin__metric__collector_1_1cached__metric.html", null ],
    [ "CacheService", "d4/df6/classCacheService.html", null ],
    [ "kcenon::monitoring::central_collector", "d8/df1/classkcenon_1_1monitoring_1_1central__collector.html", null ],
    [ "kcenon::monitoring::circuit_breaker< T >", "d0/d38/classkcenon_1_1monitoring_1_1circuit__breaker.html", null ],
    [ "kcenon::monitoring::circuit_breaker< T >", "d0/d38/classkcenon_1_1monitoring_1_1circuit__breaker.html", null ],
    [ "kcenon::monitoring::circuit_breaker_config", "d3/def/structkcenon_1_1monitoring_1_1circuit__breaker__config.html", null ],
    [ "kcenon::monitoring::circuit_breaker_metrics", "d8/d90/structkcenon_1_1monitoring_1_1circuit__breaker__metrics.html", null ],
    [ "kcenon::monitoring::circuit_breaker_registry", "d5/d51/classkcenon_1_1monitoring_1_1circuit__breaker__registry.html", null ],
    [ "kcenon::monitoring::collection_config", "d6/d16/structkcenon_1_1monitoring_1_1collection__config.html", null ],
    [ "kcenon::monitoring::thread_to_monitoring_adapter::collection_config", "d3/dfc/structkcenon_1_1monitoring_1_1thread__to__monitoring__adapter_1_1collection__config.html", null ],
    [ "kcenon::monitoring::collector_base< Derived >", "db/d97/classkcenon_1_1monitoring_1_1collector__base.html", null ],
    [ "kcenon::monitoring::collector_interface", "d2/d5a/classkcenon_1_1monitoring_1_1collector__interface.html", [
      [ "kcenon::monitoring::crtp_collector_adapter< T >", "d7/d37/classkcenon_1_1monitoring_1_1crtp__collector__adapter.html", null ],
      [ "kcenon::monitoring::plugin_collector_adapter< T >", "db/da2/classkcenon_1_1monitoring_1_1plugin__collector__adapter.html", null ],
      [ "kcenon::monitoring::standalone_collector_adapter< T >", "dd/ddf/classkcenon_1_1monitoring_1_1standalone__collector__adapter.html", null ]
    ] ],
    [ "kcenon::monitoring::collector_plugin", "d6/d59/classkcenon_1_1monitoring_1_1collector__plugin.html", [
      [ "example_plugin", "d8/d5a/classexample__plugin.html", null ],
      [ "kcenon::monitoring::battery_collector", "da/d8c/classkcenon_1_1monitoring_1_1battery__collector.html", null ],
      [ "kcenon::monitoring::container_collector", "d4/ddb/classkcenon_1_1monitoring_1_1container__collector.html", null ],
      [ "kcenon::monitoring::gpu_collector", "d5/de7/classkcenon_1_1monitoring_1_1gpu__collector.html", null ],
      [ "kcenon::monitoring::interrupt_collector", "d3/d80/classkcenon_1_1monitoring_1_1interrupt__collector.html", null ],
      [ "kcenon::monitoring::network_metrics_collector", "d9/db1/classkcenon_1_1monitoring_1_1network__metrics__collector.html", null ],
      [ "kcenon::monitoring::platform_metrics_collector", "d8/d65/classkcenon_1_1monitoring_1_1platform__metrics__collector.html", null ],
      [ "kcenon::monitoring::power_collector", "d3/dec/classkcenon_1_1monitoring_1_1power__collector.html", null ],
      [ "kcenon::monitoring::process_metrics_collector", "de/ddc/classkcenon_1_1monitoring_1_1process__metrics__collector.html", null ],
      [ "kcenon::monitoring::security_collector", "dd/d8c/classkcenon_1_1monitoring_1_1security__collector.html", null ],
      [ "kcenon::monitoring::smart_collector", "d6/d04/classkcenon_1_1monitoring_1_1smart__collector.html", null ],
      [ "kcenon::monitoring::temperature_collector", "d9/ddf/classkcenon_1_1monitoring_1_1temperature__collector.html", null ],
      [ "kcenon::monitoring::uptime_collector", "de/dfc/classkcenon_1_1monitoring_1_1uptime__collector.html", null ],
      [ "kcenon::monitoring::vm_collector", "d5/d6e/classkcenon_1_1monitoring_1_1vm__collector.html", null ]
    ] ],
    [ "kcenon::monitoring::collector_registry", "d7/d36/classkcenon_1_1monitoring_1_1collector__registry.html", null ],
    [ "kcenon::monitoring::compact_metric_value", "d0/d41/structkcenon_1_1monitoring_1_1compact__metric__value.html", null ],
    [ "kcenon::monitoring::opentelemetry_compatibility_layer::compatibility_stats", "d6/dda/structkcenon_1_1monitoring_1_1opentelemetry__compatibility__layer_1_1compatibility__stats.html", null ],
    [ "kcenon::monitoring::config_parser", "db/d90/classkcenon_1_1monitoring_1_1config__parser.html", null ],
    [ "kcenon::monitoring::container_info", "db/dca/structkcenon_1_1monitoring_1_1container__info.html", null ],
    [ "kcenon::monitoring::container_info_collector", "d5/d43/classkcenon_1_1monitoring_1_1container__info__collector.html", null ],
    [ "kcenon::monitoring::container_metrics", "df/d2c/structkcenon_1_1monitoring_1_1container__metrics.html", null ],
    [ "kcenon::monitoring::plugins::container_plugin_config", "d8/d86/structkcenon_1_1monitoring_1_1plugins_1_1container__plugin__config.html", null ],
    [ "kcenon::monitoring::context_metadata", "d4/d3c/structkcenon_1_1monitoring_1_1context__metadata.html", null ],
    [ "kcenon::monitoring::platform::context_switch_info", "d4/d1a/structkcenon_1_1monitoring_1_1platform_1_1context__switch__info.html", null ],
    [ "kcenon::monitoring::context_switch_info_collector", "dc/dca/classkcenon_1_1monitoring_1_1context__switch__info__collector.html", null ],
    [ "kcenon::monitoring::context_switch_metrics", "db/d12/structkcenon_1_1monitoring_1_1context__switch__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::context_switch_metrics", "db/dc5/structkcenon_1_1monitoring_1_1system__resources_1_1context__switch__metrics.html", null ],
    [ "kcenon::monitoring::cooldown_tracker", "de/d5e/classkcenon_1_1monitoring_1_1cooldown__tracker.html", null ],
    [ "kcenon::monitoring::cpu_interrupt_info", "d0/d4f/structkcenon_1_1monitoring_1_1cpu__interrupt__info.html", null ],
    [ "kcenon::monitoring::system_resources::cpu_metrics", "d8/d58/structkcenon_1_1monitoring_1_1system__resources_1_1cpu__metrics.html", null ],
    [ "kcenon::monitoring::container_info_collector::cpu_stats", "d6/d9d/structkcenon_1_1monitoring_1_1container__info__collector_1_1cpu__stats.html", null ],
    [ "kcenon::monitoring::system_info_collector::cpu_stats", "d2/dc5/structkcenon_1_1monitoring_1_1system__info__collector_1_1cpu__stats.html", null ],
    [ "kcenon::monitoring::cpu_throttle_config", "d9/d09/structkcenon_1_1monitoring_1_1cpu__throttle__config.html", null ],
    [ "kcenon::monitoring::cpu_throttler", "dc/d73/classkcenon_1_1monitoring_1_1cpu__throttler.html", null ],
    [ "kcenon::monitoring::create_result", "d0/d13/structkcenon_1_1monitoring_1_1create__result.html", null ],
    [ "kcenon::monitoring::data_consistency_manager", "d5/d16/classkcenon_1_1monitoring_1_1data__consistency__manager.html", null ],
    [ "DatabaseConnection", "d2/d12/classDatabaseConnection.html", null ],
    [ "kcenon::monitoring::safe_event_dispatcher::dead_letter_entry", "df/d3d/structkcenon_1_1monitoring_1_1safe__event__dispatcher_1_1dead__letter__entry.html", null ],
    [ "kcenon::monitoring::degradable_service< T >", "d0/db5/classkcenon_1_1monitoring_1_1degradable__service.html", null ],
    [ "kcenon::monitoring::degradation_plan", "d8/df5/structkcenon_1_1monitoring_1_1degradation__plan.html", null ],
    [ "kcenon::monitoring::disk_info", "d6/dd7/structkcenon_1_1monitoring_1_1disk__info.html", null ],
    [ "kcenon::monitoring::system_resources::disk_metrics", "d6/d0b/structkcenon_1_1monitoring_1_1system__resources_1_1disk__metrics.html", null ],
    [ "kcenon::monitoring::system_info_collector::disk_stats", "de/d82/structkcenon_1_1monitoring_1_1system__info__collector_1_1disk__stats.html", null ],
    [ "kcenon::monitoring::distributed_tracer", "d3/d83/classkcenon_1_1monitoring_1_1distributed__tracer.html", null ],
    [ "kcenon::monitoring::moving_window_aggregator< T >::entry", "dd/d79/structkcenon_1_1monitoring_1_1moving__window__aggregator_1_1entry.html", null ],
    [ "kcenon::monitoring::error_boundary< T >", "d0/d55/classkcenon_1_1monitoring_1_1error__boundary.html", null ],
    [ "kcenon::monitoring::error_boundary_config", "dd/dfd/structkcenon_1_1monitoring_1_1error__boundary__config.html", null ],
    [ "kcenon::monitoring::error_boundary_metrics", "d1/d69/structkcenon_1_1monitoring_1_1error__boundary__metrics.html", null ],
    [ "kcenon::monitoring::error_boundary_registry", "de/dce/classkcenon_1_1monitoring_1_1error__boundary__registry.html", null ],
    [ "kcenon::monitoring::error_info", "d5/d36/structkcenon_1_1monitoring_1_1error__info.html", null ],
    [ "kcenon::monitoring::event_base", "d2/d95/classkcenon_1_1monitoring_1_1event__base.html", [
      [ "kcenon::monitoring::component_lifecycle_event", "df/d67/classkcenon_1_1monitoring_1_1component__lifecycle__event.html", null ],
      [ "kcenon::monitoring::configuration_change_event", "da/d7a/classkcenon_1_1monitoring_1_1configuration__change__event.html", null ],
      [ "kcenon::monitoring::health_check_event", "d2/d8d/classkcenon_1_1monitoring_1_1health__check__event.html", null ],
      [ "kcenon::monitoring::logging_metric_event", "d5/df9/classkcenon_1_1monitoring_1_1logging__metric__event.html", null ],
      [ "kcenon::monitoring::metric_collection_event", "df/d19/classkcenon_1_1monitoring_1_1metric__collection__event.html", null ],
      [ "kcenon::monitoring::performance_alert_event", "d4/d66/classkcenon_1_1monitoring_1_1performance__alert__event.html", null ],
      [ "kcenon::monitoring::system_resource_event", "d5/dd2/classkcenon_1_1monitoring_1_1system__resource__event.html", null ],
      [ "kcenon::monitoring::thread_pool_metric_event", "de/d2d/classkcenon_1_1monitoring_1_1thread__pool__metric__event.html", null ]
    ] ],
    [ "kcenon::monitoring::event_bus_config", "db/dc9/structkcenon_1_1monitoring_1_1event__bus__config.html", null ],
    [ "kcenon::monitoring::event_envelope", "d8/d50/structkcenon_1_1monitoring_1_1event__envelope.html", null ],
    [ "kcenon::monitoring::event_handler< EventType >", "d0/d89/classkcenon_1_1monitoring_1_1event__handler.html", null ],
    [ "kcenon::monitoring::event_handler_wrapper", "d8/d26/structkcenon_1_1monitoring_1_1event__handler__wrapper.html", null ],
    [ "event_priority", "dd/d73/classevent__priority.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "kcenon::monitoring::circuit_open_exception", "d8/de6/classkcenon_1_1monitoring_1_1circuit__open__exception.html", null ]
      ] ]
    ] ],
    [ "ExternalApiClient", "d6/d98/classExternalApiClient.html", null ],
    [ "kcenon::monitoring::fallback_strategy_interface< T >", "dd/d78/classkcenon_1_1monitoring_1_1fallback__strategy__interface.html", [
      [ "kcenon::monitoring::alternative_service_strategy< T >", "d5/dbc/classkcenon_1_1monitoring_1_1alternative__service__strategy.html", null ],
      [ "kcenon::monitoring::cached_value_strategy< T >", "da/dd7/classkcenon_1_1monitoring_1_1cached__value__strategy.html", null ],
      [ "kcenon::monitoring::default_value_strategy< T >", "d5/d79/classkcenon_1_1monitoring_1_1default__value__strategy.html", null ]
    ] ],
    [ "std::false_type", null, [
      [ "kcenon::monitoring::stats::detail::is_chrono_duration< T >", "d9/d03/structkcenon_1_1monitoring_1_1stats_1_1detail_1_1is__chrono__duration.html", null ]
    ] ],
    [ "kcenon::monitoring::fault_tolerance_config", "d8/de8/structkcenon_1_1monitoring_1_1fault__tolerance__config.html", null ],
    [ "kcenon::monitoring::fault_tolerance_manager< T >", "d2/d74/classkcenon_1_1monitoring_1_1fault__tolerance__manager.html", null ],
    [ "kcenon::monitoring::fault_tolerance_metrics", "df/d26/structkcenon_1_1monitoring_1_1fault__tolerance__metrics.html", null ],
    [ "kcenon::monitoring::fault_tolerance_registry", "dc/d94/classkcenon_1_1monitoring_1_1fault__tolerance__registry.html", null ],
    [ "kcenon::monitoring::platform::fd_info", "d4/de8/structkcenon_1_1monitoring_1_1platform_1_1fd__info.html", null ],
    [ "kcenon::monitoring::fd_info_collector", "d8/d4c/classkcenon_1_1monitoring_1_1fd__info__collector.html", null ],
    [ "kcenon::monitoring::fd_metrics", "d7/d07/structkcenon_1_1monitoring_1_1fd__metrics.html", null ],
    [ "kcenon::monitoring::filesystem_inode_info", "d2/db1/structkcenon_1_1monitoring_1_1filesystem__inode__info.html", null ],
    [ "kcenon::monitoring::gpu_device_info", "d1/d1a/structkcenon_1_1monitoring_1_1gpu__device__info.html", null ],
    [ "kcenon::monitoring::platform::gpu_info", "d4/dba/structkcenon_1_1monitoring_1_1platform_1_1gpu__info.html", null ],
    [ "kcenon::monitoring::gpu_info_collector", "dd/d55/classkcenon_1_1monitoring_1_1gpu__info__collector.html", null ],
    [ "kcenon::monitoring::gpu_reading", "d8/d7d/structkcenon_1_1monitoring_1_1gpu__reading.html", null ],
    [ "kcenon::monitoring::graceful_degradation_manager", "d0/df6/classkcenon_1_1monitoring_1_1graceful__degradation__manager.html", null ],
    [ "kcenon::monitoring::graceful_degradation_metrics", "d9/d96/structkcenon_1_1monitoring_1_1graceful__degradation__metrics.html", null ],
    [ "kcenon::monitoring::grpc_request", "d1/d40/structkcenon_1_1monitoring_1_1grpc__request.html", null ],
    [ "kcenon::monitoring::grpc_response", "df/df7/structkcenon_1_1monitoring_1_1grpc__response.html", null ],
    [ "kcenon::monitoring::grpc_statistics", "d9/da9/structkcenon_1_1monitoring_1_1grpc__statistics.html", null ],
    [ "kcenon::monitoring::grpc_transport", "d8/d6c/classkcenon_1_1monitoring_1_1grpc__transport.html", [
      [ "kcenon::monitoring::stub_grpc_transport", "d2/d5b/classkcenon_1_1monitoring_1_1stub__grpc__transport.html", null ]
    ] ],
    [ "kcenon::monitoring::handler_error_info", "d0/ddf/structkcenon_1_1monitoring_1_1handler__error__info.html", null ],
    [ "kcenon::monitoring::plugins::hardware_plugin_config", "d9/d19/structkcenon_1_1monitoring_1_1plugins_1_1hardware__plugin__config.html", null ],
    [ "kcenon::monitoring::health_check", "da/d96/classkcenon_1_1monitoring_1_1health__check.html", [
      [ "database_health_check", "dc/d62/classdatabase__health__check.html", null ],
      [ "external_api_health_check", "d4/db5/classexternal__api__health__check.html", null ],
      [ "kcenon::monitoring::composite_health_check", "d3/d4b/classkcenon_1_1monitoring_1_1composite__health__check.html", null ],
      [ "kcenon::monitoring::functional_health_check", "d7/dfb/classkcenon_1_1monitoring_1_1functional__health__check.html", null ],
      [ "test_health_check", "d2/dea/classtest__health__check.html", null ]
    ] ],
    [ "kcenon::monitoring::health_check_builder", "d2/d7c/classkcenon_1_1monitoring_1_1health__check__builder.html", null ],
    [ "kcenon::monitoring::health_check_event::health_check_result", "d3/d6e/structkcenon_1_1monitoring_1_1health__check__event_1_1health__check__result.html", null ],
    [ "kcenon::monitoring::health_check_result", "dd/d56/structkcenon_1_1monitoring_1_1health__check__result.html", null ],
    [ "kcenon::monitoring::health_dependency_graph", "d8/d8e/classkcenon_1_1monitoring_1_1health__dependency__graph.html", null ],
    [ "kcenon::monitoring::health_monitor", "d5/d42/classkcenon_1_1monitoring_1_1health__monitor.html", null ],
    [ "kcenon::monitoring::health_monitor_config", "de/dba/structkcenon_1_1monitoring_1_1health__monitor__config.html", null ],
    [ "kcenon::monitoring::health_monitor_stats", "de/d31/structkcenon_1_1monitoring_1_1health__monitor__stats.html", null ],
    [ "kcenon::monitoring::histogram_bucket", "dd/d90/structkcenon_1_1monitoring_1_1histogram__bucket.html", null ],
    [ "kcenon::monitoring::histogram_data", "d4/da9/structkcenon_1_1monitoring_1_1histogram__data.html", null ],
    [ "kcenon::monitoring::http_request", "d4/d99/structkcenon_1_1monitoring_1_1http__request.html", null ],
    [ "kcenon::monitoring::http_response", "da/d05/structkcenon_1_1monitoring_1_1http__response.html", null ],
    [ "kcenon::monitoring::http_transport", "de/d16/classkcenon_1_1monitoring_1_1http__transport.html", [
      [ "kcenon::monitoring::simple_http_client", "d1/d1c/classkcenon_1_1monitoring_1_1simple__http__client.html", null ],
      [ "kcenon::monitoring::stub_http_transport", "dd/dde/classkcenon_1_1monitoring_1_1stub__http__transport.html", null ]
    ] ],
    [ "ILogger", null, [
      [ "console_logger", "d4/d06/classconsole__logger.html", null ],
      [ "example_logger", "d3/dfa/classexample__logger.html", null ],
      [ "mock_logger", "dd/d02/classmock__logger.html", null ],
      [ "simple_console_logger", "d2/d10/classsimple__console__logger.html", null ]
    ] ],
    [ "kcenon::common::interfaces::ILogger", null, [
      [ "simple_mock_logger", "d1/da6/classsimple__mock__logger.html", null ]
    ] ],
    [ "common::interfaces::IMonitor", null, [
      [ "kcenon::monitoring::performance_monitor_adapter", "d6/d13/classkcenon_1_1monitoring_1_1performance__monitor__adapter.html", null ]
    ] ],
    [ "IMonitor", null, [
      [ "aggregating_monitor", "d7/d29/classaggregating__monitor.html", null ]
    ] ],
    [ "kcenon::common::interfaces::IMonitor", null, [
      [ "mock_monitor", "d1/d21/classmock__monitor.html", null ]
    ] ],
    [ "imonitor_interface", "d4/d3d/classimonitor__interface.html", [
      [ "imonitor_adapter", "d1/d1a/classimonitor__adapter.html", null ],
      [ "performance_monitor_old", "d2/d91/classperformance__monitor__old.html", null ]
    ] ],
    [ "IMonitorable", null, [
      [ "console_logger", "d4/d06/classconsole__logger.html", null ]
    ] ],
    [ "kcenon::common::interfaces::IMonitorable", null, [
      [ "simple_mock_logger", "d1/da6/classsimple__mock__logger.html", null ]
    ] ],
    [ "IMonitorProvider", null, [
      [ "monitor_factory", "da/db2/classmonitor__factory.html", null ]
    ] ],
    [ "kcenon::monitoring::inhibition_rule", "df/df8/structkcenon_1_1monitoring_1_1inhibition__rule.html", null ],
    [ "kcenon::monitoring::platform::inode_info", "da/d79/structkcenon_1_1monitoring_1_1platform_1_1inode__info.html", null ],
    [ "kcenon::monitoring::inode_info_collector", "d4/dd1/classkcenon_1_1monitoring_1_1inode__info__collector.html", null ],
    [ "kcenon::monitoring::inode_metrics", "d3/d0c/structkcenon_1_1monitoring_1_1inode__metrics.html", null ],
    [ "kcenon::monitoring::interface_event_bus", "d5/df2/classkcenon_1_1monitoring_1_1interface__event__bus.html", [
      [ "kcenon::monitoring::event_bus", "df/d2a/classkcenon_1_1monitoring_1_1event__bus.html", null ]
    ] ],
    [ "kcenon::monitoring::interface_event_publisher", "de/da3/classkcenon_1_1monitoring_1_1interface__event__publisher.html", null ],
    [ "kcenon::monitoring::interface_event_subscriber", "d6/d98/classkcenon_1_1monitoring_1_1interface__event__subscriber.html", null ],
    [ "kcenon::monitoring::interface_metric_source", "d6/d0e/classkcenon_1_1monitoring_1_1interface__metric__source.html", null ],
    [ "kcenon::monitoring::interface_monitoring_observer", "d2/db2/classkcenon_1_1monitoring_1_1interface__monitoring__observer.html", [
      [ "test_observer", "d2/da5/classtest__observer.html", null ]
    ] ],
    [ "kcenon::monitoring::interface_observable", "d8/dc6/classkcenon_1_1monitoring_1_1interface__observable.html", [
      [ "kcenon::monitoring::interface_metric_collector", "d0/d6a/classkcenon_1_1monitoring_1_1interface__metric__collector.html", [
        [ "kcenon::monitoring::interface_aggregated_collector", "dc/de1/classkcenon_1_1monitoring_1_1interface__aggregated__collector.html", null ],
        [ "kcenon::monitoring::plugin_metric_collector", "de/d7a/classkcenon_1_1monitoring_1_1plugin__metric__collector.html", null ],
        [ "test_collector", "d9/d71/classtest__collector.html", null ]
      ] ]
    ] ],
    [ "kcenon::monitoring::platform::interrupt_info", "d4/db8/structkcenon_1_1monitoring_1_1platform_1_1interrupt__info.html", null ],
    [ "kcenon::monitoring::interrupt_info_collector", "d0/d3a/classkcenon_1_1monitoring_1_1interrupt__info__collector.html", null ],
    [ "kcenon::monitoring::interrupt_metrics", "d1/dc6/structkcenon_1_1monitoring_1_1interrupt__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::disk_metrics::io_throughput", "de/d36/structkcenon_1_1monitoring_1_1system__resources_1_1disk__metrics_1_1io__throughput.html", null ],
    [ "IService", "df/d8b/classIService.html", [
      [ "ServiceA", "d6/d19/classServiceA.html", null ],
      [ "ServiceB", "dd/d93/classServiceB.html", null ]
    ] ],
    [ "kcenon::monitoring::jaeger_span_data", "d7/df1/structkcenon_1_1monitoring_1_1jaeger__span__data.html", null ],
    [ "kcenon::monitoring::kv_storage_backend", "d0/d0e/classkcenon_1_1monitoring_1_1kv__storage__backend.html", [
      [ "kcenon::monitoring::kv_memory_storage_backend", "d1/d44/classkcenon_1_1monitoring_1_1kv__memory__storage__backend.html", null ]
    ] ],
    [ "library_handle", "df/d1d/structlibrary__handle.html", null ],
    [ "kcenon::monitoring::system_resources::cpu_metrics::load_average", "de/dc9/structkcenon_1_1monitoring_1_1system__resources_1_1cpu__metrics_1_1load__average.html", null ],
    [ "kcenon::monitoring::load_average_history", "de/d77/classkcenon_1_1monitoring_1_1load__average__history.html", null ],
    [ "kcenon::monitoring::load_average_sample", "db/daa/structkcenon_1_1monitoring_1_1load__average__sample.html", null ],
    [ "kcenon::monitoring::load_average_statistics", "d7/d40/structkcenon_1_1monitoring_1_1load__average__statistics.html", null ],
    [ "kcenon::monitoring::lockfree_queue< T >", "d0/dae/classkcenon_1_1monitoring_1_1lockfree__queue.html", null ],
    [ "kcenon::monitoring::lockfree_queue_config", "da/d03/structkcenon_1_1monitoring_1_1lockfree__queue__config.html", null ],
    [ "kcenon::monitoring::lockfree_queue_statistics", "d6/d70/structkcenon_1_1monitoring_1_1lockfree__queue__statistics.html", null ],
    [ "kcenon::monitoring::logger_to_monitoring_adapter", "d7/d37/classkcenon_1_1monitoring_1_1logger__to__monitoring__adapter.html", null ],
    [ "kcenon::monitoring::logging_metric_event::logging_stats", "d2/dad/structkcenon_1_1monitoring_1_1logging__metric__event_1_1logging__stats.html", null ],
    [ "kcenon::monitoring::system_resources::memory_metrics", "d1/dc9/structkcenon_1_1monitoring_1_1system__resources_1_1memory__metrics.html", null ],
    [ "kcenon::monitoring::memory_pool", "d0/d95/classkcenon_1_1monitoring_1_1memory__pool.html", null ],
    [ "kcenon::monitoring::memory_pool_config", "d1/dfd/structkcenon_1_1monitoring_1_1memory__pool__config.html", null ],
    [ "kcenon::monitoring::memory_pool_statistics", "d3/d18/structkcenon_1_1monitoring_1_1memory__pool__statistics.html", null ],
    [ "kcenon::monitoring::memory_quota_manager", "db/d30/classkcenon_1_1monitoring_1_1memory__quota__manager.html", null ],
    [ "kcenon::monitoring::metric", "d2/d54/structkcenon_1_1monitoring_1_1metric.html", null ],
    [ "kcenon::monitoring::metric_batch", "d2/d88/structkcenon_1_1monitoring_1_1metric__batch.html", null ],
    [ "kcenon::monitoring::metric_collector_plugin", "d7/d80/classkcenon_1_1monitoring_1_1metric__collector__plugin.html", [
      [ "kcenon::monitoring::plugins::container_plugin", "d8/d78/classkcenon_1_1monitoring_1_1plugins_1_1container__plugin.html", null ],
      [ "kcenon::monitoring::plugins::hardware_plugin", "dc/d5a/classkcenon_1_1monitoring_1_1plugins_1_1hardware__plugin.html", null ],
      [ "kcenon::monitoring::system_resource_collector", "d7/d5f/classkcenon_1_1monitoring_1_1system__resource__collector.html", null ]
    ] ],
    [ "kcenon::monitoring::performance_monitor::metric_data", "d1/d64/structkcenon_1_1monitoring_1_1performance__monitor_1_1metric__data.html", null ],
    [ "kcenon::monitoring::metric_event", "d1/d65/classkcenon_1_1monitoring_1_1metric__event.html", null ],
    [ "kcenon::monitoring::metric_export_config", "de/d6f/structkcenon_1_1monitoring_1_1metric__export__config.html", null ],
    [ "kcenon::monitoring::metric_exporter_factory", "d7/d57/classkcenon_1_1monitoring_1_1metric__exporter__factory.html", null ],
    [ "kcenon::monitoring::metric_exporter_interface", "d9/d3c/classkcenon_1_1monitoring_1_1metric__exporter__interface.html", [
      [ "kcenon::monitoring::otlp_metrics_exporter", "d1/dc5/classkcenon_1_1monitoring_1_1otlp__metrics__exporter.html", null ],
      [ "kcenon::monitoring::prometheus_exporter", "d6/dd7/classkcenon_1_1monitoring_1_1prometheus__exporter.html", null ],
      [ "kcenon::monitoring::statsd_exporter", "d4/dd1/classkcenon_1_1monitoring_1_1statsd__exporter.html", null ]
    ] ],
    [ "kcenon::monitoring::metric_factory", "d3/df2/classkcenon_1_1monitoring_1_1metric__factory.html", null ],
    [ "kcenon::monitoring::metric_filter", "de/d26/classkcenon_1_1monitoring_1_1metric__filter.html", null ],
    [ "kcenon::monitoring::metric_metadata", "da/df6/structkcenon_1_1monitoring_1_1metric__metadata.html", null ],
    [ "kcenon::monitoring::metric_sample", "d5/d97/structkcenon_1_1monitoring_1_1metric__sample.html", null ],
    [ "kcenon::monitoring::metric_stats", "dc/d14/structkcenon_1_1monitoring_1_1metric__stats.html", null ],
    [ "kcenon::monitoring::metric_storage", "d4/dc5/classkcenon_1_1monitoring_1_1metric__storage.html", null ],
    [ "kcenon::monitoring::metric_storage_config", "d0/d17/structkcenon_1_1monitoring_1_1metric__storage__config.html", null ],
    [ "kcenon::monitoring::metric_storage_stats", "d4/d85/structkcenon_1_1monitoring_1_1metric__storage__stats.html", null ],
    [ "kcenon::monitoring::metric_value", "d1/d45/structkcenon_1_1monitoring_1_1metric__value.html", null ],
    [ "kcenon::monitoring::metrics_analyzer", "d0/da4/classkcenon_1_1monitoring_1_1metrics__analyzer.html", null ],
    [ "kcenon::monitoring::metrics_collector", "d0/d4a/classkcenon_1_1monitoring_1_1metrics__collector.html", [
      [ "kcenon::monitoring::performance_monitor", "d6/daa/classkcenon_1_1monitoring_1_1performance__monitor.html", null ],
      [ "mock_collector", "d9/d8d/classmock__collector.html", null ]
    ] ],
    [ "metrics_collector_interface", "df/d8a/classmetrics__collector__interface.html", [
      [ "metrics_collector_adapter", "dc/d68/classmetrics__collector__adapter.html", null ],
      [ "performance_monitor_old", "d2/d91/classperformance__monitor__old.html", null ]
    ] ],
    [ "kcenon::monitoring::platform::metrics_provider", "d3/d8e/classkcenon_1_1monitoring_1_1platform_1_1metrics__provider.html", null ],
    [ "kcenon::monitoring::metrics_snapshot", "dd/dd7/structkcenon_1_1monitoring_1_1metrics__snapshot.html", null ],
    [ "kcenon::monitoring::monitorable_interface", "db/d67/classkcenon_1_1monitoring_1_1monitorable__interface.html", [
      [ "kcenon::monitoring::monitorable_component", "d7/da1/classkcenon_1_1monitoring_1_1monitorable__component.html", [
        [ "test_monitorable_component", "d9/db4/classtest__monitorable__component.html", null ]
      ] ]
    ] ],
    [ "kcenon::monitoring::monitoring_aggregator", "db/df3/classkcenon_1_1monitoring_1_1monitoring__aggregator.html", null ],
    [ "kcenon::monitoring::monitoring_config", "dc/db5/structkcenon_1_1monitoring_1_1monitoring__config.html", null ],
    [ "kcenon::monitoring::monitoring_data", "df/d98/structkcenon_1_1monitoring_1_1monitoring__data.html", null ],
    [ "kcenon::monitoring::monitoring_interface", "da/d7d/classkcenon_1_1monitoring_1_1monitoring__interface.html", null ],
    [ "kcenon::monitoring::moving_window_aggregator< T >", "db/d89/classkcenon_1_1monitoring_1_1moving__window__aggregator.html", null ],
    [ "kcenon::monitoring::network_info_collector", "d5/de7/classkcenon_1_1monitoring_1_1network__info__collector.html", null ],
    [ "kcenon::monitoring::network_metrics", "d0/d8f/structkcenon_1_1monitoring_1_1network__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::network_metrics", "d9/d2d/structkcenon_1_1monitoring_1_1system__resources_1_1network__metrics.html", null ],
    [ "kcenon::monitoring::network_metrics_config", "d0/d3c/structkcenon_1_1monitoring_1_1network__metrics__config.html", null ],
    [ "kcenon::monitoring::system_info_collector::network_stats", "d3/d3d/structkcenon_1_1monitoring_1_1system__info__collector_1_1network__stats.html", null ],
    [ "kcenon::monitoring::online_statistics", "d8/dca/classkcenon_1_1monitoring_1_1online__statistics.html", null ],
    [ "kcenon::monitoring::opentelemetry_compatibility_layer", "de/d18/classkcenon_1_1monitoring_1_1opentelemetry__compatibility__layer.html", null ],
    [ "kcenon::monitoring::opentelemetry_exporter_config", "d0/db3/structkcenon_1_1monitoring_1_1opentelemetry__exporter__config.html", null ],
    [ "kcenon::monitoring::opentelemetry_metrics_adapter", "d6/d8d/classkcenon_1_1monitoring_1_1opentelemetry__metrics__adapter.html", null ],
    [ "kcenon::monitoring::opentelemetry_tracer_adapter", "dd/d43/classkcenon_1_1monitoring_1_1opentelemetry__tracer__adapter.html", null ],
    [ "kcenon::monitoring::otel_attribute", "d0/d58/structkcenon_1_1monitoring_1_1otel__attribute.html", null ],
    [ "kcenon::monitoring::otel_metric_data", "db/de4/structkcenon_1_1monitoring_1_1otel__metric__data.html", null ],
    [ "kcenon::monitoring::otel_resource", "d0/d70/structkcenon_1_1monitoring_1_1otel__resource.html", null ],
    [ "kcenon::monitoring::otel_span_context", "dd/d2f/structkcenon_1_1monitoring_1_1otel__span__context.html", null ],
    [ "kcenon::monitoring::otel_span_data", "d1/d33/structkcenon_1_1monitoring_1_1otel__span__data.html", null ],
    [ "kcenon::monitoring::otlp_exporter_stats", "d0/d0f/structkcenon_1_1monitoring_1_1otlp__exporter__stats.html", null ],
    [ "kcenon::monitoring::otlp_grpc_config", "db/dca/structkcenon_1_1monitoring_1_1otlp__grpc__config.html", null ],
    [ "kcenon::monitoring::otlp_span_converter", "d1/d45/classkcenon_1_1monitoring_1_1otlp__span__converter.html", null ],
    [ "kcenon::monitoring::performance_benchmark", "de/d69/classkcenon_1_1monitoring_1_1performance__benchmark.html", null ],
    [ "kcenon::monitoring::performance_metrics", "db/d4d/structkcenon_1_1monitoring_1_1performance__metrics.html", null ],
    [ "kcenon::monitoring::adapters::performance_monitor_adapter", "d0/d73/classkcenon_1_1monitoring_1_1adapters_1_1performance__monitor__adapter.html", null ],
    [ "performance_monitor_facade", "d9/d17/classperformance__monitor__facade.html", null ],
    [ "performance_monitor_impl", "db/d7f/classperformance__monitor__impl.html", null ],
    [ "kcenon::monitoring::performance_profile", "d8/d86/structkcenon_1_1monitoring_1_1performance__profile.html", null ],
    [ "kcenon::monitoring::performance_profiler", "d4/d20/classkcenon_1_1monitoring_1_1performance__profiler.html", null ],
    [ "kcenon::monitoring::pipeline_stage", "d2/d82/classkcenon_1_1monitoring_1_1pipeline__stage.html", null ],
    [ "kcenon::monitoring::platform_context_switches", "d2/d26/structkcenon_1_1monitoring_1_1platform__context__switches.html", null ],
    [ "kcenon::monitoring::platform_info", "da/d4d/structkcenon_1_1monitoring_1_1platform__info.html", null ],
    [ "kcenon::monitoring::platform_info_collector", "dc/d77/classkcenon_1_1monitoring_1_1platform__info__collector.html", null ],
    [ "kcenon::monitoring::platform_interrupt_info", "d4/d13/structkcenon_1_1monitoring_1_1platform__interrupt__info.html", null ],
    [ "kcenon::monitoring::platform_metrics", "d7/d69/structkcenon_1_1monitoring_1_1platform__metrics.html", null ],
    [ "kcenon::monitoring::platform_metrics_config", "d4/d98/structkcenon_1_1monitoring_1_1platform__metrics__config.html", null ],
    [ "kcenon::monitoring::platform_socket_info", "da/d87/structkcenon_1_1monitoring_1_1platform__socket__info.html", null ],
    [ "kcenon::monitoring::platform_tcp_info", "d0/dd4/structkcenon_1_1monitoring_1_1platform__tcp__info.html", null ],
    [ "kcenon::monitoring::platform_uptime", "df/d46/structkcenon_1_1monitoring_1_1platform__uptime.html", null ],
    [ "plugin_api_metadata", "d7/d98/structplugin__api__metadata.html", null ],
    [ "kcenon::monitoring::plugin_collector_config", "dd/dd3/structkcenon_1_1monitoring_1_1plugin__collector__config.html", null ],
    [ "kcenon::monitoring::dynamic_plugin_loader::plugin_entry", "d0/d64/structkcenon_1_1monitoring_1_1dynamic__plugin__loader_1_1plugin__entry.html", null ],
    [ "kcenon::monitoring::plugin_factory", "d6/d90/classkcenon_1_1monitoring_1_1plugin__factory.html", null ],
    [ "kcenon::monitoring::plugin_loader", "dd/d7e/classkcenon_1_1monitoring_1_1plugin__loader.html", [
      [ "kcenon::monitoring::dynamic_plugin_loader", "de/d25/classkcenon_1_1monitoring_1_1dynamic__plugin__loader.html", null ]
    ] ],
    [ "kcenon::monitoring::plugin_metadata", "df/d8e/structkcenon_1_1monitoring_1_1plugin__metadata.html", null ],
    [ "kcenon::monitoring::platform::power_info", "d4/d69/structkcenon_1_1monitoring_1_1platform_1_1power__info.html", null ],
    [ "kcenon::monitoring::power_info_collector", "dc/dc2/classkcenon_1_1monitoring_1_1power__info__collector.html", null ],
    [ "kcenon::monitoring::power_reading", "d7/d3f/structkcenon_1_1monitoring_1_1power__reading.html", null ],
    [ "kcenon::monitoring::power_source_info", "d3/d78/structkcenon_1_1monitoring_1_1power__source__info.html", null ],
    [ "kcenon::monitoring::process_context_switch_info", "d7/d9e/structkcenon_1_1monitoring_1_1process__context__switch__info.html", null ],
    [ "kcenon::monitoring::process_metrics", "d9/dab/structkcenon_1_1monitoring_1_1process__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::process_metrics", "dc/d13/structkcenon_1_1monitoring_1_1system__resources_1_1process__metrics.html", null ],
    [ "kcenon::monitoring::process_metrics_config", "dc/d66/structkcenon_1_1monitoring_1_1process__metrics__config.html", null ],
    [ "kcenon::monitoring::central_collector::profile_data", "d0/ddf/structkcenon_1_1monitoring_1_1central__collector_1_1profile__data.html", null ],
    [ "kcenon::monitoring::performance_profiler::profile_data", "d1/d27/structkcenon_1_1monitoring_1_1performance__profiler_1_1profile__data.html", null ],
    [ "kcenon::monitoring::prometheus_metric_data", "d6/d21/structkcenon_1_1monitoring_1_1prometheus__metric__data.html", null ],
    [ "kcenon::monitoring::quantile_estimator", "dc/ded/classkcenon_1_1monitoring_1_1quantile__estimator.html", null ],
    [ "kcenon::monitoring::rate_limit_config", "de/d18/structkcenon_1_1monitoring_1_1rate__limit__config.html", null ],
    [ "kcenon::monitoring::rate_limiter", "df/d5b/classkcenon_1_1monitoring_1_1rate__limiter.html", [
      [ "kcenon::monitoring::leaky_bucket_limiter", "d8/dab/classkcenon_1_1monitoring_1_1leaky__bucket__limiter.html", null ],
      [ "kcenon::monitoring::token_bucket_limiter", "d8/d67/classkcenon_1_1monitoring_1_1token__bucket__limiter.html", null ]
    ] ],
    [ "kcenon::monitoring::resource_manager", "df/dfd/classkcenon_1_1monitoring_1_1resource__manager.html", null ],
    [ "kcenon::monitoring::resource_metrics", "df/dfd/structkcenon_1_1monitoring_1_1resource__metrics.html", null ],
    [ "kcenon::monitoring::resource_quota", "d2/dcd/structkcenon_1_1monitoring_1_1resource__quota.html", null ],
    [ "kcenon::monitoring::system_resource_event::resource_stats", "d0/de7/structkcenon_1_1monitoring_1_1system__resource__event_1_1resource__stats.html", null ],
    [ "kcenon::monitoring::resource_threshold_monitor", "d9/d7b/classkcenon_1_1monitoring_1_1resource__threshold__monitor.html", null ],
    [ "kcenon::monitoring::retry_config", "d4/d7d/structkcenon_1_1monitoring_1_1retry__config.html", null ],
    [ "kcenon::monitoring::retry_executor< T >", "d9/d1a/classkcenon_1_1monitoring_1_1retry__executor.html", null ],
    [ "kcenon::monitoring::retry_executor_registry", "da/d65/classkcenon_1_1monitoring_1_1retry__executor__registry.html", null ],
    [ "kcenon::monitoring::retry_metrics", "dc/de7/structkcenon_1_1monitoring_1_1retry__metrics.html", null ],
    [ "kcenon::monitoring::retry_policy", "d3/d0a/classkcenon_1_1monitoring_1_1retry__policy.html", null ],
    [ "kcenon::monitoring::ring_buffer< T >", "d8/d1f/classkcenon_1_1monitoring_1_1ring__buffer.html", null ],
    [ "kcenon::monitoring::ring_buffer< kcenon::monitoring::compact_metric_value >", "d8/d1f/classkcenon_1_1monitoring_1_1ring__buffer.html", null ],
    [ "kcenon::monitoring::ring_buffer_config", "da/d9a/structkcenon_1_1monitoring_1_1ring__buffer__config.html", null ],
    [ "kcenon::monitoring::ring_buffer_stats", "d3/d99/structkcenon_1_1monitoring_1_1ring__buffer__stats.html", null ],
    [ "kcenon::monitoring::routing_notifier::route", "d4/dc3/structkcenon_1_1monitoring_1_1routing__notifier_1_1route.html", null ],
    [ "kcenon::monitoring::rule_builder", "d0/d76/classkcenon_1_1monitoring_1_1rule__builder.html", null ],
    [ "kcenon::monitoring::rule_definition", "d0/de2/structkcenon_1_1monitoring_1_1rule__definition.html", null ],
    [ "kcenon::monitoring::rule_registry", "df/d96/classkcenon_1_1monitoring_1_1rule__registry.html", null ],
    [ "kcenon::monitoring::safe_event_dispatcher", "da/d26/classkcenon_1_1monitoring_1_1safe__event__dispatcher.html", null ],
    [ "kcenon::monitoring::rate_of_change_trigger::sample", "de/d10/structkcenon_1_1monitoring_1_1rate__of__change__trigger_1_1sample.html", null ],
    [ "kcenon::monitoring::scoped_span", "dc/d00/classkcenon_1_1monitoring_1_1scoped__span.html", null ],
    [ "kcenon::monitoring::scoped_timer", "dc/dcc/classkcenon_1_1monitoring_1_1scoped__timer.html", null ],
    [ "kcenon::monitoring::security_event", "d0/d6a/structkcenon_1_1monitoring_1_1security__event.html", null ],
    [ "kcenon::monitoring::security_event_counts", "d2/d7c/structkcenon_1_1monitoring_1_1security__event__counts.html", null ],
    [ "kcenon::monitoring::platform::security_info", "d7/d10/structkcenon_1_1monitoring_1_1platform_1_1security__info.html", null ],
    [ "kcenon::monitoring::security_info_collector", "d8/d6e/classkcenon_1_1monitoring_1_1security__info__collector.html", null ],
    [ "kcenon::monitoring::security_metrics", "d4/d5f/structkcenon_1_1monitoring_1_1security__metrics.html", null ],
    [ "kcenon::monitoring::service_config", "d7/d35/structkcenon_1_1monitoring_1_1service__config.html", null ],
    [ "kcenon::monitoring::service_state", "d5/d4f/structkcenon_1_1monitoring_1_1service__state.html", null ],
    [ "kcenon::monitoring::simd_aggregator", "d0/d86/classkcenon_1_1monitoring_1_1simd__aggregator.html", null ],
    [ "kcenon::monitoring::simd_aggregator_statistics", "db/de1/structkcenon_1_1monitoring_1_1simd__aggregator__statistics.html", null ],
    [ "kcenon::monitoring::simd_capabilities", "d1/d09/structkcenon_1_1monitoring_1_1simd__capabilities.html", null ],
    [ "kcenon::monitoring::simd_config", "d9/df8/structkcenon_1_1monitoring_1_1simd__config.html", null ],
    [ "kcenon::monitoring::lockfree_queue< T >::slot", "db/d2e/structkcenon_1_1monitoring_1_1lockfree__queue_1_1slot.html", null ],
    [ "kcenon::monitoring::smart_disk_metrics", "dd/d5f/structkcenon_1_1monitoring_1_1smart__disk__metrics.html", null ],
    [ "kcenon::monitoring::smart_info_collector", "db/dbf/classkcenon_1_1monitoring_1_1smart__info__collector.html", null ],
    [ "kcenon::monitoring::timer_data::snapshot", "d5/d2c/structkcenon_1_1monitoring_1_1timer__data_1_1snapshot.html", null ],
    [ "kcenon::monitoring::snapshot_storage_backend", "df/dba/classkcenon_1_1monitoring_1_1snapshot__storage__backend.html", [
      [ "kcenon::monitoring::cloud_storage_backend", "d9/d36/classkcenon_1_1monitoring_1_1cloud__storage__backend.html", null ],
      [ "kcenon::monitoring::database_storage_backend", "df/df3/classkcenon_1_1monitoring_1_1database__storage__backend.html", null ],
      [ "kcenon::monitoring::file_storage_backend", "df/d62/classkcenon_1_1monitoring_1_1file__storage__backend.html", null ],
      [ "kcenon::monitoring::memory_storage_backend", "d3/d1c/classkcenon_1_1monitoring_1_1memory__storage__backend.html", null ]
    ] ],
    [ "kcenon::monitoring::platform::socket_buffer_info", "d0/d6b/structkcenon_1_1monitoring_1_1platform_1_1socket__buffer__info.html", null ],
    [ "kcenon::monitoring::span_builder", "d6/dca/classkcenon_1_1monitoring_1_1span__builder.html", null ],
    [ "kcenon::monitoring::state_change_event", "d6/d27/classkcenon_1_1monitoring_1_1state__change__event.html", null ],
    [ "kcenon::monitoring::state_validator", "da/d61/classkcenon_1_1monitoring_1_1state__validator.html", null ],
    [ "kcenon::monitoring::statistical_summary", "d4/dc4/structkcenon_1_1monitoring_1_1statistical__summary.html", null ],
    [ "kcenon::monitoring::stats::statistics< T >", "db/de5/structkcenon_1_1monitoring_1_1stats_1_1statistics.html", null ],
    [ "kcenon::monitoring::central_collector::stats", "d7/dd7/structkcenon_1_1monitoring_1_1central__collector_1_1stats.html", null ],
    [ "kcenon::monitoring::event_bus::stats", "d4/d57/structkcenon_1_1monitoring_1_1event__bus_1_1stats.html", null ],
    [ "kcenon::monitoring::thread_local_buffer::stats", "de/dea/structkcenon_1_1monitoring_1_1thread__local__buffer_1_1stats.html", null ],
    [ "kcenon::monitoring::statsd_metric_data", "d0/d5e/structkcenon_1_1monitoring_1_1statsd__metric__data.html", null ],
    [ "kcenon::monitoring::storage_backend", "db/dab/classkcenon_1_1monitoring_1_1storage__backend.html", null ],
    [ "kcenon::monitoring::storage_backend_factory", "da/dbb/classkcenon_1_1monitoring_1_1storage__backend__factory.html", null ],
    [ "kcenon::monitoring::storage_config", "da/d75/structkcenon_1_1monitoring_1_1storage__config.html", null ],
    [ "kcenon::monitoring::stream_aggregation_result", "d8/de5/structkcenon_1_1monitoring_1_1stream__aggregation__result.html", null ],
    [ "kcenon::monitoring::stream_aggregator", "d3/d10/classkcenon_1_1monitoring_1_1stream__aggregator.html", null ],
    [ "kcenon::monitoring::stream_aggregator_config", "dd/d14/structkcenon_1_1monitoring_1_1stream__aggregator__config.html", null ],
    [ "kcenon::monitoring::streaming_statistics", "d9/dae/structkcenon_1_1monitoring_1_1streaming__statistics.html", null ],
    [ "kcenon::monitoring::subscription_token", "d2/df0/classkcenon_1_1monitoring_1_1subscription__token.html", null ],
    [ "kcenon::monitoring::summary_data", "d0/da2/structkcenon_1_1monitoring_1_1summary__data.html", null ],
    [ "kcenon::monitoring::system_resources::memory_metrics::swap_info", "dd/da1/structkcenon_1_1monitoring_1_1system__resources_1_1memory__metrics_1_1swap__info.html", null ],
    [ "kcenon::monitoring::system_event", "db/d0d/classkcenon_1_1monitoring_1_1system__event.html", null ],
    [ "kcenon::monitoring::system_info_collector", "d2/d4d/classkcenon_1_1monitoring_1_1system__info__collector.html", null ],
    [ "kcenon::monitoring::system_metrics", "df/de9/structkcenon_1_1monitoring_1_1system__metrics.html", null ],
    [ "kcenon::monitoring::system_metrics_config", "de/da6/structkcenon_1_1monitoring_1_1system__metrics__config.html", null ],
    [ "kcenon::monitoring::system_monitor", "dc/d4e/classkcenon_1_1monitoring_1_1system__monitor.html", null ],
    [ "kcenon::monitoring::system_resources", "dc/d4b/structkcenon_1_1monitoring_1_1system__resources.html", null ],
    [ "kcenon::monitoring::tagged_metric", "d4/d55/structkcenon_1_1monitoring_1_1tagged__metric.html", null ],
    [ "kcenon::monitoring::tcp_state_counts", "d0/d63/structkcenon_1_1monitoring_1_1tcp__state__counts.html", null ],
    [ "kcenon::monitoring::platform::tcp_state_info", "d5/d7d/structkcenon_1_1monitoring_1_1platform_1_1tcp__state__info.html", null ],
    [ "kcenon::monitoring::temperature_info_collector", "d0/d06/classkcenon_1_1monitoring_1_1temperature__info__collector.html", null ],
    [ "kcenon::monitoring::temperature_reading", "dc/d0e/structkcenon_1_1monitoring_1_1temperature__reading.html", null ],
    [ "kcenon::monitoring::temperature_sensor_info", "d7/dab/structkcenon_1_1monitoring_1_1temperature__sensor__info.html", null ],
    [ "testing::Test", null, [
      [ "AbsentTriggerTest", "d4/d9e/classAbsentTriggerTest.html", null ],
      [ "AdaptiveMonitoringTest", "d9/dfa/classAdaptiveMonitoringTest.html", null ],
      [ "AlertGroupTest", "d5/d8e/classAlertGroupTest.html", null ],
      [ "AlertLabelsTest", "d7/dce/classAlertLabelsTest.html", null ],
      [ "AlertManagerLifecycleTest", "dc/d62/classAlertManagerLifecycleTest.html", null ],
      [ "AlertManagerNotifierTest", "df/d49/classAlertManagerNotifierTest.html", null ],
      [ "AlertManagerProcessingTest", "dd/dfb/classAlertManagerProcessingTest.html", null ],
      [ "AlertManagerResolutionTest", "d7/d22/classAlertManagerResolutionTest.html", null ],
      [ "AlertManagerRuleTest", "d3/dd7/classAlertManagerRuleTest.html", null ],
      [ "AlertManagerSilenceTest", "d6/d33/classAlertManagerSilenceTest.html", null ],
      [ "AlertSilenceTest", "d3/d87/classAlertSilenceTest.html", null ],
      [ "AlertTest", "d7/db5/classAlertTest.html", null ],
      [ "AlertTransitionTest", "d3/d2c/classAlertTransitionTest.html", null ],
      [ "AnomalyTriggerTest", "d6/dd6/classAnomalyTriggerTest.html", null ],
      [ "BufferingStrategiesTest", "d9/dee/classBufferingStrategiesTest.html", null ],
      [ "CollectorRegistryIntegrationTest", "d5/dc2/classCollectorRegistryIntegrationTest.html", null ],
      [ "CompositeTriggerTest", "d9/ded/classCompositeTriggerTest.html", null ],
      [ "DIContainerTest", "d9/da4/classDIContainerTest.html", null ],
      [ "DataConsistencyTest", "d8/d07/classDataConsistencyTest.html", null ],
      [ "DeltaTriggerTest", "d4/dcd/classDeltaTriggerTest.html", null ],
      [ "DistributedTracingTest", "d9/d51/classDistributedTracingTest.html", null ],
      [ "ErrorBoundariesTest", "db/d11/classErrorBoundariesTest.html", null ],
      [ "EventBusTest", "d7/d12/classEventBusTest.html", null ],
      [ "ExporterIntegrationTest", "dd/d3d/classExporterIntegrationTest.html", null ],
      [ "FaultToleranceTest", "d4/d91/classFaultToleranceTest.html", null ],
      [ "HealthMonitoringTest", "da/d18/classHealthMonitoringTest.html", null ],
      [ "HistogramMetricsTest", "d0/d7d/classHistogramMetricsTest.html", null ],
      [ "HotPathHelperTest", "de/d76/classHotPathHelperTest.html", null ],
      [ "IntegrationE2ETest", "d9/d92/classIntegrationE2ETest.html", null ],
      [ "LockFreeCollectorTest", "d6/dab/classLockFreeCollectorTest.html", null ],
      [ "MetricExportersTest", "d9/d66/classMetricExportersTest.html", null ],
      [ "MetricStorageTest", "d6/d95/classMetricStorageTest.html", null ],
      [ "MonitorableInterfaceTest", "d8/d4d/classMonitorableInterfaceTest.html", null ],
      [ "MonitoringThreadSafetyTest", "d9/d57/classMonitoringThreadSafetyTest.html", null ],
      [ "OpenTelemetryAdapterTest", "d5/d90/classOpenTelemetryAdapterTest.html", null ],
      [ "OptimizationTest", "db/d93/classOptimizationTest.html", null ],
      [ "PerformanceMonitorThreadSafetyTest", "d8/d32/classPerformanceMonitorThreadSafetyTest.html", null ],
      [ "PerformanceMonitoringTest", "d7/dbe/classPerformanceMonitoringTest.html", null ],
      [ "PerformanceProfilerThreadSafetyTest", "df/d0f/classPerformanceProfilerThreadSafetyTest.html", null ],
      [ "RangeTriggerTest", "d1/dd2/classRangeTriggerTest.html", null ],
      [ "RateOfChangeTriggerTest", "d3/d59/classRateOfChangeTriggerTest.html", null ],
      [ "ResourceManagementTest", "d7/d4c/classResourceManagementTest.html", null ],
      [ "ResultTypesTest", "d3/d70/classResultTypesTest.html", null ],
      [ "StatisticsUtilsTest", "d3/dd3/classStatisticsUtilsTest.html", null ],
      [ "StorageBackendsTest", "d4/dcd/classStorageBackendsTest.html", null ],
      [ "StreamAggregationTest", "de/d8e/classStreamAggregationTest.html", null ],
      [ "StressPerformanceTest", "d9/dbf/classStressPerformanceTest.html", null ],
      [ "SummaryMetricsTest", "db/da7/classSummaryMetricsTest.html", null ],
      [ "SystemResourceCollectorTest", "da/df3/classSystemResourceCollectorTest.html", null ],
      [ "ThreadContextTest", "d5/d8c/classThreadContextTest.html", null ],
      [ "ThresholdTriggerTest", "dc/d76/classThresholdTriggerTest.html", null ],
      [ "TimerMetricsTest", "da/d72/classTimerMetricsTest.html", null ],
      [ "TraceExportersTest", "de/d2d/classTraceExportersTest.html", [
        [ "OtlpGrpcExporterTest", "df/de1/classOtlpGrpcExporterTest.html", null ]
      ] ]
    ] ],
    [ "kcenon::monitoring::thread_context", "d8/d14/classkcenon_1_1monitoring_1_1thread__context.html", null ],
    [ "kcenon::monitoring::thread_context_data", "d8/d87/structkcenon_1_1monitoring_1_1thread__context__data.html", null ],
    [ "kcenon::monitoring::thread_context_manager", "d3/dc6/classkcenon_1_1monitoring_1_1thread__context__manager.html", null ],
    [ "kcenon::monitoring::thread_local_buffer", "d6/dd1/classkcenon_1_1monitoring_1_1thread__local__buffer.html", null ],
    [ "kcenon::monitoring::thread_pool_metric_event::thread_pool_stats", "d8/d14/structkcenon_1_1monitoring_1_1thread__pool__metric__event_1_1thread__pool__stats.html", null ],
    [ "kcenon::monitoring::thread_to_monitoring_adapter", "dc/d7f/classkcenon_1_1monitoring_1_1thread__to__monitoring__adapter.html", null ],
    [ "kcenon::monitoring::performance_monitor::thresholds", "dc/dc9/structkcenon_1_1monitoring_1_1performance__monitor_1_1thresholds.html", null ],
    [ "kcenon::monitoring::resource_threshold_monitor::thresholds", "db/d23/structkcenon_1_1monitoring_1_1resource__threshold__monitor_1_1thresholds.html", null ],
    [ "kcenon::monitoring::time_point_data", "da/df4/structkcenon_1_1monitoring_1_1time__point__data.html", null ],
    [ "kcenon::monitoring::time_series", "dc/d3c/classkcenon_1_1monitoring_1_1time__series.html", null ],
    [ "kcenon::monitoring::time_series_buffer< T >", "d7/d7c/classkcenon_1_1monitoring_1_1time__series__buffer.html", null ],
    [ "kcenon::monitoring::time_series_buffer_config", "d6/df9/structkcenon_1_1monitoring_1_1time__series__buffer__config.html", null ],
    [ "kcenon::monitoring::time_series_config", "d3/d52/structkcenon_1_1monitoring_1_1time__series__config.html", null ],
    [ "kcenon::monitoring::time_series_query", "d2/dff/structkcenon_1_1monitoring_1_1time__series__query.html", null ],
    [ "kcenon::monitoring::detail::time_series_ring_buffer< Sample >", "d8/d2f/classkcenon_1_1monitoring_1_1detail_1_1time__series__ring__buffer.html", null ],
    [ "kcenon::monitoring::detail::time_series_ring_buffer< kcenon::monitoring::load_average_sample >", "d8/d2f/classkcenon_1_1monitoring_1_1detail_1_1time__series__ring__buffer.html", null ],
    [ "kcenon::monitoring::detail::time_series_ring_buffer< kcenon::monitoring::time_series_sample< T > >", "d8/d2f/classkcenon_1_1monitoring_1_1detail_1_1time__series__ring__buffer.html", null ],
    [ "kcenon::monitoring::time_series_sample< T >", "dc/d90/structkcenon_1_1monitoring_1_1time__series__sample.html", null ],
    [ "kcenon::monitoring::time_series_statistics", "d9/de6/structkcenon_1_1monitoring_1_1time__series__statistics.html", null ],
    [ "kcenon::monitoring::timer_data", "db/d67/structkcenon_1_1monitoring_1_1timer__data.html", null ],
    [ "kcenon::monitoring::timer_scope", "d4/d01/classkcenon_1_1monitoring_1_1timer__scope.html", null ],
    [ "kcenon::monitoring::trace_context", "d1/de5/structkcenon_1_1monitoring_1_1trace__context.html", null ],
    [ "kcenon::monitoring::trace_export_config", "d0/d59/structkcenon_1_1monitoring_1_1trace__export__config.html", null ],
    [ "kcenon::monitoring::trace_export_settings", "d5/d90/structkcenon_1_1monitoring_1_1trace__export__settings.html", null ],
    [ "kcenon::monitoring::trace_exporter_factory", "dd/d09/classkcenon_1_1monitoring_1_1trace__exporter__factory.html", null ],
    [ "kcenon::monitoring::trace_exporter_interface", "dd/d66/classkcenon_1_1monitoring_1_1trace__exporter__interface.html", [
      [ "MockTraceExporter", "d7/da2/classMockTraceExporter.html", null ],
      [ "kcenon::monitoring::jaeger_exporter", "d2/dc2/classkcenon_1_1monitoring_1_1jaeger__exporter.html", null ],
      [ "kcenon::monitoring::otlp_exporter", "d5/d71/classkcenon_1_1monitoring_1_1otlp__exporter.html", null ],
      [ "kcenon::monitoring::otlp_grpc_exporter", "da/daa/classkcenon_1_1monitoring_1_1otlp__grpc__exporter.html", null ],
      [ "kcenon::monitoring::zipkin_exporter", "db/d0a/classkcenon_1_1monitoring_1_1zipkin__exporter.html", null ]
    ] ],
    [ "kcenon::monitoring::trace_span", "d1/d04/structkcenon_1_1monitoring_1_1trace__span.html", null ],
    [ "kcenon::monitoring::transaction", "dd/d84/classkcenon_1_1monitoring_1_1transaction.html", null ],
    [ "kcenon::monitoring::transaction_config", "d6/de3/structkcenon_1_1monitoring_1_1transaction__config.html", null ],
    [ "kcenon::monitoring::transaction_manager", "d3/ddf/classkcenon_1_1monitoring_1_1transaction__manager.html", null ],
    [ "kcenon::monitoring::transaction_metrics", "d9/dc2/structkcenon_1_1monitoring_1_1transaction__metrics.html", null ],
    [ "kcenon::monitoring::transaction_operation", "d2/dab/classkcenon_1_1monitoring_1_1transaction__operation.html", null ],
    [ "kcenon::monitoring::rule_definition::trigger_config", "d4/d74/structkcenon_1_1monitoring_1_1rule__definition_1_1trigger__config.html", null ],
    [ "std::true_type", null, [
      [ "kcenon::monitoring::stats::detail::is_chrono_duration< std::chrono::duration< Rep, Period > >", "d6/d8e/structkcenon_1_1monitoring_1_1stats_1_1detail_1_1is__chrono__duration_3_01std_1_1chrono_1_1durat67ba77e32eb716cbe525f0013060fa95.html", null ]
    ] ],
    [ "kcenon::monitoring::udp_send_result", "db/d33/structkcenon_1_1monitoring_1_1udp__send__result.html", null ],
    [ "kcenon::monitoring::udp_statistics", "d4/d45/structkcenon_1_1monitoring_1_1udp__statistics.html", null ],
    [ "kcenon::monitoring::udp_transport", "d7/dda/classkcenon_1_1monitoring_1_1udp__transport.html", [
      [ "kcenon::monitoring::stub_udp_transport", "da/d9f/classkcenon_1_1monitoring_1_1stub__udp__transport.html", null ]
    ] ],
    [ "unreliable_service", "db/dad/classunreliable__service.html", null ],
    [ "kcenon::monitoring::platform::uptime_info", "d7/d55/structkcenon_1_1monitoring_1_1platform_1_1uptime__info.html", null ],
    [ "kcenon::monitoring::uptime_info_collector", "d1/d74/classkcenon_1_1monitoring_1_1uptime__info__collector.html", null ],
    [ "kcenon::monitoring::uptime_metrics", "d4/d40/structkcenon_1_1monitoring_1_1uptime__metrics.html", null ],
    [ "kcenon::monitoring::simple_http_client::url_parts", "d4/d69/structkcenon_1_1monitoring_1_1simple__http__client_1_1url__parts.html", null ],
    [ "UserService", "d9/dd9/classUserService.html", null ],
    [ "kcenon::monitoring::validation_config", "d9/db4/structkcenon_1_1monitoring_1_1validation__config.html", null ],
    [ "kcenon::monitoring::validation_metrics", "d5/dc1/structkcenon_1_1monitoring_1_1validation__metrics.html", null ],
    [ "kcenon::monitoring::state_validator::validation_rule", "d9/df8/structkcenon_1_1monitoring_1_1state__validator_1_1validation__rule.html", null ],
    [ "kcenon::monitoring::vm_info_collector", "d7/d39/classkcenon_1_1monitoring_1_1vm__info__collector.html", null ],
    [ "kcenon::monitoring::vm_metrics", "d9/d79/structkcenon_1_1monitoring_1_1vm__metrics.html", null ],
    [ "kcenon::monitoring::webhook_config", "da/d26/structkcenon_1_1monitoring_1_1webhook__config.html", null ],
    [ "WebService", "df/d65/classWebService.html", null ],
    [ "kcenon::monitoring::zipkin_span_data", "d1/d12/structkcenon_1_1monitoring_1_1zipkin__span__data.html", null ]
];