var hierarchy =
[
    [ "kcenon::monitoring::adaptation_stats", "structkcenon_1_1monitoring_1_1adaptation__stats.html", null ],
    [ "kcenon::monitoring::adaptive_collector", "classkcenon_1_1monitoring_1_1adaptive__collector.html", null ],
    [ "kcenon::monitoring::adaptive_config", "structkcenon_1_1monitoring_1_1adaptive__config.html", null ],
    [ "kcenon::monitoring::adaptive_monitor", "classkcenon_1_1monitoring_1_1adaptive__monitor.html", null ],
    [ "kcenon::monitoring::adaptive_scope", "classkcenon_1_1monitoring_1_1adaptive__scope.html", null ],
    [ "kcenon::monitoring::aggregation_processor", "classkcenon_1_1monitoring_1_1aggregation__processor.html", null ],
    [ "kcenon::monitoring::aggregation_result", "structkcenon_1_1monitoring_1_1aggregation__result.html", null ],
    [ "kcenon::monitoring::aggregation_rule", "structkcenon_1_1monitoring_1_1aggregation__rule.html", null ],
    [ "kcenon::monitoring::aggregation_processor::aggregator_entry", "structkcenon_1_1monitoring_1_1aggregation__processor_1_1aggregator__entry.html", null ],
    [ "kcenon::monitoring::alert", "structkcenon_1_1monitoring_1_1alert.html", null ],
    [ "kcenon::monitoring::resource_threshold_monitor::alert", "structkcenon_1_1monitoring_1_1resource__threshold__monitor_1_1alert.html", null ],
    [ "kcenon::monitoring::alert_aggregator", "classkcenon_1_1monitoring_1_1alert__aggregator.html", null ],
    [ "kcenon::monitoring::alert_aggregator_config", "structkcenon_1_1monitoring_1_1alert__aggregator__config.html", null ],
    [ "kcenon::monitoring::alert_annotations", "structkcenon_1_1monitoring_1_1alert__annotations.html", null ],
    [ "kcenon::monitoring::alert_deduplicator", "classkcenon_1_1monitoring_1_1alert__deduplicator.html", null ],
    [ "kcenon::monitoring::alert_formatter", "classkcenon_1_1monitoring_1_1alert__formatter.html", [
      [ "kcenon::monitoring::json_alert_formatter", "classkcenon_1_1monitoring_1_1json__alert__formatter.html", null ],
      [ "kcenon::monitoring::text_alert_formatter", "classkcenon_1_1monitoring_1_1text__alert__formatter.html", null ]
    ] ],
    [ "kcenon::monitoring::alert_group", "structkcenon_1_1monitoring_1_1alert__group.html", null ],
    [ "kcenon::monitoring::alert_inhibitor", "classkcenon_1_1monitoring_1_1alert__inhibitor.html", null ],
    [ "kcenon::monitoring::alert_labels", "structkcenon_1_1monitoring_1_1alert__labels.html", null ],
    [ "kcenon::monitoring::alert_manager", "classkcenon_1_1monitoring_1_1alert__manager.html", null ],
    [ "kcenon::monitoring::alert_manager_config", "structkcenon_1_1monitoring_1_1alert__manager__config.html", null ],
    [ "kcenon::monitoring::alert_manager_metrics", "structkcenon_1_1monitoring_1_1alert__manager__metrics.html", null ],
    [ "kcenon::monitoring::alert_notifier", "classkcenon_1_1monitoring_1_1alert__notifier.html", [
      [ "kcenon::monitoring::buffered_notifier", "classkcenon_1_1monitoring_1_1buffered__notifier.html", null ],
      [ "kcenon::monitoring::callback_notifier", "classkcenon_1_1monitoring_1_1callback__notifier.html", null ],
      [ "kcenon::monitoring::console_color_notifier", "classkcenon_1_1monitoring_1_1console__color__notifier.html", null ],
      [ "kcenon::monitoring::file_notifier", "classkcenon_1_1monitoring_1_1file__notifier.html", null ],
      [ "kcenon::monitoring::log_notifier", "classkcenon_1_1monitoring_1_1log__notifier.html", null ],
      [ "kcenon::monitoring::multi_notifier", "classkcenon_1_1monitoring_1_1multi__notifier.html", null ],
      [ "kcenon::monitoring::routing_notifier", "classkcenon_1_1monitoring_1_1routing__notifier.html", null ],
      [ "kcenon::monitoring::statistics_notifier", "classkcenon_1_1monitoring_1_1statistics__notifier.html", null ],
      [ "kcenon::monitoring::webhook_notifier", "classkcenon_1_1monitoring_1_1webhook__notifier.html", null ]
    ] ],
    [ "kcenon::monitoring::alert_pipeline", "classkcenon_1_1monitoring_1_1alert__pipeline.html", null ],
    [ "kcenon::monitoring::alert_rule", "classkcenon_1_1monitoring_1_1alert__rule.html", null ],
    [ "kcenon::monitoring::alert_rule_config", "structkcenon_1_1monitoring_1_1alert__rule__config.html", null ],
    [ "kcenon::monitoring::alert_rule_group", "classkcenon_1_1monitoring_1_1alert__rule__group.html", null ],
    [ "kcenon::monitoring::alert_silence", "structkcenon_1_1monitoring_1_1alert__silence.html", null ],
    [ "kcenon::monitoring::alert_template", "classkcenon_1_1monitoring_1_1alert__template.html", null ],
    [ "kcenon::monitoring::alert_trigger", "classkcenon_1_1monitoring_1_1alert__trigger.html", [
      [ "kcenon::monitoring::absent_trigger", "classkcenon_1_1monitoring_1_1absent__trigger.html", null ],
      [ "kcenon::monitoring::anomaly_trigger", "classkcenon_1_1monitoring_1_1anomaly__trigger.html", null ],
      [ "kcenon::monitoring::composite_trigger", "classkcenon_1_1monitoring_1_1composite__trigger.html", null ],
      [ "kcenon::monitoring::delta_trigger", "classkcenon_1_1monitoring_1_1delta__trigger.html", null ],
      [ "kcenon::monitoring::range_trigger", "classkcenon_1_1monitoring_1_1range__trigger.html", null ],
      [ "kcenon::monitoring::rate_of_change_trigger", "classkcenon_1_1monitoring_1_1rate__of__change__trigger.html", null ],
      [ "kcenon::monitoring::threshold_trigger", "classkcenon_1_1monitoring_1_1threshold__trigger.html", null ],
      [ "moving_average_trigger", "classmoving__average__trigger.html", null ],
      [ "periodic_trigger", "classperiodic__trigger.html", null ]
    ] ],
    [ "ApiGatewayService", "classApiGatewayService.html", null ],
    [ "AuthService", "classAuthService.html", null ],
    [ "kcenon::monitoring::battery_info", "structkcenon_1_1monitoring_1_1battery__info.html", null ],
    [ "kcenon::monitoring::battery_info_collector", "classkcenon_1_1monitoring_1_1battery__info__collector.html", null ],
    [ "kcenon::monitoring::battery_reading", "structkcenon_1_1monitoring_1_1battery__reading.html", null ],
    [ "kcenon::monitoring::plugin_metric_collector::cached_metric", "structkcenon_1_1monitoring_1_1plugin__metric__collector_1_1cached__metric.html", null ],
    [ "CacheService", "classCacheService.html", null ],
    [ "kcenon::monitoring::central_collector", "classkcenon_1_1monitoring_1_1central__collector.html", null ],
    [ "kcenon::monitoring::circuit_breaker_registry", "classkcenon_1_1monitoring_1_1circuit__breaker__registry.html", null ],
    [ "kcenon::monitoring::collection_config", "structkcenon_1_1monitoring_1_1collection__config.html", null ],
    [ "kcenon::monitoring::thread_to_monitoring_adapter::collection_config", "structkcenon_1_1monitoring_1_1thread__to__monitoring__adapter_1_1collection__config.html", null ],
    [ "kcenon::monitoring::collector_base< Derived >", "classkcenon_1_1monitoring_1_1collector__base.html", null ],
    [ "kcenon::monitoring::collector_interface", "classkcenon_1_1monitoring_1_1collector__interface.html", [
      [ "kcenon::monitoring::crtp_collector_adapter< T >", "classkcenon_1_1monitoring_1_1crtp__collector__adapter.html", null ],
      [ "kcenon::monitoring::plugin_collector_adapter< T >", "classkcenon_1_1monitoring_1_1plugin__collector__adapter.html", null ],
      [ "kcenon::monitoring::standalone_collector_adapter< T >", "classkcenon_1_1monitoring_1_1standalone__collector__adapter.html", null ]
    ] ],
    [ "kcenon::monitoring::collector_plugin", "classkcenon_1_1monitoring_1_1collector__plugin.html", [
      [ "example_plugin", "classexample__plugin.html", null ],
      [ "kcenon::monitoring::battery_collector", "classkcenon_1_1monitoring_1_1battery__collector.html", null ],
      [ "kcenon::monitoring::container_collector", "classkcenon_1_1monitoring_1_1container__collector.html", null ],
      [ "kcenon::monitoring::gpu_collector", "classkcenon_1_1monitoring_1_1gpu__collector.html", null ],
      [ "kcenon::monitoring::interrupt_collector", "classkcenon_1_1monitoring_1_1interrupt__collector.html", null ],
      [ "kcenon::monitoring::network_metrics_collector", "classkcenon_1_1monitoring_1_1network__metrics__collector.html", null ],
      [ "kcenon::monitoring::platform_metrics_collector", "classkcenon_1_1monitoring_1_1platform__metrics__collector.html", null ],
      [ "kcenon::monitoring::power_collector", "classkcenon_1_1monitoring_1_1power__collector.html", null ],
      [ "kcenon::monitoring::process_metrics_collector", "classkcenon_1_1monitoring_1_1process__metrics__collector.html", null ],
      [ "kcenon::monitoring::security_collector", "classkcenon_1_1monitoring_1_1security__collector.html", null ],
      [ "kcenon::monitoring::smart_collector", "classkcenon_1_1monitoring_1_1smart__collector.html", null ],
      [ "kcenon::monitoring::temperature_collector", "classkcenon_1_1monitoring_1_1temperature__collector.html", null ],
      [ "kcenon::monitoring::uptime_collector", "classkcenon_1_1monitoring_1_1uptime__collector.html", null ],
      [ "kcenon::monitoring::vm_collector", "classkcenon_1_1monitoring_1_1vm__collector.html", null ]
    ] ],
    [ "kcenon::monitoring::collector_registry", "classkcenon_1_1monitoring_1_1collector__registry.html", null ],
    [ "kcenon::monitoring::compact_metric_value", "structkcenon_1_1monitoring_1_1compact__metric__value.html", null ],
    [ "kcenon::monitoring::opentelemetry_compatibility_layer::compatibility_stats", "structkcenon_1_1monitoring_1_1opentelemetry__compatibility__layer_1_1compatibility__stats.html", null ],
    [ "kcenon::monitoring::config_parser", "classkcenon_1_1monitoring_1_1config__parser.html", null ],
    [ "kcenon::monitoring::container_info", "structkcenon_1_1monitoring_1_1container__info.html", null ],
    [ "kcenon::monitoring::container_info_collector", "classkcenon_1_1monitoring_1_1container__info__collector.html", null ],
    [ "kcenon::monitoring::container_metrics", "structkcenon_1_1monitoring_1_1container__metrics.html", null ],
    [ "kcenon::monitoring::plugins::container_plugin_config", "structkcenon_1_1monitoring_1_1plugins_1_1container__plugin__config.html", null ],
    [ "kcenon::monitoring::context_metadata", "structkcenon_1_1monitoring_1_1context__metadata.html", null ],
    [ "kcenon::monitoring::platform::context_switch_info", "structkcenon_1_1monitoring_1_1platform_1_1context__switch__info.html", null ],
    [ "kcenon::monitoring::context_switch_info_collector", "classkcenon_1_1monitoring_1_1context__switch__info__collector.html", null ],
    [ "kcenon::monitoring::context_switch_metrics", "structkcenon_1_1monitoring_1_1context__switch__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::context_switch_metrics", "structkcenon_1_1monitoring_1_1system__resources_1_1context__switch__metrics.html", null ],
    [ "kcenon::monitoring::cooldown_tracker", "classkcenon_1_1monitoring_1_1cooldown__tracker.html", null ],
    [ "kcenon::monitoring::cpu_interrupt_info", "structkcenon_1_1monitoring_1_1cpu__interrupt__info.html", null ],
    [ "kcenon::monitoring::system_resources::cpu_metrics", "structkcenon_1_1monitoring_1_1system__resources_1_1cpu__metrics.html", null ],
    [ "kcenon::monitoring::container_info_collector::cpu_stats", "structkcenon_1_1monitoring_1_1container__info__collector_1_1cpu__stats.html", null ],
    [ "kcenon::monitoring::system_info_collector::cpu_stats", "structkcenon_1_1monitoring_1_1system__info__collector_1_1cpu__stats.html", null ],
    [ "kcenon::monitoring::cpu_throttle_config", "structkcenon_1_1monitoring_1_1cpu__throttle__config.html", null ],
    [ "kcenon::monitoring::cpu_throttler", "classkcenon_1_1monitoring_1_1cpu__throttler.html", null ],
    [ "kcenon::monitoring::create_result", "structkcenon_1_1monitoring_1_1create__result.html", null ],
    [ "kcenon::monitoring::data_consistency_manager", "classkcenon_1_1monitoring_1_1data__consistency__manager.html", null ],
    [ "DatabaseConnection", "classDatabaseConnection.html", null ],
    [ "kcenon::monitoring::safe_event_dispatcher::dead_letter_entry", "structkcenon_1_1monitoring_1_1safe__event__dispatcher_1_1dead__letter__entry.html", null ],
    [ "kcenon::monitoring::degradable_service< T >", "classkcenon_1_1monitoring_1_1degradable__service.html", null ],
    [ "kcenon::monitoring::degradation_plan", "structkcenon_1_1monitoring_1_1degradation__plan.html", null ],
    [ "kcenon::monitoring::disk_info", "structkcenon_1_1monitoring_1_1disk__info.html", null ],
    [ "kcenon::monitoring::system_resources::disk_metrics", "structkcenon_1_1monitoring_1_1system__resources_1_1disk__metrics.html", null ],
    [ "kcenon::monitoring::system_info_collector::disk_stats", "structkcenon_1_1monitoring_1_1system__info__collector_1_1disk__stats.html", null ],
    [ "kcenon::monitoring::distributed_tracer", "classkcenon_1_1monitoring_1_1distributed__tracer.html", null ],
    [ "kcenon::monitoring::moving_window_aggregator< T >::entry", "structkcenon_1_1monitoring_1_1moving__window__aggregator_1_1entry.html", null ],
    [ "kcenon::monitoring::error_boundary< T >", "classkcenon_1_1monitoring_1_1error__boundary.html", null ],
    [ "kcenon::monitoring::error_boundary_config", "structkcenon_1_1monitoring_1_1error__boundary__config.html", null ],
    [ "kcenon::monitoring::error_boundary_metrics", "structkcenon_1_1monitoring_1_1error__boundary__metrics.html", null ],
    [ "kcenon::monitoring::error_boundary_registry", "classkcenon_1_1monitoring_1_1error__boundary__registry.html", null ],
    [ "kcenon::monitoring::error_info", "structkcenon_1_1monitoring_1_1error__info.html", null ],
    [ "kcenon::monitoring::event_base", "classkcenon_1_1monitoring_1_1event__base.html", [
      [ "kcenon::monitoring::component_lifecycle_event", "classkcenon_1_1monitoring_1_1component__lifecycle__event.html", null ],
      [ "kcenon::monitoring::configuration_change_event", "classkcenon_1_1monitoring_1_1configuration__change__event.html", null ],
      [ "kcenon::monitoring::health_check_event", "classkcenon_1_1monitoring_1_1health__check__event.html", null ],
      [ "kcenon::monitoring::logging_metric_event", "classkcenon_1_1monitoring_1_1logging__metric__event.html", null ],
      [ "kcenon::monitoring::metric_collection_event", "classkcenon_1_1monitoring_1_1metric__collection__event.html", null ],
      [ "kcenon::monitoring::performance_alert_event", "classkcenon_1_1monitoring_1_1performance__alert__event.html", null ],
      [ "kcenon::monitoring::system_resource_event", "classkcenon_1_1monitoring_1_1system__resource__event.html", null ],
      [ "kcenon::monitoring::thread_pool_metric_event", "classkcenon_1_1monitoring_1_1thread__pool__metric__event.html", null ]
    ] ],
    [ "kcenon::monitoring::event_bus_config", "structkcenon_1_1monitoring_1_1event__bus__config.html", null ],
    [ "kcenon::monitoring::event_envelope", "structkcenon_1_1monitoring_1_1event__envelope.html", null ],
    [ "kcenon::monitoring::event_handler< EventType >", "classkcenon_1_1monitoring_1_1event__handler.html", null ],
    [ "kcenon::monitoring::event_handler_wrapper", "structkcenon_1_1monitoring_1_1event__handler__wrapper.html", null ],
    [ "event_priority", "classevent__priority.html", null ],
    [ "ExternalApiClient", "classExternalApiClient.html", null ],
    [ "kcenon::monitoring::fallback_strategy_interface< T >", "classkcenon_1_1monitoring_1_1fallback__strategy__interface.html", [
      [ "kcenon::monitoring::alternative_service_strategy< T >", "classkcenon_1_1monitoring_1_1alternative__service__strategy.html", null ],
      [ "kcenon::monitoring::cached_value_strategy< T >", "classkcenon_1_1monitoring_1_1cached__value__strategy.html", null ],
      [ "kcenon::monitoring::default_value_strategy< T >", "classkcenon_1_1monitoring_1_1default__value__strategy.html", null ]
    ] ],
    [ "std::false_type", null, [
      [ "kcenon::monitoring::stats::detail::is_chrono_duration< T >", "structkcenon_1_1monitoring_1_1stats_1_1detail_1_1is__chrono__duration.html", null ]
    ] ],
    [ "kcenon::monitoring::fault_tolerance_config", "structkcenon_1_1monitoring_1_1fault__tolerance__config.html", null ],
    [ "kcenon::monitoring::fault_tolerance_manager< T >", "classkcenon_1_1monitoring_1_1fault__tolerance__manager.html", null ],
    [ "kcenon::monitoring::fault_tolerance_metrics", "structkcenon_1_1monitoring_1_1fault__tolerance__metrics.html", null ],
    [ "kcenon::monitoring::fault_tolerance_registry", "classkcenon_1_1monitoring_1_1fault__tolerance__registry.html", null ],
    [ "kcenon::monitoring::platform::fd_info", "structkcenon_1_1monitoring_1_1platform_1_1fd__info.html", null ],
    [ "kcenon::monitoring::fd_info_collector", "classkcenon_1_1monitoring_1_1fd__info__collector.html", null ],
    [ "kcenon::monitoring::fd_metrics", "structkcenon_1_1monitoring_1_1fd__metrics.html", null ],
    [ "kcenon::monitoring::filesystem_inode_info", "structkcenon_1_1monitoring_1_1filesystem__inode__info.html", null ],
    [ "kcenon::monitoring::gpu_device_info", "structkcenon_1_1monitoring_1_1gpu__device__info.html", null ],
    [ "kcenon::monitoring::platform::gpu_info", "structkcenon_1_1monitoring_1_1platform_1_1gpu__info.html", null ],
    [ "kcenon::monitoring::gpu_info_collector", "classkcenon_1_1monitoring_1_1gpu__info__collector.html", null ],
    [ "kcenon::monitoring::gpu_reading", "structkcenon_1_1monitoring_1_1gpu__reading.html", null ],
    [ "kcenon::monitoring::graceful_degradation_manager", "classkcenon_1_1monitoring_1_1graceful__degradation__manager.html", null ],
    [ "kcenon::monitoring::graceful_degradation_metrics", "structkcenon_1_1monitoring_1_1graceful__degradation__metrics.html", null ],
    [ "kcenon::monitoring::grpc_request", "structkcenon_1_1monitoring_1_1grpc__request.html", null ],
    [ "kcenon::monitoring::grpc_response", "structkcenon_1_1monitoring_1_1grpc__response.html", null ],
    [ "kcenon::monitoring::grpc_statistics", "structkcenon_1_1monitoring_1_1grpc__statistics.html", null ],
    [ "kcenon::monitoring::grpc_transport", "classkcenon_1_1monitoring_1_1grpc__transport.html", [
      [ "kcenon::monitoring::stub_grpc_transport", "classkcenon_1_1monitoring_1_1stub__grpc__transport.html", null ]
    ] ],
    [ "kcenon::monitoring::handler_error_info", "structkcenon_1_1monitoring_1_1handler__error__info.html", null ],
    [ "kcenon::monitoring::plugins::hardware_plugin_config", "structkcenon_1_1monitoring_1_1plugins_1_1hardware__plugin__config.html", null ],
    [ "kcenon::monitoring::health_check", "classkcenon_1_1monitoring_1_1health__check.html", [
      [ "database_health_check", "classdatabase__health__check.html", null ],
      [ "external_api_health_check", "classexternal__api__health__check.html", null ],
      [ "kcenon::monitoring::composite_health_check", "classkcenon_1_1monitoring_1_1composite__health__check.html", null ],
      [ "kcenon::monitoring::functional_health_check", "classkcenon_1_1monitoring_1_1functional__health__check.html", null ],
      [ "test_health_check", "classtest__health__check.html", null ]
    ] ],
    [ "kcenon::monitoring::health_check_builder", "classkcenon_1_1monitoring_1_1health__check__builder.html", null ],
    [ "kcenon::monitoring::health_check_event::health_check_result", "structkcenon_1_1monitoring_1_1health__check__event_1_1health__check__result.html", null ],
    [ "kcenon::monitoring::health_check_result", "structkcenon_1_1monitoring_1_1health__check__result.html", null ],
    [ "kcenon::monitoring::health_dependency_graph", "classkcenon_1_1monitoring_1_1health__dependency__graph.html", null ],
    [ "kcenon::monitoring::health_monitor", "classkcenon_1_1monitoring_1_1health__monitor.html", null ],
    [ "kcenon::monitoring::health_monitor_config", "structkcenon_1_1monitoring_1_1health__monitor__config.html", null ],
    [ "kcenon::monitoring::health_monitor_stats", "structkcenon_1_1monitoring_1_1health__monitor__stats.html", null ],
    [ "kcenon::monitoring::histogram_bucket", "structkcenon_1_1monitoring_1_1histogram__bucket.html", null ],
    [ "kcenon::monitoring::histogram_data", "structkcenon_1_1monitoring_1_1histogram__data.html", null ],
    [ "kcenon::monitoring::http_request", "structkcenon_1_1monitoring_1_1http__request.html", null ],
    [ "kcenon::monitoring::http_response", "structkcenon_1_1monitoring_1_1http__response.html", null ],
    [ "kcenon::monitoring::http_transport", "classkcenon_1_1monitoring_1_1http__transport.html", [
      [ "kcenon::monitoring::simple_http_client", "classkcenon_1_1monitoring_1_1simple__http__client.html", null ],
      [ "kcenon::monitoring::stub_http_transport", "classkcenon_1_1monitoring_1_1stub__http__transport.html", null ]
    ] ],
    [ "ILogger", null, [
      [ "console_logger", "classconsole__logger.html", null ],
      [ "example_logger", "classexample__logger.html", null ],
      [ "mock_logger", "classmock__logger.html", null ],
      [ "simple_console_logger", "classsimple__console__logger.html", null ]
    ] ],
    [ "kcenon::common::interfaces::ILogger", null, [
      [ "simple_mock_logger", "classsimple__mock__logger.html", null ]
    ] ],
    [ "common::interfaces::IMonitor", null, [
      [ "kcenon::monitoring::performance_monitor_adapter", "classkcenon_1_1monitoring_1_1performance__monitor__adapter.html", null ]
    ] ],
    [ "IMonitor", null, [
      [ "aggregating_monitor", "classaggregating__monitor.html", null ]
    ] ],
    [ "kcenon::common::interfaces::IMonitor", null, [
      [ "mock_monitor", "classmock__monitor.html", null ]
    ] ],
    [ "imonitor_interface", "classimonitor__interface.html", [
      [ "imonitor_adapter", "classimonitor__adapter.html", null ],
      [ "performance_monitor_old", "classperformance__monitor__old.html", null ]
    ] ],
    [ "IMonitorable", null, [
      [ "console_logger", "classconsole__logger.html", null ]
    ] ],
    [ "kcenon::common::interfaces::IMonitorable", null, [
      [ "simple_mock_logger", "classsimple__mock__logger.html", null ]
    ] ],
    [ "IMonitorProvider", null, [
      [ "monitor_factory", "classmonitor__factory.html", null ]
    ] ],
    [ "kcenon::monitoring::inhibition_rule", "structkcenon_1_1monitoring_1_1inhibition__rule.html", null ],
    [ "kcenon::monitoring::platform::inode_info", "structkcenon_1_1monitoring_1_1platform_1_1inode__info.html", null ],
    [ "kcenon::monitoring::inode_info_collector", "classkcenon_1_1monitoring_1_1inode__info__collector.html", null ],
    [ "kcenon::monitoring::inode_metrics", "structkcenon_1_1monitoring_1_1inode__metrics.html", null ],
    [ "kcenon::monitoring::interface_event_bus", "classkcenon_1_1monitoring_1_1interface__event__bus.html", [
      [ "kcenon::monitoring::event_bus", "classkcenon_1_1monitoring_1_1event__bus.html", null ]
    ] ],
    [ "kcenon::monitoring::interface_event_publisher", "classkcenon_1_1monitoring_1_1interface__event__publisher.html", null ],
    [ "kcenon::monitoring::interface_event_subscriber", "classkcenon_1_1monitoring_1_1interface__event__subscriber.html", null ],
    [ "kcenon::monitoring::interface_metric_source", "classkcenon_1_1monitoring_1_1interface__metric__source.html", null ],
    [ "kcenon::monitoring::interface_monitoring_observer", "classkcenon_1_1monitoring_1_1interface__monitoring__observer.html", [
      [ "test_observer", "classtest__observer.html", null ]
    ] ],
    [ "kcenon::monitoring::interface_observable", "classkcenon_1_1monitoring_1_1interface__observable.html", [
      [ "kcenon::monitoring::interface_metric_collector", "classkcenon_1_1monitoring_1_1interface__metric__collector.html", [
        [ "kcenon::monitoring::interface_aggregated_collector", "classkcenon_1_1monitoring_1_1interface__aggregated__collector.html", null ],
        [ "kcenon::monitoring::plugin_metric_collector", "classkcenon_1_1monitoring_1_1plugin__metric__collector.html", null ],
        [ "test_collector", "classtest__collector.html", null ]
      ] ]
    ] ],
    [ "kcenon::monitoring::platform::interrupt_info", "structkcenon_1_1monitoring_1_1platform_1_1interrupt__info.html", null ],
    [ "kcenon::monitoring::interrupt_info_collector", "classkcenon_1_1monitoring_1_1interrupt__info__collector.html", null ],
    [ "kcenon::monitoring::interrupt_metrics", "structkcenon_1_1monitoring_1_1interrupt__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::disk_metrics::io_throughput", "structkcenon_1_1monitoring_1_1system__resources_1_1disk__metrics_1_1io__throughput.html", null ],
    [ "IService", "classIService.html", [
      [ "ServiceA", "classServiceA.html", null ],
      [ "ServiceB", "classServiceB.html", null ]
    ] ],
    [ "kcenon::monitoring::jaeger_span_data", "structkcenon_1_1monitoring_1_1jaeger__span__data.html", null ],
    [ "kcenon::monitoring::kv_storage_backend", "classkcenon_1_1monitoring_1_1kv__storage__backend.html", [
      [ "kcenon::monitoring::kv_memory_storage_backend", "classkcenon_1_1monitoring_1_1kv__memory__storage__backend.html", null ]
    ] ],
    [ "library_handle", "structlibrary__handle.html", null ],
    [ "kcenon::monitoring::system_resources::cpu_metrics::load_average", "structkcenon_1_1monitoring_1_1system__resources_1_1cpu__metrics_1_1load__average.html", null ],
    [ "kcenon::monitoring::load_average_history", "classkcenon_1_1monitoring_1_1load__average__history.html", null ],
    [ "kcenon::monitoring::load_average_sample", "structkcenon_1_1monitoring_1_1load__average__sample.html", null ],
    [ "kcenon::monitoring::load_average_statistics", "structkcenon_1_1monitoring_1_1load__average__statistics.html", null ],
    [ "kcenon::monitoring::lockfree_queue< T >", "classkcenon_1_1monitoring_1_1lockfree__queue.html", null ],
    [ "kcenon::monitoring::lockfree_queue_config", "structkcenon_1_1monitoring_1_1lockfree__queue__config.html", null ],
    [ "kcenon::monitoring::lockfree_queue_statistics", "structkcenon_1_1monitoring_1_1lockfree__queue__statistics.html", null ],
    [ "kcenon::monitoring::logger_to_monitoring_adapter", "classkcenon_1_1monitoring_1_1logger__to__monitoring__adapter.html", null ],
    [ "kcenon::monitoring::logging_metric_event::logging_stats", "structkcenon_1_1monitoring_1_1logging__metric__event_1_1logging__stats.html", null ],
    [ "kcenon::monitoring::system_resources::memory_metrics", "structkcenon_1_1monitoring_1_1system__resources_1_1memory__metrics.html", null ],
    [ "kcenon::monitoring::memory_pool", "classkcenon_1_1monitoring_1_1memory__pool.html", null ],
    [ "kcenon::monitoring::memory_pool_config", "structkcenon_1_1monitoring_1_1memory__pool__config.html", null ],
    [ "kcenon::monitoring::memory_pool_statistics", "structkcenon_1_1monitoring_1_1memory__pool__statistics.html", null ],
    [ "kcenon::monitoring::memory_quota_manager", "classkcenon_1_1monitoring_1_1memory__quota__manager.html", null ],
    [ "kcenon::monitoring::metric", "structkcenon_1_1monitoring_1_1metric.html", null ],
    [ "kcenon::monitoring::metric_batch", "structkcenon_1_1monitoring_1_1metric__batch.html", null ],
    [ "kcenon::monitoring::metric_collector_plugin", "classkcenon_1_1monitoring_1_1metric__collector__plugin.html", [
      [ "kcenon::monitoring::plugins::container_plugin", "classkcenon_1_1monitoring_1_1plugins_1_1container__plugin.html", null ],
      [ "kcenon::monitoring::plugins::hardware_plugin", "classkcenon_1_1monitoring_1_1plugins_1_1hardware__plugin.html", null ],
      [ "kcenon::monitoring::system_resource_collector", "classkcenon_1_1monitoring_1_1system__resource__collector.html", null ]
    ] ],
    [ "kcenon::monitoring::performance_monitor::metric_data", "structkcenon_1_1monitoring_1_1performance__monitor_1_1metric__data.html", null ],
    [ "kcenon::monitoring::metric_event", "classkcenon_1_1monitoring_1_1metric__event.html", null ],
    [ "kcenon::monitoring::metric_export_config", "structkcenon_1_1monitoring_1_1metric__export__config.html", null ],
    [ "kcenon::monitoring::metric_exporter_factory", "classkcenon_1_1monitoring_1_1metric__exporter__factory.html", null ],
    [ "kcenon::monitoring::metric_exporter_interface", "classkcenon_1_1monitoring_1_1metric__exporter__interface.html", [
      [ "kcenon::monitoring::otlp_metrics_exporter", "classkcenon_1_1monitoring_1_1otlp__metrics__exporter.html", null ],
      [ "kcenon::monitoring::prometheus_exporter", "classkcenon_1_1monitoring_1_1prometheus__exporter.html", null ],
      [ "kcenon::monitoring::statsd_exporter", "classkcenon_1_1monitoring_1_1statsd__exporter.html", null ]
    ] ],
    [ "kcenon::monitoring::metric_factory", "classkcenon_1_1monitoring_1_1metric__factory.html", null ],
    [ "kcenon::monitoring::metric_filter", "classkcenon_1_1monitoring_1_1metric__filter.html", null ],
    [ "kcenon::monitoring::metric_metadata", "structkcenon_1_1monitoring_1_1metric__metadata.html", null ],
    [ "kcenon::monitoring::metric_sample", "structkcenon_1_1monitoring_1_1metric__sample.html", null ],
    [ "kcenon::monitoring::metric_stats", "structkcenon_1_1monitoring_1_1metric__stats.html", null ],
    [ "kcenon::monitoring::metric_storage", "classkcenon_1_1monitoring_1_1metric__storage.html", null ],
    [ "kcenon::monitoring::metric_storage_config", "structkcenon_1_1monitoring_1_1metric__storage__config.html", null ],
    [ "kcenon::monitoring::metric_storage_stats", "structkcenon_1_1monitoring_1_1metric__storage__stats.html", null ],
    [ "kcenon::monitoring::metric_value", "structkcenon_1_1monitoring_1_1metric__value.html", null ],
    [ "kcenon::monitoring::metrics_analyzer", "classkcenon_1_1monitoring_1_1metrics__analyzer.html", null ],
    [ "kcenon::monitoring::metrics_collector", "classkcenon_1_1monitoring_1_1metrics__collector.html", [
      [ "kcenon::monitoring::performance_monitor", "classkcenon_1_1monitoring_1_1performance__monitor.html", null ],
      [ "mock_collector", "classmock__collector.html", null ]
    ] ],
    [ "metrics_collector_interface", "classmetrics__collector__interface.html", [
      [ "metrics_collector_adapter", "classmetrics__collector__adapter.html", null ],
      [ "performance_monitor_old", "classperformance__monitor__old.html", null ]
    ] ],
    [ "kcenon::monitoring::platform::metrics_provider", "classkcenon_1_1monitoring_1_1platform_1_1metrics__provider.html", null ],
    [ "kcenon::monitoring::metrics_snapshot", "structkcenon_1_1monitoring_1_1metrics__snapshot.html", null ],
    [ "kcenon::monitoring::monitorable_interface", "classkcenon_1_1monitoring_1_1monitorable__interface.html", [
      [ "kcenon::monitoring::monitorable_component", "classkcenon_1_1monitoring_1_1monitorable__component.html", [
        [ "test_monitorable_component", "classtest__monitorable__component.html", null ]
      ] ]
    ] ],
    [ "kcenon::monitoring::monitoring_aggregator", "classkcenon_1_1monitoring_1_1monitoring__aggregator.html", null ],
    [ "kcenon::monitoring::monitoring_config", "structkcenon_1_1monitoring_1_1monitoring__config.html", null ],
    [ "kcenon::monitoring::monitoring_data", "structkcenon_1_1monitoring_1_1monitoring__data.html", null ],
    [ "kcenon::monitoring::monitoring_interface", "classkcenon_1_1monitoring_1_1monitoring__interface.html", null ],
    [ "kcenon::monitoring::moving_window_aggregator< T >", "classkcenon_1_1monitoring_1_1moving__window__aggregator.html", null ],
    [ "kcenon::monitoring::network_info_collector", "classkcenon_1_1monitoring_1_1network__info__collector.html", null ],
    [ "kcenon::monitoring::network_metrics", "structkcenon_1_1monitoring_1_1network__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::network_metrics", "structkcenon_1_1monitoring_1_1system__resources_1_1network__metrics.html", null ],
    [ "kcenon::monitoring::network_metrics_config", "structkcenon_1_1monitoring_1_1network__metrics__config.html", null ],
    [ "kcenon::monitoring::system_info_collector::network_stats", "structkcenon_1_1monitoring_1_1system__info__collector_1_1network__stats.html", null ],
    [ "kcenon::monitoring::online_statistics", "classkcenon_1_1monitoring_1_1online__statistics.html", null ],
    [ "kcenon::monitoring::opentelemetry_compatibility_layer", "classkcenon_1_1monitoring_1_1opentelemetry__compatibility__layer.html", null ],
    [ "kcenon::monitoring::opentelemetry_exporter_config", "structkcenon_1_1monitoring_1_1opentelemetry__exporter__config.html", null ],
    [ "kcenon::monitoring::opentelemetry_metrics_adapter", "classkcenon_1_1monitoring_1_1opentelemetry__metrics__adapter.html", null ],
    [ "kcenon::monitoring::opentelemetry_tracer_adapter", "classkcenon_1_1monitoring_1_1opentelemetry__tracer__adapter.html", null ],
    [ "kcenon::monitoring::otel_attribute", "structkcenon_1_1monitoring_1_1otel__attribute.html", null ],
    [ "kcenon::monitoring::otel_metric_data", "structkcenon_1_1monitoring_1_1otel__metric__data.html", null ],
    [ "kcenon::monitoring::otel_resource", "structkcenon_1_1monitoring_1_1otel__resource.html", null ],
    [ "kcenon::monitoring::otel_span_context", "structkcenon_1_1monitoring_1_1otel__span__context.html", null ],
    [ "kcenon::monitoring::otel_span_data", "structkcenon_1_1monitoring_1_1otel__span__data.html", null ],
    [ "kcenon::monitoring::otlp_exporter_stats", "structkcenon_1_1monitoring_1_1otlp__exporter__stats.html", null ],
    [ "kcenon::monitoring::otlp_grpc_config", "structkcenon_1_1monitoring_1_1otlp__grpc__config.html", null ],
    [ "kcenon::monitoring::otlp_span_converter", "classkcenon_1_1monitoring_1_1otlp__span__converter.html", null ],
    [ "kcenon::monitoring::performance_benchmark", "classkcenon_1_1monitoring_1_1performance__benchmark.html", null ],
    [ "kcenon::monitoring::performance_metrics", "structkcenon_1_1monitoring_1_1performance__metrics.html", null ],
    [ "kcenon::monitoring::adapters::performance_monitor_adapter", "classkcenon_1_1monitoring_1_1adapters_1_1performance__monitor__adapter.html", null ],
    [ "performance_monitor_facade", "classperformance__monitor__facade.html", null ],
    [ "performance_monitor_impl", "classperformance__monitor__impl.html", null ],
    [ "kcenon::monitoring::performance_profile", "structkcenon_1_1monitoring_1_1performance__profile.html", null ],
    [ "kcenon::monitoring::performance_profiler", "classkcenon_1_1monitoring_1_1performance__profiler.html", null ],
    [ "kcenon::monitoring::pipeline_stage", "classkcenon_1_1monitoring_1_1pipeline__stage.html", null ],
    [ "kcenon::monitoring::platform_context_switches", "structkcenon_1_1monitoring_1_1platform__context__switches.html", null ],
    [ "kcenon::monitoring::platform_info", "structkcenon_1_1monitoring_1_1platform__info.html", null ],
    [ "kcenon::monitoring::platform_info_collector", "classkcenon_1_1monitoring_1_1platform__info__collector.html", null ],
    [ "kcenon::monitoring::platform_interrupt_info", "structkcenon_1_1monitoring_1_1platform__interrupt__info.html", null ],
    [ "kcenon::monitoring::platform_metrics", "structkcenon_1_1monitoring_1_1platform__metrics.html", null ],
    [ "kcenon::monitoring::platform_metrics_config", "structkcenon_1_1monitoring_1_1platform__metrics__config.html", null ],
    [ "kcenon::monitoring::platform_socket_info", "structkcenon_1_1monitoring_1_1platform__socket__info.html", null ],
    [ "kcenon::monitoring::platform_tcp_info", "structkcenon_1_1monitoring_1_1platform__tcp__info.html", null ],
    [ "kcenon::monitoring::platform_uptime", "structkcenon_1_1monitoring_1_1platform__uptime.html", null ],
    [ "plugin_api_metadata", "structplugin__api__metadata.html", null ],
    [ "kcenon::monitoring::plugin_collector_config", "structkcenon_1_1monitoring_1_1plugin__collector__config.html", null ],
    [ "kcenon::monitoring::dynamic_plugin_loader::plugin_entry", "structkcenon_1_1monitoring_1_1dynamic__plugin__loader_1_1plugin__entry.html", null ],
    [ "kcenon::monitoring::plugin_factory", "classkcenon_1_1monitoring_1_1plugin__factory.html", null ],
    [ "kcenon::monitoring::plugin_loader", "classkcenon_1_1monitoring_1_1plugin__loader.html", [
      [ "kcenon::monitoring::dynamic_plugin_loader", "classkcenon_1_1monitoring_1_1dynamic__plugin__loader.html", null ]
    ] ],
    [ "kcenon::monitoring::plugin_metadata", "structkcenon_1_1monitoring_1_1plugin__metadata.html", null ],
    [ "kcenon::monitoring::platform::power_info", "structkcenon_1_1monitoring_1_1platform_1_1power__info.html", null ],
    [ "kcenon::monitoring::power_info_collector", "classkcenon_1_1monitoring_1_1power__info__collector.html", null ],
    [ "kcenon::monitoring::power_reading", "structkcenon_1_1monitoring_1_1power__reading.html", null ],
    [ "kcenon::monitoring::power_source_info", "structkcenon_1_1monitoring_1_1power__source__info.html", null ],
    [ "kcenon::monitoring::process_context_switch_info", "structkcenon_1_1monitoring_1_1process__context__switch__info.html", null ],
    [ "kcenon::monitoring::process_metrics", "structkcenon_1_1monitoring_1_1process__metrics.html", null ],
    [ "kcenon::monitoring::system_resources::process_metrics", "structkcenon_1_1monitoring_1_1system__resources_1_1process__metrics.html", null ],
    [ "kcenon::monitoring::process_metrics_config", "structkcenon_1_1monitoring_1_1process__metrics__config.html", null ],
    [ "kcenon::monitoring::central_collector::profile_data", "structkcenon_1_1monitoring_1_1central__collector_1_1profile__data.html", null ],
    [ "kcenon::monitoring::performance_profiler::profile_data", "structkcenon_1_1monitoring_1_1performance__profiler_1_1profile__data.html", null ],
    [ "kcenon::monitoring::prometheus_metric_data", "structkcenon_1_1monitoring_1_1prometheus__metric__data.html", null ],
    [ "kcenon::monitoring::quantile_estimator", "classkcenon_1_1monitoring_1_1quantile__estimator.html", null ],
    [ "kcenon::monitoring::rate_limit_config", "structkcenon_1_1monitoring_1_1rate__limit__config.html", null ],
    [ "kcenon::monitoring::rate_limiter", "classkcenon_1_1monitoring_1_1rate__limiter.html", [
      [ "kcenon::monitoring::leaky_bucket_limiter", "classkcenon_1_1monitoring_1_1leaky__bucket__limiter.html", null ],
      [ "kcenon::monitoring::token_bucket_limiter", "classkcenon_1_1monitoring_1_1token__bucket__limiter.html", null ]
    ] ],
    [ "kcenon::monitoring::resource_manager", "classkcenon_1_1monitoring_1_1resource__manager.html", null ],
    [ "kcenon::monitoring::resource_metrics", "structkcenon_1_1monitoring_1_1resource__metrics.html", null ],
    [ "kcenon::monitoring::resource_quota", "structkcenon_1_1monitoring_1_1resource__quota.html", null ],
    [ "kcenon::monitoring::system_resource_event::resource_stats", "structkcenon_1_1monitoring_1_1system__resource__event_1_1resource__stats.html", null ],
    [ "kcenon::monitoring::resource_threshold_monitor", "classkcenon_1_1monitoring_1_1resource__threshold__monitor.html", null ],
    [ "kcenon::monitoring::retry_config", "structkcenon_1_1monitoring_1_1retry__config.html", null ],
    [ "kcenon::monitoring::retry_executor< T >", "classkcenon_1_1monitoring_1_1retry__executor.html", null ],
    [ "kcenon::monitoring::retry_executor_registry", "classkcenon_1_1monitoring_1_1retry__executor__registry.html", null ],
    [ "kcenon::monitoring::retry_metrics", "structkcenon_1_1monitoring_1_1retry__metrics.html", null ],
    [ "kcenon::monitoring::retry_policy", "classkcenon_1_1monitoring_1_1retry__policy.html", null ],
    [ "kcenon::monitoring::ring_buffer< T >", "classkcenon_1_1monitoring_1_1ring__buffer.html", null ],
    [ "kcenon::monitoring::ring_buffer< kcenon::monitoring::compact_metric_value >", "classkcenon_1_1monitoring_1_1ring__buffer.html", null ],
    [ "kcenon::monitoring::ring_buffer_config", "structkcenon_1_1monitoring_1_1ring__buffer__config.html", null ],
    [ "kcenon::monitoring::ring_buffer_stats", "structkcenon_1_1monitoring_1_1ring__buffer__stats.html", null ],
    [ "kcenon::monitoring::routing_notifier::route", "structkcenon_1_1monitoring_1_1routing__notifier_1_1route.html", null ],
    [ "kcenon::monitoring::rule_builder", "classkcenon_1_1monitoring_1_1rule__builder.html", null ],
    [ "kcenon::monitoring::rule_definition", "structkcenon_1_1monitoring_1_1rule__definition.html", null ],
    [ "kcenon::monitoring::rule_registry", "classkcenon_1_1monitoring_1_1rule__registry.html", null ],
    [ "kcenon::monitoring::safe_event_dispatcher", "classkcenon_1_1monitoring_1_1safe__event__dispatcher.html", null ],
    [ "kcenon::monitoring::rate_of_change_trigger::sample", "structkcenon_1_1monitoring_1_1rate__of__change__trigger_1_1sample.html", null ],
    [ "kcenon::monitoring::scoped_span", "classkcenon_1_1monitoring_1_1scoped__span.html", null ],
    [ "kcenon::monitoring::scoped_timer", "classkcenon_1_1monitoring_1_1scoped__timer.html", null ],
    [ "kcenon::monitoring::security_event", "structkcenon_1_1monitoring_1_1security__event.html", null ],
    [ "kcenon::monitoring::security_event_counts", "structkcenon_1_1monitoring_1_1security__event__counts.html", null ],
    [ "kcenon::monitoring::platform::security_info", "structkcenon_1_1monitoring_1_1platform_1_1security__info.html", null ],
    [ "kcenon::monitoring::security_info_collector", "classkcenon_1_1monitoring_1_1security__info__collector.html", null ],
    [ "kcenon::monitoring::security_metrics", "structkcenon_1_1monitoring_1_1security__metrics.html", null ],
    [ "kcenon::monitoring::service_config", "structkcenon_1_1monitoring_1_1service__config.html", null ],
    [ "kcenon::monitoring::service_state", "structkcenon_1_1monitoring_1_1service__state.html", null ],
    [ "kcenon::monitoring::simd_aggregator", "classkcenon_1_1monitoring_1_1simd__aggregator.html", null ],
    [ "kcenon::monitoring::simd_aggregator_statistics", "structkcenon_1_1monitoring_1_1simd__aggregator__statistics.html", null ],
    [ "kcenon::monitoring::simd_capabilities", "structkcenon_1_1monitoring_1_1simd__capabilities.html", null ],
    [ "kcenon::monitoring::simd_config", "structkcenon_1_1monitoring_1_1simd__config.html", null ],
    [ "kcenon::monitoring::lockfree_queue< T >::slot", "structkcenon_1_1monitoring_1_1lockfree__queue_1_1slot.html", null ],
    [ "kcenon::monitoring::smart_disk_metrics", "structkcenon_1_1monitoring_1_1smart__disk__metrics.html", null ],
    [ "kcenon::monitoring::smart_info_collector", "classkcenon_1_1monitoring_1_1smart__info__collector.html", null ],
    [ "kcenon::monitoring::timer_data::snapshot", "structkcenon_1_1monitoring_1_1timer__data_1_1snapshot.html", null ],
    [ "kcenon::monitoring::snapshot_storage_backend", "classkcenon_1_1monitoring_1_1snapshot__storage__backend.html", [
      [ "kcenon::monitoring::cloud_storage_backend", "classkcenon_1_1monitoring_1_1cloud__storage__backend.html", null ],
      [ "kcenon::monitoring::database_storage_backend", "classkcenon_1_1monitoring_1_1database__storage__backend.html", null ],
      [ "kcenon::monitoring::file_storage_backend", "classkcenon_1_1monitoring_1_1file__storage__backend.html", null ],
      [ "kcenon::monitoring::memory_storage_backend", "classkcenon_1_1monitoring_1_1memory__storage__backend.html", null ]
    ] ],
    [ "kcenon::monitoring::platform::socket_buffer_info", "structkcenon_1_1monitoring_1_1platform_1_1socket__buffer__info.html", null ],
    [ "kcenon::monitoring::span_builder", "classkcenon_1_1monitoring_1_1span__builder.html", null ],
    [ "kcenon::monitoring::state_change_event", "classkcenon_1_1monitoring_1_1state__change__event.html", null ],
    [ "kcenon::monitoring::state_validator", "classkcenon_1_1monitoring_1_1state__validator.html", null ],
    [ "kcenon::monitoring::statistical_summary", "structkcenon_1_1monitoring_1_1statistical__summary.html", null ],
    [ "kcenon::monitoring::stats::statistics< T >", "structkcenon_1_1monitoring_1_1stats_1_1statistics.html", null ],
    [ "kcenon::monitoring::central_collector::stats", "structkcenon_1_1monitoring_1_1central__collector_1_1stats.html", null ],
    [ "kcenon::monitoring::event_bus::stats", "structkcenon_1_1monitoring_1_1event__bus_1_1stats.html", null ],
    [ "kcenon::monitoring::thread_local_buffer::stats", "structkcenon_1_1monitoring_1_1thread__local__buffer_1_1stats.html", null ],
    [ "kcenon::monitoring::statsd_metric_data", "structkcenon_1_1monitoring_1_1statsd__metric__data.html", null ],
    [ "kcenon::monitoring::storage_backend", "classkcenon_1_1monitoring_1_1storage__backend.html", null ],
    [ "kcenon::monitoring::storage_backend_factory", "classkcenon_1_1monitoring_1_1storage__backend__factory.html", null ],
    [ "kcenon::monitoring::storage_config", "structkcenon_1_1monitoring_1_1storage__config.html", null ],
    [ "kcenon::monitoring::stream_aggregation_result", "structkcenon_1_1monitoring_1_1stream__aggregation__result.html", null ],
    [ "kcenon::monitoring::stream_aggregator", "classkcenon_1_1monitoring_1_1stream__aggregator.html", null ],
    [ "kcenon::monitoring::stream_aggregator_config", "structkcenon_1_1monitoring_1_1stream__aggregator__config.html", null ],
    [ "kcenon::monitoring::streaming_statistics", "structkcenon_1_1monitoring_1_1streaming__statistics.html", null ],
    [ "kcenon::monitoring::subscription_token", "classkcenon_1_1monitoring_1_1subscription__token.html", null ],
    [ "kcenon::monitoring::summary_data", "structkcenon_1_1monitoring_1_1summary__data.html", null ],
    [ "kcenon::monitoring::system_resources::memory_metrics::swap_info", "structkcenon_1_1monitoring_1_1system__resources_1_1memory__metrics_1_1swap__info.html", null ],
    [ "kcenon::monitoring::system_event", "classkcenon_1_1monitoring_1_1system__event.html", null ],
    [ "kcenon::monitoring::system_info_collector", "classkcenon_1_1monitoring_1_1system__info__collector.html", null ],
    [ "kcenon::monitoring::system_metrics", "structkcenon_1_1monitoring_1_1system__metrics.html", null ],
    [ "kcenon::monitoring::system_metrics_config", "structkcenon_1_1monitoring_1_1system__metrics__config.html", null ],
    [ "kcenon::monitoring::system_monitor", "classkcenon_1_1monitoring_1_1system__monitor.html", null ],
    [ "kcenon::monitoring::system_resources", "structkcenon_1_1monitoring_1_1system__resources.html", null ],
    [ "kcenon::monitoring::tagged_metric", "structkcenon_1_1monitoring_1_1tagged__metric.html", null ],
    [ "kcenon::monitoring::tcp_state_counts", "structkcenon_1_1monitoring_1_1tcp__state__counts.html", null ],
    [ "kcenon::monitoring::platform::tcp_state_info", "structkcenon_1_1monitoring_1_1platform_1_1tcp__state__info.html", null ],
    [ "kcenon::monitoring::temperature_info_collector", "classkcenon_1_1monitoring_1_1temperature__info__collector.html", null ],
    [ "kcenon::monitoring::temperature_reading", "structkcenon_1_1monitoring_1_1temperature__reading.html", null ],
    [ "kcenon::monitoring::temperature_sensor_info", "structkcenon_1_1monitoring_1_1temperature__sensor__info.html", null ],
    [ "testing::Test", null, [
      [ "AbsentTriggerTest", "classAbsentTriggerTest.html", null ],
      [ "AdaptiveMonitoringTest", "classAdaptiveMonitoringTest.html", null ],
      [ "AlertGroupTest", "classAlertGroupTest.html", null ],
      [ "AlertLabelsTest", "classAlertLabelsTest.html", null ],
      [ "AlertManagerLifecycleTest", "classAlertManagerLifecycleTest.html", null ],
      [ "AlertManagerNotifierTest", "classAlertManagerNotifierTest.html", null ],
      [ "AlertManagerProcessingTest", "classAlertManagerProcessingTest.html", null ],
      [ "AlertManagerResolutionTest", "classAlertManagerResolutionTest.html", null ],
      [ "AlertManagerRuleTest", "classAlertManagerRuleTest.html", null ],
      [ "AlertManagerSilenceTest", "classAlertManagerSilenceTest.html", null ],
      [ "AlertSilenceTest", "classAlertSilenceTest.html", null ],
      [ "AlertTest", "classAlertTest.html", null ],
      [ "AlertTransitionTest", "classAlertTransitionTest.html", null ],
      [ "AnomalyTriggerTest", "classAnomalyTriggerTest.html", null ],
      [ "BufferingStrategiesTest", "classBufferingStrategiesTest.html", null ],
      [ "CollectorRegistryIntegrationTest", "classCollectorRegistryIntegrationTest.html", null ],
      [ "CompositeTriggerTest", "classCompositeTriggerTest.html", null ],
      [ "DIContainerTest", "classDIContainerTest.html", null ],
      [ "DataConsistencyTest", "classDataConsistencyTest.html", null ],
      [ "DeltaTriggerTest", "classDeltaTriggerTest.html", null ],
      [ "DistributedTracingTest", "classDistributedTracingTest.html", null ],
      [ "ErrorBoundariesTest", "classErrorBoundariesTest.html", null ],
      [ "EventBusTest", "classEventBusTest.html", null ],
      [ "ExporterIntegrationTest", "classExporterIntegrationTest.html", null ],
      [ "FaultToleranceTest", "classFaultToleranceTest.html", null ],
      [ "HealthMonitoringTest", "classHealthMonitoringTest.html", null ],
      [ "HistogramMetricsTest", "classHistogramMetricsTest.html", null ],
      [ "HotPathHelperTest", "classHotPathHelperTest.html", null ],
      [ "IntegrationE2ETest", "classIntegrationE2ETest.html", null ],
      [ "LockFreeCollectorTest", "classLockFreeCollectorTest.html", null ],
      [ "MetricExportersTest", "classMetricExportersTest.html", null ],
      [ "MetricStorageTest", "classMetricStorageTest.html", null ],
      [ "MonitorableInterfaceTest", "classMonitorableInterfaceTest.html", null ],
      [ "MonitoringThreadSafetyTest", "classMonitoringThreadSafetyTest.html", null ],
      [ "OpenTelemetryAdapterTest", "classOpenTelemetryAdapterTest.html", null ],
      [ "OptimizationTest", "classOptimizationTest.html", null ],
      [ "PerformanceMonitorThreadSafetyTest", "classPerformanceMonitorThreadSafetyTest.html", null ],
      [ "PerformanceMonitoringTest", "classPerformanceMonitoringTest.html", null ],
      [ "PerformanceProfilerThreadSafetyTest", "classPerformanceProfilerThreadSafetyTest.html", null ],
      [ "RangeTriggerTest", "classRangeTriggerTest.html", null ],
      [ "RateOfChangeTriggerTest", "classRateOfChangeTriggerTest.html", null ],
      [ "ResourceManagementTest", "classResourceManagementTest.html", null ],
      [ "ResultTypesTest", "classResultTypesTest.html", null ],
      [ "StatisticsUtilsTest", "classStatisticsUtilsTest.html", null ],
      [ "StorageBackendsTest", "classStorageBackendsTest.html", null ],
      [ "StreamAggregationTest", "classStreamAggregationTest.html", null ],
      [ "StressPerformanceTest", "classStressPerformanceTest.html", null ],
      [ "SummaryMetricsTest", "classSummaryMetricsTest.html", null ],
      [ "SystemResourceCollectorTest", "classSystemResourceCollectorTest.html", null ],
      [ "ThreadContextTest", "classThreadContextTest.html", null ],
      [ "ThresholdTriggerTest", "classThresholdTriggerTest.html", null ],
      [ "TimerMetricsTest", "classTimerMetricsTest.html", null ],
      [ "TraceExportersTest", "classTraceExportersTest.html", [
        [ "OtlpGrpcExporterTest", "classOtlpGrpcExporterTest.html", null ]
      ] ]
    ] ],
    [ "kcenon::monitoring::thread_context", "classkcenon_1_1monitoring_1_1thread__context.html", null ],
    [ "kcenon::monitoring::thread_context_data", "structkcenon_1_1monitoring_1_1thread__context__data.html", null ],
    [ "kcenon::monitoring::thread_local_buffer", "classkcenon_1_1monitoring_1_1thread__local__buffer.html", null ],
    [ "kcenon::monitoring::thread_pool_metric_event::thread_pool_stats", "structkcenon_1_1monitoring_1_1thread__pool__metric__event_1_1thread__pool__stats.html", null ],
    [ "kcenon::monitoring::thread_to_monitoring_adapter", "classkcenon_1_1monitoring_1_1thread__to__monitoring__adapter.html", null ],
    [ "kcenon::monitoring::performance_monitor::thresholds", "structkcenon_1_1monitoring_1_1performance__monitor_1_1thresholds.html", null ],
    [ "kcenon::monitoring::resource_threshold_monitor::thresholds", "structkcenon_1_1monitoring_1_1resource__threshold__monitor_1_1thresholds.html", null ],
    [ "kcenon::monitoring::time_point_data", "structkcenon_1_1monitoring_1_1time__point__data.html", null ],
    [ "kcenon::monitoring::time_series", "classkcenon_1_1monitoring_1_1time__series.html", null ],
    [ "kcenon::monitoring::time_series_buffer< T >", "classkcenon_1_1monitoring_1_1time__series__buffer.html", null ],
    [ "kcenon::monitoring::time_series_buffer_config", "structkcenon_1_1monitoring_1_1time__series__buffer__config.html", null ],
    [ "kcenon::monitoring::time_series_config", "structkcenon_1_1monitoring_1_1time__series__config.html", null ],
    [ "kcenon::monitoring::time_series_query", "structkcenon_1_1monitoring_1_1time__series__query.html", null ],
    [ "kcenon::monitoring::detail::time_series_ring_buffer< Sample >", "classkcenon_1_1monitoring_1_1detail_1_1time__series__ring__buffer.html", null ],
    [ "kcenon::monitoring::detail::time_series_ring_buffer< kcenon::monitoring::load_average_sample >", "classkcenon_1_1monitoring_1_1detail_1_1time__series__ring__buffer.html", null ],
    [ "kcenon::monitoring::detail::time_series_ring_buffer< kcenon::monitoring::time_series_sample< T > >", "classkcenon_1_1monitoring_1_1detail_1_1time__series__ring__buffer.html", null ],
    [ "kcenon::monitoring::time_series_sample< T >", "structkcenon_1_1monitoring_1_1time__series__sample.html", null ],
    [ "kcenon::monitoring::time_series_statistics", "structkcenon_1_1monitoring_1_1time__series__statistics.html", null ],
    [ "kcenon::monitoring::timer_data", "structkcenon_1_1monitoring_1_1timer__data.html", null ],
    [ "kcenon::monitoring::timer_scope", "classkcenon_1_1monitoring_1_1timer__scope.html", null ],
    [ "kcenon::monitoring::trace_context", "structkcenon_1_1monitoring_1_1trace__context.html", null ],
    [ "kcenon::monitoring::trace_export_config", "structkcenon_1_1monitoring_1_1trace__export__config.html", null ],
    [ "kcenon::monitoring::trace_export_settings", "structkcenon_1_1monitoring_1_1trace__export__settings.html", null ],
    [ "kcenon::monitoring::trace_exporter_factory", "classkcenon_1_1monitoring_1_1trace__exporter__factory.html", null ],
    [ "kcenon::monitoring::trace_exporter_interface", "classkcenon_1_1monitoring_1_1trace__exporter__interface.html", [
      [ "MockTraceExporter", "classMockTraceExporter.html", null ],
      [ "kcenon::monitoring::jaeger_exporter", "classkcenon_1_1monitoring_1_1jaeger__exporter.html", null ],
      [ "kcenon::monitoring::otlp_exporter", "classkcenon_1_1monitoring_1_1otlp__exporter.html", null ],
      [ "kcenon::monitoring::otlp_grpc_exporter", "classkcenon_1_1monitoring_1_1otlp__grpc__exporter.html", null ],
      [ "kcenon::monitoring::zipkin_exporter", "classkcenon_1_1monitoring_1_1zipkin__exporter.html", null ]
    ] ],
    [ "kcenon::monitoring::trace_span", "structkcenon_1_1monitoring_1_1trace__span.html", null ],
    [ "kcenon::monitoring::transaction", "classkcenon_1_1monitoring_1_1transaction.html", null ],
    [ "kcenon::monitoring::transaction_config", "structkcenon_1_1monitoring_1_1transaction__config.html", null ],
    [ "kcenon::monitoring::transaction_manager", "classkcenon_1_1monitoring_1_1transaction__manager.html", null ],
    [ "kcenon::monitoring::transaction_metrics", "structkcenon_1_1monitoring_1_1transaction__metrics.html", null ],
    [ "kcenon::monitoring::transaction_operation", "classkcenon_1_1monitoring_1_1transaction__operation.html", null ],
    [ "kcenon::monitoring::rule_definition::trigger_config", "structkcenon_1_1monitoring_1_1rule__definition_1_1trigger__config.html", null ],
    [ "std::true_type", null, [
      [ "kcenon::monitoring::stats::detail::is_chrono_duration< std::chrono::duration< Rep, Period > >", "structkcenon_1_1monitoring_1_1stats_1_1detail_1_1is__chrono__duration_3_01std_1_1chrono_1_1durat67ba77e32eb716cbe525f0013060fa95.html", null ]
    ] ],
    [ "kcenon::monitoring::udp_send_result", "structkcenon_1_1monitoring_1_1udp__send__result.html", null ],
    [ "kcenon::monitoring::udp_statistics", "structkcenon_1_1monitoring_1_1udp__statistics.html", null ],
    [ "kcenon::monitoring::udp_transport", "classkcenon_1_1monitoring_1_1udp__transport.html", [
      [ "kcenon::monitoring::stub_udp_transport", "classkcenon_1_1monitoring_1_1stub__udp__transport.html", null ]
    ] ],
    [ "unreliable_service", "classunreliable__service.html", null ],
    [ "kcenon::monitoring::platform::uptime_info", "structkcenon_1_1monitoring_1_1platform_1_1uptime__info.html", null ],
    [ "kcenon::monitoring::uptime_info_collector", "classkcenon_1_1monitoring_1_1uptime__info__collector.html", null ],
    [ "kcenon::monitoring::uptime_metrics", "structkcenon_1_1monitoring_1_1uptime__metrics.html", null ],
    [ "kcenon::monitoring::simple_http_client::url_parts", "structkcenon_1_1monitoring_1_1simple__http__client_1_1url__parts.html", null ],
    [ "UserService", "classUserService.html", null ],
    [ "kcenon::monitoring::validation_config", "structkcenon_1_1monitoring_1_1validation__config.html", null ],
    [ "kcenon::monitoring::validation_metrics", "structkcenon_1_1monitoring_1_1validation__metrics.html", null ],
    [ "kcenon::monitoring::state_validator::validation_rule", "structkcenon_1_1monitoring_1_1state__validator_1_1validation__rule.html", null ],
    [ "kcenon::monitoring::vm_info_collector", "classkcenon_1_1monitoring_1_1vm__info__collector.html", null ],
    [ "kcenon::monitoring::vm_metrics", "structkcenon_1_1monitoring_1_1vm__metrics.html", null ],
    [ "kcenon::monitoring::webhook_config", "structkcenon_1_1monitoring_1_1webhook__config.html", null ],
    [ "WebService", "classWebService.html", null ],
    [ "kcenon::monitoring::zipkin_span_data", "structkcenon_1_1monitoring_1_1zipkin__span__data.html", null ]
];