Monitoring System: kcenon::monitoring::stats Namespace Reference
kcenon::monitoring::stats Namespace Reference
Namespaces
namespace detail
Classes
struct statistics
Statistical summary for a collection of values.
Functions
template<typename T >
T percentile (const std::vector< T > &sorted_values, double percentile_value)
template<typename T >
statistics< T > compute_sorted (const std::vector< T > &sorted_values)
Compute statistics from sorted values.
template<typename T >
statistics< T > compute (const std::vector< T > &values)
template<typename T >
statistics< T > compute_inplace (std::vector< T > &values)
Compute statistics in place (modifies input)
Function Documentation
compute()
template<typename T > statistics< T > kcenon::monitoring::stats::compute (const std::vector< T > & values)
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/utils/statistics.h.
Definition at line 228 of file statistics.h.
{
    if (values.empty()) {
        return compute_sorted<T>({});
    }
    std::vector<T> sorted = values;
    std::sort(sorted.begin(), sorted.end());
    return compute_sorted(sorted);
}
References compute_sorted().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
compute_inplace()
template<typename T > statistics< T > kcenon::monitoring::stats::compute_inplace (std::vector< T > & values)
Compute statistics in place (modifies input)
This is more efficient when you don't need to preserve the original order.
Template Parameters
T Value type
Parameters
values Vector of values (will be sorted in place)
Returns
statistics<T> containing all computed statistics
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/utils/statistics.h.
Definition at line 248 of file statistics.h.
{
    if (values.empty()) {
        return compute_sorted<T>({});
    }
    std::sort(values.begin(), values.end());
    return compute_sorted(values);
}
References compute_sorted().
Referenced by TEST_F().
compute_sorted()
template<typename T > statistics< T > kcenon::monitoring::stats::compute_sorted (const std::vector< T > & sorted_values)
Compute statistics from sorted values.
This is more efficient when you already have sorted data.
Template Parameters
T Value type
Parameters
sorted_values Vector of sorted values (ascending order)
Returns
statistics<T> containing all computed statistics
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/utils/statistics.h.
Definition at line 173 of file statistics.h.
{
    statistics<T> result{};
    if (sorted_values.empty()) {
        result.min = detail::zero_value<T>();
        result.max = detail::zero_value<T>();
        result.mean = detail::zero_value<T>();
        result.median = detail::zero_value<T>();
        result.p95 = detail::zero_value<T>();
        result.p99 = detail::zero_value<T>();
        result.total = detail::zero_value<T>();
        result.count = 0;
        return result;
    }
    result.count = sorted_values.size();
    result.min = sorted_values.front();
    result.max = sorted_values.back();
    // Calculate total
    result.total = std::accumulate(sorted_values.begin(), sorted_values.end(),
                                   detail::zero_value<T>());
    // Calculate mean
    result.mean = detail::divide(result.total, result.count);
    // Calculate percentiles
    result.median = percentile(sorted_values, 50.0);
    result.p95 = percentile(sorted_values, 95.0);
    result.p99 = percentile(sorted_values, 99.0);
    return result;
}
References kcenon::monitoring::stats::statistics< T >::count, kcenon::monitoring::stats::detail::divide(), percentile(), and kcenon::monitoring::stats::detail::zero_value().
Referenced by compute(), compute_inplace(), and TEST_F().
percentile()
template<typename T > T kcenon::monitoring::stats::percentile (const std::vector< T > & sorted_values, double percentile_value)
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/utils/statistics.h.
Definition at line 130 of file statistics.h.
{
    if (sorted_values.empty()) {
        return detail::zero_value<T>();
    }
    if (percentile_value <= 0.0) {
        return sorted_values.front();
    }
    if (percentile_value >= 100.0) {
        return sorted_values.back();
    }
    double rank = (percentile_value / 100.0) * (sorted_values.size() - 1);
    size_t lower_idx = static_cast<size_t>(rank);
    size_t upper_idx = lower_idx + 1;
    if (upper_idx >= sorted_values.size()) {
        return sorted_values[lower_idx];
    }
    // For chrono types, use simple index-based selection
    // For numeric types, use linear interpolation
    if constexpr (detail::is_chrono_duration_v<T>) {
        // Use nearest-rank method for duration types
        return sorted_values[static_cast<size_t>(std::round(rank))];
    } else {
        double fraction = rank - static_cast<double>(lower_idx);
        return sorted_values[lower_idx] +
               static_cast<T>(fraction * (sorted_values[upper_idx] - sorted_values[lower_idx]));
    }
}
References kcenon::monitoring::stats::detail::is_chrono_duration_v, and kcenon::monitoring::stats::detail::zero_value().
Referenced by compute_sorted(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().