Monitoring System: kcenon::monitoring::compact_metric_value Struct Reference
kcenon::monitoring::compact_metric_value Struct Reference
Memory-efficient metric value storage.
#include <metric_types.h>
Public Types
using value_type
Public Member Functions
compact_metric_value () noexcept
compact_metric_value (const metric_metadata &meta, double val) noexcept
compact_metric_value (const metric_metadata &meta, int64_t val) noexcept
compact_metric_value (const metric_metadata &meta, std::string val) noexcept
double as_double () const
Get value as double.
int64_t as_int64 () const
Get value as integer.
std::string as_string () const
Get value as string.
std::chrono::system_clock::time_point get_timestamp () const
Get timestamp as time_point.
bool is_numeric () const noexcept
Check if metric is numeric.
size_t memory_footprint () const noexcept
Get memory footprint in bytes.
Public Attributes
metric_metadata metadata
value_type value
uint64_t timestamp_us
Detailed Description
Memory-efficient metric value storage.
Examples
custom_metric_types_example.cpp.
Definition at line 95 of file metric_types.h.
Member Typedef Documentation
value_type
using kcenon::monitoring::compact_metric_value::value_type
Initial value:
 std::variant<
        double,
        int64_t,
        std::string
    >
Definition at line 96 of file metric_types.h.
Constructor & Destructor Documentation
compact_metric_value() [1/4]
kcenon::monitoring::compact_metric_value::compact_metric_value () inline noexcept
Definition at line 106 of file metric_types.h.
        : value(0.0), timestamp_us(0) {}
compact_metric_value() [2/4]
kcenon::monitoring::compact_metric_value::compact_metric_value (const metric_metadata & meta, double val) inline noexcept
Definition at line 109 of file metric_types.h.
        : metadata(meta), value(val) {
        timestamp_us = std::chrono::duration_cast<std::chrono::microseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();
    }
References timestamp_us.
compact_metric_value() [3/4]
kcenon::monitoring::compact_metric_value::compact_metric_value (const metric_metadata & meta, int64_t val) inline noexcept
Definition at line 115 of file metric_types.h.
        : metadata(meta), value(val) {
        timestamp_us = std::chrono::duration_cast<std::chrono::microseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();
    }
References timestamp_us.
compact_metric_value() [4/4]
kcenon::monitoring::compact_metric_value::compact_metric_value (const metric_metadata & meta, std::string val) inline noexcept
Definition at line 121 of file metric_types.h.
        : metadata(meta), value(std::move(val)) {
        timestamp_us = std::chrono::duration_cast<std::chrono::microseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count();
    }
References timestamp_us.
Member Function Documentation
as_double()
double kcenon::monitoring::compact_metric_value::as_double () const inline
Get value as double.
Definition at line 130 of file metric_types.h.
{
        if (std::holds_alternative<double>(value)) {
            return std::get<double>(value);
        } else if (std::holds_alternative<int64_t>(value)) {
            return static_cast<double>(std::get<int64_t>(value));
        }
        return 0.0;
    }
References value.
Referenced by demonstrate_metric_metadata(), and TEST_F().
as_int64()
int64_t kcenon::monitoring::compact_metric_value::as_int64 () const inline
Get value as integer.
Definition at line 142 of file metric_types.h.
{
        if (std::holds_alternative<int64_t>(value)) {
            return std::get<int64_t>(value);
        } else if (std::holds_alternative<double>(value)) {
            return static_cast<int64_t>(std::get<double>(value));
        }
        return 0;
    }
References value.
Referenced by TEST_F().
as_string()
std::string kcenon::monitoring::compact_metric_value::as_string () const inline
Get value as string.
Definition at line 154 of file metric_types.h.
{
        if (std::holds_alternative<std::string>(value)) {
            return std::get<std::string>(value);
        } else if (std::holds_alternative<double>(value)) {
            return std::to_string(std::get<double>(value));
        } else if (std::holds_alternative<int64_t>(value)) {
            return std::to_string(std::get<int64_t>(value));
        }
        return "";
    }
References value.
Referenced by TEST_F().
get_timestamp()
std::chrono::system_clock::time_point kcenon::monitoring::compact_metric_value::get_timestamp () const inline
Get timestamp as time_point.
Definition at line 168 of file metric_types.h.
{
        return std::chrono::system_clock::time_point(
            std::chrono::microseconds(timestamp_us));
    }
References timestamp_us.
is_numeric()
bool kcenon::monitoring::compact_metric_value::is_numeric () const inline noexcept
Check if metric is numeric.
Definition at line 176 of file metric_types.h.
{
        return std::holds_alternative<double>(value) ||
               std::holds_alternative<int64_t>(value);
    }
References value.
Referenced by TEST_F().
memory_footprint()
size_t kcenon::monitoring::compact_metric_value::memory_footprint () const inline noexcept
Get memory footprint in bytes.
Definition at line 184 of file metric_types.h.
{
        size_t base_size = sizeof(metric_metadata) + sizeof(timestamp_us) + sizeof(value_type);
        if (std::holds_alternative<std::string>(value)) {
            base_size += std::get<std::string>(value).capacity();
        }
        return base_size;
    }
References timestamp_us, and value.
Referenced by demonstrate_metric_metadata().
Member Data Documentation
metadata
metric_metadata kcenon::monitoring::compact_metric_value::metadata
Definition at line 102 of file metric_types.h.
timestamp_us
uint64_t kcenon::monitoring::compact_metric_value::timestamp_us
Definition at line 104 of file metric_types.h.
Referenced by compact_metric_value(), compact_metric_value(), compact_metric_value(), get_timestamp(), and memory_footprint().
value
value_type kcenon::monitoring::compact_metric_value::value
Definition at line 103 of file metric_types.h.
Referenced by as_double(), as_int64(), as_string(), is_numeric(), and memory_footprint().
The documentation for this struct was generated from the following file:
include/kcenon/monitoring/utils/metric_types.h