Monitoring System: kcenon::monitoring::timer_data Struct Reference
kcenon::monitoring::timer_data Struct Reference
Timer data with percentile calculations.
#include <metric_types.h>
Classes
struct snapshot
Get snapshot of current statistics.
Public Member Functions
timer_data ()
Construct timer with default reservoir size.
timer_data (size_t reservoir_size)
Construct timer with custom reservoir size.
void record (double duration_ms)
Record a duration sample (in milliseconds)
template<typename Rep , typename Period >
void record (std::chrono::duration< Rep, Period > duration)
Record a duration using chrono duration.
double get_percentile (double percentile) const
Get percentile value (0-100)
double median () const
Get median (p50)
double p90 () const
Get p90 value.
double p95 () const
Get p95 value.
double p99 () const
Get p99 value.
double p999 () const
Get p999 value (99.9th percentile)
double mean () const noexcept
Get mean value.
uint64_t count () const noexcept
Get sample count.
double min () const noexcept
Get minimum recorded value.
double max () const noexcept
Get maximum recorded value.
double stddev () const
Get standard deviation.
void reset ()
Reset all data.
snapshot get_snapshot () const
Public Attributes
std::vector< double > samples
size_t max_samples
uint64_t total_count = 0
double sum = 0.0
double min_value = (std::numeric_limits<double>::max)()
double max_value = (std::numeric_limits<double>::lowest)()
bool sorted = false
Static Public Attributes
static constexpr size_t DEFAULT_RESERVOIR_SIZE = 1024
Private Member Functions
void ensure_sorted () const
Detailed Description
Timer data with percentile calculations.
Stores duration samples and provides percentile calculations. Uses a reservoir sampling approach for memory efficiency.
Examples
custom_metric_types_example.cpp.
Definition at line 359 of file metric_types.h.
Constructor & Destructor Documentation
timer_data() [1/2]
kcenon::monitoring::timer_data::timer_data () inline
Construct timer with default reservoir size.
Definition at line 373 of file metric_types.h.
                 : max_samples(DEFAULT_RESERVOIR_SIZE) {
        samples.reserve(max_samples);
    }
References max_samples, and samples.
timer_data() [2/2]
kcenon::monitoring::timer_data::timer_data (size_t reservoir_size) inline explicit
Construct timer with custom reservoir size.
Definition at line 380 of file metric_types.h.
        : max_samples(reservoir_size) {
        samples.reserve(max_samples);
    }
References max_samples, and samples.
Member Function Documentation
count()
uint64_t kcenon::monitoring::timer_data::count () const inline noexcept
Get sample count.
Examples
custom_metric_types_example.cpp.
Definition at line 485 of file metric_types.h.
{
        return total_count;
    }
References total_count.
Referenced by demonstrate_timer_scope().
ensure_sorted()
void kcenon::monitoring::timer_data::ensure_sorted () const inline private
Definition at line 564 of file metric_types.h.
{
        if (!sorted && !samples.empty()) {
            auto& mutable_samples = const_cast<std::vector<double>&>(samples);
            std::sort(mutable_samples.begin(), mutable_samples.end());
            const_cast<bool&>(sorted) = true;
        }
    }
References samples, and sorted.
Referenced by get_percentile().
get_percentile()
double kcenon::monitoring::timer_data::get_percentile (double percentile) const inline
Get percentile value (0-100)
Parameters
percentile The percentile to calculate (e.g., 50 for median, 99 for p99)
Returns
The value at the given percentile
Definition at line 420 of file metric_types.h.
{
        if (samples.empty()) return 0.0;
        if (percentile <= 0) return min_value;
        if (percentile >= 100) return max_value;
        ensure_sorted();
        double rank = (percentile / 100.0) * (samples.size() - 1);
        size_t lower_idx = static_cast<size_t>(rank);
        size_t upper_idx = lower_idx + 1;
        double fraction = rank - lower_idx;
        if (upper_idx >= samples.size()) {
            return samples[lower_idx];
        }
        // Linear interpolation between adjacent values
        return samples[lower_idx] + fraction * (samples[upper_idx] - samples[lower_idx]);
    }
References ensure_sorted(), max_value, min_value, and samples.
Referenced by median(), p90(), p95(), p99(), and p999().
get_snapshot()
snapshot kcenon::monitoring::timer_data::get_snapshot () const inline
Definition at line 548 of file metric_types.h.
{
        return snapshot{
            total_count,
            mean(),
            min(),
            max(),
            stddev(),
            median(),
            p90(),
            p95(),
            p99(),
            p999()
        };
    }
References max(), mean(), median(), min(), p90(), p95(), p99(), p999(), stddev(), and total_count.
Referenced by demonstrate_timer(), and TEST_F().
max()
double kcenon::monitoring::timer_data::max () const inline noexcept
Get maximum recorded value.
Examples
custom_metric_types_example.cpp.
Definition at line 499 of file metric_types.h.
{
        return total_count > 0 ? max_value : 0.0;
    }
References max_value, and total_count.
Referenced by demonstrate_timer_scope(), and get_snapshot().
mean()
double kcenon::monitoring::timer_data::mean () const inline noexcept
Get mean value.
Examples
custom_metric_types_example.cpp.
Definition at line 478 of file metric_types.h.
{
        return total_count > 0 ? sum / total_count : 0.0;
    }
References sum, and total_count.
Referenced by demonstrate_timer_scope(), get_snapshot(), and stddev().
median()
double kcenon::monitoring::timer_data::median () const inline
Get median (p50)
Definition at line 443 of file metric_types.h.
{
        return get_percentile(50.0);
    }
References get_percentile().
Referenced by get_snapshot(), and TEST_F().
min()
double kcenon::monitoring::timer_data::min () const inline noexcept
Get minimum recorded value.
Examples
custom_metric_types_example.cpp.
Definition at line 492 of file metric_types.h.
{
        return total_count > 0 ? min_value : 0.0;
    }
References min_value, and total_count.
Referenced by demonstrate_timer_scope(), and get_snapshot().
p90()
double kcenon::monitoring::timer_data::p90 () const inline
Get p90 value.
Definition at line 450 of file metric_types.h.
                       {
        return get_percentile(90.0);
    }
References get_percentile().
Referenced by get_snapshot().
p95()
double kcenon::monitoring::timer_data::p95 () const inline
Get p95 value.
Examples
custom_metric_types_example.cpp.
Definition at line 457 of file metric_types.h.
                       {
        return get_percentile(95.0);
    }
References get_percentile().
Referenced by demonstrate_timer_scope(), and get_snapshot().
p99()
double kcenon::monitoring::timer_data::p99 () const inline
Get p99 value.
Definition at line 464 of file metric_types.h.
                       {
        return get_percentile(99.0);
    }
References get_percentile().
Referenced by get_snapshot().
p999()
double kcenon::monitoring::timer_data::p999 () const inline
Get p999 value (99.9th percentile)
Definition at line 471 of file metric_types.h.
{
        return get_percentile(99.9);
    }
References get_percentile().
Referenced by get_snapshot().
record() [1/2]
void kcenon::monitoring::timer_data::record (double duration_ms) inline
Record a duration sample (in milliseconds)
Definition at line 388 of file metric_types.h.
{
        total_count++;
        sum += duration_ms;
        min_value = (std::min)(min_value, duration_ms);
        max_value = (std::max)(max_value, duration_ms);
        sorted = false;
        if (samples.size() < max_samples) {
            samples.push_back(duration_ms);
        } else {
            // Reservoir sampling for memory efficiency
            size_t idx = static_cast<size_t>(rand()) % total_count;
            if (idx < max_samples) {
                samples[idx] = duration_ms;
            }
        }
    }
References max_samples, max_value, min_value, samples, sorted, sum, and total_count.
Referenced by demonstrate_timer(), record(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and kcenon::monitoring::timer_scope::~timer_scope().
record() [2/2]
template<typename Rep , typename Period > void kcenon::monitoring::timer_data::record (std::chrono::duration< Rep, Period > duration) inline
Record a duration using chrono duration.
Definition at line 410 of file metric_types.h.
{
        auto ms = std::chrono::duration_cast<std::chrono::microseconds>(duration).count() / 1000.0;
        record(ms);
    }
References record().
reset()
void kcenon::monitoring::timer_data::reset () inline
Reset all data.
Definition at line 522 of file metric_types.h.
                 {
        samples.clear();
        samples.reserve(max_samples);
        total_count = 0;
        sum = 0.0;
        min_value = (std::numeric_limits<double>::max)();
        max_value = (std::numeric_limits<double>::lowest)();
        sorted = false;
    }
References max_samples, max_value, min_value, samples, sorted, sum, and total_count.
stddev()
double kcenon::monitoring::timer_data::stddev () const inline
Get standard deviation.
Definition at line 506 of file metric_types.h.
{
        if (samples.size() < 2) return 0.0;
        double avg = mean();
        double variance = 0.0;
        for (double sample : samples) {
            double diff = sample - avg;
            variance += diff * diff;
        }
        variance /= samples.size();
        return std::sqrt(variance);
    }
References mean(), and samples.
Referenced by get_snapshot().
Member Data Documentation
DEFAULT_RESERVOIR_SIZE
size_t kcenon::monitoring::timer_data::DEFAULT_RESERVOIR_SIZE = 1024 static constexpr
Definition at line 360 of file metric_types.h.
max_samples
size_t kcenon::monitoring::timer_data::max_samples
Definition at line 363 of file metric_types.h.
Referenced by record(), reset(), timer_data(), and timer_data().
max_value
double kcenon::monitoring::timer_data::max_value = (std::numeric_limits<double>::lowest)()
Definition at line 367 of file metric_types.h.
Referenced by get_percentile(), max(), record(), and reset().
min_value
double kcenon::monitoring::timer_data::min_value = (std::numeric_limits<double>::max)()
Definition at line 366 of file metric_types.h.
Referenced by get_percentile(), min(), record(), and reset().
samples
std::vector<double> kcenon::monitoring::timer_data::samples
Definition at line 362 of file metric_types.h.
Referenced by ensure_sorted(), get_percentile(), record(), reset(), stddev(), timer_data(), and timer_data().
sorted
bool kcenon::monitoring::timer_data::sorted = false mutable
Definition at line 368 of file metric_types.h.
Referenced by ensure_sorted(), record(), and reset().
sum
double kcenon::monitoring::timer_data::sum = 0.0
Definition at line 365 of file metric_types.h.
Referenced by mean(), record(), and reset().
total_count
uint64_t kcenon::monitoring::timer_data::total_count = 0
Definition at line 364 of file metric_types.h.
Referenced by count(), get_snapshot(), max(), mean(), min(), record(), and reset().
The documentation for this struct was generated from the following file:
include/kcenon/monitoring/utils/metric_types.h