Monitoring System: kcenon::monitoring::inhibition_rule Struct Reference
kcenon::monitoring::inhibition_rule Struct Reference
Rule for inhibiting alerts based on other alerts.
#include <alert_pipeline.h>
Public Member Functions
bool matches_source (const alert &a) const
Check if source alert matches this rule.
bool should_inhibit (const alert &source, const alert &target) const
Check if target alert should be inhibited by source.
Public Attributes
std::string name
alert_labels source_match
Labels that source alert must have.
alert_labels target_match
Labels that target alert must have.
std::vector< std::string > equal
Labels that must be equal on both.
Detailed Description
Rule for inhibiting alerts based on other alerts.
When a source alert is firing, target alerts matching the specified labels are inhibited (silenced).
Examples
alert_pipeline_example.cpp.
Definition at line 261 of file alert_pipeline.h.
Member Function Documentation
matches_source()
bool kcenon::monitoring::inhibition_rule::matches_source (const alert & a) const inline
Check if source alert matches this rule.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 270 of file alert_pipeline.h.
{
        for (const auto& [key, value] : source_match.labels) {
            if (a.labels.get(key) != value) {
                return false;
            }
        }
        return true;
    }
References kcenon::monitoring::alert_labels::get(), kcenon::monitoring::alert::labels, kcenon::monitoring::alert_labels::labels, and source_match.
Referenced by should_inhibit().
should_inhibit()
bool kcenon::monitoring::inhibition_rule::should_inhibit (const alert & source, const alert & target) const inline
Check if target alert should be inhibited by source.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h.
Definition at line 282 of file alert_pipeline.h.
{
        // Source must match
        if (!matches_source(source)) {
            return false;
        }
        // Target must match target_match labels
        for (const auto& [key, value] : target_match.labels) {
            if (target.labels.get(key) != value) {
                return false;
            }
        }
        // Equal labels must match between source and target
        for (const auto& label : equal) {
            if (source.labels.get(label) != target.labels.get(label)) {
                return false;
            }
        }
        return true;
    }
References equal, kcenon::monitoring::alert_labels::get(), kcenon::monitoring::alert::labels, kcenon::monitoring::alert_labels::labels, matches_source(), and target_match.
Member Data Documentation
equal
std::vector<std::string> kcenon::monitoring::inhibition_rule::equal
Labels that must be equal on both.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h, and alert_pipeline_example.cpp.
Definition at line 265 of file alert_pipeline.h.
Referenced by main(), and should_inhibit().
name
std::string kcenon::monitoring::inhibition_rule::name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h, and alert_pipeline_example.cpp.
Definition at line 262 of file alert_pipeline.h.
Referenced by main().
source_match
alert_labels kcenon::monitoring::inhibition_rule::source_match
Labels that source alert must have.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h, and alert_pipeline_example.cpp.
Definition at line 263 of file alert_pipeline.h.
Referenced by main(), and matches_source().
target_match
alert_labels kcenon::monitoring::inhibition_rule::target_match
Labels that target alert must have.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_pipeline.h, and alert_pipeline_example.cpp.
Definition at line 264 of file alert_pipeline.h.
Referenced by main(), and should_inhibit().
The documentation for this struct was generated from the following file:
include/kcenon/monitoring/alert/alert_pipeline.h