Monitoring System: kcenon::monitoring::retry_config Struct Reference
kcenon::monitoring::retry_config Struct Reference
Retry configuration.
#include <retry_policy.h>
Public Member Functions
bool validate () const
Validate configuration.
Public Attributes
size_t max_attempts = 3
retry_strategy strategy = retry_strategy::exponential_backoff
std::chrono::milliseconds initial_delay = std::chrono::milliseconds(1000)
std::chrono::milliseconds max_delay = std::chrono::milliseconds(30000)
double backoff_multiplier = 2.0
std::function< bool(const error_info &)> should_retry = nullptr
Detailed Description
Retry configuration.
Examples
graceful_degradation_example.cpp, and health_reliability_example.cpp.
Definition at line 54 of file retry_policy.h.
Member Function Documentation
validate()
bool kcenon::monitoring::retry_config::validate () const inline
Validate configuration.
Returns
true if configuration is valid
Definition at line 66 of file retry_policy.h.
{
        if (max_attempts == 0) {
            return false;
        }
        if (backoff_multiplier < 1.0) {
            return false;
        }
        return true;
    }
References backoff_multiplier, and max_attempts.
Referenced by TEST_F(), and kcenon::monitoring::fault_tolerance_config::validate().
Member Data Documentation
backoff_multiplier
double kcenon::monitoring::retry_config::backoff_multiplier = 2.0
Examples
graceful_degradation_example.cpp, and health_reliability_example.cpp.
Definition at line 59 of file retry_policy.h.
Referenced by kcenon::monitoring::retry_executor< T >::calculate_delay(), kcenon::monitoring::create_exponential_backoff_config(), demonstrate_retry_policy(), TEST_F(), TEST_F(), and validate().
initial_delay
std::chrono::milliseconds kcenon::monitoring::retry_config::initial_delay = std::chrono::milliseconds(1000)
Examples
graceful_degradation_example.cpp, and health_reliability_example.cpp.
Definition at line 57 of file retry_policy.h.
Referenced by kcenon::monitoring::retry_executor< T >::calculate_delay(), kcenon::monitoring::create_exponential_backoff_config(), kcenon::monitoring::create_fibonacci_backoff_config(), kcenon::monitoring::create_fixed_delay_config(), demonstrate_combined_patterns(), demonstrate_retry_policy(), TEST_F(), and TEST_F().
max_attempts
size_t kcenon::monitoring::retry_config::max_attempts = 3
Examples
graceful_degradation_example.cpp, and health_reliability_example.cpp.
Definition at line 55 of file retry_policy.h.
Referenced by kcenon::monitoring::create_exponential_backoff_config(), kcenon::monitoring::create_fibonacci_backoff_config(), kcenon::monitoring::create_fixed_delay_config(), demonstrate_combined_patterns(), demonstrate_retry_policy(), kcenon::monitoring::retry_executor< T >::execute(), TEST_F(), TEST_F(), TEST_F(), and validate().
max_delay
std::chrono::milliseconds kcenon::monitoring::retry_config::max_delay = std::chrono::milliseconds(30000)
Examples
health_reliability_example.cpp.
Definition at line 58 of file retry_policy.h.
Referenced by kcenon::monitoring::retry_executor< T >::calculate_delay(), and demonstrate_retry_policy().
should_retry
std::function<bool(const error_info&)> kcenon::monitoring::retry_config::should_retry = nullptr
Definition at line 60 of file retry_policy.h.
Referenced by kcenon::monitoring::retry_executor< T >::execute(), and TEST_F().
strategy
retry_strategy kcenon::monitoring::retry_config::strategy = retry_strategy::exponential_backoff
Examples
graceful_degradation_example.cpp, and health_reliability_example.cpp.
Definition at line 56 of file retry_policy.h.
Referenced by kcenon::monitoring::retry_executor< T >::calculate_delay(), kcenon::monitoring::create_exponential_backoff_config(), kcenon::monitoring::create_fibonacci_backoff_config(), kcenon::monitoring::create_fixed_delay_config(), demonstrate_combined_patterns(), and demonstrate_retry_policy().
The documentation for this struct was generated from the following file:
include/kcenon/monitoring/reliability/retry_policy.h