Monitoring System: kcenon::monitoring::health_check_result Struct Reference
kcenon::monitoring::health_check_result Struct Reference
Result of a health check operation.
#include <monitoring_core.h>
Public Member Functions
health_check_result ()
bool is_healthy () const
bool is_operational () const
Static Public Member Functions
static health_check_result healthy (const std::string &msg="OK")
static health_check_result unhealthy (const std::string &msg)
static health_check_result degraded (const std::string &msg)
Public Attributes
health_status status = health_status::unknown
std::string message
std::vector< std::string > issues
std::chrono::system_clock::time_point check_time
std::chrono::system_clock::time_point timestamp
std::chrono::milliseconds check_duration {0}
std::unordered_map< std::string, std::string > metadata
std::optional< std::exception_ptr > error
Detailed Description
Result of a health check operation.
Examples
bidirectional_di_example.cpp, health_reliability_example.cpp, monitor_factory_pattern_example.cpp, and production_monitoring_example.cpp.
Definition at line 124 of file monitoring_core.h.
Constructor & Destructor Documentation
health_check_result()
kcenon::monitoring::health_check_result::health_check_result () inline
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 134 of file monitoring_core.h.
        : check_time(std::chrono::system_clock::now()),
          timestamp(std::chrono::system_clock::now()) {}
Member Function Documentation
degraded()
static health_check_result kcenon::monitoring::health_check_result::degraded (const std::string & msg) inline static
Definition at line 165 of file monitoring_core.h.
{
        health_check_result result;
        result.status = health_status::degraded;
        result.message = msg;
        result.timestamp = std::chrono::system_clock::now();
        result.check_time = result.timestamp;
        return result;
    }
References check_time, kcenon::monitoring::degraded, message, status, and timestamp.
Referenced by kcenon::monitoring::composite_health_check::check_all_required(), kcenon::monitoring::health_dependency_graph::check_with_dependencies(), demonstrate_health_monitoring(), and TEST_F().
healthy()
static health_check_result kcenon::monitoring::health_check_result::healthy (const std::string & msg = "OK") inline static
Definition at line 147 of file monitoring_core.h.
{
        health_check_result result;
        result.status = health_status::healthy;
        result.message = msg;
        result.timestamp = std::chrono::system_clock::now();
        result.check_time = result.timestamp;
        return result;
    }
References check_time, kcenon::monitoring::healthy, message, status, and timestamp.
Referenced by database_health_check::check(), external_api_health_check::check(), kcenon::monitoring::composite_health_check::check(), kcenon::monitoring::functional_health_check::check(), kcenon::monitoring::composite_health_check::check_all_required(), kcenon::monitoring::composite_health_check::check_any_required(), demonstrate_health_monitoring(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
is_healthy()
bool kcenon::monitoring::health_check_result::is_healthy () const inline
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 138 of file monitoring_core.h.
{
        return status == health_status::healthy;
    }
References kcenon::monitoring::healthy, and status.
Referenced by TEST_F().
is_operational()
bool kcenon::monitoring::health_check_result::is_operational () const inline
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 142 of file monitoring_core.h.
{
        return status == health_status::healthy ||
               status == health_status::degraded;
    }
References kcenon::monitoring::degraded, kcenon::monitoring::healthy, and status.
unhealthy()
static health_check_result kcenon::monitoring::health_check_result::unhealthy (const std::string & msg) inline static
Definition at line 156 of file monitoring_core.h.
{
        health_check_result result;
        result.status = health_status::unhealthy;
        result.message = msg;
        result.timestamp = std::chrono::system_clock::now();
        result.check_time = result.timestamp;
        return result;
    }
References check_time, message, status, timestamp, and kcenon::monitoring::unhealthy.
Referenced by kcenon::monitoring::composite_health_check::check_all_required(), kcenon::monitoring::composite_health_check::check_any_required(), kcenon::monitoring::health_dependency_graph::check_with_dependencies(), demonstrate_health_monitoring(), TEST_F(), and TEST_F().
Member Data Documentation
check_duration
std::chrono::milliseconds kcenon::monitoring::health_check_result::check_duration {0}
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 130 of file monitoring_core.h.
{0};
Referenced by test_health_check::check().
check_time
std::chrono::system_clock::time_point kcenon::monitoring::health_check_result::check_time
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 128 of file monitoring_core.h.
Referenced by degraded(), healthy(), and unhealthy().
error
std::optional<std::exception_ptr> kcenon::monitoring::health_check_result::error
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 132 of file monitoring_core.h.
issues
std::vector<std::string> kcenon::monitoring::health_check_result::issues
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h.
Definition at line 127 of file monitoring_core.h.
Referenced by TEST_F().
message
std::string kcenon::monitoring::health_check_result::message
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h, bidirectional_di_example.cpp, and monitor_factory_pattern_example.cpp.
Definition at line 126 of file monitoring_core.h.
Referenced by test_health_check::check(), aggregating_monitor::check_health(), kcenon::monitoring::health_monitor::check_health(), degraded(), console_logger::health_check(), healthy(), TEST(), and unhealthy().
metadata
std::unordered_map<std::string, std::string> kcenon::monitoring::health_check_result::metadata
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h, and bidirectional_di_example.cpp.
Definition at line 131 of file monitoring_core.h.
Referenced by console_logger::health_check().
status
health_status kcenon::monitoring::health_check_result::status = health_status::unknown
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h, bidirectional_di_example.cpp, and monitor_factory_pattern_example.cpp.
Definition at line 125 of file monitoring_core.h.
Referenced by test_health_check::check(), aggregating_monitor::check_health(), kcenon::monitoring::health_monitor::check_health(), degraded(), console_logger::health_check(), healthy(), is_healthy(), is_operational(), TEST(), TEST_F(), unhealthy(), and kcenon::monitoring::health_monitor::update_stats().
timestamp
std::chrono::system_clock::time_point kcenon::monitoring::health_check_result::timestamp
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_core.h, and monitor_factory_pattern_example.cpp.
Definition at line 129 of file monitoring_core.h.
Referenced by test_health_check::check(), aggregating_monitor::check_health(), kcenon::monitoring::health_monitor::check_health(), degraded(), healthy(), and unhealthy().
The documentation for this struct was generated from the following file:
include/kcenon/monitoring/interfaces/monitoring_core.h