Monitoring System: kcenon::monitoring::transaction_config Struct Reference
kcenon::monitoring::transaction_config Struct Reference
Transaction configuration.
#include <data_consistency.h>
Public Member Functions
bool validate () const
Public Attributes
std::chrono::milliseconds timeout {std::chrono::milliseconds(30000)}
std::chrono::milliseconds lock_timeout {std::chrono::milliseconds(10000)}
size_t max_retries {3}
Detailed Description
Transaction configuration.
Definition at line 49 of file data_consistency.h.
Member Function Documentation
validate()
bool kcenon::monitoring::transaction_config::validate () const inline nodiscard
Definition at line 54 of file data_consistency.h.
{
        if (timeout.count() <= 0) {
            return false;
        }
        if (lock_timeout.count() <= 0) {
            return false;
        }
        if (max_retries == 0) {
            return false;
        }
        return true;
    }
References lock_timeout, max_retries, and timeout.
Referenced by TEST_F().
Member Data Documentation
lock_timeout
std::chrono::milliseconds kcenon::monitoring::transaction_config::lock_timeout {std::chrono::milliseconds(10000)}
Definition at line 51 of file data_consistency.h.
{std::chrono::milliseconds(10000)};
Referenced by TEST_F(), and validate().
max_retries
size_t kcenon::monitoring::transaction_config::max_retries {3}
Definition at line 52 of file data_consistency.h.
{3};
Referenced by TEST_F(), and validate().
timeout
std::chrono::milliseconds kcenon::monitoring::transaction_config::timeout {std::chrono::milliseconds(30000)}
Definition at line 50 of file data_consistency.h.
{std::chrono::milliseconds(30000)};
Referenced by kcenon::monitoring::transaction::commit(), kcenon::monitoring::transaction_manager::detect_deadlocks(), TEST_F(), TEST_F(), TEST_F(), and validate().
The documentation for this struct was generated from the following file:
include/kcenon/monitoring/reliability/data_consistency.h