Monitoring System: tests/test_error_boundaries.cpp File Reference
test_error_boundaries.cpp File Reference
#include <gtest/gtest.h>
#include <algorithm>
#include <thread>
#include <chrono>
#include <atomic>
#include <kcenon/monitoring/reliability/error_boundary.h>
#include <kcenon/monitoring/reliability/graceful_degradation.h>
Classes
class ErrorBoundariesTest
Functions
TEST_F (ErrorBoundariesTest, ErrorBoundaryNormalOperation)
TEST_F (ErrorBoundariesTest, ErrorBoundaryFailFastPolicy)
TEST_F (ErrorBoundariesTest, ErrorBoundaryIsolatePolicy)
TEST_F (ErrorBoundariesTest, ErrorBoundaryDegradePolicy)
TEST_F (ErrorBoundariesTest, ErrorBoundaryWithFallback)
TEST_F (ErrorBoundariesTest, ErrorBoundaryExceptionHandling)
TEST_F (ErrorBoundariesTest, ErrorBoundaryMetrics)
TEST_F (ErrorBoundariesTest, ErrorBoundaryRecovery)
TEST_F (ErrorBoundariesTest, DefaultValueStrategy)
TEST_F (ErrorBoundariesTest, CachedValueStrategy)
TEST_F (ErrorBoundariesTest, AlternativeServiceStrategy)
TEST_F (ErrorBoundariesTest, GracefulDegradationManagerBasic)
TEST_F (ErrorBoundariesTest, GracefulDegradationServiceDegrade)
TEST_F (ErrorBoundariesTest, GracefulDegradationPlanExecution)
TEST_F (ErrorBoundariesTest, GracefulDegradationServiceRecovery)
TEST_F (ErrorBoundariesTest, GracefulDegradationRecoverAll)
TEST_F (ErrorBoundariesTest, GracefulDegradationMetrics)
TEST_F (ErrorBoundariesTest, DegradableServiceWrapper)
TEST_F (ErrorBoundariesTest, ErrorBoundaryRegistry)
TEST_F (ErrorBoundariesTest, ErrorBoundaryConfigValidation)
TEST_F (ErrorBoundariesTest, ServiceConfigValidation)
TEST_F (ErrorBoundariesTest, DegradationPlanValidation)
TEST_F (ErrorBoundariesTest, ErrorBoundaryHealthCheck)
TEST_F (ErrorBoundariesTest, DegradationManagerHealthCheck)
TEST_F (ErrorBoundariesTest, UnregisterNonexistentService)
TEST_F (ErrorBoundariesTest, DegradeNonexistentService)
TEST_F (ErrorBoundariesTest, RecoverNonexistentService)
TEST_F (ErrorBoundariesTest, ExecuteNonexistentPlan)
TEST_F (ErrorBoundariesTest, AddDegradationPlanEmptyName)
TEST_F (ErrorBoundariesTest, RegisterDuplicateService)
TEST_F (ErrorBoundariesTest, DegradationManagerGetName)
TEST_F (ErrorBoundariesTest, DegradationManagerGetServiceNames)
TEST_F (ErrorBoundariesTest, ServiceConfigValidationBoundaryValues)
TEST_F (ErrorBoundariesTest, DegradableServiceNullptrManager)
Function Documentation
TEST_F() [1/34]
TEST_F (ErrorBoundariesTest , AddDegradationPlanEmptyName)
Definition at line 513 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    degradation_plan plan;
    plan.name = "";
    auto result = manager->add_degradation_plan(plan);
    EXPECT_TRUE(result.is_err());
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::degradation_plan::name.
TEST_F() [2/34]
TEST_F (ErrorBoundariesTest , AlternativeServiceStrategy)
Definition at line 222 of file test_error_boundaries.cpp.
{
    auto alternative_op = []() { return kcenon::common::ok(888); };
    auto strategy = std::make_shared<alternative_service_strategy<int>>(alternative_op);
    error_boundary_config config;
    config.policy = error_boundary_policy::fallback;
    error_boundary<int> boundary("alternative_test", config);
    boundary.set_fallback_strategy(strategy);
    auto result = boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(result.value(), 888);
}
References kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary_config::policy, and kcenon::monitoring::error_boundary< T >::set_fallback_strategy().
TEST_F() [3/34]
TEST_F (ErrorBoundariesTest , CachedValueStrategy)
Definition at line 205 of file test_error_boundaries.cpp.
{
    auto strategy = std::make_shared<cached_value_strategy<int>>(std::chrono::seconds(1));
    // Update cache with a value
    strategy->update_cache(555);
    error_boundary_config config;
    config.policy = error_boundary_policy::fallback;
    error_boundary<int> boundary("cached_test", config);
    boundary.set_fallback_strategy(strategy);
    auto result = boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(result.value(), 555);
}
References kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary_config::policy, and kcenon::monitoring::error_boundary< T >::set_fallback_strategy().
TEST_F() [4/34]
TEST_F (ErrorBoundariesTest , DefaultValueStrategy)
Definition at line 188 of file test_error_boundaries.cpp.
{
    error_boundary<int> boundary("test_boundary");
    auto strategy = std::make_shared<default_value_strategy<int>>(777);
    boundary.set_fallback_strategy(strategy);
    error_boundary_config config;
    config.policy = error_boundary_policy::fallback;
    error_boundary<int> fallback_boundary("fallback_test", config);
    fallback_boundary.set_fallback_strategy(strategy);
    auto result = fallback_boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(result.value(), 777);
}
References kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary_config::policy, and kcenon::monitoring::error_boundary< T >::set_fallback_strategy().
TEST_F() [5/34]
TEST_F (ErrorBoundariesTest , DegradableServiceNullptrManager)
Definition at line 588 of file test_error_boundaries.cpp.
{
    auto normal_op = []() { return kcenon::common::ok(42); };
    auto degraded_op = [](degradation_level) { return kcenon::common::ok(0); };
    // Create with nullptr manager
    degradable_service<int> service("null_manager_service", nullptr, normal_op, degraded_op);
    // Should use normal_op directly when manager is nullptr
    auto result = service.execute();
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(result.value(), 42);
    EXPECT_EQ(service.get_name(), "null_manager_service");
}
References kcenon::monitoring::service.
TEST_F() [6/34]
TEST_F (ErrorBoundariesTest , DegradableServiceWrapper)
Definition at line 332 of file test_error_boundaries.cpp.
{
    auto manager = std::make_shared<graceful_degradation_manager>("test_manager");
    auto config = create_service_config("wrapper_service", service_priority::normal);
    manager->register_service(config);
    auto normal_op = [this]() { return always_succeeding_operation(); };
    auto degraded_op = [](degradation_level level) {
        return kcenon::common::ok(static_cast<int>(level) * 100);
    };
    auto service = create_degradable_service<int>("wrapper_service", manager, normal_op, degraded_op);
    // Test normal operation
    auto result1 = service->execute();
    EXPECT_TRUE(result1.is_ok());
    EXPECT_EQ(result1.value(), 100);
    // Degrade service and test degraded operation
    manager->degrade_service("wrapper_service", degradation_level::limited, "Test");
    auto result2 = service->execute();
    EXPECT_TRUE(result2.is_ok());
    EXPECT_EQ(result2.value(), static_cast<int>(degradation_level::limited) * 100);
}
References kcenon::monitoring::create_degradable_service(), kcenon::monitoring::create_service_config(), and kcenon::monitoring::service.
TEST_F() [7/34]
TEST_F (ErrorBoundariesTest , DegradationManagerGetName)
Definition at line 537 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("my_manager");
    EXPECT_EQ(manager->get_name(), "my_manager");
    graceful_degradation_manager default_mgr;
    EXPECT_EQ(default_mgr.get_name(), "default");
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::graceful_degradation_manager::get_name().
TEST_F() [8/34]
TEST_F (ErrorBoundariesTest , DegradationManagerGetServiceNames)
Definition at line 545 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    // Empty initially
    auto names = manager->get_service_names();
    EXPECT_TRUE(names.empty());
    // Register services
    manager->register_service(create_service_config("alpha", service_priority::normal));
    manager->register_service(create_service_config("beta", service_priority::important));
    manager->register_service(create_service_config("gamma", service_priority::critical));
    names = manager->get_service_names();
    EXPECT_EQ(names.size(), 3);
    // Verify all names present (order may vary due to unordered_map)
    std::sort(names.begin(), names.end());
    EXPECT_EQ(names[0], "alpha");
    EXPECT_EQ(names[1], "beta");
    EXPECT_EQ(names[2], "gamma");
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [9/34]
TEST_F (ErrorBoundariesTest , DegradationManagerHealthCheck)
Definition at line 456 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("health_test");
    // Register multiple services
    manager->register_service(create_service_config("service1", service_priority::normal));
    manager->register_service(create_service_config("service2", service_priority::normal));
    // Initially healthy
    auto health = manager->is_healthy();
    EXPECT_TRUE(health.is_ok());
    EXPECT_TRUE(health.value());
    // Degrade more than 50% of services
    manager->degrade_service("service1", degradation_level::minimal, "Test");
    manager->degrade_service("service2", degradation_level::minimal, "Test");
    // Should now be unhealthy
    health = manager->is_healthy();
    EXPECT_TRUE(health.is_ok());
    EXPECT_FALSE(health.value());
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [10/34]
TEST_F (ErrorBoundariesTest , DegradationPlanValidation)
Definition at line 420 of file test_error_boundaries.cpp.
{
    degradation_plan plan;
    // Valid plan
    plan.name = "test_plan";
    EXPECT_TRUE(plan.validate());
    // Invalid plan - empty name
    plan.name = "";
    EXPECT_FALSE(plan.validate());
}
References kcenon::monitoring::degradation_plan::name, and kcenon::monitoring::degradation_plan::validate().
TEST_F() [11/34]
TEST_F (ErrorBoundariesTest , DegradeNonexistentService)
Definition at line 489 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto result = manager->degrade_service("nonexistent", degradation_level::limited, "test");
    EXPECT_TRUE(result.is_err());
    auto metrics = manager->get_metrics();
    EXPECT_EQ(metrics.failed_degradations.load(), 1);
}
References kcenon::monitoring::create_degradation_manager().
TEST_F() [12/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryConfigValidation)
Definition at line 377 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    // Valid config
    config.name = "test";
    EXPECT_TRUE(config.validate());
    // Invalid config - empty name
    config.name = "";
    EXPECT_FALSE(config.validate());
    // Reset to valid
    config.name = "test";
    EXPECT_TRUE(config.validate());
    // Invalid error threshold
    config.error_threshold = 0;
    EXPECT_FALSE(config.validate());
}
References kcenon::monitoring::error_boundary_config::error_threshold, kcenon::monitoring::error_boundary_config::name, and kcenon::monitoring::error_boundary_config::validate().
TEST_F() [13/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryDegradePolicy)
Definition at line 98 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    config.policy = error_boundary_policy::degrade;
    config.error_threshold = 2;
    error_boundary<int> boundary("test_boundary", config);
    // First failure
    auto result1 = boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result1.is_err());
    // Second failure should trigger degradation
    auto result2 = boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result2.is_err());
    // Check that degradation occurred
    EXPECT_GT(boundary.get_degradation_level(), degradation_level::normal);
}
References kcenon::monitoring::error_boundary_config::error_threshold, kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary< T >::get_degradation_level(), and kcenon::monitoring::error_boundary_config::policy.
TEST_F() [14/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryExceptionHandling)
Definition at line 133 of file test_error_boundaries.cpp.
{
    error_boundary<int> boundary("test_boundary");
    auto result = boundary.execute([this]() { return throwing_operation(); });
    EXPECT_TRUE(result.is_err());
    EXPECT_EQ(result.error().code, static_cast<int>(monitoring_error_code::operation_failed));
    EXPECT_EQ(call_count.load(), 1);
}
References kcenon::monitoring::error_boundary< T >::execute().
TEST_F() [15/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryFailFastPolicy)
Definition at line 72 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    config.policy = error_boundary_policy::fail_fast;
    error_boundary<int> boundary("test_boundary", config);
    auto result = boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result.is_err());
    EXPECT_EQ(result.error().code, static_cast<int>(monitoring_error_code::operation_failed));
    EXPECT_EQ(boundary.get_degradation_level(), degradation_level::normal);
}
References kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary< T >::get_degradation_level(), and kcenon::monitoring::error_boundary_config::policy.
TEST_F() [16/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryHealthCheck)
Definition at line 433 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    config.max_degradation = degradation_level::emergency; // Allow emergency degradation
    error_boundary<int> boundary("health_test", config);
    // Initially healthy
    auto health = boundary.is_healthy();
    EXPECT_TRUE(health.is_ok());
    EXPECT_TRUE(health.value());
    EXPECT_EQ(boundary.get_degradation_level(), degradation_level::normal);
    // Force degradation to emergency
    boundary.force_degradation(degradation_level::emergency);
    // Verify degradation was applied
    EXPECT_EQ(boundary.get_degradation_level(), degradation_level::emergency);
    // Test that health check method works (even if logic needs refinement)
    health = boundary.is_healthy();
    EXPECT_TRUE(health.is_ok()); // Health check method returns a valid result
    // Note: Health check logic may need refinement for emergency degradation
}
References kcenon::monitoring::error_boundary< T >::force_degradation(), kcenon::monitoring::error_boundary< T >::get_degradation_level(), kcenon::monitoring::error_boundary< T >::is_healthy(), and kcenon::monitoring::error_boundary_config::max_degradation.
TEST_F() [17/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryIsolatePolicy)
Definition at line 85 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    config.policy = error_boundary_policy::isolate;
    error_boundary<int> boundary("test_boundary", config);
    auto result = boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_TRUE(result.is_err());
    EXPECT_EQ(result.error().code, static_cast<int>(monitoring_error_code::service_degraded));
    EXPECT_EQ(boundary.get_degradation_level(), degradation_level::normal);
}
References kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary< T >::get_degradation_level(), and kcenon::monitoring::error_boundary_config::policy.
TEST_F() [18/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryMetrics)
Definition at line 143 of file test_error_boundaries.cpp.
{
    error_boundary<int> boundary("test_boundary");
    // Execute some operations
    boundary.execute([this]() { return always_succeeding_operation(); });
    boundary.execute([this]() { return always_failing_operation(); });
    boundary.execute([this]() { return always_succeeding_operation(); });
    auto metrics = boundary.get_metrics();
    EXPECT_EQ(metrics.total_operations.load(), 3);
    EXPECT_EQ(metrics.successful_operations.load(), 2);
    EXPECT_EQ(metrics.failed_operations.load(), 1);
    EXPECT_NEAR(metrics.get_success_rate(), 2.0/3.0, 0.01);
}
References kcenon::monitoring::error_boundary< T >::execute(), and kcenon::monitoring::error_boundary< T >::get_metrics().
TEST_F() [19/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryNormalOperation)
Definition at line 60 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    error_boundary<int> boundary("test_boundary", config);
    auto result = boundary.execute([this]() { return always_succeeding_operation(); });
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(result.value(), 100);
    EXPECT_EQ(boundary.get_degradation_level(), degradation_level::normal);
    EXPECT_EQ(call_count.load(), 1);
}
References kcenon::monitoring::error_boundary< T >::execute(), and kcenon::monitoring::error_boundary< T >::get_degradation_level().
TEST_F() [20/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryRecovery)
Definition at line 158 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    config.policy = error_boundary_policy::degrade;
    config.error_threshold = 1;
    config.enable_automatic_recovery = true;
    config.recovery_timeout = std::chrono::milliseconds(100);
    error_boundary<int> boundary("test_boundary", config);
    // Trigger degradation
    boundary.execute([this]() { return always_failing_operation(); });
    EXPECT_GT(boundary.get_degradation_level(), degradation_level::normal);
    // Wait for recovery timeout
    std::this_thread::sleep_for(std::chrono::milliseconds(150));
    // Execute successful operation to trigger recovery
    auto result = boundary.execute([this]() { return always_succeeding_operation(); });
    EXPECT_TRUE(result.is_ok());
    // Check if recovery occurred (might need multiple successful operations)
    for (int i = 0; i < 5; ++i) {
        boundary.execute([this]() { return always_succeeding_operation(); });
    }
    auto metrics = boundary.get_metrics();
    EXPECT_GT(metrics.recovery_attempts.load(), 0);
}
References kcenon::monitoring::error_boundary_config::enable_automatic_recovery, kcenon::monitoring::error_boundary_config::error_threshold, kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::error_boundary< T >::get_degradation_level(), kcenon::monitoring::error_boundary< T >::get_metrics(), kcenon::monitoring::error_boundary_config::policy, and kcenon::monitoring::error_boundary_config::recovery_timeout.
TEST_F() [21/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryRegistry)
Definition at line 358 of file test_error_boundaries.cpp.
{
    auto& registry = global_error_boundary_registry();
    auto boundary = std::make_shared<error_boundary<int>>("registry_test");
    registry.register_boundary<int>("test", boundary);
    auto retrieved = registry.get_boundary<int>("test");
    EXPECT_EQ(retrieved, boundary);
    auto names = registry.get_all_names();
    EXPECT_EQ(names.size(), 1);
    EXPECT_EQ(names[0], "test");
    registry.remove_boundary("test");
    retrieved = registry.get_boundary<int>("test");
    EXPECT_EQ(retrieved, nullptr);
}
References kcenon::monitoring::global_error_boundary_registry().
TEST_F() [22/34]
TEST_F (ErrorBoundariesTest , ErrorBoundaryWithFallback)
Definition at line 117 of file test_error_boundaries.cpp.
{
    error_boundary_config config;
    config.policy = error_boundary_policy::fallback;
    error_boundary<int> boundary("test_boundary", config);
    auto fallback = [](const error_info&, degradation_level) {
        return kcenon::common::ok(999);
    };
    auto result = boundary.execute([this]() { return always_failing_operation(); }, fallback);
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(result.value(), 999);
}
References kcenon::monitoring::error_boundary< T >::execute(), kcenon::monitoring::fallback, and kcenon::monitoring::error_boundary_config::policy.
TEST_F() [23/34]
TEST_F (ErrorBoundariesTest , ExecuteNonexistentPlan)
Definition at line 506 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto result = manager->execute_plan("nonexistent_plan", "reason");
    EXPECT_TRUE(result.is_err());
}
References kcenon::monitoring::create_degradation_manager().
TEST_F() [24/34]
TEST_F (ErrorBoundariesTest , GracefulDegradationManagerBasic)
Definition at line 238 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto config = create_service_config("test_service", service_priority::normal);
    auto result = manager->register_service(config);
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(manager->get_service_level("test_service"), degradation_level::normal);
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [25/34]
TEST_F (ErrorBoundariesTest , GracefulDegradationMetrics)
Definition at line 317 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    manager->register_service(create_service_config("service1", service_priority::normal));
    // Perform degradation and recovery operations
    manager->degrade_service("service1", degradation_level::limited, "Test");
    manager->recover_service("service1");
    auto metrics = manager->get_metrics();
    EXPECT_GT(metrics.total_degradations.load(), 0);
    EXPECT_GT(metrics.successful_degradations.load(), 0);
    EXPECT_GT(metrics.recovery_attempts.load(), 0);
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [26/34]
TEST_F (ErrorBoundariesTest , GracefulDegradationPlanExecution)
Definition at line 260 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    // Register services
    manager->register_service(create_service_config("service1", service_priority::normal));
    manager->register_service(create_service_config("service2", service_priority::optional));
    // Create degradation plan
    auto plan = create_degradation_plan("emergency_plan",
                                       {"service1"},
                                       {"service2"},
                                       degradation_level::minimal);
    manager->add_degradation_plan(plan);
    // Execute plan
    auto result = manager->execute_plan("emergency_plan", "Test emergency");
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(manager->get_service_level("service1"), degradation_level::minimal);
    EXPECT_EQ(manager->get_service_level("service2"), degradation_level::emergency);
}
References kcenon::monitoring::create_degradation_manager(), kcenon::monitoring::create_degradation_plan(), and kcenon::monitoring::create_service_config().
TEST_F() [27/34]
TEST_F (ErrorBoundariesTest , GracefulDegradationRecoverAll)
Definition at line 299 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    // Register and degrade multiple services
    manager->register_service(create_service_config("service1", service_priority::normal));
    manager->register_service(create_service_config("service2", service_priority::important));
    manager->degrade_service("service1", degradation_level::limited, "Test");
    manager->degrade_service("service2", degradation_level::minimal, "Test");
    // Recover all
    auto result = manager->recover_all_services();
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(manager->get_service_level("service1"), degradation_level::normal);
    EXPECT_EQ(manager->get_service_level("service2"), degradation_level::normal);
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [28/34]
TEST_F (ErrorBoundariesTest , GracefulDegradationServiceDegrade)
Definition at line 248 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto config = create_service_config("test_service", service_priority::normal);
    manager->register_service(config);
    auto result = manager->degrade_service("test_service", degradation_level::limited, "Test degradation");
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(manager->get_service_level("test_service"), degradation_level::limited);
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [29/34]
TEST_F (ErrorBoundariesTest , GracefulDegradationServiceRecovery)
Definition at line 282 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto config = create_service_config("test_service", service_priority::normal);
    manager->register_service(config);
    // Degrade service
    manager->degrade_service("test_service", degradation_level::minimal, "Test degradation");
    EXPECT_EQ(manager->get_service_level("test_service"), degradation_level::minimal);
    // Recover service
    auto result = manager->recover_service("test_service");
    EXPECT_TRUE(result.is_ok());
    EXPECT_EQ(manager->get_service_level("test_service"), degradation_level::normal);
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [30/34]
TEST_F (ErrorBoundariesTest , RecoverNonexistentService)
Definition at line 499 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto result = manager->recover_service("nonexistent");
    EXPECT_TRUE(result.is_err());
}
References kcenon::monitoring::create_degradation_manager().
TEST_F() [31/34]
TEST_F (ErrorBoundariesTest , RegisterDuplicateService)
Definition at line 522 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto config = create_service_config("dup_service", service_priority::normal);
    auto result1 = manager->register_service(config);
    EXPECT_TRUE(result1.is_ok());
    auto result2 = manager->register_service(config);
    EXPECT_TRUE(result2.is_err());
}
References kcenon::monitoring::create_degradation_manager(), and kcenon::monitoring::create_service_config().
TEST_F() [32/34]
TEST_F (ErrorBoundariesTest , ServiceConfigValidation)
Definition at line 397 of file test_error_boundaries.cpp.
{
    service_config config;
    // Valid config
    config.name = "test_service";
    EXPECT_TRUE(config.validate());
    // Invalid config - empty name
    config.name = "";
    EXPECT_FALSE(config.validate());
    // Reset and test error rate threshold
    config.name = "test_service";
    config.error_rate_threshold = -0.1; // Invalid
    EXPECT_FALSE(config.validate());
    config.error_rate_threshold = 1.1; // Invalid
    EXPECT_FALSE(config.validate());
    config.error_rate_threshold = 0.5; // Valid
    EXPECT_TRUE(config.validate());
}
References kcenon::monitoring::service_config::error_rate_threshold, kcenon::monitoring::service_config::name, and kcenon::monitoring::service_config::validate().
TEST_F() [33/34]
TEST_F (ErrorBoundariesTest , ServiceConfigValidationBoundaryValues)
Definition at line 571 of file test_error_boundaries.cpp.
{
    service_config config;
    config.name = "test_service";
    // error_rate_threshold = 0.0 should be valid
    config.error_rate_threshold = 0.0;
    EXPECT_TRUE(config.validate());
    // error_rate_threshold = 1.0 should be valid
    config.error_rate_threshold = 1.0;
    EXPECT_TRUE(config.validate());
}
References kcenon::monitoring::service_config::error_rate_threshold, kcenon::monitoring::service_config::name, and kcenon::monitoring::service_config::validate().
TEST_F() [34/34]
TEST_F (ErrorBoundariesTest , UnregisterNonexistentService)
Definition at line 482 of file test_error_boundaries.cpp.
{
    auto manager = create_degradation_manager("test_manager");
    auto result = manager->unregister_service("nonexistent");
    EXPECT_TRUE(result.is_err());
}
References kcenon::monitoring::create_degradation_manager().