Monitoring System: tests/test_statistics_utils.cpp File Reference
test_statistics_utils.cpp File Reference
Unit tests for statistics utilities.
#include <gtest/gtest.h>
#include <kcenon/monitoring/utils/statistics.h>
#include <chrono>
#include <vector>
Classes
class StatisticsUtilsTest
Functions
TEST_F (StatisticsUtilsTest, PercentileEmptyVector)
TEST_F (StatisticsUtilsTest, PercentileSingleValue)
TEST_F (StatisticsUtilsTest, PercentileTwoValues)
TEST_F (StatisticsUtilsTest, PercentileFiveValues)
TEST_F (StatisticsUtilsTest, PercentileP95P99)
TEST_F (StatisticsUtilsTest, PercentileBoundaryValues)
TEST_F (StatisticsUtilsTest, PercentileChronoEmpty)
TEST_F (StatisticsUtilsTest, PercentileChronoValues)
TEST_F (StatisticsUtilsTest, ComputeEmptyVector)
TEST_F (StatisticsUtilsTest, ComputeSingleValue)
TEST_F (StatisticsUtilsTest, ComputeFiveValues)
TEST_F (StatisticsUtilsTest, ComputeUnsortedValues)
TEST_F (StatisticsUtilsTest, ComputeP95P99)
TEST_F (StatisticsUtilsTest, ComputeChronoEmpty)
TEST_F (StatisticsUtilsTest, ComputeChronoValues)
TEST_F (StatisticsUtilsTest, ComputeChronoPercentiles)
TEST_F (StatisticsUtilsTest, ComputeSortedValues)
TEST_F (StatisticsUtilsTest, ComputeInplaceModifiesInput)
TEST_F (StatisticsUtilsTest, ComputeNegativeValues)
TEST_F (StatisticsUtilsTest, ComputeAllSameValues)
TEST_F (StatisticsUtilsTest, ComputeLargeValues)
Detailed Description
Unit tests for statistics utilities.
Definition in file test_statistics_utils.cpp.
Function Documentation
TEST_F() [1/21]
TEST_F (StatisticsUtilsTest , ComputeAllSameValues)
Definition at line 262 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {42.0, 42.0, 42.0, 42.0, 42.0};
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 5);
    EXPECT_DOUBLE_EQ(stats.min, 42.0);
    EXPECT_DOUBLE_EQ(stats.max, 42.0);
    EXPECT_DOUBLE_EQ(stats.mean, 42.0);
    EXPECT_DOUBLE_EQ(stats.median, 42.0);
    EXPECT_DOUBLE_EQ(stats.p95, 42.0);
    EXPECT_DOUBLE_EQ(stats.p99, 42.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [2/21]
TEST_F (StatisticsUtilsTest , ComputeChronoEmpty)
Definition at line 176 of file test_statistics_utils.cpp.
{
    std::vector<std::chrono::nanoseconds> empty;
    auto stats = compute(empty);
    EXPECT_EQ(stats.count, 0);
    EXPECT_EQ(stats.min, std::chrono::nanoseconds::zero());
    EXPECT_EQ(stats.max, std::chrono::nanoseconds::zero());
    EXPECT_EQ(stats.mean, std::chrono::nanoseconds::zero());
}
References kcenon::monitoring::stats::compute().
TEST_F() [3/21]
TEST_F (StatisticsUtilsTest , ComputeChronoPercentiles)
Definition at line 204 of file test_statistics_utils.cpp.
{
    std::vector<std::chrono::nanoseconds> values;
    for (int i = 1; i <= 100; ++i) {
        values.push_back(std::chrono::nanoseconds(i * 1000000));
    }
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 100);
    EXPECT_EQ(stats.min.count(), 1000000);
    EXPECT_EQ(stats.max.count(), 100000000);
    EXPECT_GE(stats.p95.count(), 94000000);
    EXPECT_LE(stats.p95.count(), 96000000);
    EXPECT_GE(stats.p99.count(), 98000000);
    EXPECT_LE(stats.p99.count(), 100000000);
}
References kcenon::monitoring::stats::compute().
TEST_F() [4/21]
TEST_F (StatisticsUtilsTest , ComputeChronoValues)
Definition at line 186 of file test_statistics_utils.cpp.
{
    std::vector<std::chrono::nanoseconds> values = {
        std::chrono::nanoseconds(1000000),
        std::chrono::nanoseconds(2000000),
        std::chrono::nanoseconds(3000000),
        std::chrono::nanoseconds(4000000),
        std::chrono::nanoseconds(5000000)
    };
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 5);
    EXPECT_EQ(stats.min, std::chrono::nanoseconds(1000000));
    EXPECT_EQ(stats.max, std::chrono::nanoseconds(5000000));
    EXPECT_EQ(stats.mean, std::chrono::nanoseconds(3000000));
    EXPECT_EQ(stats.median, std::chrono::nanoseconds(3000000));
    EXPECT_EQ(stats.total, std::chrono::nanoseconds(15000000));
}
References kcenon::monitoring::stats::compute().
TEST_F() [5/21]
TEST_F (StatisticsUtilsTest , ComputeEmptyVector)
Definition at line 108 of file test_statistics_utils.cpp.
{
    std::vector<double> empty;
    auto stats = compute(empty);
    EXPECT_EQ(stats.count, 0);
    EXPECT_DOUBLE_EQ(stats.min, 0.0);
    EXPECT_DOUBLE_EQ(stats.max, 0.0);
    EXPECT_DOUBLE_EQ(stats.mean, 0.0);
    EXPECT_DOUBLE_EQ(stats.total, 0.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [6/21]
TEST_F (StatisticsUtilsTest , ComputeFiveValues)
Definition at line 131 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {1.0, 2.0, 3.0, 4.0, 5.0};
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 5);
    EXPECT_DOUBLE_EQ(stats.min, 1.0);
    EXPECT_DOUBLE_EQ(stats.max, 5.0);
    EXPECT_DOUBLE_EQ(stats.mean, 3.0);
    EXPECT_DOUBLE_EQ(stats.median, 3.0);
    EXPECT_DOUBLE_EQ(stats.total, 15.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [7/21]
TEST_F (StatisticsUtilsTest , ComputeInplaceModifiesInput)
Definition at line 235 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {5.0, 1.0, 3.0, 2.0, 4.0};
    auto stats = compute_inplace(values);
    EXPECT_EQ(stats.count, 5);
    EXPECT_DOUBLE_EQ(stats.min, 1.0);
    EXPECT_DOUBLE_EQ(stats.max, 5.0);
    EXPECT_DOUBLE_EQ(values[0], 1.0);
    EXPECT_DOUBLE_EQ(values[4], 5.0);
}
References kcenon::monitoring::stats::compute_inplace().
TEST_F() [8/21]
TEST_F (StatisticsUtilsTest , ComputeLargeValues)
Definition at line 275 of file test_statistics_utils.cpp.
{
    std::vector<double> values;
    for (int i = 0; i < 10000; ++i) {
        values.push_back(static_cast<double>(i));
    }
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 10000);
    EXPECT_DOUBLE_EQ(stats.min, 0.0);
    EXPECT_DOUBLE_EQ(stats.max, 9999.0);
    EXPECT_DOUBLE_EQ(stats.mean, 4999.5);
}
References kcenon::monitoring::stats::compute().
TEST_F() [9/21]
TEST_F (StatisticsUtilsTest , ComputeNegativeValues)
Definition at line 251 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {-5.0, -3.0, -1.0, 1.0, 3.0, 5.0};
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 6);
    EXPECT_DOUBLE_EQ(stats.min, -5.0);
    EXPECT_DOUBLE_EQ(stats.max, 5.0);
    EXPECT_DOUBLE_EQ(stats.mean, 0.0);
    EXPECT_DOUBLE_EQ(stats.total, 0.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [10/21]
TEST_F (StatisticsUtilsTest , ComputeP95P99)
Definition at line 154 of file test_statistics_utils.cpp.
{
    std::vector<double> values;
    for (int i = 1; i <= 100; ++i) {
        values.push_back(static_cast<double>(i));
    }
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 100);
    EXPECT_DOUBLE_EQ(stats.min, 1.0);
    EXPECT_DOUBLE_EQ(stats.max, 100.0);
    EXPECT_DOUBLE_EQ(stats.mean, 50.5);
    EXPECT_GE(stats.p95, 94.0);
    EXPECT_LE(stats.p95, 96.0);
    EXPECT_GE(stats.p99, 98.0);
    EXPECT_LE(stats.p99, 100.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [11/21]
TEST_F (StatisticsUtilsTest , ComputeSingleValue)
Definition at line 119 of file test_statistics_utils.cpp.
{
    std::vector<double> single = {42.0};
    auto stats = compute(single);
    EXPECT_EQ(stats.count, 1);
    EXPECT_DOUBLE_EQ(stats.min, 42.0);
    EXPECT_DOUBLE_EQ(stats.max, 42.0);
    EXPECT_DOUBLE_EQ(stats.mean, 42.0);
    EXPECT_DOUBLE_EQ(stats.median, 42.0);
    EXPECT_DOUBLE_EQ(stats.total, 42.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [12/21]
TEST_F (StatisticsUtilsTest , ComputeSortedValues)
Definition at line 225 of file test_statistics_utils.cpp.
{
    std::vector<double> sorted = {1.0, 2.0, 3.0, 4.0, 5.0};
    auto stats = compute_sorted(sorted);
    EXPECT_EQ(stats.count, 5);
    EXPECT_DOUBLE_EQ(stats.min, 1.0);
    EXPECT_DOUBLE_EQ(stats.max, 5.0);
    EXPECT_DOUBLE_EQ(stats.mean, 3.0);
}
References kcenon::monitoring::stats::compute_sorted().
TEST_F() [13/21]
TEST_F (StatisticsUtilsTest , ComputeUnsortedValues)
Definition at line 143 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {5.0, 1.0, 3.0, 2.0, 4.0};
    auto stats = compute(values);
    EXPECT_EQ(stats.count, 5);
    EXPECT_DOUBLE_EQ(stats.min, 1.0);
    EXPECT_DOUBLE_EQ(stats.max, 5.0);
    EXPECT_DOUBLE_EQ(stats.mean, 3.0);
    EXPECT_DOUBLE_EQ(stats.median, 3.0);
}
References kcenon::monitoring::stats::compute().
TEST_F() [14/21]
TEST_F (StatisticsUtilsTest , PercentileBoundaryValues)
Definition at line 71 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {1.0, 2.0, 3.0, 4.0, 5.0};
    EXPECT_DOUBLE_EQ(percentile(values, -10.0), 1.0);
    EXPECT_DOUBLE_EQ(percentile(values, 110.0), 5.0);
}
References kcenon::monitoring::stats::percentile().
TEST_F() [15/21]
TEST_F (StatisticsUtilsTest , PercentileChronoEmpty)
Definition at line 81 of file test_statistics_utils.cpp.
{
    std::vector<std::chrono::nanoseconds> empty;
    EXPECT_EQ(percentile(empty, 50.0), std::chrono::nanoseconds::zero());
}
References kcenon::monitoring::stats::percentile().
TEST_F() [16/21]
TEST_F (StatisticsUtilsTest , PercentileChronoValues)
Definition at line 86 of file test_statistics_utils.cpp.
{
    std::vector<std::chrono::nanoseconds> values = {
        std::chrono::nanoseconds(100),
        std::chrono::nanoseconds(200),
        std::chrono::nanoseconds(300),
        std::chrono::nanoseconds(400),
        std::chrono::nanoseconds(500)
    };
    auto p0 = percentile(values, 0.0);
    auto p50 = percentile(values, 50.0);
    auto p100 = percentile(values, 100.0);
    EXPECT_EQ(p0, std::chrono::nanoseconds(100));
    EXPECT_EQ(p50, std::chrono::nanoseconds(300));
    EXPECT_EQ(p100, std::chrono::nanoseconds(500));
}
References kcenon::monitoring::stats::percentile().
TEST_F() [17/21]
TEST_F (StatisticsUtilsTest , PercentileEmptyVector)
Definition at line 28 of file test_statistics_utils.cpp.
{
    std::vector<double> empty;
    EXPECT_DOUBLE_EQ(percentile(empty, 50.0), 0.0);
}
References kcenon::monitoring::stats::percentile().
TEST_F() [18/21]
TEST_F (StatisticsUtilsTest , PercentileFiveValues)
Definition at line 47 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {1.0, 2.0, 3.0, 4.0, 5.0};
    EXPECT_DOUBLE_EQ(percentile(values, 0.0), 1.0);
    EXPECT_DOUBLE_EQ(percentile(values, 25.0), 2.0);
    EXPECT_DOUBLE_EQ(percentile(values, 50.0), 3.0);
    EXPECT_DOUBLE_EQ(percentile(values, 75.0), 4.0);
    EXPECT_DOUBLE_EQ(percentile(values, 100.0), 5.0);
}
References kcenon::monitoring::stats::percentile().
TEST_F() [19/21]
TEST_F (StatisticsUtilsTest , PercentileP95P99)
Definition at line 56 of file test_statistics_utils.cpp.
{
    std::vector<double> values;
    for (int i = 1; i <= 100; ++i) {
        values.push_back(static_cast<double>(i));
    }
    double p95 = percentile(values, 95.0);
    double p99 = percentile(values, 99.0);
    EXPECT_GE(p95, 94.0);
    EXPECT_LE(p95, 96.0);
    EXPECT_GE(p99, 98.0);
    EXPECT_LE(p99, 100.0);
}
References kcenon::monitoring::stats::percentile().
TEST_F() [20/21]
TEST_F (StatisticsUtilsTest , PercentileSingleValue)
Definition at line 33 of file test_statistics_utils.cpp.
{
    std::vector<double> single = {42.0};
    EXPECT_DOUBLE_EQ(percentile(single, 0.0), 42.0);
    EXPECT_DOUBLE_EQ(percentile(single, 50.0), 42.0);
    EXPECT_DOUBLE_EQ(percentile(single, 100.0), 42.0);
}
References kcenon::monitoring::stats::percentile().
TEST_F() [21/21]
TEST_F (StatisticsUtilsTest , PercentileTwoValues)
Definition at line 40 of file test_statistics_utils.cpp.
{
    std::vector<double> values = {10.0, 20.0};
    EXPECT_DOUBLE_EQ(percentile(values, 0.0), 10.0);
    EXPECT_DOUBLE_EQ(percentile(values, 50.0), 15.0);
    EXPECT_DOUBLE_EQ(percentile(values, 100.0), 20.0);
}
References kcenon::monitoring::stats::percentile().