Monitoring System: kcenon::monitoring::opentelemetry_metrics_adapter Class Reference
kcenon::monitoring::opentelemetry_metrics_adapter Class Reference
Adapter for converting monitoring system metrics to OpenTelemetry format.
#include <opentelemetry_adapter.h>
Public Member Functions
opentelemetry_metrics_adapter (const otel_resource &resource)
common::Result< std::vector< otel_metric_data > > convert_metrics (const metrics_snapshot &snapshot)
Convert metrics snapshot to OpenTelemetry metric data.
common::Result< std::vector< otel_metric_data > > convert_monitoring_data (const monitoring_data &data)
Convert monitoring data to OpenTelemetry metric data.
Private Attributes
otel_resource resource_
Detailed Description
Adapter for converting monitoring system metrics to OpenTelemetry format.
Definition at line 282 of file opentelemetry_adapter.h.
Constructor & Destructor Documentation
opentelemetry_metrics_adapter()
kcenon::monitoring::opentelemetry_metrics_adapter::opentelemetry_metrics_adapter (const otel_resource & resource) inline explicit
Definition at line 284 of file opentelemetry_adapter.h.
        : resource_(resource) {}
Member Function Documentation
convert_metrics()
common::Result< std::vector< otel_metric_data > > kcenon::monitoring::opentelemetry_metrics_adapter::convert_metrics (const metrics_snapshot & snapshot) inline
Convert metrics snapshot to OpenTelemetry metric data.
Definition at line 290 of file opentelemetry_adapter.h.
{
        std::vector<otel_metric_data> otel_metrics;
        for (const auto& metric_value : snapshot.metrics) {
            otel_metric_data metric;
            metric.name = metric_value.name;
            metric.value = metric_value.value;
            metric.timestamp = metric_value.timestamp;
            metric.resource = resource_;
            // Add tags as attributes
            for (const auto& [tag_name, tag_value] : metric_value.tags) {
                metric.add_attribute(tag_name, tag_value);
            }
            // Add common resource attributes
            metric.add_attribute("service.name", resource_.get_attribute("service.name").value_or("unknown"));
            metric.add_attribute("service.version", resource_.get_attribute("service.version").value_or("unknown"));
            otel_metrics.push_back(std::move(metric));
        }
        return common::Result<std::vector<otel_metric_data>>::ok(std::move(otel_metrics));
    }
References kcenon::monitoring::otel_resource::get_attribute(), kcenon::monitoring::metrics_snapshot::metrics, kcenon::monitoring::metric::name, kcenon::monitoring::metric_value::name, kcenon::monitoring::ok, resource_, kcenon::monitoring::metric_value::tags, kcenon::monitoring::metric::timestamp, kcenon::monitoring::metric_value::timestamp, kcenon::monitoring::metric::value, and kcenon::monitoring::metric_value::value.
convert_monitoring_data()
common::Result< std::vector< otel_metric_data > > kcenon::monitoring::opentelemetry_metrics_adapter::convert_monitoring_data (const monitoring_data & data) inline
Convert monitoring data to OpenTelemetry metric data.
Definition at line 318 of file opentelemetry_adapter.h.
{
        std::vector<otel_metric_data> otel_metrics;
        for (const auto& [name, value] : data.get_metrics()) {
            otel_metric_data metric;
            metric.name = name;
            metric.value = value;
            metric.timestamp = data.get_timestamp();
            metric.resource = resource_;
            // Add tags as attributes
            for (const auto& [tag_name, tag_value] : data.get_tags()) {
                metric.add_attribute(tag_name, tag_value);
            }
            otel_metrics.push_back(std::move(metric));
        }
        return common::Result<std::vector<otel_metric_data>>::ok(std::move(otel_metrics));
    }
References kcenon::monitoring::monitoring_data::get_metrics(), kcenon::monitoring::monitoring_data::get_tags(), kcenon::monitoring::monitoring_data::get_timestamp(), kcenon::monitoring::metric::name, kcenon::monitoring::ok, resource_, kcenon::monitoring::metric::timestamp, and kcenon::monitoring::metric::value.
Referenced by kcenon::monitoring::opentelemetry_compatibility_layer::export_metrics(), and TEST_F().
Member Data Documentation
resource_
otel_resource kcenon::monitoring::opentelemetry_metrics_adapter::resource_ private
Definition at line 340 of file opentelemetry_adapter.h.
Referenced by convert_metrics(), and convert_monitoring_data().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/exporters/opentelemetry_adapter.h