Monitoring System: examples/multi_service_tracing_example.cpp File Reference
multi_service_tracing_example.cpp File Reference
Demonstrates distributed tracing across multiple services.
#include <iostream>
#include <memory>
#include <string>
#include <chrono>
#include <thread>
#include <iomanip>
#include "kcenon/monitoring/tracing/distributed_tracer.h"
Classes
class ApiGatewayService
Simulated API Gateway service.
class AuthService
Simulated Authentication service.
class UserService
Simulated User service.
class CacheService
Simulated Cache service.
Functions
void display_span (const trace_span &span, int depth)
Display single span.
void display_children (const std::vector< trace_span > &spans, const std::string &parent_id, int depth)
Display children recursively.
void display_trace_tree (const std::vector< trace_span > &spans)
Display trace tree structure.
void simulate_multi_service_request ()
Simulate complete multi-service request flow.
int main ()
Detailed Description
Demonstrates distributed tracing across multiple services.
This example shows how to:
Simulate multi-service architecture
Propagate trace context between services
Correlate traces across service boundaries
Create parent-child span relationships
Propagate baggage for cross-cutting data
Visualize trace export patterns
Definition in file multi_service_tracing_example.cpp.
Function Documentation
display_children()
void display_children (const std::vector< trace_span > & spans, const std::string & parent_id, int depth)
Display children recursively.
Definition at line 374 of file multi_service_tracing_example.cpp.
{
    for (const auto& span : spans) {
        if (span.parent_span_id == parent_id) {
            display_span(span, depth);
            display_children(spans, span.span_id, depth + 1);
        }
    }
}
References display_children(), and display_span().
Referenced by display_children(), and display_trace_tree().
display_span()
void display_span (const trace_span & span, int depth)
Display single span.
Definition at line 347 of file multi_service_tracing_example.cpp.
{
    std::string indent(depth * 2, ' ');
    std::string prefix = depth == 0 ? "┌─" : "├─";
    std::cout << indent << prefix << " [" << span.service_name << "] "
              << span.operation_name << std::endl;
    std::cout << indent << "   Span ID: " << span.span_id << std::endl;
    std::cout << indent << "   Duration: " << span.duration.count() << "µs" << std::endl;
    if (!span.tags.empty()) {
        std::cout << indent << "   Tags:";
        int count = 0;
        for (const auto& [key, value] : span.tags) {
            if (count++ < 3) {  // Show first 3 tags
                std::cout << " " << key << "=" << value;
            }
        }
        if (span.tags.size() > 3) {
            std::cout << " +" << (span.tags.size() - 3) << " more";
        }
        std::cout << std::endl;
    }
}
References kcenon::monitoring::trace_span::duration, kcenon::monitoring::trace_span::operation_name, kcenon::monitoring::trace_span::service_name, kcenon::monitoring::trace_span::span_id, and kcenon::monitoring::trace_span::tags.
Referenced by display_children(), and display_trace_tree().
display_trace_tree()
void display_trace_tree (const std::vector< trace_span > & spans)
Display trace tree structure.
Definition at line 315 of file multi_service_tracing_example.cpp.
{
    std::cout << "\n=== Trace Tree Structure ===" << std::endl;
    // Find root span
    const trace_span* root = nullptr;
    for (const auto& span : spans) {
        if (span.parent_span_id.empty()) {
            root = &span;
            break;
        }
    }
    if (!root) {
        std::cout << "No root span found" << std::endl;
        return;
    }
    std::cout << "\nTrace ID: " << root->trace_id << "\n" << std::endl;
    // Display root
    display_span(*root, 0);
    // Display children
    display_children(spans, root->span_id, 1);
    std::cout << "\n=== Total Spans: " << spans.size() << " ===" << std::endl;
    std::cout << "Total trace duration: " << root->duration.count() << "µs" << std::endl;
}
References display_children(), display_span(), kcenon::monitoring::trace_span::duration, kcenon::monitoring::trace_span::span_id, and kcenon::monitoring::trace_span::trace_id.
Referenced by simulate_multi_service_request().
main()
int main ()
Definition at line 444 of file multi_service_tracing_example.cpp.
           {
    std::cout << "Multi-Service Distributed Tracing Example\n" << std::endl;
    simulate_multi_service_request();
    std::cout << "\n" << std::string(60, '=') << std::endl;
    std::cout << "\nKey Concepts Demonstrated:" << std::endl;
    std::cout << "1. Trace context propagation across services" << std::endl;
    std::cout << "2. Parent-child span relationships" << std::endl;
    std::cout << "3. Baggage propagation for cross-cutting data" << std::endl;
    std::cout << "4. W3C Trace Context standard" << std::endl;
    std::cout << "5. Service-specific span tags and metadata" << std::endl;
    return 0;
}
References simulate_multi_service_request().
simulate_multi_service_request()
void simulate_multi_service_request ()
Simulate complete multi-service request flow.
Definition at line 388 of file multi_service_tracing_example.cpp.
{
    std::cout << "=== Multi-Service Distributed Tracing Example ===" << std::endl;
    std::vector<trace_span> collected_spans;
    // Step 1: API Gateway receives request
    std::cout << "\n--- Step 1: API Gateway ---" << std::endl;
    ApiGatewayService gateway;
    auto gateway_span = gateway.handle_request("/api/user/profile", "GET");
    auto gateway_ctx = gateway.create_context(gateway_span);
    // Step 2: Check cache (parallel to auth)
    std::cout << "\n--- Step 2: Cache Lookup ---" << std::endl;
    CacheService cache;
    auto cache_span = cache.cache_lookup(gateway_ctx, "user:user-12345");
    collected_spans.push_back(cache_span);
    // Step 3: Authenticate request
    std::cout << "\n--- Step 3: Authentication ---" << std::endl;
    AuthService auth;
    auto auth_span = auth.verify_token(gateway_ctx, "eyJhbGc...");
    collected_spans.push_back(auth_span);
    // Create context for user service call
    trace_context user_ctx;
    user_ctx.trace_id = gateway_ctx.trace_id;
    user_ctx.span_id = gateway_span.span_id;
    user_ctx.baggage = gateway_ctx.baggage;
    // Step 4: Fetch user profile (after cache miss)
    std::cout << "\n--- Step 4: User Profile Service ---" << std::endl;
    UserService user_service;
    auto user_span = user_service.get_user_profile(user_ctx, "user-12345");
    collected_spans.push_back(user_span);
    // Complete gateway span
    std::this_thread::sleep_for(5ms);
    gateway_span.end_time = std::chrono::system_clock::now();
    gateway_span.calculate_duration();
    gateway_span.status = trace_span::status_code::ok;
    gateway_span.tags["http.status_code"] = "200";
    collected_spans.insert(collected_spans.begin(), gateway_span);
    // Display complete trace
    display_trace_tree(collected_spans);
    // Show baggage propagation
    std::cout << "\n=== Baggage Propagation ===" << std::endl;
    std::cout << "Baggage items propagated across all services:" << std::endl;
    for (const auto& [key, value] : gateway_span.baggage) {
        std::cout << "   " << key << " = " << value << std::endl;
    }
    std::cout << "\n=== Example completed successfully ===" << std::endl;
}
References kcenon::monitoring::trace_context::baggage, CacheService::cache_lookup(), ApiGatewayService::create_context(), display_trace_tree(), UserService::get_user_profile(), ApiGatewayService::handle_request(), kcenon::monitoring::trace_context::span_id, kcenon::monitoring::trace_context::trace_id, and AuthService::verify_token().
Referenced by main().