Monitoring System: performance_monitor_facade Class Reference
performance_monitor_facade Class Reference
Public Member Functions
performance_monitor_facade (const std::string &name)
metrics_collector_interface & as_metrics_collector ()
imonitor_interface & as_imonitor ()
performance_monitor_impl & impl ()
Private Attributes
std::shared_ptr< performance_monitor_impl > impl_
std::shared_ptr< metrics_collector_adapter > metrics_adapter_
std::shared_ptr< imonitor_adapter > imonitor_adapter_
Detailed Description
Definition at line 192 of file facade_adapter_poc.cpp.
Constructor & Destructor Documentation
performance_monitor_facade()
performance_monitor_facade::performance_monitor_facade (const std::string & name) inline explicit
Definition at line 194 of file facade_adapter_poc.cpp.
{
        // Create core implementation
        impl_ = std::make_shared<performance_monitor_impl>(name);
        // Create adapters
        metrics_adapter_ = std::make_shared<metrics_collector_adapter>(impl_);
        imonitor_adapter_ = std::make_shared<imonitor_adapter>(impl_);
    }
References imonitor_adapter_, impl_, and metrics_adapter_.
Member Function Documentation
as_imonitor()
imonitor_interface & performance_monitor_facade::as_imonitor () inline
Definition at line 208 of file facade_adapter_poc.cpp.
{
        return *imonitor_adapter_;
    }
References imonitor_adapter_.
Referenced by benchmark_overhead(), and demonstrate_new_approach().
as_metrics_collector()
metrics_collector_interface & performance_monitor_facade::as_metrics_collector () inline
Definition at line 204 of file facade_adapter_poc.cpp.
{
        return *metrics_adapter_;
    }
References metrics_adapter_.
Referenced by demonstrate_new_approach().
impl()
performance_monitor_impl & performance_monitor_facade::impl () inline
Definition at line 213 of file facade_adapter_poc.cpp.
{
        return *impl_;
    }
References impl_.
Referenced by demonstrate_new_approach().
Member Data Documentation
imonitor_adapter_
std::shared_ptr<imonitor_adapter> performance_monitor_facade::imonitor_adapter_ private
Definition at line 220 of file facade_adapter_poc.cpp.
Referenced by as_imonitor(), and performance_monitor_facade().
impl_
std::shared_ptr<performance_monitor_impl> performance_monitor_facade::impl_ private
Definition at line 218 of file facade_adapter_poc.cpp.
Referenced by impl(), and performance_monitor_facade().
metrics_adapter_
std::shared_ptr<metrics_collector_adapter> performance_monitor_facade::metrics_adapter_ private
Definition at line 219 of file facade_adapter_poc.cpp.
Referenced by as_metrics_collector(), and performance_monitor_facade().
The documentation for this class was generated from the following file:
examples/facade_adapter_poc.cpp