Monitoring System: AuthService Class Reference
AuthService Class Reference
Simulated Authentication service.
Public Member Functions
trace_span verify_token (const trace_context &parent_ctx, const std::string &)
Verify user authentication.
Static Private Member Functions
static std::string generate_span_id ()
Private Attributes
std::string service_name_ = "auth_service"
Detailed Description
Simulated Authentication service.
Definition at line 140 of file multi_service_tracing_example.cpp.
Member Function Documentation
generate_span_id()
static std::string AuthService::generate_span_id () inline static private
Definition at line 187 of file multi_service_tracing_example.cpp.
{
        std::string id;
        for (int i = 0; i < 16; ++i) {
            id += "0123456789abcdef"[rand() % 16];
        }
        return id;
    }
Referenced by verify_token().
verify_token()
trace_span AuthService::verify_token (const trace_context & parent_ctx, const std::string &) inline
Verify user authentication.
Definition at line 148 of file multi_service_tracing_example.cpp.
{
        std::cout << "\n[" << service_name_ << "] Verifying authentication token" << std::endl;
        std::cout << "   Received context: " << parent_ctx.to_w3c_traceparent() << std::endl;
        // Create child span
        trace_span span;
        span.trace_id = parent_ctx.trace_id;         // Same trace ID
        span.span_id = generate_span_id();           // New span ID
        span.parent_span_id = parent_ctx.span_id;    // Link to parent
        span.operation_name = "verify_token";
        span.service_name = service_name_;
        span.start_time = std::chrono::system_clock::now();
        // Inherit baggage from parent
        span.baggage = parent_ctx.baggage;
        // Add service-specific tags
        span.tags["auth.token_type"] = "bearer";
        span.tags["auth.method"] = "jwt";
        std::cout << "   → Created child span: " << span.span_id << std::endl;
        std::cout << "     Parent span: " << span.parent_span_id << std::endl;
        std::cout << "     Inherited baggage: user.id=" << span.baggage["user.id"] << std::endl;
        // Simulate authentication work
        std::this_thread::sleep_for(5ms);
        span.end_time = std::chrono::system_clock::now();
        span.calculate_duration();
        span.status = trace_span::status_code::ok;
        span.tags["auth.result"] = "success";
        std::cout << "   ✓ Authentication successful (duration: "
                  << span.duration.count() << "µs)" << std::endl;
        return span;
    }
References kcenon::monitoring::trace_span::baggage, kcenon::monitoring::trace_context::baggage, kcenon::monitoring::trace_span::calculate_duration(), kcenon::monitoring::trace_span::duration, kcenon::monitoring::trace_span::end_time, generate_span_id(), kcenon::monitoring::trace_span::operation_name, kcenon::monitoring::trace_span::parent_span_id, kcenon::monitoring::trace_span::service_name, service_name_, kcenon::monitoring::trace_span::span_id, kcenon::monitoring::trace_context::span_id, kcenon::monitoring::trace_span::start_time, kcenon::monitoring::trace_span::status, kcenon::monitoring::trace_span::tags, kcenon::monitoring::trace_context::to_w3c_traceparent(), kcenon::monitoring::trace_span::trace_id, and kcenon::monitoring::trace_context::trace_id.
Referenced by simulate_multi_service_request().
Member Data Documentation
service_name_
std::string AuthService::service_name_ = "auth_service" private
Definition at line 142 of file multi_service_tracing_example.cpp.
Referenced by verify_token().
The documentation for this class was generated from the following file:
examples/multi_service_tracing_example.cpp