Monitoring System: kcenon::monitoring::performance_monitor Class Reference
kcenon::monitoring::performance_monitor Class Reference
Performance monitor combining profiling and system monitoring.
#include <performance_monitor.h>
Classes
struct metric_data
struct thresholds
Public Member Functions
performance_monitor (const std::string &name="performance_monitor")
std::string get_name () const override
Get collector name.
bool is_enabled () const override
Check if collector is enabled.
common::VoidResult set_enabled (bool enable) override
Enable or disable the collector.
common::VoidResult initialize () override
Initialize the collector.
common::VoidResult cleanup () override
Cleanup collector resources.
common::Result< metrics_snapshot > collect () override
Collect metrics.
scoped_timer time_operation (const std::string &operation_name)
Create a scoped timer for an operation.
performance_profiler & get_profiler ()
Get performance profiler.
const performance_profiler & get_profiler () const
system_monitor & get_system_monitor ()
Get system monitor.
const system_monitor & get_system_monitor () const
void set_cpu_threshold (double threshold)
Set performance thresholds.
void set_memory_threshold (double threshold)
void set_latency_threshold (std::chrono::milliseconds threshold)
thresholds get_thresholds () const
Get current threshold values.
common::Result< bool > check_thresholds () const
Check if any thresholds are exceeded.
void reset ()
Reset all performance profiler samples and system metrics.
common::VoidResult record_counter (const std::string &name, double value, const tag_map &tags={})
common::VoidResult record_gauge (const std::string &name, double value, const tag_map &tags={})
common::VoidResult record_histogram (const std::string &name, double value, const tag_map &tags={})
std::vector< tagged_metric > get_all_tagged_metrics () const
Get all recorded tagged metrics.
void clear_all_metrics ()
Clear all recorded tagged metrics.
Public Member Functions inherited from kcenon::monitoring::metrics_collector
virtual ~metrics_collector ()=default
Private Member Functions
common::VoidResult record_metric_internal (const std::string &name, double value, recorded_metric_type type, const tag_map &tags)
Internal method to record a metric with type and tags.
Static Private Member Functions
static std::string make_metric_key (const std::string &name, const tag_map &tags)
Generate a unique key from metric name and tags.
Private Attributes
performance_profiler profiler_
system_monitor system_monitor_
std::string name_
bool enabled_ {true}
struct kcenon::monitoring::performance_monitor::thresholds thresholds_
std::mutex thresholds_mutex_
std::unordered_map< std::string, std::unique_ptr< metric_data > > tagged_metrics_
std::shared_mutex metrics_mutex_
Detailed Description
Performance monitor combining profiling and system monitoring.
Implements kcenon::monitoring::metrics_collector for internal monitoring. For interoperability with common::interfaces::IMonitor, use performance_monitor_adapter.
Thread Safety:
Thread-safe. All public methods can be called concurrently.
profiler_ is thread-safe (uses internal synchronization)
system_monitor_ is thread-safe (uses internal synchronization)
thresholds_ protected by thresholds_mutex_
See also
performance_monitor_adapter For bridging to common::interfaces::IMonitor
Definition at line 375 of file performance_monitor.h.
Constructor & Destructor Documentation
performance_monitor()
kcenon::monitoring::performance_monitor::performance_monitor (const std::string & name = "performance_monitor") inline explicit
Definition at line 403 of file performance_monitor.h.
        : name_(name) {}
Member Function Documentation
check_thresholds()
common::Result< bool > kcenon::monitoring::performance_monitor::check_thresholds () const
Check if any thresholds are exceeded.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
cleanup()
common::VoidResult kcenon::monitoring::performance_monitor::cleanup () inline override virtual
Cleanup collector resources.
Returns
Result indicating success or cleanup error
Implements kcenon::monitoring::metrics_collector.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 424 of file performance_monitor.h.
{
        auto result = system_monitor_.stop_monitoring();
        if (result.is_err()) {
            return common::VoidResult::err(result.error());
        }
        return common::ok();
    }
References kcenon::monitoring::system_monitor::stop_monitoring().
Referenced by main(), and PerformanceMonitoringTest::TearDown().
clear_all_metrics()
void kcenon::monitoring::performance_monitor::clear_all_metrics ()
Clear all recorded tagged metrics.
Thread Safety:
Thread-safe, uses shared_mutex for synchronization
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
collect()
common::Result< metrics_snapshot > kcenon::monitoring::performance_monitor::collect () override virtual
Collect metrics.
Returns
Result containing collected metrics or error
Implements kcenon::monitoring::metrics_collector.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Referenced by main().
get_all_tagged_metrics()
std::vector< tagged_metric > kcenon::monitoring::performance_monitor::get_all_tagged_metrics () const
Get all recorded tagged metrics.
Returns
Vector of tagged_metric containing all recorded metrics with their tags
Thread Safety:
Thread-safe, uses shared_mutex for synchronization
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
get_name()
std::string kcenon::monitoring::performance_monitor::get_name () const inline override virtual
Get collector name.
Returns
Collector identifier
Implements kcenon::monitoring::metrics_collector.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 407 of file performance_monitor.h.
{ return name_; }
References name_.
get_profiler() [1/2]
performance_profiler & kcenon::monitoring::performance_monitor::get_profiler () inline
Get performance profiler.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 444 of file performance_monitor.h.
{ return profiler_; }
get_profiler() [2/2]
const performance_profiler & kcenon::monitoring::performance_monitor::get_profiler () const inline
Definition at line 445 of file performance_monitor.h.
{ return profiler_; }
get_system_monitor() [1/2]
system_monitor & kcenon::monitoring::performance_monitor::get_system_monitor () inline
Get system monitor.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 450 of file performance_monitor.h.
{ return system_monitor_; }
Referenced by main().
get_system_monitor() [2/2]
const system_monitor & kcenon::monitoring::performance_monitor::get_system_monitor () const inline
Definition at line 451 of file performance_monitor.h.
{ return system_monitor_; }
get_thresholds()
thresholds kcenon::monitoring::performance_monitor::get_thresholds () const inline
Get current threshold values.
Thread Safety:
Thread-safe. Uses mutex for synchronization.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 476 of file performance_monitor.h.
{
        std::lock_guard<std::mutex> lock(thresholds_mutex_);
        return thresholds_;
    }
initialize()
common::VoidResult kcenon::monitoring::performance_monitor::initialize () inline override virtual
Initialize the collector.
Returns
Result indicating success or initialization error
Implements kcenon::monitoring::metrics_collector.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 416 of file performance_monitor.h.
{
        auto result = system_monitor_.start_monitoring();
        if (result.is_err()) {
            return common::VoidResult::err(result.error());
        }
        return common::ok();
    }
References kcenon::monitoring::system_monitor::start_monitoring().
Referenced by main().
is_enabled()
bool kcenon::monitoring::performance_monitor::is_enabled () const inline override virtual
Check if collector is enabled.
Returns
true if collector is active
Implements kcenon::monitoring::metrics_collector.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 408 of file performance_monitor.h.
{ return enabled_; }
make_metric_key()
static std::string kcenon::monitoring::performance_monitor::make_metric_key (const std::string & name, const tag_map & tags) static private
Generate a unique key from metric name and tags.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
record_counter()
common::VoidResult kcenon::monitoring::performance_monitor::record_counter (const std::string & name, double value, const tag_map & tags = {})
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
record_gauge()
common::VoidResult kcenon::monitoring::performance_monitor::record_gauge (const std::string & name, double value, const tag_map & tags = {})
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
record_histogram()
common::VoidResult kcenon::monitoring::performance_monitor::record_histogram (const std::string & name, double value, const tag_map & tags = {})
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
record_metric_internal()
common::VoidResult kcenon::monitoring::performance_monitor::record_metric_internal (const std::string & name, double value, recorded_metric_type type, const tag_map & tags) private
Internal method to record a metric with type and tags.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
reset()
void kcenon::monitoring::performance_monitor::reset () inline
Reset all performance profiler samples and system metrics.
Note
For IMonitor interface compatibility, use performance_monitor_adapter
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 492 of file performance_monitor.h.
                 {
        profiler_.clear_all_samples();
        clear_all_metrics();
    }
References kcenon::monitoring::performance_profiler::clear_all_samples().
set_cpu_threshold()
void kcenon::monitoring::performance_monitor::set_cpu_threshold (double threshold) inline
Set performance thresholds.
Thread Safety:
Thread-safe. Uses mutex for synchronization.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 457 of file performance_monitor.h.
{
        std::lock_guard<std::mutex> lock(thresholds_mutex_);
        thresholds_.cpu_threshold = threshold;
    }
set_enabled()
common::VoidResult kcenon::monitoring::performance_monitor::set_enabled (bool enable) inline override virtual
Enable or disable the collector.
Parameters
enable true to enable, false to disable
Returns
Result indicating success or error
Implements kcenon::monitoring::metrics_collector.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 410 of file performance_monitor.h.
{
        enabled_ = enable;
        profiler_.set_enabled(enable);
        return common::ok();
    }
References kcenon::monitoring::performance_profiler::set_enabled().
Referenced by PerformanceMonitoringTest::SetUp().
set_latency_threshold()
void kcenon::monitoring::performance_monitor::set_latency_threshold (std::chrono::milliseconds threshold) inline
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 467 of file performance_monitor.h.
{
        std::lock_guard<std::mutex> lock(thresholds_mutex_);
        thresholds_.latency_threshold = threshold;
    }
set_memory_threshold()
void kcenon::monitoring::performance_monitor::set_memory_threshold (double threshold) inline
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 462 of file performance_monitor.h.
{
        std::lock_guard<std::mutex> lock(thresholds_mutex_);
        thresholds_.memory_threshold = threshold;
    }
time_operation()
scoped_timer kcenon::monitoring::performance_monitor::time_operation (const std::string & operation_name) inline
Create a scoped timer for an operation.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 437 of file performance_monitor.h.
{
        return scoped_timer(&profiler_, operation_name);
    }
Referenced by main().
Member Data Documentation
enabled_
bool kcenon::monitoring::performance_monitor::enabled_ {true} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 380 of file performance_monitor.h.
{true};
metrics_mutex_
std::shared_mutex kcenon::monitoring::performance_monitor::metrics_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 400 of file performance_monitor.h.
name_
std::string kcenon::monitoring::performance_monitor::name_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 379 of file performance_monitor.h.
profiler_
performance_profiler kcenon::monitoring::performance_monitor::profiler_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 377 of file performance_monitor.h.
system_monitor_
system_monitor kcenon::monitoring::performance_monitor::system_monitor_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 378 of file performance_monitor.h.
tagged_metrics_
std::unordered_map<std::string, std::unique_ptr<metric_data> > kcenon::monitoring::performance_monitor::tagged_metrics_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 399 of file performance_monitor.h.
thresholds_
struct kcenon::monitoring::performance_monitor::thresholds kcenon::monitoring::performance_monitor::thresholds_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
thresholds_mutex_
std::mutex kcenon::monitoring::performance_monitor::thresholds_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 388 of file performance_monitor.h.
The documentation for this class was generated from the following file:
include/kcenon/monitoring/core/performance_monitor.h