Monitoring System: kcenon::monitoring::logger_to_monitoring_adapter Class Reference
kcenon::monitoring::logger_to_monitoring_adapter Class Reference
Logger system adapter using dependency injection (Phase 2.3.3)
#include <logger_to_monitoring_adapter.h>
Public Member Functions
logger_to_monitoring_adapter (std::shared_ptr< event_bus > bus, std::shared_ptr< common::interfaces::ILogger > logger=nullptr)
Constructor with optional logger injection.
bool is_logger_system_available () const
Check if logger is available.
void set_logger (std::shared_ptr< common::interfaces::ILogger > logger)
Set or replace the logger instance.
std::shared_ptr< common::interfaces::ILogger > get_logger () const
Get the current logger instance.
common::Result< std::vector< metric > > collect_metrics ()
Collect metrics from logger if available (Phase 2.3.3)
common::VoidResult register_logger (const std::string &)
Register a logger instance by name.
double get_current_log_rate () const
Get current log rate (if logger supports metrics)
Private Attributes
std::shared_ptr< event_bus > bus_
std::shared_ptr< common::interfaces::ILogger > logger_
Detailed Description
Logger system adapter using dependency injection (Phase 2.3.3)
This adapter uses common::interfaces::ILogger instead of concrete logger_system classes, removing compile-time dependency on logger_system. Works with any ILogger implementation through dependency injection.
Definition at line 42 of file logger_to_monitoring_adapter.h.
Constructor & Destructor Documentation
logger_to_monitoring_adapter()
kcenon::monitoring::logger_to_monitoring_adapter::logger_to_monitoring_adapter (std::shared_ptr< event_bus > bus, std::shared_ptr< common::interfaces::ILogger > logger = nullptr) inline explicit
Constructor with optional logger injection.
Parameters
bus Event bus for monitoring events
logger Optional logger instance (any ILogger implementation)
Definition at line 49 of file logger_to_monitoring_adapter.h.
      : bus_(std::move(bus)), logger_(std::move(logger)) {}
Member Function Documentation
collect_metrics()
common::Result< std::vector< metric > > kcenon::monitoring::logger_to_monitoring_adapter::collect_metrics () inline
Collect metrics from logger if available (Phase 2.3.3)
Definition at line 79 of file logger_to_monitoring_adapter.h.
{
        std::vector<metric> out;
        if (logger_) {
            // If logger implements IMonitorable, collect its metrics
            auto monitorable = std::dynamic_pointer_cast<common::interfaces::IMonitorable>(logger_);
            if (monitorable) {
                auto metrics_result = monitorable->get_monitoring_data();
                if (metrics_result.is_ok()) {
                    const auto& snapshot = metrics_result.value();
                    // Convert to monitoring_system metric format
                    for (const auto& m : snapshot.metrics) {
                        metric converted;
                        converted.name = m.name;
                        converted.value = m.value;
                        converted.timestamp = m.timestamp;
                        out.push_back(converted);
                    }
                }
            }
        }
        return common::ok(std::move(out));
    }
References logger_, kcenon::monitoring::metric::name, kcenon::monitoring::metric::timestamp, and kcenon::monitoring::metric::value.
Referenced by TEST_F().
get_current_log_rate()
double kcenon::monitoring::logger_to_monitoring_adapter::get_current_log_rate () const inline
Get current log rate (if logger supports metrics)
Definition at line 113 of file logger_to_monitoring_adapter.h.
{
        if (logger_) {
            auto monitorable = std::dynamic_pointer_cast<common::interfaces::IMonitorable>(logger_);
            if (monitorable) {
                auto metrics_result = monitorable->get_monitoring_data();
                if (metrics_result.is_ok()) {
                    const auto& snapshot = metrics_result.value();
                    for (const auto& m : snapshot.metrics) {
                        if (m.name.find("messages_logged") != std::string::npos ||
                            m.name.find("log_rate") != std::string::npos) {
                            return m.value;
                        }
                    }
                }
            }
        }
        return 0.0;
    }
References logger_.
Referenced by TEST_F().
get_logger()
std::shared_ptr< common::interfaces::ILogger > kcenon::monitoring::logger_to_monitoring_adapter::get_logger () const inline
Get the current logger instance.
Definition at line 72 of file logger_to_monitoring_adapter.h.
{
        return logger_;
    }
References logger_.
is_logger_system_available()
bool kcenon::monitoring::logger_to_monitoring_adapter::is_logger_system_available () const inline
Check if logger is available.
Definition at line 57 of file logger_to_monitoring_adapter.h.
{
        return logger_ != nullptr;
    }
References logger_.
Referenced by main(), and TEST_F().
register_logger()
common::VoidResult kcenon::monitoring::logger_to_monitoring_adapter::register_logger (const std::string &) inline
Register a logger instance by name.
Definition at line 105 of file logger_to_monitoring_adapter.h.
{
        // Logger is now provided via DI, not registered by name
        return common::ok();
    }
Referenced by TEST_F().
set_logger()
void kcenon::monitoring::logger_to_monitoring_adapter::set_logger (std::shared_ptr< common::interfaces::ILogger > logger) inline
Set or replace the logger instance.
Parameters
logger New logger instance
Definition at line 65 of file logger_to_monitoring_adapter.h.
{
        logger_ = std::move(logger);
    }
References logger_.
Member Data Documentation
bus_
std::shared_ptr<event_bus> kcenon::monitoring::logger_to_monitoring_adapter::bus_ private
Definition at line 133 of file logger_to_monitoring_adapter.h.
logger_
std::shared_ptr<common::interfaces::ILogger> kcenon::monitoring::logger_to_monitoring_adapter::logger_ private
Definition at line 134 of file logger_to_monitoring_adapter.h.
Referenced by collect_metrics(), get_current_log_rate(), get_logger(), is_logger_system_available(), and set_logger().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/adapters/logger_to_monitoring_adapter.h