Monitoring System: kcenon::monitoring::alert_manager Class Reference
kcenon::monitoring::alert_manager Class Reference
Central coordinator for the alert pipeline.
#include <alert_manager.h>
Public Types
using metric_provider_func = std::function< std::optional< double >(const std::string &)>
Public Member Functions
alert_manager ()
Default constructor.
alert_manager (const alert_manager_config &config)
Construct with configuration.
~alert_manager ()
Destructor.
alert_manager (const alert_manager &)=delete
alert_manager & operator= (const alert_manager &)=delete
alert_manager (alert_manager &&)=delete
alert_manager & operator= (alert_manager &&)=delete
common::VoidResult start ()
Start the alert manager.
common::VoidResult stop ()
Stop the alert manager.
bool is_running () const
Check if manager is running.
common::VoidResult add_rule (std::shared_ptr< alert_rule > rule)
Add an alert rule.
common::VoidResult remove_rule (const std::string &rule_name)
Remove an alert rule.
std::shared_ptr< alert_rule > get_rule (const std::string &rule_name) const
Get a rule by name.
std::vector< std::shared_ptr< alert_rule > > get_rules () const
Get all rules.
common::VoidResult add_rule_group (std::shared_ptr< alert_rule_group > group)
Add a rule group.
common::VoidResult process_metric (const std::string &metric_name, double value)
Process a metric value.
common::VoidResult process_metrics (const std::unordered_map< std::string, double > &metrics)
Process a batch of metrics.
std::vector< alert > get_active_alerts () const
Get all active alerts.
std::optional< alert > get_alert (const std::string &fingerprint) const
Get alert by fingerprint.
common::VoidResult resolve_alert (const std::string &fingerprint)
Resolve an alert manually.
common::Result< uint64_t > create_silence (const alert_silence &silence)
Create a silence.
common::VoidResult delete_silence (uint64_t silence_id)
Delete a silence.
std::vector< alert_silence > get_silences () const
Get all active silences.
bool is_silenced (const alert &a) const
Check if an alert is silenced.
common::VoidResult add_notifier (std::shared_ptr< alert_notifier > notifier)
Add a notifier.
common::VoidResult remove_notifier (const std::string &notifier_name)
Remove a notifier.
std::vector< std::shared_ptr< alert_notifier > > get_notifiers () const
Get all notifiers.
void set_metric_provider (metric_provider_func provider)
Set the metric provider function.
void set_event_bus (std::shared_ptr< interface_event_bus > event_bus)
Set event bus for publishing alert events.
alert_manager_metrics get_metrics () const
Get manager metrics.
const alert_manager_config & config () const
Get configuration.
Private Member Functions
void evaluation_loop ()
Main evaluation loop.
void evaluate_rule (const std::shared_ptr< alert_rule > &rule, double value)
Evaluate a single rule.
void update_alert_state (const std::string &fingerprint, bool condition_met, double value, const std::shared_ptr< alert_rule > &rule)
Update alert state.
void send_notifications (const alert &a)
Send notifications for an alert.
void cleanup_silences ()
Clean up expired silences.
void cleanup_resolved_alerts ()
Clean up resolved alerts.
Private Attributes
alert_manager_config config_
std::mutex rules_mutex_
std::unordered_map< std::string, std::shared_ptr< alert_rule > > rules_
std::vector< std::shared_ptr< alert_rule_group > > rule_groups_
std::mutex alerts_mutex_
std::unordered_map< std::string, alert > alerts_
std::mutex silences_mutex_
std::unordered_map< uint64_t, alert_silence > silences_
std::mutex notifiers_mutex_
std::vector< std::shared_ptr< alert_notifier > > notifiers_
std::mutex provider_mutex_
metric_provider_func metric_provider_
std::shared_ptr< interface_event_bus > event_bus_
alert_manager_metrics metrics_
std::atomic< bool > running_ {false}
std::thread evaluation_thread_
std::condition_variable cv_
std::mutex cv_mutex_
std::unordered_map< std::string, std::chrono::steady_clock::time_point > last_notification_times_
Detailed Description
Central coordinator for the alert pipeline.
The alert manager is responsible for:
Managing alert rules and their lifecycle
Evaluating rules against incoming metrics
Managing alert state transitions
Routing notifications to configured notifiers
Handling alert silencing and grouping
Thread Safety:
This class is thread-safe. All public methods can be called from multiple threads simultaneously.
Definition at line 147 of file alert_manager.h.
Member Typedef Documentation
metric_provider_func
using kcenon::monitoring::alert_manager::metric_provider_func = std::function<std::optional<double>(const std::string&)>
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 149 of file alert_manager.h.
Constructor & Destructor Documentation
alert_manager() [1/4]
kcenon::monitoring::alert_manager::alert_manager ()
Default constructor.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
alert_manager() [2/4]
kcenon::monitoring::alert_manager::alert_manager (const alert_manager_config & config) explicit
Construct with configuration.
Parameters
config Manager configuration
~alert_manager()
kcenon::monitoring::alert_manager::~alert_manager ()
Destructor.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
alert_manager() [3/4]
kcenon::monitoring::alert_manager::alert_manager (const alert_manager &) delete
alert_manager() [4/4]
kcenon::monitoring::alert_manager::alert_manager (alert_manager &&) delete
Member Function Documentation
add_notifier()
common::VoidResult kcenon::monitoring::alert_manager::add_notifier (std::shared_ptr< alert_notifier > notifier)
Add a notifier.
Parameters
notifier Notifier to add
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main().
add_rule()
common::VoidResult kcenon::monitoring::alert_manager::add_rule (std::shared_ptr< alert_rule > rule)
Add an alert rule.
Parameters
rule Rule to add
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), AlertManagerProcessingTest::SetUp(), and TEST().
add_rule_group()
common::VoidResult kcenon::monitoring::alert_manager::add_rule_group (std::shared_ptr< alert_rule_group > group)
Add a rule group.
Parameters
group Rule group to add
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), and TEST().
cleanup_resolved_alerts()
void kcenon::monitoring::alert_manager::cleanup_resolved_alerts () private
Clean up resolved alerts.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
cleanup_silences()
void kcenon::monitoring::alert_manager::cleanup_silences () private
Clean up expired silences.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
config()
const alert_manager_config & kcenon::monitoring::alert_manager::config () const
Get configuration.
Returns
Current configuration
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by TEST(), TEST(), and TEST_F().
create_silence()
common::Result< uint64_t > kcenon::monitoring::alert_manager::create_silence (const alert_silence & silence)
Create a silence.
Parameters
silence Silence configuration
Returns
Result containing silence ID
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
delete_silence()
common::VoidResult kcenon::monitoring::alert_manager::delete_silence (uint64_t silence_id)
Delete a silence.
Parameters
silence_id Silence ID
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
evaluate_rule()
void kcenon::monitoring::alert_manager::evaluate_rule (const std::shared_ptr< alert_rule > & rule, double value) private
Evaluate a single rule.
Parameters
rule Rule to evaluate
value Metric value
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
evaluation_loop()
void kcenon::monitoring::alert_manager::evaluation_loop () private
Main evaluation loop.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
get_active_alerts()
std::vector< alert > kcenon::monitoring::alert_manager::get_active_alerts () const
Get all active alerts.
Returns
Vector of active alerts
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), and print_active_alerts().
get_alert()
std::optional< alert > kcenon::monitoring::alert_manager::get_alert (const std::string & fingerprint) const
Get alert by fingerprint.
Parameters
fingerprint Alert fingerprint
Returns
Alert if found
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
get_metrics()
alert_manager_metrics kcenon::monitoring::alert_manager::get_metrics () const
Get manager metrics.
Returns
Current metrics
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), TEST(), and TEST().
get_notifiers()
std::vector< std::shared_ptr< alert_notifier > > kcenon::monitoring::alert_manager::get_notifiers () const
Get all notifiers.
Returns
Vector of notifiers
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
get_rule()
std::shared_ptr< alert_rule > kcenon::monitoring::alert_manager::get_rule (const std::string & rule_name) const
Get a rule by name.
Parameters
rule_name Name of rule
Returns
Rule if found
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
get_rules()
std::vector< std::shared_ptr< alert_rule > > kcenon::monitoring::alert_manager::get_rules () const
Get all rules.
Returns
Vector of all rules
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main().
get_silences()
std::vector< alert_silence > kcenon::monitoring::alert_manager::get_silences () const
Get all active silences.
Returns
Vector of active silences
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
is_running()
bool kcenon::monitoring::alert_manager::is_running () const
Check if manager is running.
Returns
True if running
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
is_silenced()
bool kcenon::monitoring::alert_manager::is_silenced (const alert & a) const
Check if an alert is silenced.
Parameters
a Alert to check
Returns
True if silenced
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
operator=() [1/2]
alert_manager & kcenon::monitoring::alert_manager::operator= (alert_manager &&) delete
operator=() [2/2]
alert_manager & kcenon::monitoring::alert_manager::operator= (const alert_manager &) delete
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
process_metric()
common::VoidResult kcenon::monitoring::alert_manager::process_metric (const std::string & metric_name, double value)
Process a metric value.
Parameters
metric_name Name of the metric
value Metric value
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), and TEST().
process_metrics()
common::VoidResult kcenon::monitoring::alert_manager::process_metrics (const std::unordered_map< std::string, double > & metrics)
Process a batch of metrics.
Parameters
metrics Map of metric names to values
Returns
Result indicating success or failure
remove_notifier()
common::VoidResult kcenon::monitoring::alert_manager::remove_notifier (const std::string & notifier_name)
Remove a notifier.
Parameters
notifier_name Name of notifier
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
remove_rule()
common::VoidResult kcenon::monitoring::alert_manager::remove_rule (const std::string & rule_name)
Remove an alert rule.
Parameters
rule_name Name of rule to remove
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
resolve_alert()
common::VoidResult kcenon::monitoring::alert_manager::resolve_alert (const std::string & fingerprint)
Resolve an alert manually.
Parameters
fingerprint Alert fingerprint
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by TEST_F().
send_notifications()
void kcenon::monitoring::alert_manager::send_notifications (const alert & a) private
Send notifications for an alert.
Parameters
a Alert to notify about
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
set_event_bus()
void kcenon::monitoring::alert_manager::set_event_bus (std::shared_ptr< interface_event_bus > event_bus)
Set event bus for publishing alert events.
Parameters
event_bus Event bus instance
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by TEST().
set_metric_provider()
void kcenon::monitoring::alert_manager::set_metric_provider (metric_provider_func provider)
Set the metric provider function.
Parameters
provider Function that returns metric values by name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by TEST().
start()
common::VoidResult kcenon::monitoring::alert_manager::start ()
Start the alert manager.
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), TEST_F(), TEST_F(), and TEST_F().
stop()
common::VoidResult kcenon::monitoring::alert_manager::stop ()
Stop the alert manager.
Returns
Result indicating success or failure
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Referenced by main(), TEST_F(), TEST_F(), and TEST_F().
update_alert_state()
void kcenon::monitoring::alert_manager::update_alert_state (const std::string & fingerprint, bool condition_met, double value, const std::shared_ptr< alert_rule > & rule) private
Update alert state.
Parameters
fingerprint Alert fingerprint
condition_met Whether condition is met
value Current metric value
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Member Data Documentation
alerts_
std::unordered_map<std::string, alert> kcenon::monitoring::alert_manager::alerts_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 397 of file alert_manager.h.
alerts_mutex_
std::mutex kcenon::monitoring::alert_manager::alerts_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 396 of file alert_manager.h.
config_
alert_manager_config kcenon::monitoring::alert_manager::config_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 388 of file alert_manager.h.
cv_
std::condition_variable kcenon::monitoring::alert_manager::cv_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 420 of file alert_manager.h.
cv_mutex_
std::mutex kcenon::monitoring::alert_manager::cv_mutex_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 421 of file alert_manager.h.
evaluation_thread_
std::thread kcenon::monitoring::alert_manager::evaluation_thread_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 419 of file alert_manager.h.
event_bus_
std::shared_ptr<interface_event_bus> kcenon::monitoring::alert_manager::event_bus_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 412 of file alert_manager.h.
last_notification_times_
std::unordered_map<std::string, std::chrono::steady_clock::time_point> kcenon::monitoring::alert_manager::last_notification_times_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 424 of file alert_manager.h.
metric_provider_
metric_provider_func kcenon::monitoring::alert_manager::metric_provider_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 409 of file alert_manager.h.
metrics_
alert_manager_metrics kcenon::monitoring::alert_manager::metrics_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 415 of file alert_manager.h.
notifiers_
std::vector<std::shared_ptr<alert_notifier> > kcenon::monitoring::alert_manager::notifiers_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 405 of file alert_manager.h.
notifiers_mutex_
std::mutex kcenon::monitoring::alert_manager::notifiers_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 404 of file alert_manager.h.
provider_mutex_
std::mutex kcenon::monitoring::alert_manager::provider_mutex_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 408 of file alert_manager.h.
rule_groups_
std::vector<std::shared_ptr<alert_rule_group> > kcenon::monitoring::alert_manager::rule_groups_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 393 of file alert_manager.h.
rules_
std::unordered_map<std::string, std::shared_ptr<alert_rule> > kcenon::monitoring::alert_manager::rules_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 392 of file alert_manager.h.
rules_mutex_
std::mutex kcenon::monitoring::alert_manager::rules_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 391 of file alert_manager.h.
running_
std::atomic<bool> kcenon::monitoring::alert_manager::running_ {false} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 418 of file alert_manager.h.
{false};
silences_
std::unordered_map<uint64_t, alert_silence> kcenon::monitoring::alert_manager::silences_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 401 of file alert_manager.h.
silences_mutex_
std::mutex kcenon::monitoring::alert_manager::silences_mutex_ mutable private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_manager.h.
Definition at line 400 of file alert_manager.h.
The documentation for this class was generated from the following file:
include/kcenon/monitoring/alert/alert_manager.h