Monitoring System: kcenon::monitoring::data_consistency_manager Class Reference
kcenon::monitoring::data_consistency_manager Class Reference
Data consistency manager coordinating transaction managers and validators.
#include <data_consistency.h>
Public Member Functions
data_consistency_manager (const std::string &name)
common::VoidResult add_transaction_manager (const std::string &name, const transaction_config &config)
transaction_manager * get_transaction_manager (const std::string &name)
common::VoidResult add_state_validator (const std::string &name, const validation_config &config)
state_validator * get_state_validator (const std::string &name)
common::VoidResult start_all_validators ()
common::VoidResult stop_all_validators ()
common::Result< bool > is_healthy () const
std::unordered_map< std::string, std::string > get_all_metrics () const
Private Attributes
std::string name_
std::mutex mutex_
std::unordered_map< std::string, std::shared_ptr< transaction_manager > > transaction_managers_
std::unordered_map< std::string, std::shared_ptr< state_validator > > state_validators_
Detailed Description
Data consistency manager coordinating transaction managers and validators.
Definition at line 496 of file data_consistency.h.
Constructor & Destructor Documentation
data_consistency_manager()
kcenon::monitoring::data_consistency_manager::data_consistency_manager (const std::string & name) inline explicit
Definition at line 498 of file data_consistency.h.
        : name_(name) {}
Member Function Documentation
add_state_validator()
common::VoidResult kcenon::monitoring::data_consistency_manager::add_state_validator (const std::string & name, const validation_config & config) inline
Definition at line 526 of file data_consistency.h.
{
        std::unique_lock<std::mutex> lock(mutex_);
        if (state_validators_.find(name) != state_validators_.end()) {
            return common::VoidResult::err(common::error_info(
                static_cast<int>(monitoring_error_code::already_exists),
                "State validator '" + name + "' already exists",
                "monitoring_system"));
        }
        state_validators_[name] = std::make_shared<state_validator>(name, config);
        return common::ok();
    }
References kcenon::monitoring::already_exists, mutex_, and state_validators_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
add_transaction_manager()
common::VoidResult kcenon::monitoring::data_consistency_manager::add_transaction_manager (const std::string & name, const transaction_config & config) inline
Definition at line 501 of file data_consistency.h.
{
        std::unique_lock<std::mutex> lock(mutex_);
        if (transaction_managers_.find(name) != transaction_managers_.end()) {
            return common::VoidResult::err(common::error_info(
                static_cast<int>(monitoring_error_code::already_exists),
                "Transaction manager '" + name + "' already exists",
                "monitoring_system"));
        }
        transaction_managers_[name] = std::make_shared<transaction_manager>(name, config);
        return common::ok();
    }
References kcenon::monitoring::already_exists, mutex_, and transaction_managers_.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_all_metrics()
std::unordered_map< std::string, std::string > kcenon::monitoring::data_consistency_manager::get_all_metrics () const inline
Definition at line 576 of file data_consistency.h.
{
        std::unordered_map<std::string, std::string> all_metrics;
        for (const auto& [name, manager] : transaction_managers_) {
            all_metrics[name + "_transactions"] = std::to_string(manager->get_metrics().total_transactions.load());
        }
        for (const auto& [name, validator] : state_validators_) {
            all_metrics[name + "_validation"] = std::to_string(validator->get_metrics().validation_runs.load());
        }
        return all_metrics;
    }
References state_validators_, and transaction_managers_.
Referenced by TEST_F().
get_state_validator()
state_validator * kcenon::monitoring::data_consistency_manager::get_state_validator (const std::string & name) inline
Definition at line 541 of file data_consistency.h.
{
        std::unique_lock<std::mutex> lock(mutex_);
        auto it = state_validators_.find(name);
        if (it == state_validators_.end()) {
            return nullptr;
        }
        return it->second.get();
    }
References mutex_, and state_validators_.
Referenced by TEST_F().
get_transaction_manager()
transaction_manager * kcenon::monitoring::data_consistency_manager::get_transaction_manager (const std::string & name) inline
Definition at line 516 of file data_consistency.h.
{
        std::unique_lock<std::mutex> lock(mutex_);
        auto it = transaction_managers_.find(name);
        if (it == transaction_managers_.end()) {
            return nullptr;
        }
        return it->second.get();
    }
References mutex_, and transaction_managers_.
Referenced by TEST_F().
is_healthy()
common::Result< bool > kcenon::monitoring::data_consistency_manager::is_healthy () const inline
Definition at line 572 of file data_consistency.h.
{
        return common::ok(true);
    }
Referenced by TEST_F().
start_all_validators()
common::VoidResult kcenon::monitoring::data_consistency_manager::start_all_validators () inline
Definition at line 551 of file data_consistency.h.
{
        std::unique_lock<std::mutex> lock(mutex_);
        for (auto& [name, validator] : state_validators_) {
            auto result = validator->start();
            if (!result.is_ok()) {
                return result;
            }
        }
        return common::ok();
    }
References mutex_, and state_validators_.
Referenced by TEST_F().
stop_all_validators()
common::VoidResult kcenon::monitoring::data_consistency_manager::stop_all_validators () inline
Definition at line 563 of file data_consistency.h.
{
        std::unique_lock<std::mutex> lock(mutex_);
        for (auto& [name, validator] : state_validators_) {
            validator->stop();
        }
        return common::ok();
    }
References mutex_, and state_validators_.
Referenced by TEST_F().
Member Data Documentation
mutex_
std::mutex kcenon::monitoring::data_consistency_manager::mutex_ private
Definition at line 592 of file data_consistency.h.
Referenced by add_state_validator(), add_transaction_manager(), get_state_validator(), get_transaction_manager(), start_all_validators(), and stop_all_validators().
name_
std::string kcenon::monitoring::data_consistency_manager::name_ private
Definition at line 591 of file data_consistency.h.
state_validators_
std::unordered_map<std::string, std::shared_ptr<state_validator> > kcenon::monitoring::data_consistency_manager::state_validators_ private
Definition at line 594 of file data_consistency.h.
Referenced by add_state_validator(), get_all_metrics(), get_state_validator(), start_all_validators(), and stop_all_validators().
transaction_managers_
std::unordered_map<std::string, std::shared_ptr<transaction_manager> > kcenon::monitoring::data_consistency_manager::transaction_managers_ private
Definition at line 593 of file data_consistency.h.
Referenced by add_transaction_manager(), get_all_metrics(), and get_transaction_manager().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/reliability/data_consistency.h