Monitoring System: kcenon::monitoring::database_storage_backend Class Reference
kcenon::monitoring::database_storage_backend Class Reference
Database storage backend (stub implementation)
#include <storage_backends.h>
Public Member Functions
database_storage_backend ()
database_storage_backend (const storage_config &config)
common::Result< bool > store (const metrics_snapshot &snapshot) override
common::Result< metrics_snapshot > retrieve (size_t index) override
common::Result< std::vector< metrics_snapshot > > retrieve_range (size_t start, size_t count) override
size_t size () const override
size_t capacity () const override
common::Result< bool > flush () override
common::Result< bool > clear () override
std::unordered_map< std::string, size_t > get_stats () const override
Public Member Functions inherited from kcenon::monitoring::snapshot_storage_backend
virtual ~snapshot_storage_backend ()=default
Private Attributes
storage_config config_
std::deque< metrics_snapshot > snapshots_
std::mutex mutex_
bool connected_ {false}
Detailed Description
Database storage backend (stub implementation)
Definition at line 221 of file storage_backends.h.
Constructor & Destructor Documentation
database_storage_backend() [1/2]
kcenon::monitoring::database_storage_backend::database_storage_backend () inline
Definition at line 223 of file storage_backends.h.
: config_() {}
database_storage_backend() [2/2]
kcenon::monitoring::database_storage_backend::database_storage_backend (const storage_config & config) inline explicit
Definition at line 225 of file storage_backends.h.
        : config_(config), connected_(true) {}
Member Function Documentation
capacity()
size_t kcenon::monitoring::database_storage_backend::capacity () const inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 267 of file storage_backends.h.
{
        return config_.max_capacity;
    }
References config_, and kcenon::monitoring::storage_config::max_capacity.
Referenced by TEST_F().
clear()
common::Result< bool > kcenon::monitoring::database_storage_backend::clear () inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 275 of file storage_backends.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        snapshots_.clear();
        return common::ok(true);
    }
References mutex_, and snapshots_.
Referenced by TEST_F().
flush()
common::Result< bool > kcenon::monitoring::database_storage_backend::flush () inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 271 of file storage_backends.h.
{
        return common::ok(true);
    }
Referenced by TEST_F().
get_stats()
std::unordered_map< std::string, size_t > kcenon::monitoring::database_storage_backend::get_stats () const inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 281 of file storage_backends.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return {
            {"stored_count", snapshots_.size()},
            {"capacity", config_.max_capacity},
            {"connected", connected_ ? 1UL : 0UL}
        };
    }
References config_, connected_, kcenon::monitoring::storage_config::max_capacity, mutex_, and snapshots_.
Referenced by TEST_F().
retrieve()
common::Result< metrics_snapshot > kcenon::monitoring::database_storage_backend::retrieve (size_t index) inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 239 of file storage_backends.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (index >= snapshots_.size()) {
            return common::Result<metrics_snapshot>::err(error_info(monitoring_error_code::not_found, "Snapshot index out of range").to_common_error());
        }
        return common::ok(snapshots_[index]);
    }
References mutex_, kcenon::monitoring::not_found, and snapshots_.
Referenced by TEST_F().
retrieve_range()
common::Result< std::vector< metrics_snapshot > > kcenon::monitoring::database_storage_backend::retrieve_range (size_t start, size_t count) inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 249 of file storage_backends.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        std::vector<metrics_snapshot> result;
        size_t end = std::min(start + count, snapshots_.size());
        for (size_t i = start; i < end; ++i) {
            result.push_back(snapshots_[i]);
        }
        return common::ok(std::move(result));
    }
References mutex_, and snapshots_.
Referenced by TEST_F().
size()
size_t kcenon::monitoring::database_storage_backend::size () const inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 262 of file storage_backends.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return snapshots_.size();
    }
References mutex_, and snapshots_.
Referenced by TEST_F().
store()
common::Result< bool > kcenon::monitoring::database_storage_backend::store (const metrics_snapshot & snapshot) inline override virtual
Implements kcenon::monitoring::snapshot_storage_backend.
Definition at line 228 of file storage_backends.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (snapshots_.size() >= config_.max_capacity) {
            snapshots_.pop_front();
        }
        snapshots_.push_back(snapshot);
        return common::ok(true);
    }
References config_, kcenon::monitoring::storage_config::max_capacity, mutex_, and snapshots_.
Referenced by TEST_F(), and TEST_F().
Member Data Documentation
config_
storage_config kcenon::monitoring::database_storage_backend::config_ private
Definition at line 291 of file storage_backends.h.
Referenced by capacity(), get_stats(), and store().
connected_
bool kcenon::monitoring::database_storage_backend::connected_ {false} private
Definition at line 294 of file storage_backends.h.
{false};
Referenced by get_stats().
mutex_
std::mutex kcenon::monitoring::database_storage_backend::mutex_ mutable private
Definition at line 293 of file storage_backends.h.
Referenced by clear(), get_stats(), retrieve(), retrieve_range(), size(), and store().
snapshots_
std::deque<metrics_snapshot> kcenon::monitoring::database_storage_backend::snapshots_ private
Definition at line 292 of file storage_backends.h.
Referenced by clear(), get_stats(), retrieve(), retrieve_range(), size(), and store().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/storage/storage_backends.h