Monitoring System: test_monitorable_component Class Reference
test_monitorable_component Class Reference
Public Member Functions
test_monitorable_component (const std::string &id)
kcenon::common::Result< monitoring_data > get_monitoring_data () const override
Get current monitoring data from the component.
void perform_operation ()
void set_cpu_usage (double usage)
void set_memory_usage (double usage)
int get_operation_count () const
Public Member Functions inherited from kcenon::monitoring::monitorable_component
monitorable_component (const std::string &id)
Constructor.
std::string get_monitoring_id () const override
Get monitoring identifier.
bool is_monitoring_enabled () const override
Check if monitoring is enabled.
common::VoidResult set_monitoring_enabled (bool enable) override
Enable or disable monitoring.
common::VoidResult reset_monitoring () override
Reset monitoring data.
Public Member Functions inherited from kcenon::monitoring::monitorable_interface
virtual ~monitorable_interface ()=default
Private Attributes
std::atomic< int > operation_count_ {0}
std::atomic< double > cpu_usage_ {0.0}
std::atomic< double > memory_usage_ {0.0}
Additional Inherited Members
Protected Member Functions inherited from kcenon::monitoring::monitorable_component
void update_metric (const std::string &key, double value) const
Helper to update a metric.
void update_tag (const std::string &key, const std::string &value) const
Helper to update a tag.
Protected Attributes inherited from kcenon::monitoring::monitorable_component
std::string monitoring_id_
bool monitoring_enabled_ = true
monitoring_data cached_data_
Detailed Description
Test implementation of monitorable_interface
Definition at line 23 of file test_monitorable_interface.cpp.
Constructor & Destructor Documentation
test_monitorable_component()
test_monitorable_component::test_monitorable_component (const std::string & id) inline explicit
Definition at line 30 of file test_monitorable_interface.cpp.
        : monitorable_component(id) {}
Member Function Documentation
get_monitoring_data()
kcenon::common::Result< monitoring_data > test_monitorable_component::get_monitoring_data () const inline override virtual
Get current monitoring data from the component.
Returns
Result containing monitoring data or error
Implements kcenon::monitoring::monitorable_interface.
Definition at line 33 of file test_monitorable_interface.cpp.
{
        if (!is_monitoring_enabled()) {
            return kcenon::common::make_error<monitoring_data>(
                static_cast<int>(monitoring_error_code::monitoring_disabled),
                "Monitoring is disabled for this component"
            );
        }
        monitoring_data data(get_monitoring_id());
        // Add metrics
        data.add_metric("operation_count", operation_count_.load());
        data.add_metric("cpu_usage", cpu_usage_.load());
        data.add_metric("memory_usage", memory_usage_.load());
        // Add tags
        data.add_tag("component_type", "test");
        data.add_tag("version", "1.0.0");
        data.add_tag("status", "running");
        return kcenon::common::ok(std::move(data));
    }
References kcenon::monitoring::monitoring_data::add_metric(), kcenon::monitoring::monitoring_data::add_tag(), cpu_usage_, kcenon::monitoring::monitorable_component::get_monitoring_id(), kcenon::monitoring::monitorable_component::is_monitoring_enabled(), memory_usage_, and operation_count_.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_operation_count()
int test_monitorable_component::get_operation_count () const inline
Definition at line 69 of file test_monitorable_interface.cpp.
{
        return operation_count_.load();
    }
References operation_count_.
Referenced by TEST_F(), and TEST_F().
perform_operation()
void test_monitorable_component::perform_operation () inline
Definition at line 57 of file test_monitorable_interface.cpp.
{
        operation_count_++;
    }
References operation_count_.
Referenced by TEST_F(), TEST_F(), and TEST_F().
set_cpu_usage()
void test_monitorable_component::set_cpu_usage (double usage) inline
Definition at line 61 of file test_monitorable_interface.cpp.
{
        cpu_usage_ = usage;
    }
References cpu_usage_.
Referenced by TEST_F().
set_memory_usage()
void test_monitorable_component::set_memory_usage (double usage) inline
Definition at line 65 of file test_monitorable_interface.cpp.
{
        memory_usage_ = usage;
    }
References memory_usage_.
Referenced by TEST_F().
Member Data Documentation
cpu_usage_
std::atomic<double> test_monitorable_component::cpu_usage_ {0.0} private
Definition at line 26 of file test_monitorable_interface.cpp.
{0.0};
Referenced by get_monitoring_data(), and set_cpu_usage().
memory_usage_
std::atomic<double> test_monitorable_component::memory_usage_ {0.0} private
Definition at line 27 of file test_monitorable_interface.cpp.
{0.0};
Referenced by get_monitoring_data(), and set_memory_usage().
operation_count_
std::atomic<int> test_monitorable_component::operation_count_ {0} private
Definition at line 25 of file test_monitorable_interface.cpp.
{0};
Referenced by get_monitoring_data(), get_operation_count(), and perform_operation().
The documentation for this class was generated from the following file:
tests/test_monitorable_interface.cpp