Monitoring System: TraceExportersTest Class Reference
TraceExportersTest Class Reference
Protected Member Functions
void SetUp () override
std::vector< trace_span > create_test_spans ()
Protected Attributes
std::vector< trace_span > test_spans_
otel_resource otel_resource_
Detailed Description
Definition at line 18 of file test_trace_exporters.cpp.
Member Function Documentation
create_test_spans()
std::vector< trace_span > TraceExportersTest::create_test_spans () inline protected
Definition at line 28 of file test_trace_exporters.cpp.
{
        std::vector<trace_span> spans;
        // Root span
        trace_span root_span;
        root_span.trace_id = "trace123";
        root_span.span_id = "span001";
        root_span.operation_name = "http_request";
        root_span.service_name = "web_service";
        root_span.start_time = std::chrono::system_clock::now();
        root_span.end_time = root_span.start_time + std::chrono::milliseconds(100);
        root_span.tags["http.method"] = "GET";
        root_span.tags["http.url"] = "/api/users";
        root_span.tags["span.kind"] = "server";
        spans.push_back(root_span);
        // Child span
        trace_span child_span;
        child_span.trace_id = "trace123";
        child_span.span_id = "span002";
        child_span.parent_span_id = "span001";
        child_span.operation_name = "database_query";
        child_span.service_name = "db_service";
        child_span.start_time = root_span.start_time + std::chrono::milliseconds(10);
        child_span.end_time = root_span.start_time + std::chrono::milliseconds(80);
        child_span.tags["db.statement"] = "SELECT * FROM users WHERE id = ?";
        child_span.tags["db.type"] = "postgresql";
        child_span.tags["span.kind"] = "client";
        spans.push_back(child_span);
        return spans;
    }
References kcenon::monitoring::trace_span::end_time, kcenon::monitoring::trace_span::operation_name, kcenon::monitoring::trace_span::parent_span_id, kcenon::monitoring::trace_span::service_name, kcenon::monitoring::trace_span::span_id, kcenon::monitoring::trace_span::start_time, kcenon::monitoring::trace_span::tags, and kcenon::monitoring::trace_span::trace_id.
Referenced by SetUp().
SetUp()
void TraceExportersTest::SetUp () inline override protected
Definition at line 20 of file test_trace_exporters.cpp.
{
        // Create test spans
        test_spans_ = create_test_spans();
        // Create OTEL resource
        otel_resource_ = create_service_resource("test_service", "1.0.0", "test_namespace");
    }
References kcenon::monitoring::create_service_resource(), create_test_spans(), otel_resource_, and test_spans_.
Referenced by OtlpGrpcExporterTest::SetUp().
Member Data Documentation
otel_resource_
otel_resource TraceExportersTest::otel_resource_ protected
Definition at line 62 of file test_trace_exporters.cpp.
Referenced by SetUp().
test_spans_
std::vector<trace_span> TraceExportersTest::test_spans_ protected
Definition at line 61 of file test_trace_exporters.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
tests/test_trace_exporters.cpp