Monitoring System: MetricExportersTest Class Reference
MetricExportersTest Class Reference
Protected Member Functions
void SetUp () override
monitoring_data create_test_monitoring_data ()
metrics_snapshot create_test_snapshot ()
Protected Attributes
monitoring_data test_data_
metrics_snapshot test_snapshot_
otel_resource otel_resource_
Detailed Description
Definition at line 21 of file test_metric_exporters.cpp.
Member Function Documentation
create_test_monitoring_data()
monitoring_data MetricExportersTest::create_test_monitoring_data () inline protected
Definition at line 34 of file test_metric_exporters.cpp.
{
        monitoring_data data("web_server");
        data.add_metric("http_requests_total", 1500.0);
        data.add_metric("http_request_duration_seconds", 0.250);
        data.add_metric("memory_usage_bytes", 1024000.0);
        data.add_metric("cpu_usage_percent", 75.5);
        data.add_tag("environment", "production");
        data.add_tag("region", "us-west-2");
        data.add_tag("version", "1.2.3");
        return data;
    }
References kcenon::monitoring::monitoring_data::add_metric(), and kcenon::monitoring::monitoring_data::add_tag().
Referenced by SetUp().
create_test_snapshot()
metrics_snapshot MetricExportersTest::create_test_snapshot () inline protected
Definition at line 48 of file test_metric_exporters.cpp.
{
        metrics_snapshot snapshot;
        snapshot.source_id = "system_monitor";
        snapshot.capture_time = std::chrono::system_clock::now();
        snapshot.add_metric("system_load_1m", 2.1);
        snapshot.add_metric("system_load_5m", 1.8);
        snapshot.add_metric("disk_usage_percent", 68.3);
        snapshot.add_metric("network_bytes_in", 987654.0);
        snapshot.add_metric("network_bytes_out", 654321.0);
        // Add tags to metrics
        snapshot.metrics[0].tags["host"] = "server01";
        snapshot.metrics[1].tags["host"] = "server01";
        snapshot.metrics[2].tags["mount"] = "/var";
        snapshot.metrics[3].tags["interface"] = "eth0";
        snapshot.metrics[4].tags["interface"] = "eth0";
        return snapshot;
    }
References kcenon::monitoring::metrics_snapshot::add_metric(), kcenon::monitoring::metrics_snapshot::capture_time, kcenon::monitoring::metrics_snapshot::metrics, and kcenon::monitoring::metrics_snapshot::source_id.
Referenced by SetUp().
SetUp()
void MetricExportersTest::SetUp () inline override protected
Definition at line 23 of file test_metric_exporters.cpp.
{
        // Create test monitoring data
        test_data_ = create_test_monitoring_data();
        // Create test metrics snapshot
        test_snapshot_ = create_test_snapshot();
        // Create OTEL resource
        otel_resource_ = create_service_resource("test_service", "1.0.0", "test_namespace");
    }
References kcenon::monitoring::create_service_resource(), create_test_monitoring_data(), create_test_snapshot(), otel_resource_, test_data_, and test_snapshot_.
Member Data Documentation
otel_resource_
otel_resource MetricExportersTest::otel_resource_ protected
Definition at line 71 of file test_metric_exporters.cpp.
Referenced by SetUp().
test_data_
monitoring_data MetricExportersTest::test_data_ protected
Definition at line 69 of file test_metric_exporters.cpp.
Referenced by SetUp().
test_snapshot_
metrics_snapshot MetricExportersTest::test_snapshot_ protected
Definition at line 70 of file test_metric_exporters.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
tests/test_metric_exporters.cpp