Monitoring System: kcenon::monitoring::alert_rule_group Class Reference
kcenon::monitoring::alert_rule_group Class Reference
A group of related alert rules.
#include <alert_rule.h>
Public Member Functions
alert_rule_group (std::string name)
Construct a rule group.
const std::string & name () const
Get group name.
void add_rule (std::shared_ptr< alert_rule > rule)
Add a rule to the group.
const std::vector< std::shared_ptr< alert_rule > > & rules () const
Get all rules in the group.
size_t size () const
Get number of rules.
bool empty () const
Check if group is empty.
void set_common_interval (std::chrono::milliseconds interval)
Set common evaluation interval for all rules.
std::optional< std::chrono::milliseconds > common_interval () const
Get common evaluation interval.
Private Attributes
std::string name_
std::vector< std::shared_ptr< alert_rule > > rules_
std::optional< std::chrono::milliseconds > common_interval_
Detailed Description
A group of related alert rules.
Rule groups allow organizing rules and applying common settings to multiple rules.
Definition at line 381 of file alert_rule.h.
Constructor & Destructor Documentation
alert_rule_group()
kcenon::monitoring::alert_rule_group::alert_rule_group (std::string name) inline explicit
Construct a rule group.
Parameters
name Group name
Definition at line 387 of file alert_rule.h.
        : name_(std::move(name)) {}
Member Function Documentation
add_rule()
void kcenon::monitoring::alert_rule_group::add_rule (std::shared_ptr< alert_rule > rule) inline
Add a rule to the group.
Parameters
rule Rule to add
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 400 of file alert_rule.h.
{
        if (rule) {
            rule->set_group(name_);
            rules_.push_back(std::move(rule));
        }
    }
References name_, and rules_.
Referenced by TEST(), TEST(), and TEST().
common_interval()
std::optional< std::chrono::milliseconds > kcenon::monitoring::alert_rule_group::common_interval () const inline
Get common evaluation interval.
Returns
Evaluation interval if set
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 442 of file alert_rule.h.
{
        return common_interval_;
    }
References common_interval_.
Referenced by TEST(), and TEST().
empty()
bool kcenon::monitoring::alert_rule_group::empty () const inline
Check if group is empty.
Returns
True if no rules
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 425 of file alert_rule.h.
{ return rules_.empty(); }
References rules_.
Referenced by TEST(), TEST(), and TEST().
name()
const std::string & kcenon::monitoring::alert_rule_group::name () const inline
Get group name.
Returns
Group name
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 394 of file alert_rule.h.
{ return name_; }
References name_.
Referenced by TEST().
rules()
const std::vector< std::shared_ptr< alert_rule > > & kcenon::monitoring::alert_rule_group::rules () const inline
Get all rules in the group.
Returns
Vector of rules
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 411 of file alert_rule.h.
{
        return rules_;
    }
References rules_.
set_common_interval()
void kcenon::monitoring::alert_rule_group::set_common_interval (std::chrono::milliseconds interval) inline
Set common evaluation interval for all rules.
Parameters
interval Evaluation interval
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 431 of file alert_rule.h.
{
        common_interval_ = interval;
        for (auto& rule : rules_) {
            rule->set_evaluation_interval(interval);
        }
    }
References common_interval_, and rules_.
Referenced by TEST().
size()
size_t kcenon::monitoring::alert_rule_group::size () const inline
Get number of rules.
Returns
Rule count
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 419 of file alert_rule.h.
{ return rules_.size(); }
References rules_.
Referenced by TEST(), and TEST().
Member Data Documentation
common_interval_
std::optional<std::chrono::milliseconds> kcenon::monitoring::alert_rule_group::common_interval_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 449 of file alert_rule.h.
Referenced by common_interval(), and set_common_interval().
name_
std::string kcenon::monitoring::alert_rule_group::name_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 447 of file alert_rule.h.
Referenced by add_rule(), and name().
rules_
std::vector<std::shared_ptr<alert_rule> > kcenon::monitoring::alert_rule_group::rules_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/alert/alert_rule.h.
Definition at line 448 of file alert_rule.h.
Referenced by add_rule(), empty(), rules(), set_common_interval(), and size().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/alert/alert_rule.h