Monitoring System: kcenon::monitoring::performance_benchmark Class Reference
kcenon::monitoring::performance_benchmark Class Reference
Performance benchmark utility.
#include <performance_monitor.h>
Public Member Functions
performance_benchmark (const std::string &name)
void set_iterations (std::uint32_t iterations)
Set number of iterations.
void set_warmup_iterations (std::uint32_t warmup)
Set warmup iterations.
template<typename Func >
common::Result< performance_metrics > run (const std::string &operation_name, Func &&func)
Run a benchmark.
template<typename Func1 , typename Func2 >
common::Result< std::pair< performance_metrics, performance_metrics > > compare (const std::string &operation1_name, Func1 &&func1, const std::string &operation2_name, Func2 &&func2)
Compare two operations.
Private Attributes
performance_profiler profiler_
std::string name_
std::uint32_t iterations_ {1000}
std::uint32_t warmup_iterations_ {100}
Detailed Description
Performance benchmark utility.
Definition at line 626 of file performance_monitor.h.
Constructor & Destructor Documentation
performance_benchmark()
kcenon::monitoring::performance_benchmark::performance_benchmark (const std::string & name) inline explicit
Definition at line 634 of file performance_monitor.h.
        : name_(name) {}
Member Function Documentation
compare()
template<typename Func1 , typename Func2 > common::Result< std::pair< performance_metrics, performance_metrics > > kcenon::monitoring::performance_benchmark::compare (const std::string & operation1_name, Func1 && func1, const std::string & operation2_name, Func2 && func2) inline
Compare two operations.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 694 of file performance_monitor.h.
      {
        auto result1 = run(operation1_name, std::forward<Func1>(func1));
        if (result1.is_err()) {
            return common::Result<std::pair<performance_metrics, performance_metrics>>::err(result1.error());
        }
        auto result2 = run(operation2_name, std::forward<Func2>(func2));
        if (result2.is_err()) {
            return common::Result<std::pair<performance_metrics, performance_metrics>>::err(result2.error());
        }
        return common::ok(std::make_pair(result1.value(), result2.value()));
    }
Referenced by TEST_F().
run()
template<typename Func > common::Result< performance_metrics > kcenon::monitoring::performance_benchmark::run (const std::string & operation_name, Func && func) inline
Run a benchmark.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 655 of file performance_monitor.h.
      {
        // Warmup
        for (std::uint32_t i = 0; i < warmup_iterations_; ++i) {
            func();
        }
        // Actual benchmark
        for (std::uint32_t i = 0; i < iterations_; ++i) {
            auto start = std::chrono::high_resolution_clock::now();
            try {
                func();
            } catch (...) {
                // Record error
                auto end = std::chrono::high_resolution_clock::now();
                auto duration = std::chrono::duration_cast<std::chrono::nanoseconds>(
                    end - start
                );
                profiler_.record_sample(operation_name, duration, false);
                continue;
            }
            auto end = std::chrono::high_resolution_clock::now();
            auto duration = std::chrono::duration_cast<std::chrono::nanoseconds>(
                end - start
            );
            profiler_.record_sample(operation_name, duration, true);
        }
        return profiler_.get_metrics(operation_name);
    }
References kcenon::monitoring::performance_profiler::get_metrics(), and kcenon::monitoring::performance_profiler::record_sample().
Referenced by TEST_F().
set_iterations()
void kcenon::monitoring::performance_benchmark::set_iterations (std::uint32_t iterations) inline
Set number of iterations.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 640 of file performance_monitor.h.
{
        iterations_ = iterations;
    }
Referenced by TEST_F(), and TEST_F().
set_warmup_iterations()
void kcenon::monitoring::performance_benchmark::set_warmup_iterations (std::uint32_t warmup) inline
Set warmup iterations.
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 647 of file performance_monitor.h.
{
        warmup_iterations_ = warmup;
    }
Referenced by TEST_F(), and TEST_F().
Member Data Documentation
iterations_
std::uint32_t kcenon::monitoring::performance_benchmark::iterations_ {1000} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 630 of file performance_monitor.h.
{1000};
name_
std::string kcenon::monitoring::performance_benchmark::name_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 629 of file performance_monitor.h.
profiler_
performance_profiler kcenon::monitoring::performance_benchmark::profiler_ private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 628 of file performance_monitor.h.
warmup_iterations_
std::uint32_t kcenon::monitoring::performance_benchmark::warmup_iterations_ {100} private
Examples
/home/runner/work/monitoring_system/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h.
Definition at line 631 of file performance_monitor.h.
{100};
The documentation for this class was generated from the following file:
include/kcenon/monitoring/core/performance_monitor.h