Monitoring System: kcenon::monitoring::thread_to_monitoring_adapter Class Reference
kcenon::monitoring::thread_to_monitoring_adapter Class Reference
#include <thread_to_monitoring_adapter.h>
Classes
struct collection_config
Public Member Functions
thread_to_monitoring_adapter (std::shared_ptr< event_bus > bus)
bool is_thread_system_available () const
common::Result< std::vector< metric > > collect_metrics ()
std::vector< std::string > get_metric_types () const
common::VoidResult start_collection (const collection_config &cfg)
common::VoidResult stop_collection ()
~thread_to_monitoring_adapter ()
Private Attributes
std::shared_ptr< event_bus > bus_
std::atomic< bool > running_ {false}
std::thread worker_
Detailed Description
Definition at line 55 of file thread_to_monitoring_adapter.h.
Constructor & Destructor Documentation
thread_to_monitoring_adapter()
kcenon::monitoring::thread_to_monitoring_adapter::thread_to_monitoring_adapter (std::shared_ptr< event_bus > bus) inline explicit
Definition at line 62 of file thread_to_monitoring_adapter.h.
        : bus_(std::move(bus)) {}
~thread_to_monitoring_adapter()
kcenon::monitoring::thread_to_monitoring_adapter::~thread_to_monitoring_adapter () inline
Definition at line 164 of file thread_to_monitoring_adapter.h.
{ (void)stop_collection(); }
Member Function Documentation
collect_metrics()
common::Result< std::vector< metric > > kcenon::monitoring::thread_to_monitoring_adapter::collect_metrics () inline
Definition at line 88 of file thread_to_monitoring_adapter.h.
{
        std::vector<metric> out;
#if MONITORING_THREAD_SYSTEM_AVAILABLE && defined(MONITORING_HAS_COMMON_INTERFACES)
        try {
            auto& container = kcenon::thread::service_container::global();
            auto monitorable = container.resolve<kcenon::common::interfaces::IMonitorable>();
            if (monitorable) {
                // Convert minimal subset of thread_system metrics into adapter metrics
                // thread_system v3.0 uses common::interfaces::IMonitorable
                auto monitoring_result = monitorable->get_monitoring_data();
                if (!monitoring_result.is_err()) {
                    const auto& snap = monitoring_result.value();
                    // Map metrics from common_system snapshot
                    for (const auto& m : snap.metrics) {
                        metric adapted{m.name, m.value, {}};
                        out.emplace_back(std::move(adapted));
                    }
                }
            }
        } catch (...) {
            // Fall back to empty on any failure
        }
#endif
        return common::ok(std::move(out));
    }
References kcenon::monitoring::container, and kcenon::monitoring::metric::name.
Referenced by TEST_F().
get_metric_types()
std::vector< std::string > kcenon::monitoring::thread_to_monitoring_adapter::get_metric_types () const inline
Definition at line 117 of file thread_to_monitoring_adapter.h.
{
#if MONITORING_THREAD_SYSTEM_AVAILABLE
        return {
            "thread.pool.jobs_pending",
            "thread.pool.jobs_completed",
            "thread.pool.worker_threads"
        };
#else
        return {};
#endif
    }
Referenced by TEST_F().
is_thread_system_available()
bool kcenon::monitoring::thread_to_monitoring_adapter::is_thread_system_available () const inline
Definition at line 67 of file thread_to_monitoring_adapter.h.
{
#if MONITORING_THREAD_SYSTEM_AVAILABLE
        // thread_system v3.0+ uses common_system interfaces
#  if defined(MONITORING_HAS_COMMON_INTERFACES)
        // Dynamic discovery via service_container if present
        try {
            auto& container = kcenon::thread::service_container::global();
            auto monitorable = container.resolve<kcenon::common::interfaces::IMonitorable>();
            return static_cast<bool>(monitorable);
        } catch (...) {
            return true; // Headers present; treat as available even if not registered
        }
#  else
        return true; // thread_system available but no common interfaces
#  endif
#else
        return false;
#endif
    }
References kcenon::monitoring::container.
Referenced by main(), and TEST_F().
start_collection()
common::VoidResult kcenon::monitoring::thread_to_monitoring_adapter::start_collection (const collection_config & cfg) inline
Definition at line 131 of file thread_to_monitoring_adapter.h.
{
        if (running_.exchange(true)) {
            return common::ok(); // already running
        }
        if (!bus_) {
            running_ = false;
            return common::VoidResult::err(static_cast<int>(monitoring_error_code::operation_failed), "event_bus not set");
        }
        worker_ = std::thread([this, cfg]() {
            while (running_.load()) {
                auto res = collect_metrics();
                if (res.is_ok() && cfg.publish_events && !res.value().empty()) {
                    bus_->publish_event(metric_collection_event("thread_system_adapter", res.value()));
                }
                std::this_thread::sleep_for(cfg.interval);
            }
        });
        return common::ok();
    }
References bus_, kcenon::monitoring::thread_to_monitoring_adapter::collection_config::interval, kcenon::monitoring::operation_failed, running_, and worker_.
Referenced by main().
stop_collection()
common::VoidResult kcenon::monitoring::thread_to_monitoring_adapter::stop_collection () inline
Definition at line 154 of file thread_to_monitoring_adapter.h.
{
        if (!running_.exchange(false)) {
            return common::ok();
        }
        if (worker_.joinable()) {
            worker_.join();
        }
        return common::ok();
    }
Referenced by main().
Member Data Documentation
bus_
std::shared_ptr<event_bus> kcenon::monitoring::thread_to_monitoring_adapter::bus_ private
Definition at line 167 of file thread_to_monitoring_adapter.h.
Referenced by start_collection().
running_
std::atomic<bool> kcenon::monitoring::thread_to_monitoring_adapter::running_ {false} private
Definition at line 168 of file thread_to_monitoring_adapter.h.
{false};
Referenced by start_collection().
worker_
std::thread kcenon::monitoring::thread_to_monitoring_adapter::worker_ private
Definition at line 169 of file thread_to_monitoring_adapter.h.
Referenced by start_collection().
The documentation for this class was generated from the following file:
include/kcenon/monitoring/adapters/thread_to_monitoring_adapter.h