# kcenon-logger-system portfile
# High-performance C++20 async logging library with 4.34M msg/sec throughput

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO kcenon/logger_system
    REF v0.1.1
    SHA512 96df6c6213e618052999301de4f3b4a1aa5ccac42148ea1f02c408f68f38e13620c78b98ebca7abcf7d706907debf4e95766d4fca3b53d848cc90fd0c6e3ba61
    HEAD_REF main
    PATCHES
        fix-unified-deps-target-names.patch
)

# Disable thread_system integration: upstream CMake does not link thread_system
# library properly in vcpkg mode (unresolved externals for thread_pool symbols).
# The logger falls back to its standalone executor which works correctly.
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_TESTS=OFF
        -DBUILD_BENCHMARKS=OFF
        -DBUILD_SAMPLES=OFF
        -DBUILD_SHARED_LIBS=OFF
        -DLOGGER_BUILD_INTEGRATION_TESTS=OFF
        -DLOGGER_ENABLE_COVERAGE=OFF
        -DLOGGER_USE_THREAD_SYSTEM=OFF
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(
    PACKAGE_NAME LoggerSystem
    CONFIG_PATH lib/cmake/LoggerSystem
)

# Upstream omits install(EXPORT) — generate LoggerSystemTargets.cmake manually.
# On Windows (x64-windows triplet), vcpkg builds SHARED (DLL); on Unix, STATIC.
if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    set(_lib_type SHARED)
else()
    set(_lib_type STATIC)
endif()

set(_targets_file "${CURRENT_PACKAGES_DIR}/share/LoggerSystem/LoggerSystemTargets.cmake")
file(WRITE "${_targets_file}"
[=[
# Generated by vcpkg portfile — upstream does not export CMake targets
cmake_minimum_required(VERSION 3.14)

get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)

if(NOT TARGET LoggerSystem::LoggerSystem)
    add_library(LoggerSystem::LoggerSystem ]=] "${_lib_type}" [=[ IMPORTED)
    set_target_properties(LoggerSystem::LoggerSystem PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    )
endif()

# Load per-configuration import files
file(GLOB _config_files "${CMAKE_CURRENT_LIST_DIR}/LoggerSystemTargets-*.cmake")
foreach(_config_file IN LISTS _config_files)
    include("${_config_file}")
endforeach()
]=])

# Create per-config import files with platform-appropriate paths
set(_rel_targets "${CURRENT_PACKAGES_DIR}/share/LoggerSystem/LoggerSystemTargets-release.cmake")
set(_dbg_targets "${CURRENT_PACKAGES_DIR}/share/LoggerSystem/LoggerSystemTargets-debug.cmake")

if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    # DLL: IMPORTED_LOCATION -> bin/*.dll, IMPORTED_IMPLIB -> lib/*.lib
    file(WRITE "${_rel_targets}"
[=[
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
set_property(TARGET LoggerSystem::LoggerSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LoggerSystem::LoggerSystem PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/LoggerSystem.dll"
    IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/LoggerSystem.lib"
)
]=])
    file(WRITE "${_dbg_targets}"
[=[
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../debug/" ABSOLUTE)
set_property(TARGET LoggerSystem::LoggerSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(LoggerSystem::LoggerSystem PROPERTIES
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bin/LoggerSystem.dll"
    IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/lib/LoggerSystem.lib"
)
]=])
else()
    # Static: IMPORTED_LOCATION -> lib/libLoggerSystem.a
    file(WRITE "${_rel_targets}"
[=[
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
set_property(TARGET LoggerSystem::LoggerSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LoggerSystem::LoggerSystem PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libLoggerSystem.a"
)
]=])
    file(WRITE "${_dbg_targets}"
[=[
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../debug/" ABSOLUTE)
set_property(TARGET LoggerSystem::LoggerSystem APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(LoggerSystem::LoggerSystem PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/libLoggerSystem.a"
)
]=])
endif()

# Fix include paths: upstream headers use kcenon/logger/ but vcpkg installs under logger_system/
file(GLOB_RECURSE _logger_headers "${CURRENT_PACKAGES_DIR}/include/logger_system/*.h")
foreach(_header IN LISTS _logger_headers)
    file(READ "${_header}" _content)
    if(_content MATCHES "kcenon/logger/")
        string(REPLACE "kcenon/logger/" "logger_system/" _content "${_content}")
        file(WRITE "${_header}" "${_content}")
    endif()
endforeach()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
